### ISSUE TITLE
resourcePath what does?

### ISSUE THREAD

**Issue by keyiis** [node-opcua/node-opcua#1012]
I tried add or remove `resourcePath ` has no effect on UaExpert,so what is the function of `resourcePath ` ?
```
const server = new opcua.OPCUAServer({
    port: 4334, // the port of the listening socket of the server
    resourcePath: "/UA/MyLittleServer", // this path will be added to the endpoint resource name
     buildInfo : {
        productName: "MySampleServer1",
        buildNumber: "7658",
        buildDate: new Date(2021,6,7)
    }
});
```
![image](https://user-images.githubusercontent.com/7766085/121283659-15f47700-c90e-11eb-9203-6f4249fedbda.png)

**Comment by erossignon** [comment]
Servers may optionally implement multiple endpoints on the same TCP port.
The resources path helps to distinguish which endpoint the client wants to connect to. 

If the Endpoint URL does not provide a resource path element, the server typically falls back to a default behavior. In many cases, this default behavior is determined by the OPC UA server implementation, and it might involve either using a predefined resource path or attempting to connect to the default OPC UA server instance.

It is important to note that the actual behavior depends on the specific OPC UA server implementation, and the fallback mechanism may vary between different servers. It is generally a good practice to provide a resource path in the Endpoint URL to ensure that clients connect to the correct server instance and avoid any confusion or unexpected behavior.
