### ISSUE TITLE
GetMonitoredItems method call to the subscription containing roughly 35 variables result in warning prints.

### ISSUE THREAD

**Issue by Graos** [node-opcua/node-opcua#1018]
**Current behavior**
GetMonitoredItems method call to the subscription containing roughly 35 variables from UaExpert client result in warning prints in node-opcua server.

**Describe the bug**
Create a subscription with around 35 variables and call GetMonitoredItem method to that subscription. To have much better performance it is required to use the Typed array rather than the generic array (That's exactly what the warning print says) But unfortunately the prints are coming from the node-opcua stack.

**Screenshots**

![image](https://user-images.githubusercontent.com/69800669/123986135-56ec2280-d9c6-11eb-85c9-71cd06e56fab.png)

Warning ! an array containing  UInt32 elements has been provided as a generic array.
          This is inefficient as every array value will have to be coerced and verified against the expected type
          It is highly recommended that you use a  typed array  Function  instead
Warning ! an array containing  UInt32 elements has been provided as a generic array.
          This is inefficient as every array value will have to be coerced and verified against the expected type
          It is highly recommended that you use a  typed array  Function  instead
Warning ! an array containing  UInt32 elements has been provided as a generic array.
          This is inefficient as every array value will have to be coerced and verified against the expected type
          It is highly recommended that you use a  typed array  Function  instead
Warning ! an array containing  UInt32 elements has been provided as a generic array.
          This is inefficient as every array value will have to be coerced and verified against the expected type
          It is highly recommended that you use a  typed array  Function  instead
Warning ! an array containing  UInt32 elements has been provided as a generic array.
          This is inefficient as every array value will have to be coerced and verified against the expected type
          It is highly recommended that you use a  typed array  Function  instead
Warning ! an array containing  UInt32 elements has been provided as a generic array.
          This is inefficient as every array value will have to be coerced and verified against the expected type
          It is highly recommended that you use a  typed array  Function  instead

**Gist**

  

- **Node:**
  `node --version` = 14.6

**Comment by erossignon** [comment]
was fixed in c73a0ae3bdc83a8991a570f6964783b735bcddc3
