### ISSUE TITLE
Resend method Implementation in node-opcua server

### ISSUE THREAD

**Issue by Graos** [node-opcua/node-opcua#1019]
**Is your feature request related to a problem? Please describe.**
When republish response fails for a subscription from server client Executes Resend method to get the latest value of the monitored items.

**Describe the solution you'd like**
When republish response fails for a subscription from server client Executes Resend method to get the latest value of the monitored items. node-opcua server should handle the Resend method call from client by sending the latest notification of the subscription requested.

**Comment by erossignon** [comment]
resend is available in 2.84.0
