### ISSUE TITLE
OPC UA Server availale on the internet.

### ISSUE THREAD

**Issue by mpostol** [node-opcua/node-opcua#102]
Hi,

FYI, an OPC UA server is exposed on the Internet. It provides ADI Information Model, but it is not connected to any real device - just random numbers are provided. The instruction how to configure the client:
[OPC UA Viewer - Software](http://www.commsvr.com/DownloadCenter/ProductSoftware/OPCUAViewerSoftware.aspx)
is in the documentation at:
[How to remotely access the CommServer UA](http://www.commsvr.com/OPC-Help/Index.aspx?topic=html/2d5937cb-8f0a-464b-8169-c21baa17a6d4.htm)

Hopefully you may use any OPC UA Client and configuartion should be similar. 
I am going to use it to test the Data Binding concept I am working on in the project [DataBindingsSolution](https://github.com/mpostol/OPC-UA-OOI/tree/master/DataBindingsSolution)

Any comments are welcome.

Thank you,
Mariusz Postol

**Comment by erossignon** [comment]
Thank you Mariuz, Let me add this into the wiki for expanding references 

https://github.com/node-opcua/node-opcua/wiki/publicly-available-OPCUA-servers

if you know any other publicly available OPCUA server, do not hesitate to complement the wiki page.
