### ISSUE TITLE
OPCUAServer with hostname error when subscribed to a discovery server

### ISSUE THREAD

**Issue by nicoloereni** [node-opcua/node-opcua#1024]
Hello,
with a Server like:

```
let server = new OPCUAServer({
            port: 64101,
            hostname: hostname + '/nozomi',
            registerServerMethod: RegisterServerMethod.LDS,
            discoveryServerEndpointUrl: discoveryServerEndpointUrl})
        await server.initialize();
```
        
we have a server on:
`on opc.tcp://Nicolos-MacBook-Pro-2.local/nozomi:64101`

the discovery server when the server start throws:
```What shall I do ? Required port not given
Error: Required port not given
    at new Service (/Users/nicolo/Documents/opcua_spike/node_modules/bonjour/lib/service.js:18:25)
    at Registry.publish (/Users/nicolo/Documents/opcua_spike/node_modules/bonjour/lib/registry.js:18:17)
    at Bonjour.publish (/Users/nicolo/Documents/opcua_spike/node_modules/bonjour/index.js:16:25)
```

removing the 'hostname' option everything works fine.

We expect to have `opc.tcp://Nicolos-MacBook-Pro-2.local:64101/nozomi` instead of 
`on opc.tcp://Nicolos-MacBook-Pro-2.local/nozomi:64101`

Is this a bug or am I doing something wrong?

with a configuration like:
```
let server = new OPCUAServer({
            hostname: hostname + ':64101/nozomi',
            registerServerMethod: RegisterServerMethod.LDS,
            discoveryServerEndpointUrl: discoveryServerEndpointUrl})
        await server.initialize();
```
the subscription to the discovery server works, but the endpoint is:
`on opc.tcp://Nicolos-MacBook-Pro-2.local:64101/nozomi:26543`

Many thanks

**Comment by erossignon** [comment]
hostname should only be hostname. / is a invalid character in hostname.

I guess you want to use `ressourcePath` instead

```javascript
const server = new OPCUAServer({
      port: 64101,
      hostname,
      resourcePath: '/nozomi',
      registerServerMethod: RegisterServerMethod.LDS,
      discoveryServerEndpointUrl
});
await server.start();
console.log(server.getEndpointUrl());
await server.shutdown();
```

will produce the endpointUrl `opc.tcp://Nicolos-MacBook-Pro-2.local:64101/nozomi`
