### ISSUE TITLE
Handling write errors on UAVariables is not working (as expected) and causing UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by marcodisarno** [node-opcua/node-opcua#1030]
**Current behavior**

Adding a variable using `Namespace.addVariable(options: AddVariableOptions)` with the following `options`:
```typescript
{
  dataType: "myDataType",
  nodeId: "myNodeId",
  browseName: "myBrowseName",
  componentOf: "myParentNode",
  // now comes the important part ;)
  // BindVariableOptionsVariation1
  value: {
    get: aGetterForMyValue(),
    // VariableSetterVariation2
    set: (variant: any, doneSetting: (err: Error | null, statusCode: StatusCode) => void)) => {                                  
      // trying to forward whatever was set here to the machine that variable originally came from
      const myMachineErrorCallback = (error?: string) => {
        doneSetting(error ? new Error(error) : null, error ? StatusCodes.Bad : StatusCodes.Good);
      }
      MyMachine.write((variant.value), myMachineErrorCallback );
    }
  }
}
```

**Describe the bug**

When `MyMachine.write()` succeeds, everything is fine, the value is updated in my client and on my server and I live happily ever after.

When `MyMachine.write()` fails, things go sideways twofold:
1. I get a "UnhandledPromiseRejectionWarning" (see below)
2. The value is updated in the client and on my server

```
(node:20468) UnhandledPromiseRejectionWarning: Error
    at Object.assert (C:\pathToMyProject\node_modules\node-opcua-assert\dist\index.js:13:21)
    at C:\pathToMyProject\node_modules\node-opcua-server\dist\opcua_server.js:1803:41
    at C:\pathToMyProject\node_modules\node-opcua-server\dist\server_engine.js:947:17
    at C:\pathToMyProject\node_modules\async\dist\async.js:248:13
    at wrapper (C:\pathToMyProject\node_modules\async\dist\async.js:268:20)
    at iteratorCallback (C:\pathToMyProject\node_modules\async\dist\async.js:493:17)
    at C:\pathToMyProject\node_modules\async\dist\async.js:321:20
    at C:\pathToMyProject\node_modules\async\dist\async.js:245:17
    at C:\pathToMyProject\node_modules\node-opcua-address-space\dist\src\ua_variable.js:546:13
    at C:\pathToMyProject\node_modules\node-opcua-address-space\dist\src\ua_variable.js:1527:13
(node:20468) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:20468) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I traced that stack back to [opcua_server.ts#L2778](https://github.com/node-opcua/node-opcua/blob/master/packages/node-opcua-server/source/opcua_server.ts#L2778), where I at least could fix the UnhandledPromiseRejectionWarning, like this:

```typescript
server.engine.write(context, request.nodesToWrite, (err: Error | null, results?: StatusCode[]) => { // why is results an array but error is not?
                    const validGood = !err && results.includes(StatusCode.Good);  // that would probably need to be a list of all "Good"
                    const validBad = !!err && !results.includes(StatusCode.Good); // same here
                    assert(validGood || validBad);
                    ...
```

I don't know if I'm doing any good here, but if, I'm happy to provide a branch, just shout out.

**Step by step instruction to reproduce**

1. add a variable to your namespace as described above
2. call the "doneWriting" callback with `error !== null`
3. enjoy the ride

**Expected behavior**

I as a user expect a user's invalid an entry from a client to be validatable at a remote location (`MyMachine` in this case, but could also be a REST endpoint or whatever). If that value is not ok according to the user, it would be nice if it was replaced with the old value automatically.

I presume that's what the `VariableSetterVariation2` is for.

**Context**

- ( ) my request is related to node-opcua acting as an OPCUA CLIENT
- (X) my request is related to node-opcua acting as an OPCUA SERVER

- ( ) I have installed node-opcua from source ( using git clone)
- (X) I have installed node-opcua as a package ( using npm install )
- ( ) I am using an application that uses node-opcua
    - ( ) node-red
    - ( ) other : please specify

- Device: Embedded Windows mini PC
- OS version: Windows 10

    - (X) Windows : version : 10.0.18363
    - ( ) Linux : version : ______
    - ( ) MacOs : version : ______
    - ( ) Raspbian: version : ______
    - ( ) Other : specify : ______

- Description of the other OPCUA system I am trying to connect to:

    - Name: UAExpert
    - Version: 1.5.1 331
    - Manufacturer/Software vendor: ______
    - link to the manufacturer or product site: https://

- **node-opcua version:** : 2.18.0
  
  

- **Node:**
  `node --version` = v12.16.1

**Comment by erossignon** [comment]
@marcodisarno let me close this issue as it hasn't received any update.
