### ISSUE TITLE
Async get for time consuming queries.

### ISSUE THREAD

**Issue by faljse** [node-opcua/node-opcua#1034]
**Is your feature request related to a problem? Please describe.**
We are developing a opcua-to-vendorapi bridge.
Calls to the api are time consuming, so we need a way to parallelize/async them

**Describe the solution you'd like**
enable "async get()" when using node.bindVariable()

**Describe alternatives you've considered**
A general (async) filter-function, that captures all requests

**Comment by erossignon** [comment]
use `timestamped_get` instead, this one accept an async or callback method to let you del with long operation. 

Check example  in [NodeOPUCA by Example](https://leanpub.com/node-opcuabyexample)
