### ISSUE TITLE
node-opcua-pki Flashing command prompts on windows

### ISSUE THREAD

**Issue by BartaG512** [node-opcua/node-opcua#1043]
**Is your feature request related to a problem? Please describe.**

When starting a nodejs process with pm2 using node-opcua on Windows 10 a Windows Prompt windows pops ups each time when "node-opcua-pki" package runs `child_process.exec()` method.  The `exec` process is calling openssl.
There are two occurances: `lib/misc/install_prerequisite.ts:98` and `lib/pki/toolbox.js:123`

**Describe the solution you'd like**

I would like to make disappear the flashing popups each time the application starts.
This could be achieved by using options `windowsHide: true` in exec method
[Source nodejs docs](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback)
 
**Additional context**
 
I was able to stop the popups with editing the two js files in dist folder.
install_prerequisite.js
![image](https://user-images.githubusercontent.com/28688421/130564790-0cde5efe-1d97-409c-afe8-907cf2f3eda5.png)
toolbox.js
![image](https://user-images.githubusercontent.com/28688421/130564829-a65298f3-392a-4619-bb07-0f354f0bd842.png)

node-opcua version: node-opcua@^2.47.0
node version: v14.17.0
Operating System: win32 10.0.19042

**Comment by erossignon** [comment]
issue could be registered at https://github.com/node-opcua/node-opcua-pki where the node-opcua-pki package in maintained.

**Comment by erossignon** [comment]
fixed in node-opcua-pki@2.12.1
