### ISSUE TITLE
Browsing of UAVariable instance of BaseDataVariableType or Property in node-opcua server does not return references

### ISSUE THREAD

**Issue by Graos** [node-opcua/node-opcua#1045]
Issue in node-opcua server version: 2.50.0

Steps to reproduce the issue:

Steps in node-opcua-Server:

Add a folder(say "TestFolder1) under Object folder .
Add a variable (say "TestVariable1) of BaseDataVariableType or Property TypeDefinition and any DataType under the "TestFolder1" as (Has component) reference.

Use any third party OPC UA client  , connect to node-opcua server and browse the above defined Variable "TestVariable1" using the following browse parameters
NodeId : "s=TestVariable1"
ReferenceTypeId : ReferenceTypeIds.References
BrowseDirection: BrowseDirection.Both
includeSubtypes: true,
resultMask: 0x3f,

Actual Result: node-opcua server returns no references.
Expected Result: It should return the following two reference for the above variable s=TestVariable1
{
            referenceTypeId: NodeId { identifierType: 1, value: 47, namespace: 0 }, ==> HasComponent
            isForward: false,
            nodeId: 's=TestFolder1'
          },
          {
            referenceTypeId: NodeId { identifierType: 1, value: 40, namespace: 0 }, ==> HasTypeDefinition
            nodeId: 'ns=0;i=63' ==> BaseDataVariableType.
          },

**Comment by erossignon** [comment]
Please provide a gist

**Comment by Graos** [comment]
I used the node-opcua client example source code for browse as it is. recursively browsing all the references  nodeClassMask is not defined but i thought it is default to 0x0 when not provided. It does not matter I tried even with nodeClassMask 0x0 but still the same issue. However the same node-opcua client browse code can get the reference of the same variable from Unified Automation CPP server.

                let nodeToBrowse1 = {
                    nodeId: browseResult.references[i].nodeId,
                    referenceTypeId: opcua.ReferenceTypeIds.References,
                    browseDirection: BrowseDirection.Both,
                    includeSubtypes: true,
                    resultMask: 0x3f,
                 };
                await browseNode(nodeToBrowse1);

**Comment by Graos** [comment]
Wireshark capture of Browse request of a variable called "matrixBool" 
![image](https://user-images.githubusercontent.com/69800669/132178558-193eae7b-2762-4913-b3b6-277cd7ccdd95.png)
Wireshark response from node-opcua server for the above variable
![image](https://user-images.githubusercontent.com/69800669/132178678-2fedb3ae-15cd-48c4-988b-c2d49fa41254.png)

**Comment by Graos** [comment]
same variable when browsed from UaExpert does not yield any difference. node-opcua server always responds with no references.
![image](https://user-images.githubusercontent.com/69800669/132179004-3ff0d05c-d7c3-4ced-ba8b-4faeaca66818.png)

**Comment by Graos** [comment]
I am pretty sure the Node-OPCUA server has some problem in providing the references of UAVAriable and UAMethod. The same configuration works fine with other OPC UA servers .

**Comment by erossignon** [comment]
Please contact support for a deeper investigation. causes could be multiples.
