### ISSUE TITLE
how to enable debugging to  console ?

### ISSUE THREAD

**Issue by gilesbradshaw** [node-opcua/node-opcua#1049]
What do I need to do to get the code to write debug info to the console?

I am setting NODEOPCUADEBUG variable but it seems to make no difference

I have tried *, TRACE and TRACE-REQUST-RESPONSE

**Comment by mg90707** [comment]
Try DEBUG=ALL

**Comment by erossignon** [comment]
The NODEOPCUADEBUG variable content has been improved in v2.32.0 in https://github.com/node-opcua/node-opcua/releases/tag/v2.32.0
check the release note for more detailed
