### ISSUE TITLE
Acknowledge Alarm error BadNodeIdUnknown

### ISSUE THREAD

**Issue by boualid** [node-opcua/node-opcua#1050]
**Current behavior**
Currently i am developing OPCUA client using Node Red. I am able to read the event/Alarm from OPC UA server.
Now i want to acknowledge the same, so i had create a data flow, with OPCUA nodes , that allow to call acknowledgement method for opcua.

**Describe the bug**
Although i insert the right parameters (conditionId, eventId and comment) i get below error message.
I take the values of the parameter from UA EXpert.
![image](https://user-images.githubusercontent.com/25208470/132860349-99647841-aba5-4c2f-9c1b-e27d86641b14.png)

**Step by step instruction to reproduce**

1. the below screenshot show the alarms that have been generated by the server
![image](https://user-images.githubusercontent.com/25208470/132863110-51a51e6e-d19c-4c20-bda2-5fad27ec8839.png)

2. I want to acknowledge for example  the «Alm03», so 
2.1 the condtitionID == 2673
![image](https://user-images.githubusercontent.com/25208470/132863904-fa20991b-c7ff-4a40-b37d-408d72e0542e.png)
2.2 the eventId == 0x31b1dea5609b89ece2f0b856321fb58600000004
![image](https://user-images.githubusercontent.com/25208470/132864091-dd100af0-1100-4dfb-9aa1-afb6e2ca5054.png)
2.3 In the end i add comments

**Expected behavior**
i should be able to acknowledge the alarm «Alm03»

**Gist**

 
gist:

**Context**

- (X ) my request is related to node-opcua acting as an OPCUA CLIENT
- (X) my request is related to node-opcua acting as an OPCUA SERVER

- ( ) I have installed node-opcua from source ( using git clone)
- ( ) I have installed node-opcua as a package ( using npm install )
- ( ) I am using an application that uses node-opcua

    - (X) node-red
    - ( ) other : please specify

- Device: ______
- OS version: ______

    - ( ) Windows : version : ______
    - (X) Linux : version : Ubuntu 18.04.2 LTS(Bionic Beaver)
    - ( ) MacOs : version : ______
    - ( ) Raspbian: version : ______
    - ( ) Other : specify : ______

- **node-opcua version:** :
  
  

- **Node:**
  `node --version` =v16.5.0

**Comment by boualid** [comment]
my problem is resolved

**Comment by AcureroAdrian** [comment]
How was the problem solved?

**Comment by AcureroAdrian** [comment]
@boualid How was the problem solved?
