### ISSUE TITLE
Raspberry Pi 2 - HDA capability

### ISSUE THREAD

**Issue by jcodling** [node-opcua/node-opcua#106]
Greetings everyone,

I have the node OPC UA server running on a Raspberry Pi 2 exposing two simulated variables and an ultrasonic sensor. It works great using a modified node OPC UA simple-client with a RESTful API to a custom web front end displaying the results. I am currently involved in a project to have an OPC UA server running in low cost packages exposing remote sensor data. I require HDA functionality built into the server in case the connection is severed so that data is not lost while the remote package is still functional and the connection is re-established. Once reconnected the server should return the missing data and continue with the subscription.

I have looked at the code and documentation for the Historian capability. Is there anyone who has implemented HDA functionality using node OPC UA with this kind of capability or can point me in a direction to implement this feature?

This node OPC UA project gave me a great headstart. Thank you,

Jeff Codling

**Comment by damienclaveau** [comment]
Hi Jeff,

I'm looking for the same feature.
Are you going to work on it in your forker repository ?

Damien

**Comment by jcodling** [comment]
I tried but didn't have any luck figuring out the current code enough to implement it. I've moved on to using the Open OPC-UA package which can be compiled for ARM7 and implements all the standards.

**Comment by erossignon** [comment]
HDA is now implemented as in memory storage and can be extended to stored to custom database oif necessary.
