### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by MarcoSeb** [node-opcua/node-opcua#1061]
Please follw the rule of semantic versioning rule 8 https://semver.org/#spec-item-8

Examples:
Version 2.37.0 -> 2.40.0
has incompatible changes in the public api
Intruduced by commit d11178da7d59d3e9b4d07c10cdeaf65073d55533 impplement rolePermission

It would be nice, if such incompatible API changes would lead to a change in the major version.
2.40.0 would be 3.0.0

**Comment by erossignon** [comment]
We try to keep the API stable as much as we possibly can.

- we use patches (ie. 2.2.0 => 2.2.1) to fix bugs with no API change
- minor release (ie 2.2.0 => 2.3.0) for the addition of features or enhancement of emerging feature (and we allow API evolution in emerging feature)
- minor release keeps the API stable except for emerging features that are not stabilized yet.
- major releases are kept for major refactoring and changes of stable feature.


we encourage you to look at the release notes before you upgrade to a newer version of node-opcua.
Breaking changes are highlighted in release notes: 
💥 breaking change
https://github.com/node-opcua/node-opcua/releases?after=v2.46.0
https://github.com/node-opcua/node-opcua/releases/tag/v2.40.0


permission and role were still in beta phase and under active development for one of our sponsor.

Please [support us](https://support.sterfive.com) if you can.
