### ISSUE TITLE
Issue with BrowseDescriptionOptions

### ISSUE THREAD

**Issue by ata1704** [node-opcua/node-opcua#1065]
Hi. Almost every values of the references in the BrowseResult are incorrect if I'm using BrowseDescriptionOptions instead of simple NodeId (String).

I wanted to use BrowseDescriptionsOptions to use BrowseDirection. For comparison I'm using the direction 0, which is Forward. But I could also just comment out the browseDirection with the same result.
```
const nodeId = "ns=6;s=MyMethod";
const browseResult = await session.browse({
            nodeId: nodeId,
            browseDirection: 0
        });
```

StatusCode is Good, but I'm getting back the following reference (just giving you one for comparison):
```
{
  referenceTypeId: 'ns=0;i=0',
  isForward: false,
  nodeId: 'ns=6;s=MyMethod/0:OutputArguments',
  browseName: { namespaceIndex: 0 },
  displayName: {},
  nodeClass: 'Unspecified',
  typeDefinition: 'ns=0;i=0'
}
```

Now with the usual BrowseRequest:
```
const nodeId = "ns=6;s=MyMethod";
const browseResult = await session.browse(nodeId);
```

The BrowseResult is:
```
{
  referenceTypeId: 'ns=0;i=46',
  isForward: true,
  nodeId: 'ns=6;s=MyMethod/0:OutputArguments',
  browseName: { namespaceIndex: 0, name: 'OutputArguments' },
  displayName: { text: 'OutputArguments' },
  nodeClass: 'Variable',
  typeDefinition: 'ns=0;i=68'
}
```

As you can see the only the property _nodeId_ is correct. I'm getting the same result no matter what Node I browse. Only the NodeId is changing (correctly).

**Context**

- (x) my request is related to node-opcua acting as an OPCUA CLIENT
- ( ) my request is related to node-opcua acting as an OPCUA SERVER

- ( ) I have installed node-opcua from source ( using git clone)
- (x) I have installed node-opcua as a package ( using npm install )
- ( ) I am using an application that uses node-opcua

- Device: Macbook Pro (15-inch, 2018)
- OS version: 11.2.3

- Description of the other OPCUA system I am trying to connect to:

    - Name: Prosys OPC UA Simulation Server
    - Version: 5.0.08-330
    - Manufacturer/Software vendor: Prosys
    - link to the manufacturer or product site: https://www.prosysopc.com/

- **node-opcua version:** :
  node-opcua@2.42.0

- **Node:**
  `node --version` = v14.15.5

**Comment by Graos** [comment]
I have reported the same problem Browsing of UAVariable instance of BaseDataVariableType or Property in node-opcua server does not return references #1045
I am using the latest version Node-OPCUA 2.50.0 and i see no references returned for UAVariable and UAMethods and I use the BrowseDescription with all the necessary attributes.
