### ISSUE TITLE
Making this package available in Deno

### ISSUE THREAD

**Issue by Noxdor** [node-opcua/node-opcua#1066]
I would like to use this package in Deno. Is there any plans or already any way to use this package via a CDN as an ES module? That would greatly simplify the usage of this package in Deno.

**Is your feature request related to a problem? Please describe.**

The problem is that right now it seems that the module only exports its functionality in commonJS, which makes it impracticable  to use in modern build systems.

**Describe the solution you'd like**

ES module exports for the easy use from a CDN.

**Describe alternatives you've considered**

Using it via the yet unstable Deno require API. I didn't test it out, but it should work. unfortunately the API is not stable yet and is anyway a workaround solution.

**Comment by erossignon** [comment]
There is no massive interest in getting node-occur ported to Deno, apparently. 
Closing for now: We can always reopen if Deno becomes mainstream.
