### ISSUE TITLE
Getter and setter with object types?

### ISSUE THREAD

**Issue by lukepass** [node-opcua/node-opcua#1069]
**Is your feature request related to a problem? Please describe.**

I tried adding a getter and a setter on my object type following this tutorial: https://github.com/node-opcua/node-opcua/blob/master/documentation/create_new_object_type.md

```
  // declares a machine type
  const machineType = namespace.addObjectType({
    browseName: 'BaseMachineType',
  });

  let temperature = 0;

  // adds a new variable to the machine type
  namespace.addVariable({
    componentOf: machineType,
    browseName: 'Temperature',
    dataType: DataType.Double,
    modellingRule: 'Mandatory',
    value: {
      get: () => {
        return new Variant({dataType: DataType.Double, value: temperature});
      },
      set: (variant) => {
        temperature = parseFloat(variant.value);
        return StatusCodes.Good;
      },
    },
  });
```

Unfortunately I could not use a getter / setter because the variable on the instantiated object is always updated without calling the getters / setters.

**Describe the solution you'd like**

The getter / setter is called.

**Describe alternatives you've considered**

I tried using `setValueFromSource` with a getter / setter but it didn't work.

**Additional context**

Thanks.

**Comment by erossignon** [comment]
@lukepass the use of getter and setter should usually be restricted to when there is a need to extract the value from an external source or write to a external device.
In all other cases, you can rely on the build in mechanism provided by UAVariable.

No need to use bindVariable get/set , just use setValueFromSource when you want to update the value.
