### ISSUE TITLE
method call returns datatype "null" when returning an array containing objects

### ISSUE THREAD

**Issue by JenniferFalkenstein** [node-opcua/node-opcua#1073]
**Current behavior**
The javascript-method `getFoodInformations()` is a serverscript on an opcua server. It returns an array, containing objects, e.g. like this:
`return [{ name: "Apple", isFavorite: true }, { name: "chocolate", isFavorite: true }]`
Node-OPCUA just calls this method with no parameter and wants to receive the return-value.

**Describe the bug**
When I extract the result of `ClientSession.call` with `JSON.stringify()`, I can see that the call returns
`value: [{ dataType: "Null", arrayType: "Scalar" }]`
I already tried returning other types, like strings, numbers, one object and also string-arrays and number-arrays. This bug only seems to appear, when it's an array of objects. Of course I could `JSON.stringify()` the return-value of my method and then parse it in my node.js-code, but that doesn't sound like a nice solution to me, only as a workaround for the time being.
Is this "bug" possible to fix or is there a nicer workaround? Is this even a bug from `node-opcua` or does it work fine with another opcua server?

**Step by step instruction to reproduce**

1. write a method on an opcua server, which returns an object-array
2. call this method with `ClientSession.call()`
3. extract the `outputArguments` of the call-result

**Expected behavior**
It should return the requested array with the objects and not nothing

**Screenshots**
I added a screenshot of the script lying on the opcua server
![method on opcua server](https://user-images.githubusercontent.com/80680536/139855607-838abfa3-23d0-42ec-850c-27e3053bb702.JPG)
and the result coming back from `ClientSession.call()` (please ignore the input arguments 😃)
![json](https://user-images.githubusercontent.com/80680536/139855655-5997fa7b-4d29-4977-9153-79c8f7f5017e.JPG)

**Gist**

 
gist:

**Context**

- (x) my request is related to node-opcua acting as an OPCUA CLIENT
- ( ) my request is related to node-opcua acting as an OPCUA SERVER

- ( ) I have installed node-opcua from source ( using git clone)
- (x) I have installed node-opcua as a package ( using npm install ) (I don't remember it anymore, but I think it was npm)
- ( ) I am using an application that uses node-opcua

    - ( ) node-red
    - ( ) other : please specify

- Device: ______
- OS version: ______

    - (x) Windows : version : 10
    - ( ) Linux : version : ______
    - ( ) MacOs : version : ______
    - ( ) Raspbian: version : ______
    - ( ) Other : specify : ______

- Description of the other OPCUA system I am trying to connect to:

    - Name: ______
    - Version: _______
    - Manufacturer/Software vendor: _______
    - link to the manufacturer or product site: https://

- **node-opcua version:** :
- "node-opcua-client": "^2.47.0"
  
  

- **Node:**
  `node --version` = v14.17.4

**Comment by erossignon** [comment]
The object in the array need to be constructed as Extension Object inside the getFoodInformation function. Plain Old JavaScript Object cannot be used directly as they need to be typed with a corresponding OPCUA DataType.

Refer to [NodeOPCUA by Example](https://leanpub.com/node-opcuabyexample-edition2022) chapter 10: 10 extension objects for an example of use.
