### ISSUE TITLE
Function break from Node-opcua 2.56.0 -> 2.57.0 possibly due to the change done against [3325f6c] 

### ISSUE THREAD

**Issue by Graos** [node-opcua/node-opcua#1081]
Node-opcua (Server) :2.57.0

Register a call back when server is closed

**e.g code snippet:**

this.server.on("session_closed", this.closeSessionEventCallback);
closeSessionEventCallback(session) {
....
}

initiate a close from Client to Node-opcua server
session object passed as function parameter to the registered callback function has the following wrong values:

session.aborted = true and session.channel is undefined.

The above flag session.aborted  is false and channel contains a valid object in node-opcua version 2.56.0 when connection is closed from client.

**Comment by erossignon** [comment]
Correct. the behavior is now the intended one. 

session.aborted = true  & session.channel is undefined is the  new expected behavior.

**Comment by Graos** [comment]
Thanks for the information.
