### ISSUE TITLE
NodeJS OPC UA Client - Extension Object Handling

### ISSUE THREAD

**Issue by mohitkumaragarwal** [node-opcua/node-opcua#1107]
**I'm submitting a question  (check one with "x")
 - (x ) support request 

**Current behavior**
Hello,

I have an OPC UA Server which is running and has few complex data types.

I am trying to use the OPC UA Client from Node JS - https://github.com/node-opcua/.....cua-sample and trying to read an extension object.

I have also referred to the NodeJS Handbook - node-opcuabyexample.pdf and the example says, to parse the Extension Object, it says just do the following: console.log(dataValue.toString());

But, when I try to do that, I get the following output for one of the structures:

New Value = { /* DataValue */
value: Variant(Array<ExtensionObject>, l= 2, value=[/* OpaqueStructure */ {
nodeId ns=1;i=5017
buffer =
00000000: 03 00 00 00 56 49 4e 08 00 00 00 45 59 58 31 32 34 35 36 ....VIN....EYX12456

},/* OpaqueStructure */ {
nodeId ns=1;i=5017
buffer =
00000000: 0d 00 00 00 53 4f 43 4b 45 54 5f 4e 55 4d 42 45 52 01 00 00 00 33 ....SOCKET_NUMBER....3

}])
statusCode: Good (0x00000)
serverTimestamp: 2022-01-04T09:35:12.501Z $ 526.000.000
sourceTimestamp: 1601-01-01T00:00:00.000Z $ 000.000.000
}

How DO I parse extension objects so that I can map respective values correctly. Currently the output is in the binary form but the NodeJS example does NOT any details on parsing the structure field accordingly.
**Expected behavior**

**Please tell us about your environment:**

  * (x) my request is related to node-opcua acting as a  OPCUA CLIENT 

  * (x) I have installed node-opcua as a package ( using npm install )
        
  * Device: Dell Laptop
  * OS version: Windows 10    
    - ( ) Windows : version : 20H2
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name: OPC UA Flex SDK Server - Based on Matrikon Flex SDK.
     - Version: This is an application on top of Matrikon Flex SDK 5.0 Version
     - Manufacturer/Software vendor: Matrikon Flex SDK
     - link : https://
     
    
* **node-opcua version:**  :
https://github.com/node-opcua/node-opcua-sample

**Comment by AndreasHeine** [comment]
have you tried latest version of node-opcua?

**Comment by mohitkumaragarwal** [comment]
Hi,
I tried with latest base from the below link: https://github.com/node-opcua/node-opcua
Is there any specific version you would like me to try?

Best regards,

Mohit Agarwal
System Architect
R&D System Solutions
________________________________
AC MVI GI
Atlas Copco Industrial Technique AB

Visitor Address: Sickla Industriväg 19, Stockholm, 131 54, Sweden
Postal Address: 105 23, Stockholm, 131 54 Nacka, Stockholm

Phone: +46 (0) 87438290 - Mobile: +46 (0) 766961990
E-mail: ***@***.******@***.***>

Visit Atlas Copco at:   http://www.atlascopco.com<http://www.atlascopco.com/>
Follow us at:  Facebook<https://www.facebook.com/atlascopco> - LinkedIn<http://www.linkedin.com/company/atlas-copco> - Twitter<https://twitter.com/AtlasCopcoGroup> - YouTube<http://www.youtube.com/user/atlascopcogroup> - Instagram<https://www.instagram.com/atlascopcogroup/>
________________________________
Home of Industrial Ideas

**Comment by AndreasHeine** [comment]
https://github.com/node-opcua/node-opcua/commit/d9c9930eb0a5a80322393364cdc59e8dbcfc9cf2 :
> In 1.04, the definition of extension Object is now attached the
> corresponding dataType object.
> In 1.03 the extension object definition was store into a embedded
> BSD in a DataTypeSystemType. This required a complex preparation
> on the client side.
> 
> DataType
>   | 1
>   |
>   | n
>   +-HasEncoding-> "Default Binary" (O)[DataTypeEncodingType]
>                      |
>                      +-HasDescription->"MyItemType" (V)[DataTypeDescriptionType]
>                                          |
> 					 +-ComponentOf->Schema(V) []
>                                               |
>                                               +-ComponentOf->OPC Binary(V)[DataTypeSystemType]
> 
> Up to recently, 1.04 servers was mainly mixing the 1.03 and 1.04
> approcah in the address space.
> New 1.04 server are now only exposing dataType definition inside
> the DataTypeDefinition attribute of the DataType Object and do not
> expose the DataTypeDescriptionType nor the Schema nodes
> 
> In this commit, we introduce support for this new setup.

would be interesting what matrikon uses 1.03 or 1.04!

**Comment by mohitkumaragarwal** [comment]
Thanks for the response, Matrikon SDK which I am using is based on 1.04 and from the CS NodeSet perspective, I have removed the TypeDictionary node which is deprecated since NodeOPC earlier was not able to read the built-in type due to that.

So, I have 1.04 based OPC UA Server and trying to parse the CS specific extension object. Are there any specific APIs which I can refer or any example on parsing user defined structures on the client side?

Also, I have pulled the latest commit from the NodeOPCUA GIT.

Best regards,
Mohit Agarwal

**Comment by AndreasHeine** [comment]
i guess this is what happens:

https://github.com/node-opcua/node-opcua/blob/90bb9139261a0edbb531081afcc6904c74e9ee52/packages/node-opcua-extension-object/source/extension_object.ts#L158

https://github.com/node-opcua/node-opcua/blob/90bb9139261a0edbb531081afcc6904c74e9ee52/packages/node-opcua-extension-object/source/extension_object.ts#L125

**Comment by mohitkumaragarwal** [comment]
Thank you again, the link explains the decoding of extension object as opaque structure, but how can I make it to a meaningful structure? Any suggestion or example would be really helpful.

Best regards,

Mohit Agarwal
System Architect
R&D System Solutions
________________________________
AC MVI GI
Atlas Copco Industrial Technique AB

Visitor Address: Sickla Industriväg 19, Stockholm, 131 54, Sweden
Postal Address: 105 23, Stockholm, 131 54 Nacka, Stockholm

Phone: +46 (0) 87438290 - Mobile: +46 (0) 766961990
E-mail: ***@***.******@***.***>

Visit Atlas Copco at:   http://www.atlascopco.com<http://www.atlascopco.com/>
Follow us at:  Facebook<https://www.facebook.com/atlascopco> - LinkedIn<http://www.linkedin.com/company/atlas-copco> - Twitter<https://twitter.com/AtlasCopcoGroup> - YouTube<http://www.youtube.com/user/atlascopcogroup> - Instagram<https://www.instagram.com/atlascopcogroup/>
________________________________
Home of Industrial Ideas

**Comment by AndreasHeine** [comment]
hey, sorry for the delay i was looking into:
https://github.com/node-opcua/node-opcua/blob/master/packages/node-opcua-client-dynamic-extension-object/source/populate_data_type_manager.ts
but i have not manage to get it work without error!
@erossignon not sure why it tells me: "FIX YOUR APP BECAUSE OF SIMULTANIOUS REQUESTS"!? 
is it ment to be used from client side?

**Comment by mohitkumaragarwal** [comment]
Hi,

No problems and thanks again. I have following the below steps:


  *   Node OPC UA: Taken the latest master branch code from https://github.com/node-opcua/node-opcua
  *   Node OPC UA Sample Client:
     *   Taken the latest master branch code from https://github.com/node-opcua/node-opcua-sample
     *   Replaced the node_modules in this folder with the newer version of  https://github.com/node-opcua/node-opcua
  *   Connected Unified Automation UaCpp Server with following endpoint and monitored a node below by updating the two variables in simple_client.js
     *   const endpointUrl = "opc.tcp://localhost:48010";
     *   const nodeId = "ns=3;s=ControllerConfigurations";
  *   From the command line, ran the following command: node .\simple_client.js
     *   I get the attached output from the command. Basically, I am getting the binary stream and now, I wanted to parse it as a meaningful structure.  So, I am not sure how to do that with NodeOPCUA.

Best regards,
Mohit Agarwal
