### ISSUE TITLE
node-opcua-file-transfer error adding file transfer node to server

### ISSUE THREAD

**Issue by pelis** [node-opcua/node-opcua#1111]
**Current behavior**
I am running the following code from one of the given server examples (converted from type script to java script)

```
const {
    OPCUAServer,
    UAFileType
}  = require("node-opcua");

const {installFileType, getFileData } = require("node-opcua-file-transfer");
const fs = require("fs");

const my_data_filename = "c:/temp/someFile.txt";
fs.writeFileSync(my_data_filename, "some content", "utf8");

(async () => {
    try {
        const server = new OPCUAServer({
            port: 26540,
        });

        await server.initialize();

        // now add a file object in the address Space
        const addressSpace = server.engine.addressSpace;
        const namespace = addressSpace.getOwnNamespace();

        // retrieve the FileType UAObjectType
        const fileType = addressSpace.findObjectType("FileType");

        // create a instance of FileType
        const opcuaFile = fileType.instantiate({
            nodeId: "s=MyFile",
            browseName: "MyFile",
            organizedBy: addressSpace.rootFolder.objects,
        });

        // now bind the opcuaFile object with our file
        installFileType(opcuaFile, {
            filename: my_data_filename,
        });

        await server.start();
        console.log("Server is now listening on port 26540.. ( press CTRL+C to stop)");
       
    } catch (err) {
        console.log("err", err);
    }
})();
```
**The folowing Exception is in line installFileType(...)**  
```
err Error:  bindVariable : the value getter function returns a invalid result ( expecting a Variant or a StatusCode !!!
    at UAVariableImpl.timestamped_get_func_from__Variable_bind_with_simple_get [as _timestamped_get_func] (c:\labor\opcua\node_modules\node-opcua-address-space\dist\src\ua_variable_impl.js:1656:19)
    at UAVariableImpl._Variable_bind_with_timestamped_get (c:\labor\opcua\node_modules\node-opcua-address-space\dist\src\ua_variable_impl.js:1623:50)
    at UAVariableImpl._Variable_bind_with_simple_get (c:\labor\opcua\node_modules\node-opcua-address-space\dist\src\ua_variable_impl.js:1668:41)
    at UAVariableImpl.bind_getter (c:\labor\opcua\node_modules\node-opcua-address-space\dist\src\ua_variable_impl.js:1731:40)
    at UAVariableImpl.bindVariable (c:\labor\opcua\node_modules\node-opcua-address-space\dist\src\ua_variable_impl.js:892:21)
    at new FileTypeData (c:\labor\opcua\node_modules\node-opcua-file-transfer\dist\server\file_type_helpers.js:45:24)
    at installFileType (c:\labor\opcua\node_modules\node-opcua-file-transfer\dist\server\file_type_helpers.js:475:23)
    at c:\labor\opcua\file_server2.js:35:9
```

Additionally, it seems that **UAFileType** is not contained in node-opcua but in node-opcua-file-transfer

**Context**

- ( ) my request is related to node-opcua acting as an OPCUA CLIENT
- (x) my request is related to node-opcua acting as an OPCUA SERVER

- ( ) I have installed node-opcua from source ( using git clone)
- (x) I have installed node-opcua as a package ( using npm install )
- ( ) I am using an application that uses node-opcua

    - ( ) node-red
    - ( ) other : please specify

- Device: Windows PC
- OS version: windows 10

    - ( ) Windows : version : 10
    - ( ) Linux : version : ______
    - ( ) MacOs : version : ______
    - ( ) Raspbian: version : ______
    - ( ) Other : specify : ______

- Description of the other OPCUA system I am trying to connect to:

    - Name: ______
    - Version: ______
    - Manufacturer/Software vendor: ______
    - link to the manufacturer or product site: https://

- **node-opcua version:** :
2.63.2 (also tried earlier versions)

- **Node:**
  `node --version` = 14.16.0

**Comment by erossignon** [comment]
This happens when you have node-opcua-* packages that do not match the same version.
Please make sure that you upgrade all your node-opcua-<name> to the same version..
One way to do this is to use the npm-check-updates package


```` 
npx npm-check-update -u -p "node-opcua*" 
````

**Comment by pelis** [comment]
Thanks Etienne,

I actually used npm to update everything, however, it did not seem to work.
Finally, I removed and re-installed the whole thing and now it does work (I have tested js and ts).
However, in .ts I had to modify the sample source, installFileType seems to expect UAFile rather than UAFileType.

One more question, just to confirm:
There is no implementation yet for FileDirectoryType - correct?

Thanks again, please feel free to close this issue.

**Comment by erossignon** [comment]
> installFileType seems to expect UAFile rather than UAFileType.

Yes, UAFileType was wrongly used before, we fixed this.

FileDirectoryType is not yet implemented as we do not have customers using it yet.
If you want to get it implemented by us, let's talk ( drop me a mail at contact@sterfive.com)

**Comment by erossignon** [comment]
For the record, FileDirectoryType is now implemented and is available to NodeOPCUA Support Subscription members.
