### ISSUE TITLE
Allow event chaining to support asynchronous functions

### ISSUE THREAD

**Issue by bruceceng** [node-opcua/node-opcua#1112]
**Is your feature request related to a problem? Please describe.**

It is often the case that the OPC-UA server needs to go out an get some data in order to handle a request. For example, to browse the node, the OPC-UA server may need to call a web service. These calls are often implemented using asynchronous functions or callbacks.

**Describe the solution you'd like**

There should be a function that removes the default response function and then allows the event handler function to call the default response function after its asynchronous callbacks have resolved.

**Describe alternatives you've considered**

I found a hacky way to achieve this:
At the start of the event handler, I do the following:

```
            //first remove the default event handler
            //to do so, we need to change the schema.name
            request.schema.name = "DeferBrowseRequest";
            //we also have to make a function to handle this so we don't get an error

            let captureMessage = null;
            server["_on_DeferBrowseRequest"] = function(message, channel) {
                console.log("--- Not doing anything for now ---");
                captureMessage = message; //actually we do need to capture the message.
            }
```

Then after my asynchronous event has resolved I do this:

```
            //now we can run the default browse request handler.
            //since we have done some awaiting, it will have already resolved.
            request.schema.name = "BrowseRequest";
            console.log("is still browse request?",captureMessage);
            server["_on_BrowseRequest"].apply(server,[captureMessage, channel]);
```

**Additional context**

It would be better to add this to the public API so that I can confidently use this mechanism without worrying that future changes to the node-opcua library will break my hacky solution.

**Comment by erossignon** [comment]
There is a mechanism that exists for this in the professional edition of node-opcua to cover async operation during browse. This is not available in the public API community edition.  ( contact us or subscribe to https://support.sterfive.com )
