### ISSUE TITLE
Disable publish of initial Value 

### ISSUE THREAD

**Issue by opcua-user** [node-opcua/node-opcua#1113]
**I'm submitting a ...**  (check one with "x")

 - ( ) bug report => search github for a similar issue or PR before submitting
 - ( ) feature request

 - (x) support request 

When I monitor a variable, I first get the initial value and then it reacts to changes. Is it possible to disable the publish of the initial value?

**Please tell us about your environment:**

  * (x) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * ( )  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * (x) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
       - ( ) node-red
       - ( ) other : please specify 
       
    
* **node-opcua version:**  : 2.63.2

* **Node:** 
   `node --version` = v14.18.1

* **Typscript:** 
   `tsc --version` = 4.5.5

**Comment by erossignon** [comment]
The OPCUA  specifications require that the initial value is sent once the monitored item is created. 
You would have to ignore the first notification on your end.
