### ISSUE TITLE
findNode throws assert error when providing wrong namespace

### ISSUE THREAD

**Issue by bruceceng** [node-opcua/node-opcua#1118]
**Current behavior**

Running the following: 

`namespace.findNode("ns=0;i=85")`

will throw an error:

> Error
>     at assert (C:\Users\bruce.eng\Documents\bifrost-opcua\node_modules\node-opcua-assert\dist\index.js:11:21)
>     at NamespaceImpl.findNode2 (C:\Users\bruce.eng\Documents\bifrost-opcua\node_modules\node-opcua-address-space\dist\src\namespace_impl.js:190:40)
>     at NamespaceImpl.findNode (C:\Users\bruce.eng\Documents\bifrost-opcua\node_modules\node-opcua-address-space\dist\src\namespace_impl.js:200:21)
>     at [USER-CODE]

**Describe the bug**

If a node isn't found but the namespace is correct, the function returns null.

**Step by step instruction to reproduce**

1. Start with the example server
2. Add the code: `namespace.findNode("ns=0;i=85");` to the end of the constructAddressSpace function
3. Start the example server

**Expected behavior**

It should return null since this node isn't found in the namespace. Having separate behavior for the namespace not matching vs not finding the node in the namespace is a questionable design choice since it means that an arbitrary string can't be safely passed to findNode without wrapping everything in a try {} catch {}. 

Additionally, the documentation doesn't provide any information about what will happen if the node isn't found.

**Screenshots**

**Gist**

gist:

**Context**

- ( ) my request is related to node-opcua acting as an OPCUA CLIENT
- (X) my request is related to node-opcua acting as an OPCUA SERVER

- ( ) I have installed node-opcua from source ( using git clone)
- (X) I have installed node-opcua as a package ( using npm install )
- ( ) I am using an application that uses node-opcua

    - ( ) node-red
    - ( ) other : please specify

- Device: Intel PC
- OS version: ______

    - (X) Windows : version : 10
    - ( ) Linux : version : ______
    - ( ) MacOs : version : ______
    - ( ) Raspbian: version : ______
    - ( ) Other : specify : ______

- Description of the other OPCUA system I am trying to connect to:

    - Name: ______
    - Version: ______
    - Manufacturer/Software vendor: ______
    - link to the manufacturer or product site: https://

- **node-opcua version:** : 2.64.0
-
2.64.0
- **Node:**
  `node --version` = v14.15.4

**Comment by AndreasHeine** [comment]
hey!
in my oppinion if you look up a nodeid in the wrong namespace (the one you use the findNode) it should throw an error!?

why not:
```js
const node = addressSpace.findNode(`ns=0;i=85`)
```
instead of:

```js
const node = namespace.findNode(`ns=0;i=85`)
```
