### ISSUE TITLE
Version 2.64.1 can cause problems in Windows

### ISSUE THREAD

**Issue by marcodisarno** [node-opcua/node-opcua#1125]
**Current behavior**

When installing 2.64.1's node-opcua-server package from npm, we receive a corrupt package, in the way that there is the same file twice, once with a capital first letter as only distinction: `i_register_server_manager.d.ts`

![image](https://user-images.githubusercontent.com/14130041/158560235-fcad86bf-933a-4f66-9993-e725865ba58b.png)

So of course, I can switch to another version (doesn't happen in 2.65.1, e.g.), this is more to help that this doesn't happen to future releases.

**Describe the bug**

Both files are being extracted to the same folder, thus, once get's overwritten in windows file systems (unix can handle that, though I'd still consider it a bad thing to to).

Now (on my setup at least) this leads to the file being scrambled up when overwritten (which seems to be the fallback used on windows due the filesystem limitations):

![image](https://user-images.githubusercontent.com/14130041/158561336-e6db2fe5-960e-4b80-aae1-140715e600ea.png)

This of course, doesn't compile:

`node_modules/node-opcua-server/dist/i_register_server_manager.d.ts(16,3): error TS1005: ';' expected.
node_modules/node-opcua-server/dist/i_register_server_manager.d.ts(16,38): error TS1002: Unterminated string literal.
node_modules/node-opcua-server/dist/i_register_server_manager.d.ts(17,1): error TS1128: Declaration or statement expected.
`

**Step by step instruction to reproduce**

1. npm install node-opcua-server@2.64.1
2. use the server API with typescript
3. run tsc

**Expected behavior**

Should work ;)

**Screenshots**

**Gist**

 
gist:

**Context**

- ( ) my request is related to node-opcua acting as an OPCUA CLIENT
- (X) my request is related to node-opcua acting as an OPCUA SERVER

- ( ) I have installed node-opcua from source ( using git clone)
- (X) I have installed node-opcua as a package ( using npm install )
- ( ) I am using an application that uses node-opcua

    - ( ) node-red
    - ( ) other : please specify

- Device: ______
- OS version: Windows 10 Enterprise 

    - (X) Windows : version : 20H2
    - ( ) Linux : version : ______
    - ( ) MacOs : version : ______
    - ( ) Raspbian: version : ______
    - ( ) Other : specify : ______

- Description of the other OPCUA system I am trying to connect to:

    - Name: ______
    - Version: ______
    - Manufacturer/Software vendor: ______
    - link to the manufacturer or product site: https://

- **node-opcua version:** : 2.64.1
  
  

- **Node:**
  `node --version` =

**Comment by erossignon** [comment]
Well, spotted! Thank. The problem is not easily reproducible bu you found the root cause: 2 files with almost identical name ( lower/upper case difference)
As you said newer version 2.65.0 doesn't exhibit the same issue.
whereas we are using windows mos of the time, it occurs that 2.64.1 was built & pack on  a Linux where the dist folder was holding old files from a previous version
The counter measure is to build & pack from a fresh clean folder or clean the dist folders before transpiring.
