### ISSUE TITLE
[QUESTION]: How to raise events with custom message, etc.?

### ISSUE THREAD

**Issue by DStr276** [node-opcua/node-opcua#1131]
I'm trying to implement custom events to transfer internal error messages or warnings of the server application to the client.
For this task I tried to use raiseEvent as described in the documentation. However, I cannot find any examples for raising events with custom message, severity, etc.

For alarms the following code worked for me:

const eve = await addrS.findEventType(new NodeId(NodeIdType.NUMERIC, 39, 5));
const nid = await addrS.findNode(new NodeId(NodeIdType.NUMERIC, 5011, 6));
		const alarm = namespace.instantiateAlarmCondition(eve, {
			browseName: "AlarmCondition",
			componentOf: nid,
			conditionSource: nid,
			inputNode: vnode,
			optionals: [
				"ConfirmedState", "Confirm" // confirm state and confirm Method
			]
		});
...
var cinf = new ConditionInfo({
		message: "Oh no!",
		serverity: 100,
		retain: true,
	});
	alarm.raiseNewCondition(cinf);

I'm working with custom nodesets (.xml) - I'm not manually adding nodes to the server.

How can I raise events with custom message, severity etc.?

Thanks for the help!

**Context**

- ( ) my request is related to node-opcua acting as an OPCUA CLIENT
- (x) my request is related to node-opcua acting as an OPCUA SERVER

- ( ) I have installed node-opcua from source ( using git clone)
- (x) I have installed node-opcua as a package ( using npm install )
- ( ) I am using an application that uses node-opcua

    - ( ) node-red
    - ( ) other : please specify

- Device: ______
- OS version: ______

    - ( ) Windows : version : 10______
    - ( ) Linux : version : ______
    - ( ) MacOs : version : ______
    - ( ) Raspbian: version : ______
    - ( ) Other : specify : ______

- Description of the other OPCUA system I am trying to connect to:

    - Name: ______
    - Version: ______
    - Manufacturer/Software vendor: ______
    - link to the manufacturer or product site: https://

- **node-opcua version:** :
  
  

- **Node:**
  `node --version` =

**Comment by AndreasHeine** [comment]
hey @DStr276,

you could look into the unittests (probably most accurate):
https://github.com/node-opcua/node-opcua/blob/bb9e5c1160a4362fc33a124ae1476d6bbf102157/packages/node-opcua-address-space/test/alarms_and_conditions/utest_condition.ts#L430

https://github.com/node-opcua/node-opcua/blob/bb9e5c1160a4362fc33a124ae1476d6bbf102157/packages/node-opcua-address-space/test/alarms_and_conditions/utest_condition.ts#L575

or look into one of umati's showcases/samples:
https://github.com/umati/Sample-Server-node-opcua/blob/d64e501579a4b96d92defdc6c1f761b1b80df559/src/serveraddressspace/serveraddressspace.ts#L380

happy coding!

**Comment by DStr276** [comment]
Thanks very much for the links! This helped me a lot!
