### ISSUE TITLE
Loading nodeset XML file fails inside performPostLoadingTasks / makeXmlExtensionObjectReader

### ISSUE THREAD

**Issue by mikakaraila** [node-opcua/node-opcua#1132]
**Current behavior**

**Describe the bug**

**Step by step instruction to reproduce**

1. ....Start server with testsave.xml
2. ....
3. ....

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5184524/162027201-25f71a93-b3a5-4759-bf7d-1441afafdc10.png)

![image](https://user-images.githubusercontent.com/5184524/162023538-a0d3969c-39d4-4f81-bb45-633f1a98c46f.png)

**Gist**

 
gist:

**Context**

- ( ) my request is related to node-opcua acting as an OPCUA CLIENT
- ( X) my request is related to node-opcua acting as an OPCUA SERVER

- ( ) I have installed node-opcua from source ( using git clone)
- ( X) I have installed node-opcua as a package ( using npm install )
- ( ) I am using an application that uses node-opcua

    - (X ) node-red
    - ( ) other : please specify

- Device: _Laptop_____
- OS version: ______

    - (X ) Windows : version : _10_____
    - ( ) Linux : version : ______
    - ( ) MacOs : version : ______
    - ( ) Raspbian: version : ______
    - ( ) Other : specify : ______

- Description of the other OPCUA system I am trying to connect to:

    - Name: ______
    - Version: ______
    - Manufacturer/Software vendor: ______
    - link to the manufacturer or product site: https://

- **node-opcua version:** : 2.66.3
  
  

- **Node:**
  `node --version` = 12.16.2

**Comment by mikakaraila** [comment]
I have emailed corresponding testsave.xml by email for the investigation.

**Comment by mikakaraila** [comment]
This way it will work:
![image](https://user-images.githubusercontent.com/5184524/162030235-909df122-1263-4086-b634-94637c8110ff.png)

![image](https://user-images.githubusercontent.com/5184524/162030078-47ab5b83-b642-4812-8195-f1d06052a1e0.png)

There are commands: getNamespaceIndex and getNamespaces.

**Comment by mikakaraila** [comment]
Latest Prosys UA Simulation server support export nodeset:
https://downloads.prosysopc.com/opcua/simulationserver/Prosys_OPC_UA_Simulation_Server_5_Release_Notes.html

New: Exporting namespace as a NodeSet file (available in Professional Edition only). Right-clicking an instance namespace (namespace with no types) and clicking Export Namespace…​ will save the namespace in a file using the NodeSet format defined in the OPC UA specification .

**Comment by erossignon** [comment]
fixed in node-opcua@2.67.0
