### ISSUE TITLE
node-opcua-server crashes if invalid user identity token certificate is given

### ISSUE THREAD

**Issue by SanderDeWaal1992** [node-opcua/node-opcua#1136]
**Current behavior**

The server crashes when I connect with a client with an invalid user identity token certificate.

**Describe the bug**

The server crashes when I connect with a client with an invalid user token certificate. It is the assertion here:
https://github.com/node-opcua/node-opcua/blob/bb9e5c1160a4362fc33a124ae1476d6bbf102157/packages/node-opcua-server/source/opcua_server.ts#L2079

As you can see there, the error is not used. It immediately crashes because it assumes that the certificate is valid.

**Step by step instruction to reproduce**

1. Connect to the server with an invalid user token certificate (I encountered it while using the node-opcua-client with an PEM formatted certificate as the userIdentity certificate instead of a der formatted certificate, but I believe it can basically be any invalid certificate)
2. See the server crashing with a non-informative 'expecting statusCode' error

**Expected behavior**

Clients can not be trusted so the server should not crash. The error should be logged.
This to prevent easy DOS attacks and guaranteeing that the correct operation of the rest of the system can not be harmed by one client accidentally having an invalid certificate (and not even having a clue what client it is due to lack of logging of the error).  

- **node-opcua version:** :
encountered it on 2.59.0 of node-opcua-server and it is also on current master

- **Node:**
16.13.1

**Comment by SanderDeWaal1992** [comment]
I now also encountered a comparable problem when supplying an invalid subjectAltName extension. In that case the server also crashes because it assumes the certificate contains the expected fields without checking it. 

Does node-opcua have the intention to prevent these kind of easy DOS attacks or protection against accidental misconfigurations (by users of our product over which we have no control)?

**Comment by SanderDeWaal1992** [comment]
I will start working on creating a PR to solve above issues.

**Comment by erossignon** [comment]
fixed in node-opcua@2.70.0
