### ISSUE TITLE
OPC UA Non-Compliance: Endpoint description information returned by node-opcua server does not match.

### ISSUE THREAD

**Issue by Graos** [node-opcua/node-opcua#1170]
NODE-OPCUA stack version : 2.72.2
NODEJS version : v16.15.1

Current Behavior:
 
Endpoint description information returned by node-opcua server in the GetEndPoint Response does not match with the Endpoint description information returned in the Create session response.
Snapshot of wireshark capture GetEndPoint response where the Product URI is returned
![image](https://user-images.githubusercontent.com/69800669/179506173-c5d38e52-c30f-4d00-a1c8-3bb1c07d0d7a.png)

However in the below CreateSession response wireshark capture snapshot Product URI is empty

![image](https://user-images.githubusercontent.com/69800669/179506354-341c72b9-3f06-4303-b58a-5cfb19f5e545.png)

**Expected behavior**
As per the OPC UA compliance spec, endpoint description returned in the GetEndpointResponse and in the CreateSessionResponse by OPC UA server should exactly match .

Test case:
<html>
<body>

Err-023 | CTT | CreateSession | productUris contained in the returned SoftwareCertificates do not match the productUris in the EndpointDescription used by the Client to connect to the Server. |   | Client closes session calling CloseSession.Client logs and/or display an error to the end user.
-- | -- | -- | -- | -- | --

</body>
</html>

- ( ) my request is related to node-opcua acting as an OPCUA SERVER

**Comment by JeanArhancet** [comment]
Hello, 

I tried to reproduce from the master branch but I can't (the endpoint client has a value in this branch https://github.com/node-opcua/node-opcua/compare/master...JeanArhancet:node-opcua:test/1170)

**Comment by Graos** [comment]
Please read my description again and confirm. I have mentioned ProductUri("nodeOPCUA-server") is returned in GetEndPointResponse but not in CreateSessionResponse. Have you tried checking he ProductUri in CreateSessionResponse ? Does the server sends a proper string ?

**Comment by JeanArhancet** [comment]
You're right @Graos, I opened a PR to fix this issue
