### ISSUE TITLE
Problem with monitoring multiple OPC UA nodes  

### ISSUE THREAD

**Issue by abdelhaksam** [node-opcua/node-opcua#1181]
**I'm submitting a ...**

 - [ ] bug report => search github for a similar issue or PR before submitting
 - [ ] feature request
 - [x] support request

  

**Current behavior**

In a client, when monitoring multiple nodes using a `forEach` loop, only two nodes get monitored on version 2.30.0 and only one in 2.72.2 while the array that generates the loop contains 5 items.

Behaviour in 2.30.0
![image](https://user-images.githubusercontent.com/47641482/183917062-483ebce2-fda5-43e2-8dde-6367e800c726.png)

Bahaviour in 2.72.2
![image](https://user-images.githubusercontent.com/47641482/183916891-c9b3cc20-3245-4d4b-9f6a-65c232e949ed.png)

UA Expert screenshot for reference
![image](https://user-images.githubusercontent.com/47641482/183922996-0c29d7c4-f506-48ad-8f9f-96e9e09b1dff.png)

**Expected behavior**

The expected behavior is that all the item nodes get processed.

**Code source for the reproduction of the problem**

```
const idsToMonitor = ["ns=4;i=16", "ns=4;i=17", "ns=4;i=11", "ns=4;i=12", "ns=4;i=18"]
const monitoringParamaters = {
				samplingInterval: 100,
				discardOldest: true,
				queueSize: 10,
			};
			idsToMonitor.forEach((nodeId) => {
				opc_subscription.monitor(
					{
						nodeId: resolveNodeId(nodeId),
						attributeId: AttributeIds.Value,
					},
					monitoringParamaters,
					TimestampsToReturn.Both,
					(err, monitoredItem) => {
						monitoredItem.on("changed", function (dataValue) {
							var Node = {nodeId: nodeId, nodeName: "111" , nodeValue: dataValue.value.value , nodeTimestamp: dataValue.sourceTimestamp.toISOString()};
							console.log(JSON.stringify(Node));
						});
					}
				);
			});

```

**Please tell us about your environment:**

  * [X] my request is related to node-opcua acting as a  OPCUA CLIENT 
  * [ ]  my request is related to node-opcua acting as a OPCUA SERVER 

  * [ ] I have installed node-opcua from source ( using git clone)
  * [X] I have installed node-opcua as a package ( using npm install )
  * [ ] I am using an application that uses node-opcua 
       - ( ) node-red
       - ( ) other : please specify 
        
  * OS version: Windows 10
    
  * Description of the other OPCUA system I am trying to connect to:
     - Name: SIMATIC OPC UA
     - Manufacturer/Software vendor: Siemens  
    
* **node-opcua version:**  :

* **Node:** 
   `node --version` = 16.16.0

**Comment by erossignon** [comment]
`subscription.monitor` is an async method that must be called sequentially ( with an await keyword)
Unfortunately, javascript doesn't allow this to happen in the lambda of a forEach method.
 

Please consider using a monitor item group instead.

Refer to the documentation available on our tutorial book "node-opcua by example"
