### ISSUE TITLE
Alarm_Tools EventFilter SelectClause contains two entries for ConditionId, instead of one

### ISSUE THREAD

**Issue by Koseng** [node-opcua/node-opcua#1183]
**Current behavior**
In ```client_alarm_tools_acknowledge_all_conditions``` and ```client_alarm_tools``` the SelectClause in the created EventFilter contains two entries for the ConditionId instead of one. A wrong one and a correct one. I found out, because I used the same pattern "extractConditionFields" -> "constructEventFilter" in the node-red opc ua library. I am not sure to what issues that leads in those two components.

**Describe the bug**
In ```client_alarm_tools_acknowledge_all_conditions``` and ```client_alarm_tools``` the SelectClause in the created EventFilter contains two entries for the ConditionId insetad of one. A wrong one and a correct one. I found out, because I used the same pattern "extractConditionFields" -> "constructEventFilter" in the node-red opc ua library. I am not sure to what issues that leads in those two components.

**Step by step instruction to reproduce**

- Execute "findActiveConditions" and inspect eventFilter
- Execute "installAlarmMonitoring" and inspect eventFilter

**Expected behavior**

**Context**

- (x ) my request is related to node-opcua acting as an OPCUA CLIENT
- ( ) my request is related to node-opcua acting as an OPCUA SERVER

- ( ) I have installed node-opcua from source ( using git clone)
- (x) I have installed node-opcua as a package ( using npm install )
- ( ) I am using an application that uses node-opcua

    - ( ) node-red
    - ( ) other : please specify

**Comment by erossignon** [comment]
fixed in node-opcua@2.75.0

you can now use more advanced whereClauses, as well.
