### ISSUE TITLE
BindVariableOptionsVariation1 getFunc can not be use async function

### ISSUE THREAD

**Issue by MichaelTsengXD** [node-opcua/node-opcua#1190]
**Current behavior**
BindVariableOptionsVariation1 getFunc can not be use async function

**Describe the bug**
In server, BindVariableOptionsVariation1 getFunc can use async function?
I try to use async function in BindVariableOptionsVariation1 getFunc, but occur "Bind variable error:   : the getter must return a Variant or a StatusCode... value_check.constructor.name  Promise"

**Step by step instruction to reproduce**

1. Red frame, I use get: async () => { // async function get value to value };
![擷取](https://user-images.githubusercontent.com/100653092/187661429-124d54ac-e6d5-4931-a646-fd82198a0b6b.PNG)

**Expected behavior**

**Screenshots**
Code
![image](https://user-images.githubusercontent.com/100653092/187662639-883d08fb-a8c2-4d32-b140-c254c19ad290.png)

Error Message
![image](https://user-images.githubusercontent.com/100653092/187662341-a5ead096-2697-4b9c-8ba8-44003c927388.png)

**Gist**

 
gist:

**Context**

- ( O ) my request is related to node-opcua acting as an OPCUA CLIENT
- ( ) my request is related to node-opcua acting as an OPCUA SERVER

- ( ) I have installed node-opcua from source ( using git clone)
- ( ) I have installed node-opcua as a package ( using npm install )
- ( ) I am using an application that uses node-opcua

    - ( ) node-red
    - ( ) other : please specify

- Device: ______
- OS version: ______

    - ( O ) Windows : version : _Win10_
    - ( ) Linux : version : ______
    - ( ) MacOs : version : ______
    - ( ) Raspbian: version : ______
    - ( ) Other : specify : ______

- Description of the other OPCUA system I am trying to connect to:

    - Name: ___Kepware___
    - Version: ___V6.11.764.0___
    - Manufacturer/Software vendor: ___PTC___
    - link to the manufacturer or product site: https://www.kepware.com/en-us/

- **node-opcua version:** :

  
  

- **Node:**

  `node --version` = v14.20.0

**Comment by AndreasHeine** [comment]
you need to look in BindVariableOptionsVariation2 -> timestamped_get -> !!! callback-pattern !!!

```js
timestamped_get: function(
    this: UAVariable, 
    callback: (err: Error | null, dataValue?: DataValue) => void): void {
    somePromiseReturningTheValue
    .then((val) => {
        callback(null, new DataValue({
            value: new Variant({
                value: val,
                dataType: dtype
            }),
            statusCode: StatusCodes.Good,
        }));
    })
}
```

**Comment by MichaelTsengXD** [comment]
> you need to look in BindVariableOptionsVariation2 -> timestamped_get -> !!! callback-pattern !!!
> 
> ```js
> timestamped_get: function(
>     this: UAVariable, 
>     callback: (err: Error | null, dataValue?: DataValue) => void): void {
>     somePromiseReturningTheValue
>     .then((val) => {
>         callback(null, new DataValue({
>             value: new Variant({
>                 value: val,
>                 dataType: dtype
>             }),
>             statusCode: StatusCodes.Good,
>         }));
>     })
>     .catch((err) => {
>         //...
>     })
> }
> ```

BindVariableOptionsVariation2 -> timestamped_get can use, but occur "asyncRefresh error: Variable is   ns=2;s=Variable01 2:Variable01"、"refresh call failed 2:Variable01 ns=2;s=Variable01 Cannot create property 'dataType' on string 'value' "...

Code
![image](https://user-images.githubusercontent.com/100653092/187679432-46961301-029d-47da-9664-07854c02c189.png)

Error Message
![image](https://user-images.githubusercontent.com/100653092/187680133-6332196e-4caa-445b-bc09-8ea3e3dbbc48.png)

How do I fix my code ? Thank!

**Comment by AndreasHeine** [comment]
you can not use async/await syntax directly...!

**Comment by AndreasHeine** [comment]
timestamped_get expects a function like this:
function(this: UAVariable, callback: (err: Error | null, dataValue?: DataValue) => void): void

just use getValue(key) as a promise:

```js
getValue(key).then((val) => {
    callback(null, new DataValue({
        value: new Variant({
            value: val,
            dataType: dtype
        }),
        statusCode: StatusCodes.Good,
    }));
})
.catch((err) => {
    //...
})

```

**Comment by MichaelTsengXD** [comment]
> You need to use the second form to get async method working as you expect
> 
> ```ts
> export type GetFunc = (this: UAVariable) => Variant;
> export type SetFunc = VariableSetter | null;
> 
> export type VariableDataValueGetterSync = (this: UAVariable) => DataValue;
> export type VariableDataValueGetterPromise = (this: UAVariable) => Promise<DataValue>;
> export type VariableDataValueGetterCallback = (this: UAVariable, callback: CallbackT<DataValue>) => void;
> 
> export type VariableDataValueSetterWithCallback = (this: UAVariable, dataValue: DataValue, callback: CallbackT<StatusCode>) => void;
> export type VariableDataValueSetterWithPromise = (this: UAVariable, dataValue: DataValue) => Promise<StatusCode>;
> 
> export type TimestampGetFunc = VariableDataValueGetterSync | VariableDataValueGetterPromise | VariableDataValueGetterCallback;
> export type TimestampSetFunc = VariableDataValueSetterWithCallback | VariableDataValueSetterWithPromise;
> 
> export interface BindVariableOptionsVariation1 {
>     get: GetFunc;
>     set?: SetFunc;
>     timestamped_get?: undefined;
>     timestamped_set?: undefined;
>     historyRead?: HistoryReadFunc;
> }
> export interface BindVariableOptionsVariation2 {
>     set?: undefined;
>     get?: undefined;
>     timestamped_get: TimestampGetFunc;
>     timestamped_set?: TimestampSetFunc;
>     historyRead?: HistoryReadFunc;
> }
> ```
> 
> timestamped_get can be a VariableDataValueGetterPromise `(this: UAVariable) => Promise<DataValue>;`
> 
> in this case you need to return a DataValue ( with Statuscode and timestamps) instead of a Variant



> timestamped_get expects a function like this: function(this: UAVariable, callback: (err: Error | null, dataValue?: DataValue) => void): void
> 
> just use getValue(key) as a promise:
> 
> ```js
> getValue(key).then((val) => {
>     callback(null, new DataValue({
>         value: new Variant({
>             value: val,
>             dataType: dtype
>         }),
>         statusCode: StatusCodes.Good,
>     }));
> })
> .catch((err) => {
>     //...
> })
> ```

**Comment by MichaelTsengXD** [comment]
Thanks for everyone's reply, this issue has been resolve.
