### ISSUE TITLE
Invalid error message on unlimited maxMessageSize (maxMessageSize = 0)

### ISSUE THREAD

**Issue by dani162** [node-opcua/node-opcua#1193]
**Current behavior**

The OPC-UA Client receives a acknowledge message with the max message size set to unlimited (=0) and set the maxMessageSize of the message chunker to that received value.

If the OPC-UA Client now sends a request it always print error messages, because the message size of these messages is greater than zero (see screenshot below)

maxMessageSize = 0 is described as unlimited:
https://reference.opcfoundation.org/v105/Core/docs/Part6/7.1.2/#7.1.2.4

https://github.com/node-opcua/node-opcua/blob/177f468a9bcdedb98fab3d3fb2f87a8af0378e0e/packages/node-opcua-secure-channel/source/client/client_secure_channel_layer.ts#L1184-L1186

https://github.com/node-opcua/node-opcua/blob/156520cbcb95c0f059ffa1aff743cc23b29ae95c/packages/node-opcua-secure-channel/source/message_chunker.ts#L208-L212

**Describe the bug**

The OPC-UA client prints invalid error messages

**Step by step instruction to reproduce**

1. Connect the OPC-UA Client to a OPC-UA Server with a unlimited MaxMessageSize (=0)
2. Send a Request to the OPC-UA Server

**Expected behavior**

No invalid error messages 

**Screenshots**

Error Message:
![image](https://user-images.githubusercontent.com/34603476/188612734-de9ead3b-07cc-4a4c-befc-510c87e9c56d.png)

Acknowledge message:
![image](https://user-images.githubusercontent.com/34603476/188621588-eae5664e-9c4d-4d6b-8d5e-0051da25a772.png)

**Context**

- (x) my request is related to node-opcua acting as an OPCUA CLIENT

- (x) I have installed node-opcua as a package ( using npm install )

- OS version:

    - (x) Windows : version : 11

- Description of the other OPCUA system I am trying to connect to:

    - Close Sourced OPC-UA Server

- **node-opcua version:** : 2.76.2

- **Node:**

  `node --version` = v16.17.0

**Comment by antoniosteiger** [comment]
I have the exact same error. Fix suggestion would be appreciated.

**Comment by erossignon** [comment]
Well spotted, will be fixed in next build
