### ISSUE TITLE
node-opcua log message on RefreshStartEventType and RefreshEndEventType

### ISSUE THREAD

**Issue by AndreasHeine** [node-opcua/node-opcua#1201]
node = 16
node-opcua = 2.77.0

weird log on RefreshStartEventType and RefreshEndEventType if i connect with UaExpert (active event subscription to all server events)

![image](https://user-images.githubusercontent.com/56362817/193240871-8f59f04d-b37c-4976-828f-a2b4d8697283.png)

**Comment by erossignon** [comment]
@AndreasHeine , can you provide more information to reproduce.

- a sample  server.js code
- version of UAExpert affected.

**Comment by AndreasHeine** [comment]
UAExpert: Version 1.5.1 331

**Comment by AndreasHeine** [comment]
the server is just a server with installed A&C Service!

**Comment by AndreasHeine** [comment]
the log is shown every time i do a CondditionRefresh

**Comment by AndreasHeine** [comment]
thanks ;)
