### ISSUE TITLE
"Error: invalid internal state = connected" when calling client.connect after opcua server goes back online

### ISSUE THREAD

**Issue by lann92** [node-opcua/node-opcua#1204]
**Current behavior**

I am using node-opcua for opcua client implementation. 
I have implemented my own reconnection strategy which is based strictly on ```connection_failed```/```close```/connection_lost events. Losing a connection to my opcua server simulator (manually turning off opcua server) throws me a ```Error: _socket has been disconnected by third party``` from the opcua client and ```close``` event is being fired. After turning back on the opcua server, calling client.connect ends up throwing with ```Error: invalid internal state = connected```.

**Describe the bug**

It looks like there is an inconsistent opcua client state. When the opcua server closes the connection, there is some issue with updating the connection state. This bug was introduced in one of the recent releases as it appeared in my application after updating the library.

**Step by step instruction to reproduce**

Constructor called with:
`OPCUAClient.create({
            ...,
            endpoint_must_exist: false,
            connectionStrategy: {
                maxRetry: 0
            },
            ...
        });`

1. Connect to the opcua server with client.connect(...).
2. Turn off the opcua server so the ```CLOSE``` event is fired. For example manually closing the Prosys OPC UA Simulation Server does the job.
3. Try to call client.connect again (it does not matter if the opcua server is running or not). Mentioned error will be thrown.

**Expected behavior**

Calling client.connect again after losing connection should attempt to connect to a opcua server.

**Context**

- (x ) my request is related to node-opcua acting as an OPCUA CLIENT
- ( ) my request is related to node-opcua acting as an OPCUA SERVER

- ( ) I have installed node-opcua from source ( using git clone)
- (x ) I have installed node-opcua as a package ( using npm install )
- ( ) I am using an application that uses node-opcua

    - ( ) node-red
    - ( ) other : please specify

- Device: Macbook PRO M1
- OS version: macOS Monterey 12.6

    - ( ) Windows : version : ______
    - ( ) Linux : version : ______
    - (x ) MacOs : version : Monterey 12.6
    - ( ) Raspbian: version : ______
    - ( ) Other : specify : ______

- Description of the other OPCUA system I am trying to connect to:

    - Name: Prosys OPC UA Simulation Server
    - Version: 5.2.2
    - Manufacturer/Software vendor: Prosys

- **node-opcua version:** : 2.79.1

  
  

- **Node:**

  `node --version` = 16.16.0

**Comment by erossignon** [comment]
> I have implemented my own reconnection strategy which is based strictly

node-opcua has a built-in reconnection strategy ... You do not need to implement your own. 

I guess the two are conflicting.

Contact sterfive privately to organize a code review of your code under professional service.
