### ISSUE TITLE
Import export functionality

### ISSUE THREAD

**Issue by jnovermars** [node-opcua/node-opcua#1206]
**Is your feature request related to a problem? Please describe.**
_No_

**Describe the solution you'd like**
_be able to export with node-opcua-client to a file and be able to import that file into node-opcua-server._

_As working on different OPC-UA projects we need to be onside to connect to the PLC. It would be nice if we could export the structure of an existing PLC (with node-opcua-client) and import it into node-opcua-server._

_This will be very nice to be able to do tests on PLC while not using the original PLC and see the values in the cloned PLC running on node-opcua-server._

_So there is kind of similar request in the past already: https://github.com/node-opcua/node-opcua/issues/348_

**Describe alternatives you've considered**
_Using the crawler, parse it to JSON and import based on that file, but this does not bring the original structure
I am aware of the XML dump functionality but this is only for the server, right?_

**Additional context**
_none_

**Comment by erossignon** [comment]
Have a look at [Sterfive's OPCUA Modeler](https://www.sterfive.com/product/modeler/) . it is based on node-opcua and help you create nodeset2.xml file that you can import to a opcua server.

Alternatively, you can also look at the [OPCUAToolbox from sterfive](https://www.sterfive.com/product/toolbox), this tool allows you to connect to a live OPCUA Server, crawl all nodes in the address space and recreate the nodeSET2.XLM that you can then use to create a node-opcua Server that replicate exactly your original server.
