### ISSUE TITLE
Each monioredItems and Handle

### ISSUE THREAD

**Issue by fatihkutuk** [node-opcua/node-opcua#1212]
Hi iam try mapping monitored items and handle it. Ist my code and ists work ;

          the_subscription.monitorItems(monitoredNodes, monitoringParamaters, TimestampsToReturn.Both, (err, monitoredItems) => {
              monitoredItems.on("changed", function (items,data) {
                  console.log("Node ID: ", items.itemToMonitor.nodeId.value);
                  console.log("Node value: ", data.value.value);
              });
          });

but when i try each data or items response its not work;
**error message : items.each is not a function**

        the_subscription.monitorItems(monitoredNodes, monitoringParamaters, TimestampsToReturn.Both, (err, monitoredItems) => {
            monitoredItems.on("changed", function (items,data) {
                items.each(function (item){
                    console.log("Node ID: ", item.itemToMonitor.nodeId.value);
                   
                })
            });
        });

**Comment by fatihkutuk** [comment]
Mr. @AndreasHeine hi again, After doing some testing, I saw that the change event re-runs for each change, so the returned items object did not include all changes. It was working again for every monitoritem, Why can't I get multiple changes as an array at once ?

**Comment by fatihkutuk** [comment]
Ookey then, Can I build a datachange event that collects the incoming changes and returns all the accumulated changes as an array at the times I specify or is there any solition for this in node-opcua ?

**Comment by erossignon** [comment]
@fatihkutuk  this is not difficult to achieve 

```javascript
const  monitoredItems = await subscription.monitorItems(monitoredNodes, monitoringParamaters, TimestampsToReturn.Both);

const accumulated =[]; 
monitoredItems.on("changed", function(monitoredItem,dataValue, index) {
   accumulated [index] = dataValue;
   doSomething(accumulated );
});
```

**Comment by fatihkutuk** [comment]
Thank u @erossignon. Its working
