### ISSUE TITLE
Connecting simple_server to UAGateway

### ISSUE THREAD

**Issue by indigodv** [node-opcua/node-opcua#122]
Hi, I'm trying to connect the simple_server.js from the bin folder to UAGateway from unified automation. 
Seems like I cannot connect, 
 I always got this server status. 
![image](https://cloud.githubusercontent.com/assets/14814944/10064517/c1628dea-62ab-11e5-8e88-6abc52e6e4a1.png)

I'd already added the certificate on the UAGateway Administration, but still get the same server status.
Any Idea on what I missed??

![image](https://cloud.githubusercontent.com/assets/14814944/10064552/103e7fbe-62ac-11e5-9fed-914fe6bbcabb.png)

**Comment by erossignon** [comment]
you could active some debug output on simple_server
simply set the DEBUG environment variable to "ALL"

dos:
```
set DEBUG=ALL
node bin\simple_server
```

bash:
```
export DEBUG=ALL
node bin/simple_server
```

**Comment by indigodv** [comment]
still no luck.

**Comment by erleeman** [comment]
No Problem to connect UAGateway or UAExpert.

![nodegateway](https://cloud.githubusercontent.com/assets/11767826/13070229/40a9bda2-d48b-11e5-9e65-0277046c67ae.jpg)

Do you use the correct endpointUrl pointed out by the simple_server ?
