### ISSUE TITLE
Unable to establish encrypted channel connection [QUESTION]

### ISSUE THREAD

**Issue by bartlomiejwitek** [node-opcua/node-opcua#1221]
Hello,
I am trying to set up an encrypted channel connection (just TLS, not certificate-based authentication) between an OPCUA server and an OPCUA client - both written using node-opcua library. I have a server certificate signed by a CA. 

Currently my setup looks like that:

**On the server:**
- I am using an instance of a certificate manager,
- Server certificate as .pem is in the certificates directory (root dir for the certificate manager)
- Server private key I have put into the certificates/own/private/private_key.pem
When I try to connect to the server using UA Expert tool it reads the certificate chain so I thin the issue is not there.

**On the client:**
- I take the very exact same certificate that the server uses  (though, I have also tried with RootCA cert but with the same result) and read it into a buffer and then pass to the OPCUAClient constructor in the following manner:
```js
serverCert = fs.readFileSync(path.join(__dirname,'../certificates/trusted/certs/server_cert.pem'));
 
OPCUAClient.create({
      endpoint_must_exist: false,
      securityMode: MessageSecurityMode.SignAndEncrypt,
      securityPolicy: SecurityPolicy.Basic256,
      serverCertificate: serverCert});
```
However, then the application crashes while the method "extractPublicKeyFromCertificateSync" from crypto_utils.js file calls inside jsrsasign.KEYUTIL.getPEM(key). This invocation then returns an error.

```
function extractPublicKeyFromCertificateSync(certificate) {
    certificate = coerceCertificatePem(certificate);
    const key = jsrsasign.KEYUTIL.getKey(certificate);
    const publicKeyAsPem = jsrsasign.KEYUTIL.getPEM(key);
    assert(typeof publicKeyAsPem === "string");
    return publicKeyAsPem;
}
```

The error says:

```
'TypeError: Cannot read properties of null (reading 'substr')\
 at X509.getVersion (c:[...]\\node_modules\\jsrsasign\\lib\\jsrsasign.js:241:588)
 at X509.readCertHex (c:[...]\\node_modules\\jsrsasign\\lib\\jsrsasign.js:241:15688)
 at X509.readCertPEM (c:[...]\\node_modules\\node-opcua-securechannel\\dist\\source\\client\\client_secure_channel_layer.js:251:37)
 at c:[...]\\node_modules\\node-opcua-client\\dist\\private\\client_base_impl.js:454:31
 at c:\\[...]\\node_modules\\async\\dist\\async.js:3674:28'
```

**Question:** Is this a bug or am I doing something fundamentally wrong here. Thank you for any insight and help.

Some important points are that:
- The certificate is passed to the function and the coerceCertificatePem() returns a value (neither undefined nor null, but a proper value).
- I am able to extract the public key from the certificate using openssl `openssl x509 -in server_cert.pem -pubkey -noout >public_key.pem`
- Version of the jsrsasign is 10.6.1 so the newest at this time, from what I have checked.
**Context**

- (x) my request is related to node-opcua acting as an OPCUA CLIENT
- (x) my request is related to node-opcua acting as an OPCUA SERVER

**Comment by erossignon** [comment]
Make sure to read the PEM certificate as a String, not a Buffer
by adding the "utf-8" options to the readFileSync.

```
serverCert = fs.readFileSync(path.join(__dirname,'../certificates/trusted/certs/server_cert.pem', "utf-8"));
```
