### ISSUE TITLE
Fine-control ServerState during startup

### ISSUE THREAD

**Issue by marcodisarno** [node-opcua/node-opcua#1222]
**Is your feature request related to a problem? Please describe.**

We would like to be able to set the `ServerStatus` variable at will during startup, to be able to create some dynamic nodes that are not part of the nodeset.

Until then, we'd like the server to stay in `ServerStatus = CommunicationFault (6)` and only switch to `Running (0)` after we know we are done to prevent clients to exchange data before we're done.

**Describe the solution you'd like**

So the requirements would be:
- be able to start the server in a "to be completed" mode, with the ability to define the state of the server until then.
- actively finish that mode by setting something on the server

**Describe alternatives you've considered**

We have already played around with the idea to call initialize(), then set all the values, then hit start(), but this does not produce the expected result - we cannot connect to the server in this stadium.

**Comment by erossignon** [comment]
you can directly control the Server.Status.State variable from your server

here is an example: 
```
   const server = new OPCUAServer({});

    await server.initialize();

    const addressSpace = server.engine.addressSpace;
    addressSpace.rootFolder.objects.server.serverStatus.state.writeEnumValue("Suspended");

    await server.start();
    console.log("Server is now listening ... ( press CTRL+C to stop)");
    console.log(server.getEndpointUrl());

    const namespace = addressSpace.getOwnNamespace();
    let counter = 0;
    const myHistoricalSetPointVar = namespace.addVariable({
        browseName: "MyHistoricalSetPoint0",
        nodeId: "s=MyHistoricalSetPoint0",
        organizedBy: resolveNodeId("ObjectsFolder"),
        dataType: DataType.Double,
        userAccessLevel: "CurrentRead | CurrentWrite",
        minimumSamplingInterval: 100
    });
    await pause(1000);
    await addressSpace.rootFolder.objects.server.serverStatus.state.writeEnumValue("Running");
    await pause(1000);
    await addressSpace.rootFolder.objects.server.serverStatus.state.writeEnumValue("Test");
    await pause(1000);
    await addressSpace.rootFolder.objects.server.serverStatus.state.writeEnumValue("Running");
    await pause(1000);
    await server.shutdown(1000);
    console.log("Server has shut down");
}
```
