### ISSUE TITLE
DataTypeIds for Date and Time missing

### ISSUE THREAD

**Issue by sgoll** [node-opcua/node-opcua#1243]
**Current behavior**

The enum `DataTypeIds` from package `node-opcua-constants` (re-exported from `node-opcua`) is missing the definitions for the constants `Time` (value of 292) and `Date` (value of 293).

These were present before but were removed in commit 4dd1a7b5a2be428ab2eb156996ca0d296bd0f1f6 in June 2022 by @erossignon which made it into v2.70.0. The [release notes](https://github.com/node-opcua/node-opcua/releases/tag/v2.70.0) list this commit with "introduce nodeset version 1.05" but do not mention the backwards-incompatible removal of previously existing constants.

**Describe the bug**

The enum `DataTypeIds` does not contain the given known constants anymore.

**Expected behavior**

The enum `DataTypeIds` should contain the given known constants.

**Gist**

```ts
import * as opcua from 'node-opcua';

assert(opcua.DataTypeIds.Time === 292);
assert(opcua.DataTypeIds.Date === 293);
```

**Context**

- (x) my request is related to node-opcua acting as an OPCUA CLIENT
- (x) my request is related to node-opcua acting as an OPCUA SERVER

- (x) I have installed node-opcua from source ( using git clone)
- (x) I have installed node-opcua as a package ( using npm install )
- ( ) I am using an application that uses node-opcua

    - ( ) node-red
    - ( ) other : please specify

- Device: ______
- OS version: ______

    - ( ) Windows : version : ______
    - ( ) Linux : version : ______
    - ( ) MacOs : version : ______
    - ( ) Raspbian: version : ______
    - ( ) Other : specify : ______

- Description of the other OPCUA system I am trying to connect to:

    - Name: ______
    - Version: ______
    - Manufacturer/Software vendor: ______
    - link to the manufacturer or product site: https://

- **node-opcua version:** `2.90.0` (but present as early as `2.70.0`)

- **Node:** n/a

**Comment by GoetzGoerisch** [comment]
Thanks @sgoll for this report.

It is correct, that they are no longer present.
These _DataTypes_ have been removed with v1.05.0 here: https://github.com/OPCFoundation/UA-Nodeset/commit/fac8452ec11cdca5e4e0cc9a6fa44c9b19e21359

Please raise an issue with the OPC-F if you find this incorrect: https://mantis.opcfoundation.org/

**Comment by GoetzGoerisch** [comment]
These two DataTypes only appeared in v1.04.10 in the NodeSet, but as far as I can tell, never part of the specification.
Only _DateTime_ _DataType_ was specified in [Part 6: 5.2.2.5](https://reference.opcfoundation.org/Core/Part6/v104/docs/5.2.2.5)

**Comment by erossignon** [comment]
thanks [GoetzGoerisch](https://github.com/GoetzGoerisch)  for the detailed explanation.

* I strongly recommend that you application does not use Date and Time dataType anymore as those types are not supported by the foundation anymore and have been (thankfully) removed in favor of DateTime.

* those id are automatically generated by a tool by processing the material provided by the OPC Foundation (standard nodeset2.xml), not easily suited to automatically detected and marked.
* I will amend the release note with your proposal to highlight that Date & Time has been deleted 
* Typescript is recommended when using node-opcua to spot those things easily.
* please considering [sponsoring Stefive](https://opencollective.com/node-opcua), the editor of node-opcua, or become a member of the [Sterfive NodeOPCUA  Support ](https://support.sterfive.com/) if you consider node-opcua worthwhile for you.
