### ISSUE TITLE
Changing namespaceindex on an opc ua server in node.js

### ISSUE THREAD

**Issue by Newinthistopic** [node-opcua/node-opcua#1247]
Hello everyone,

I have set up an OPC UA server in node.js and generated variables in another js file. Now, I would like to change the Namespace index to organize my variables in a separate Namespace.

Unfortunately, I am not familiar enough with OPC UA and node.js to implement this change on my own. Can someone explain how I can change the Namespace index?

Attached are the code for my variables and the code for the OPC UA server.

I would be very grateful for your help!

Best regards.

module.exports = {
    run: function (namespace, device, opcua, verbose, serverValues) {
    
        
        
        // create ppC_Compound_V3 object
        var ppC_Compound_V3 = namespace.addObject({
            organizedBy: device,
            browseName: "ppC_Compound_V3",
            nodeId: "ns=1;s=PLC",
            description: "The PLC instance which supports you with OPC UA functionality" 
        });

        // create DatablocksGlobal object
        var datablocksGlobal = namespace.addObject({
            organizedBy: ppC_Compound_V3,
            browseName: "DatablocksGlobal",
            nodeId: "ns=1;s=DatablocksGlobal"
        });

        // create ZEEX_3111_Hmi object
        var prefix = namespace.addObject({
            organizedBy: datablocksGlobal,
            browseName: "ZEEX_3111_Hmi",
            nodeId: "ns=1;s=" + "\"ZEEX_3111_Hmi\""
        });

         // create udtEmPz variable undefined Datatype Equipment Module Process Zone
        var udtEmPz = namespace.addVariable({
            componentOf: prefix,
            browseName : "udtEmPz",
            dataType   : opcua.DataType.Double,
            nodeId     : "ns=1;s=" + "\"ZEEX_3111_Hmi\".\"udtEmPz\""  ,         
        });
I want to set the namespace index of the variable "udtEmPz" to 3.

console.log('Starting... please wait!');

const fs = require('fs');

const {
          OPCUAServer,
          OPCUACertificateManager
      } = require("node-opcua");

const certificateManager = new OPCUACertificateManager({
                                                           automaticallyAcceptUnknownCertificate: true,
                                                           rootFolder                           : "./certs",
                                                       });

// Select profile
var profile = 'default';
if (process.argv.length > 2) {
    profile = process.argv[2];
}
var profileDir = __dirname + '/profiles/' + profile;

if (!fs.existsSync(profileDir)) {
    console.log('ERROR: Profile does not exist: "' + profile + '" dir: ' + profileDir);
    process.exit(1);
}

console.log('Using profile "' + profile + '"');

// Functions
const opcua   = require("node-opcua");
var config    = require(profileDir + '/config.json');
const jp      = require('jsonpath');
var batchVars = null;

//console.log(batchVars);

// Settings / vars
var verbose             = config.verbose;
var serverValues        = {}; // Holds all server values except MQTT values
const methodConfigDir   = profileDir + '/methods';
const varConfigDir      = profileDir + '/variables';

// Parse config files (JS)
let methodFiles = [];
let varFiles    = [];
if (fs.existsSync(methodConfigDir)) {
    var files = fs.readdirSync(methodConfigDir);
    files.forEach(file => {
        if (file.match(/\.js$/)) {
            methodFiles.push(file);
        }
    });
}

if (fs.existsSync(varConfigDir)) {
    files = fs.readdirSync(varConfigDir);
    files.forEach(file => {
        if (file.match(/\.js$/)) {
            varFiles.push(file);
        }
    });
}

(async () => {

    try {
        /*******************/
        /*** SERVER INIT ***/
        /*******************/
        const server = new opcua.OPCUAServer(
            {
                alternateHostname       : config.opcua.serverHostname,
                port                    : config.opcua.serverPort,
                resourcePath            : config.opcua.resourcePath,
                buildInfo               : {
                    productName: config.opcua.productName,
                    buildNumber: config.opcua.buildNumber,
                    buildDate  : new Date(config.opcua.buildDate)
                },
                serverCertificateManager: certificateManager
            }
        );

        await server.initialize();
        if (verbose) console.log("[OK] OPC UA: Server created");

 

        const addressSpace = server.engine.addressSpace;
        const namespace    = addressSpace.getOwnNamespace();

        const device = namespace.addObject(
            {
                organizedBy: addressSpace.rootFolder.objects,
                browseName : config.opcua.browseName
            }
        );
      
         

        /*****************/
        /*** VARIABLES ***/
        /*****************/
        if (varFiles.length) {
            if (verbose) console.log("[..] OPC UA: Creating variables from " + varFiles.length + ' external files');
            varFiles.forEach(function (file) {
                var module            = require(profileDir + '/variables/' + file);
                var varName           = file.replace(/\.js$/);
                serverValues[varName] = module.run(namespace, device, opcua, verbose, serverValues);
            });
            if (verbose) console.log("[OK] OPC UA: Variables created");
        }
       
           
        /********************/
        /*** START SERVER ***/
        /********************/
        await server.start();
        let endpointUrl = server.endpoints[0].endpointDescriptions()[0].endpointUrl;

        // Replace host name by local ip
        endpointUrl = endpointUrl.replace(/^opc.tcp:\/\/([^:]+)/, "opc.tcp://127.0.0.1");

        if (verbose) console.log("[OK] OPC UA: Listening on port " + server.endpoints[0].port);
        console.log('\nPlease use these values to connect to this server via the IO Manager in WebIQ Designer:');
        console.log("Endpoint URL: ", endpointUrl);
        console.log("Namespace:     " + namespace.namespaceUri);

    } catch (err) {
        console.log("[ERROR]");
        console.log(err);
    }
  

})();

**Comment by AndreasHeine** [comment]
if you want ns=3 you need to create two additional namespaces because the index is some sort of fluid so the idx is always the next free idx in the namespace array
the ns-uri (http://mynamespace.com/UA) is the actual const and can be resolved via the namespacearray which each server exposes. its a better practice to not think ns-idx is something const which you can choose...

**Comment by Newinthistopic** [comment]
Hello Andreas,

many thanks for your feedback.
I understood that I have to build all namespaces before 3 first, so that I can use namespace 3.

Can you give me a code where to insert it?
I had already used a lot of codes from this forum and none worked.

I am happy about feedback.

Many greetings 



> if you want ns=3 you need to create two additional namespaces because the index is some sort of fluid so the idx is always the next free idx in the namespace array the ns-uri (http://mynamespace.com/UA) is the actual const and can be resolved via the namespacearray which each server exposes. its a better practice to not think ns-idx is something const which you can choose...
> 
> edit: ns=0 is always OPC Core ns=1 is always Serverown-Namespace ns=... imported xml or other registered namespaces depend on the order in which they will be registered

**Comment by Newinthistopic** [comment]
.

**Comment by Newinthistopic** [comment]
Hello Andreas,

many thanks for your feedback.
I understood that I have to build all namespaces before 3 first, so that I can use namespace 3.

Can you give me a code where to insert it?
I had already used a lot of codes from this forum and none worked.

I am happy about feedback.

Many greetings

**Comment by AndreasHeine** [comment]
its rather simple:

// ns=0 and ns=1 already exist!

const namespace2 = addressSpace.registerNamespace('http://mynamespace-2/UA/')

**Comment by Newinthistopic** [comment]
Hello i put it here now: 
![image](https://user-images.githubusercontent.com/123831898/222670466-15f3a0ba-938d-4140-b57e-1283b199f61c.png)

but it does not work. When I set the variable ns=2 then come this error message: 

![image](https://user-images.githubusercontent.com/123831898/222670811-016d97d0-5007-4a7b-b943-98335aa46fe6.png)

**Comment by AndreasHeine** [comment]
remove the nodeid from addVariable...

currently you try to add to "namespace" (which is ns=1) a variable with ns=2 which is impossible ^^ 

alternatively you can do 
```ts
`ns=${addressSpace.getNamespaceIndex('http://mynamespace-2/UA/')};s=DataBlocksGlobalsdsfsfs`
```

**Comment by Newinthistopic** [comment]
super thanks, that's how it worked :)  

![image](https://user-images.githubusercontent.com/123831898/222674667-ff24531f-8569-46a7-bd07-f63643285155.png)

Now I have a new problem.

I have my variables in another file. See here:

![image](https://user-images.githubusercontent.com/123831898/222675089-4ced0efe-721b-48d8-ab7e-1af4329818c8.png)



I would like to change the namespace of the variable udtEmPz, how can I do that ?

**Comment by Newinthistopic** [comment]
> I expect leave nodeId without "ns=1;" then it should use your string based nodeId.

Unfortunately this does not work

**Comment by AndreasHeine** [comment]
in your second screenshot "namespace2" is undefined!? your run function just gets namespace as param! maybe you should pass addressSpace instead so you can access all namespaces while invokin run function?

**Comment by Newinthistopic** [comment]
i now have it that way, but it doesn't work.

![image](https://user-images.githubusercontent.com/123831898/222735657-804b1b39-8506-4147-881d-b593b9c8e387.png)

**Comment by AndreasHeine** [comment]
you need to look more careful in the examples i posted...

addressSpace.getNamespaceIndex('http://mynamespace-3/UA/').addObject()

**Comment by Newinthistopic** [comment]
danke für deine Antworten. Ich habe das jetzt so:

![image](https://user-images.githubusercontent.com/123831898/222743042-9e95b5bd-1fdc-4158-8223-0ded4ed767a8.png)



UA Experts zeigt auch die Namespaces an. 

![image](https://user-images.githubusercontent.com/123831898/222743140-b570d2d5-5590-4e3c-895a-61cf409deb52.png)



ich möchte nun das bestimmte Variablen den Index 2 oder 3 haben. freue mich auf deine Hilfe :)

**Comment by AndreasHeine** [comment]
weird translation ^^ anyways my last attempt -> never hardcode a namespaceindex!

use:
```
const nsUri_xyz = "http://mynamespace-xyz"
const xyzNamespace = addressSpace.registerNamespace(nsUri_xyz)
const xyzIndex = addressSpace.getNamespaceIndex(<namespacename>)
```

you can use xyzNamespace to add stuff to xyzIndex (nsUri_xyz)!

**Comment by Newinthistopic** [comment]
Hello, thank you for your efforts. All this does not work. This is my last stand.

The test object is also displayed as index 3. that fits so f

![image](https://user-images.githubusercontent.com/123831898/222750321-8dfc3eaa-31ff-4bf7-820c-0e44921bf8dd.png)


![image](https://user-images.githubusercontent.com/123831898/222750604-d77a1a03-6cc7-4352-8b9e-cc227c939048.png)

![image](https://user-images.githubusercontent.com/123831898/222750732-84f9eb24-0a0e-4281-adbd-97d839048948.png)


I now have variables and objects in another file and want to change the namespace index there. but it doesn't work.

![image](https://user-images.githubusercontent.com/123831898/222751130-0d3b2964-e6f7-47c3-9642-e4668b2341e9.png)

**Comment by AndreasHeine** [comment]
https://github.com/AndreasHeine/SampleServer-node-opcua/blob/82d614b43cd79d29b8f888ffd732473a32255317/src/serveraddressspace/serveraddressspace.ts#L43

you can replace `const namespace = addressSpace.getOwnNamespace()` in L43 (link above) with `const namespace = addressSpace.getNamespace("http://mynamespaceuri/UA")`

and then just namespace.add... and they will all have the namespaceindex of "http://mynamespaceuri/UA" in the NamespaceArray

**Comment by Newinthistopic** [comment]
i have now this in my server.js 
![image](https://user-images.githubusercontent.com/123831898/222756773-cd863618-6403-4af7-9c69-558bb9d8e447.png)


i get this error

TypeError: Cannot read properties of undefined (reading 'addObject')
    at C:\Users\fischerfk\Desktop\webiq-opcua-demo-server-mqtt\opcua-demo-server\server.js:123:34

**Comment by AndreasHeine** [comment]
you need to use the vscode debugger to go line by line and look what happens in the objects thats the pain with plain js i mentioned! using typescript would prevent you from that hassle you experience now...

**Comment by AndreasHeine** [comment]
send me the code in the chat so i can show you what i mean!

**Comment by Newinthistopic** [comment]
> send me the code in the chat so i can show you what i mean!

here is my code:



module.exports = {
    run: function (namespace, device, opcua, verbose, serverValues) {
        
        
       
        // create ppC_Compound_V3 object
        var ppC_Compound_V3 = namespace.addObject({
            organizedBy: device,
            browseName: "ppC_Compound_V3",
            nodeId: "ns=2;s=PLC",
            description: "The PLC instance which supports you with OPC UA functionality" 
        })

      /*  // create DatablocksGlobal object
        var datablocksGlobal = namespace.addObject({
            organizedBy: ppC_Compound_V3,
            browseName: "DatablocksGlobal",
            nodeId: "ns=1;s=DatablocksGlobal"
        });

        // create ZEEX_3111_Hmi object
        var prefix = namespace.addObject({
            organizedBy: datablocksGlobal,
            browseName: "ZEEX_3111_Hmi",
            //nodeId: "ns=1;s=" + "\"ZEEX_3111_Hmi\""
        });

         // create udtEmPz variable undefined Datatype Equipment Module Process Zone
        var udtEmPz = namespace.addVariable({
            componentOf: prefix,
            browseName : "udtEmPz",
            dataType   : opcua.DataType.Double,
            nodeId     : "ns=1;s=" + "\"ZEEX_3111_Hmi\".\"udtEmPz\""  ,         
        });
        
        
        for (var i = 0; i<14; i++){
            var nr = namespace.addVariable({
            componentOf: udtEmPz,
            browseName : i.toString(),
            dataType   : opcua.DataType.Double,
            nodeId     : "ns=1;s=" + "\"ZEEX_3111_Hmi\".\"udtEmPz\""+ "[" + i + "]",
             
            
        }
        ) 
        
        var rPzTemp = namespace.addVariable({
            componentOf: nr,
            browseName : "rPzTemp",
            dataType   : opcua.DataType.String,
            nodeId     : "ns=1;s=" + "\"ZEEX_3111_Hmi\".\"udtEmPz\""+ "[" + i + "]." + "\"rPzTemp\""
           
        }
        )
        
        
        var rSet= namespace.addVariable({
            componentOf: rPzTemp,
            browseName : "rSet",
            dataType   : opcua.DataType.Float,
            nodeId     : "ns=1;s=" + "\"ZEEX_3111_Hmi\".\"udtEmPz\""+ "[" + i + "]." + "\"rPzTemp\".\"rSet\"",
            value      : {
                get: function () {
                    return new opcua.Variant({dataType: opcua.DataType.Float, value: serverValues[rSet]});
                    
                },
                set: function (variant) {
                    serverValues[rSet] = parseFloat(variant.value);
                    return opcua.StatusCodes.Good;
                    }
                                     
                },
            }
        )
        var rAct= namespace.addVariable({
            componentOf: rPzTemp,
            browseName : "rAct",
            dataType   : opcua.DataType.Double,
            nodeId     : "ns=1;s=" + "ZEEX_3111_Hmi.udtEmPz"+ "[" + i + "]" + "rPzTemp.rAct",
        }
        )

    }*/
              
    }
}

**Comment by AndreasHeine** [comment]
### reformatted + comments

```js
module.exports = {
run: function (namespace, device, opcua, verbose, serverValues) {

// at this point you have a namespace as input param and the namespace-index of that instance you cant change! if you want to add to different namespaces within the run function you need to pass addreassSpace instead of namespace

/*
function (addressSpace, device, opcua, verbose, serverValues) { 

// get the correct namespace instance associated with 'http://mynamespace-2/UA/':
const namespace2 = addressSpace.registerNamespace('http://mynamespace-2/UA/')
// if namespace2 already exists use getNamespace instead of registerNamespace:
// const namespace2 = addressSpace.getNamespace('http://mynamespace-2/UA/')

var objInNs2 = namespace2.addObject({
        organizedBy: device,
        browseName: "ObjInNs2",
        nodeId: "s=ObjInNs2", // what mika mentioned!
    })

// get the correct namespace instance associated with 'http://mynamespace-3/UA/':
const namespace3 = addressSpace.registerNamespace('http://mynamespace-3/UA/')
// if namespace3 already exists use getNamespace instead of registerNamespace:
// const namespace3 = addressSpace.getNamespace('http://mynamespace-3/UA/')


var objInNs3 = namespace3.addObject({
        organizedBy: device,
        browseName: "ObjInNs3",
        nodeId: "s=ObjInNs3", // what mika mentioned!
    })

}
*/


    // create ppC_Compound_V3 object
    var ppC_Compound_V3 = namespace.addObject({
        organizedBy: device,
        browseName: "ppC_Compound_V3",
        nodeId: "ns=2;s=PLC",
        description: "The PLC instance which supports you with OPC UA functionality" 
    })

  /*  // create DatablocksGlobal object
    var datablocksGlobal = namespace.addObject({
        organizedBy: ppC_Compound_V3,
        browseName: "DatablocksGlobal",
        nodeId: "ns=1;s=DatablocksGlobal"
    });

    // create ZEEX_3111_Hmi object
    var prefix = namespace.addObject({
        organizedBy: datablocksGlobal,
        browseName: "ZEEX_3111_Hmi",
        //nodeId: "ns=1;s=" + "\"ZEEX_3111_Hmi\""
    });

     // create udtEmPz variable undefined Datatype Equipment Module Process Zone
    var udtEmPz = namespace.addVariable({
        componentOf: prefix,
        browseName : "udtEmPz",
        dataType   : opcua.DataType.Double,
        nodeId     : "ns=1;s=" + "\"ZEEX_3111_Hmi\".\"udtEmPz\""  ,         
    });
    
    
    for (var i = 0; i<14; i++){
        var nr = namespace.addVariable({
        componentOf: udtEmPz,
        browseName : i.toString(),
        dataType   : opcua.DataType.Double,
        nodeId     : "ns=1;s=" + "\"ZEEX_3111_Hmi\".\"udtEmPz\""+ "[" + i + "]",
         
        
    }
    ) 
    
    var rPzTemp = namespace.addVariable({
        componentOf: nr,
        browseName : "rPzTemp",
        dataType   : opcua.DataType.String,
        nodeId     : "ns=1;s=" + "\"ZEEX_3111_Hmi\".\"udtEmPz\""+ "[" + i + "]." + "\"rPzTemp\""
       
    }
    )
    
    
    var rSet= namespace.addVariable({
        componentOf: rPzTemp,
        browseName : "rSet",
        dataType   : opcua.DataType.Float,
        nodeId     : "ns=1;s=" + "\"ZEEX_3111_Hmi\".\"udtEmPz\""+ "[" + i + "]." + "\"rPzTemp\".\"rSet\"",
        value      : {
            get: function () {
                return new opcua.Variant({dataType: opcua.DataType.Float, value: serverValues[rSet]});
                
            },
            set: function (variant) {
                serverValues[rSet] = parseFloat(variant.value);
                return opcua.StatusCodes.Good;
                }
                                 
            },
        }
    )
    var rAct= namespace.addVariable({
        componentOf: rPzTemp,
        browseName : "rAct",
        dataType   : opcua.DataType.Double,
        nodeId     : "ns=1;s=" + "ZEEX_3111_Hmi.udtEmPz"+ "[" + i + "]" + "rPzTemp.rAct",
    }
    )

}*/
          
}
}
```

### cleaned up:


```js
function (addressSpace, device, opcua, verbose, serverValues) { 

// get the correct namespace instance associated with 'http://mynamespace-2/UA/':
const namespace2 = addressSpace.registerNamespace('http://mynamespace-2/UA/')
// if namespace2 already exists use getNamespace instead of registerNamespace:
// const namespace2 = addressSpace.getNamespace('http://mynamespace-2/UA/')

var objInNs2 = namespace2.addObject({
        organizedBy: device,
        browseName: "ObjInNs2",
        nodeId: "s=ObjInNs2", // what mika mentioned!
    })

// get the correct namespace instance associated with 'http://mynamespace-3/UA/':
const namespace3 = addressSpace.registerNamespace('http://mynamespace-3/UA/')
// if namespace3 already exists use getNamespace instead of registerNamespace:
// const namespace3 = addressSpace.getNamespace('http://mynamespace-3/UA/')


var objInNs3 = namespace3.addObject({
        organizedBy: device,
        browseName: "ObjInNs3",
        nodeId: "s=ObjInNs3", // what mika mentioned!
    })

}
```

### hope its now clear!

**Comment by Newinthistopic** [comment]
![image](https://user-images.githubusercontent.com/123831898/222777255-7fab3ff9-e8ee-443a-a298-8981a7cfbf2f.png)

**Comment by Newinthistopic** [comment]
![image](https://user-images.githubusercontent.com/123831898/222777361-8e5f3d0f-290c-485d-ab10-152914d8d24f.png)
