### ISSUE TITLE
Creating an OpcuaServer with port 0 for a dynamic port from OS uses default port 26543 

### ISSUE THREAD

**Issue by JoelKrec** [node-opcua/node-opcua#1254]
**Current behavior**
If you create an OPCUAServer with port 0 the server will try to connect to the default port 26543 upon starting.

**Describe the bug**

In opcua_server.ts on line 1150 there an endpointDescription gets pushed to the endpointDefinitions array with the options from the options parameter.
In the next line (1151) the port gets assigned to 'options.port || 16543'. For js a 0 is considered false in these types of assignments. Therefore, trying to start the server with a dynamic port from the OS will result in the server starting at the default port.

**Step by step instruction to reproduce**

1. create a new OPCUAServer with at least {port: 0} set as the options object
2. initialize the created server
3. start the initialized server
4. read the port with ```server.endpoints[0].port``` and see that the port used is 26543 or get an EADDRINUSE Error if you have another server already using that port

**Expected behavior**

Assigning a port to 0 on most (afaik on all) OS will let the OS to use a dynamic port at the end of the port list. That is really handy for short lived servers in testing an application.
Assigning port 0 to OPCUAServer would use a dynamically assigned port, start correctly and never get the EADDRINUSE error when not starting thousands of servers this way.

**Screenshots**

![faultyPortAssignment](https://user-images.githubusercontent.com/89908554/226578364-c2f60847-9bfa-49e6-83e3-b224d2a71aa6.png)

**Gist**

gist: https://gist.github.com/JoelKrec/4ce0c60d8cbaf00cbeb995e2e5081dbf

Used node-opcua version for this gist: v2.95.0

**Context**

- ( ) my request is related to node-opcua acting as an OPCUA CLIENT
- ( X ) my request is related to node-opcua acting as an OPCUA SERVER

- ( ) I have installed node-opcua from source ( using git clone)
- ( X ) I have installed node-opcua as a package ( using npm install )
- ( ) I am using an application that uses node-opcua

    - ( ) node-red
    - ( ) other : please specify

- Device: PC
- OS version: Pop!OS 22.04

    - ( ) Windows : version : ______
    - ( X ) Linux : version : Ubuntu based Pop!OS 22.04
    - ( ) MacOs : version : ______
    - ( ) Raspbian: version : ______
    - ( ) Other : specify : ______

- Description of the other OPCUA system I am trying to connect to:

 None

- **node-opcua version:** :

v2.95.0

- **Node:**

  `node --version` = v18.11.0

**Comment by erossignon** [comment]
available now in node-opcua@2.101.0
