### ISSUE TITLE
'The connection may have been rejected by server,\nErr = (_socket has been disconnected by third party)'

### ISSUE THREAD

**Issue by raptorsj** [node-opcua/node-opcua#1259]
I'm not able to connect the device  with security policy - **http://opcfoundation.org/UA/SecurityPolicy#Aes256_Sha256_RsaPss** and throwing the above error and i'm able to connect with other security policies with the same device

  and certificate added to trusted list

**Comment by raptorsj** [comment]
@erossignon ..can you take a look

**Comment by erossignon** [comment]
Yes, through profesional services. please contact us at Sterfive.com with your professional emaiL;

**Comment by henjoe** [comment]
Hello  @raptorsj  I wonder if you solve this one? Been experiencing the same issue.

**Comment by erossignon** [comment]
fixed in node-opcua@2.213.0
