### ISSUE TITLE
Some packages (for new nodesets in v2.99.0) are missing the `dist/` folder

### ISSUE THREAD

**Issue by jacobq** [node-opcua/node-opcua#1267]
Thanks for reviewing and merging my [first PR on this project](https://github.com/node-opcua/node-opcua/pull/1265) to close #1264! Unfortunately, something went wrong with the actual publishing of the nodeset packages. (Either that or I am misunderstanding the expected way to import them.) 

**Current behavior**

```ts
import {
  UAAnalogSignalVariable,
  UASignalSet,
} from 'node-opcua-nodeset-padim';
// ^^^ TS2307: Cannot find module 'node-opcua-nodeset-padim' or its corresponding type declarations.
```

**Describe the bug**

It looks like the `dist` folder was not included with some of the `node-opcua-nodeset-*` packages, namely the new ones just added in v2.99.0. (e.g., [`node-opcua-nodeset-padim`](https://www.npmjs.com/package/node-opcua-nodeset-padim?activeTab=code) & [`node-opcua-nodeset-machinery-process-values`](https://www.npmjs.com/package/node-opcua-nodeset-machinery-process-values?activeTab=code) are missing `dist/` but [`node-opcua-nodeset-ua` is OK](https://www.npmjs.com/package/node-opcua-nodeset-ua?activeTab=code) )

Files in packages: [actual](https://www.npmjs.com/package/node-opcua-nodeset-padim?activeTab=code) vs. [expected](https://www.npmjs.com/package/@jacobq/node-opcua-nodeset-padim?activeTab=code)

<details>
<summary>File system tree for `node_modules/node-opcua-nodeset-padim`</summary>

```
$ tree node_modules/node-opcua-nodeset-padim/
node_modules/node-opcua-nodeset-padim/
├── LICENSE
├── package.json
└── source
    ├── enum_execution_mode_enum.ts
    ├── enum_reset_mode_enum.ts
    ├── index.ts
    ├── ua_actual_density_variable.ts
    ├── ua_actual_volume_flow_rate_variable.ts
    ├── ua_analog_signal.ts
    ├── ua_analog_signal_variable.ts
    ├── ua_analytical_measurement_variable.ts
    ├── ua_control_signal.ts
    ├── ua_control_variable.ts
    ├── ua_discrete_signal.ts
    ├── ua_discrete_signal_variable.ts
    ├── ua_flow_measurement_variable.ts
    ├── ua_i_administration.ts
    ├── ua_i_signal_set.ts
    ├── ua_level_measurement_variable.ts
    ├── ua_mass_flow_rate_variable.ts
    ├── ua_multi_state_discrete_signal.ts
    ├── ua_multi_state_discrete_signal_variable.ts
    ├── ua_normalized_volume_flow_rate_variable.ts
    ├── ua_padim.ts
    ├── ua_pressure_measurement_variable.ts
    ├── ua_signal_set.ts
    ├── ua_signal.ts
    ├── ua_temperature_measurement_variable.ts
    ├── ua_totalizer_variable.ts
    ├── ua_two_state_discrete_signal.ts
    └── ua_two_state_discrete_signal_variable.ts

2 directories, 30 files
```

</details>

**Step by step instruction to reproduce**

1. Install one of the new nodeset type packages:
    `npm install --save node-opcua-nodeset-machinery-process-values`
2. Observe that `node_modules/node-opcua-nodeset-machinery-process-values/dist/` does not exist.
3. Try to import types from nodeset package, e.g.

    ```ts
    import { UAProcessValueSetpointVariable } from 'node-opcua-nodeset-machinery-process-values';
    ```

4. Observe TypeScript error in IDE or at build time: "TS2307: Cannot find module 'node-opcua-nodeset-machinery-process-values' or its corresponding type declarations."

**Expected behavior**

Should be able to import types for new nodesets just like previously supported ones.

**Context**

- [ ] my request is related to node-opcua acting as an OPCUA CLIENT
- [X] my request is related to node-opcua acting as an OPCUA SERVER

- [ ] I have installed node-opcua from source ( using git clone)
- [X] I have installed node-opcua as a package ( using npm install )

- Device: developer workstation & Raspberry Pi Model 4B with 2GB RAM
- OS version: 

    - [X] Linux : Debian 6.1.20-1 (2023-03-19) x86_64 GNU/Linux (6.1.0-7-amd64)
    - [X] Raspbian (Raspberry Pi OS): version : Linux 5.10.63-v8+ aarch64 GNU/Linux 

- Description of the other OPCUA system I am trying to connect to: N/A

- **node-opcua version:** : v2.99.0

- **Node: version** v19.7.0

**Comment by erossignon** [comment]
Fixed in node-opcua-nodeset-padim@2.99.1
