### ISSUE TITLE
Error: Parent folder must be of FolderType ns=0;i=58

### ISSUE THREAD

**Issue by AndreasHeine** [node-opcua/node-opcua#1274]
### Error: Parent folder must be of FolderType ns=0;i=58

```ts
  namespace.addFolder(myMachine, {
      browseName: "MachineryBuildingBlocks"
  })
```

![image](https://github.com/node-opcua/node-opcua/assets/56362817/e859157e-9e32-4f7f-b2af-5b1bdb9c23a6)
https://reference.opcfoundation.org/Machinery/v102/docs/12

**Comment by erossignon** [comment]
to create  the MachineryBuildingBlocks you need to pass the 

```
     optionals: [ "MachineryBuildingBlocks"] 
```

parameter to the `opbejctType.instantiate(...)` method that you use to construct the machine.
