### ISSUE TITLE
Not able to add a device using Security Policy-  Aes256_Sha256_RsaPss

### ISSUE THREAD

**Issue by raptorsj** [node-opcua/node-opcua#1281]
When i'm trying to add a device using this security policy - **http://opcfoundation.org/UA/SecurityPolicy#Aes256_Sha256_RsaPss**  for a device with **UserTokenType.UserName**. It is throwing the below error while creating the session with usercredential

**Error: The connection may have been rejected by server,
Err = (ClientTCP_transport26: socket has been disconnected by third party)**

**Comment by raptorsj** [comment]
Here is the debug log

11:36:15.851Z :client_base_impl              :256     Client 4 EndpointFetcher_TmpClient : _internalState from     uninitialized to disconnected
11:36:15.852Z :client_base_impl              :1329  connecting to TmpClient
11:36:15.862Z :client_base_impl              :256     Client 4 EndpointFetcher_TmpClient : _internalState from     disconnected to connecting
11:36:15.862Z :client_base_impl              :178   installPeriodicClockAdjustment  0
11:36:15.863Z :client_base_impl              :678   __connectStep2
11:36:15.865Z :client_base_impl              :445   _internal_create_secure_channel creating new ClientSecureChannelLayer _internalState = connecting
11:36:15.865Z :client_base_impl              :468   _internal_create_secure_channel before secureChannel.create
11:36:15.866Z :tcp_transport                 :121   Setting socket ClientTCP_transport3 timeout =  60000
11:36:15.867Z :client_secure_channel_layer   :322   ClientSecureChannelLayer#create creating ClientTCP_transport with  transport.timeout =  60000
11:36:15.871Z :client_secure_channel_layer   :848   max Retry === 0 =>  No backoff required -> call the _connect function directly
11:36:15.878Z :client_tcp_transport          :124   ClientTCP_transport#connect(endpointUrl = opc.tcp://192.168.2.40:4840)
11:36:15.881Z :tcp_transport                 :232     TCP_transport#install => setting ClientTCP_transport3 _socket.setTimeout to  60000
11:36:15.881Z :tcp_transport                 :236     TCP_transport#_install_socket  ClientTCP_transport3
11:36:15.883Z :client_tcp_transport          :35    connected to server! 192.168.2.40:4840 timeout:60000
11:36:15.886Z :client_tcp_transport          :159   entering _on_socket_connect
11:36:15.887Z :client_tcp_transport          :288   entering _perform_HEL_ACK_transaction
11:36:15.894Z :client_tcp_transport          :243   entering _send_HELLO_request
11:36:15.897Z :client_tcp_transport          :291   before  _on_ACK_response
11:36:15.897Z :client_tcp_transport          :265   entering _on_ACK_response
11:36:15.898Z :client_secure_channel_layer   :799   Connection => err null
11:36:15.907Z :client_secure_channel_layer   :777   Client now sending OpenSecureChannel
11:36:15.911Z :client_secure_channel_layer   :962   Adjusted timeout =  15000
11:36:15.913Z :message_builder               :153    Sequence Header SequenceHeader { sequenceNumber: 1, requestId: 1 }
11:36:15.914Z :message_builder               :278   client3 Sequence Number =  1
11:36:15.918Z :message_builder               :217   client3 message size = 136       body size   = 57        requestHandle =  1 OpenSecureChannelResponse
11:36:15.919Z :client_secure_channel_layer   :969   ------------------------------------- Client receiving response  OpenSecureChannelRequest 1 OpenSecureChannelResponse err= null securityTokenId= x
11:36:15.926Z :client_secure_channel_layer   :749   Server has send a new security Token
11:36:15.927Z :message_builder               :106   id= client3 Pushing new token with id  1 [ 1 ]
11:36:15.929Z :client_secure_channel_layer   :659    time until next security token renewal =  450000 ( lifetime =  600000 -  tokenRenewalInterval =0
11:36:15.930Z :client_base_impl              :470   _internal_create_secure_channel after secureChannel.create
11:36:15.939Z :client_secure_channel_layer   :962   Adjusted timeout =  15000
11:36:15.940Z :client_base_impl              :262     Client 4 EndpointFetcher_TmpClient emitting  send_request
11:36:15.941Z :client_base_impl              :262     Client 4 EndpointFetcher_TmpClient emitting  send_chunk
11:36:15.944Z :client_base_impl              :262     Client 4 EndpointFetcher_TmpClient emitting  receive_chunk
11:36:15.944Z :message_builder               :153    Sequence Header SequenceHeader { sequenceNumber: 2, requestId: 2 }
11:36:15.945Z :message_builder               :278   client3 Sequence Number =  2
11:36:15.946Z :client_base_impl              :262     Client 4 EndpointFetcher_TmpClient emitting  receive_chunk
11:36:15.947Z :message_builder               :153    Sequence Header SequenceHeader { sequenceNumber: 3, requestId: 2 }
11:36:15.948Z :message_builder               :278   client3 Sequence Number =  3
11:36:15.949Z :client_base_impl              :262     Client 4 EndpointFetcher_TmpClient emitting  receive_chunk
11:36:15.950Z :message_builder               :153    Sequence Header SequenceHeader { sequenceNumber: 4, requestId: 2 }
11:36:15.951Z :message_builder               :278   client3 Sequence Number =  4
11:36:15.952Z :message_builder               :217   client3 message size = 20876     body size   = 20804     requestHandle =  2 GetEndpointsResponse
11:36:15.953Z :client_secure_channel_layer   :969   ------------------------------------- Client receiving response  GetEndpointsRequest 2 GetEndpointsResponse err= null securityTokenId= 1
11:36:15.954Z :client_base_impl              :262     Client 4 EndpointFetcher_TmpClient emitting  receive_response
11:36:15.954Z :client_base_impl              :608    Connected successfully  to  opc.tcp://192.168.2.40:4840
11:36:15.955Z :client_base_impl              :262     Client 4 EndpointFetcher_TmpClient emitting  connected
11:36:15.956Z :client_base_impl              :256     Client 4 EndpointFetcher_TmpClient : _internalState from     connecting to connected
11:36:15.957Z :client_secure_channel_layer   :962   Adjusted timeout =  15000
11:36:15.957Z :client_base_impl              :262     Client 4 EndpointFetcher_TmpClient emitting  send_request
11:36:15.958Z :client_base_impl              :262     Client 4 EndpointFetcher_TmpClient emitting  send_chunk
11:36:15.961Z :client_base_impl              :262     Client 4 EndpointFetcher_TmpClient emitting  receive_chunk
11:36:15.970Z :message_builder               :153    Sequence Header SequenceHeader { sequenceNumber: 5, requestId: 3 }
11:36:15.971Z :message_builder               :278   client3 Sequence Number =  5
11:36:15.973Z :client_base_impl              :262     Client 4 EndpointFetcher_TmpClient emitting  receive_chunk
11:36:15.974Z :message_builder               :153    Sequence Header SequenceHeader { sequenceNumber: 6, requestId: 3 }
11:36:15.975Z :message_builder               :278   client3 Sequence Number =  6
11:36:15.976Z :client_base_impl              :262     Client 4 EndpointFetcher_TmpClient emitting  receive_chunk
11:36:15.977Z :message_builder               :153    Sequence Header SequenceHeader { sequenceNumber: 7, requestId: 3 }
11:36:15.978Z :message_builder               :278   client3 Sequence Number =  7
11:36:15.980Z :message_builder               :217   client3 message size = 20876     body size   = 20804     requestHandle =  3 GetEndpointsResponse
11:36:15.980Z :client_secure_channel_layer   :969   ------------------------------------- Client receiving response  GetEndpointsRequest 3 GetEndpointsResponse err= null securityTokenId= 1
11:36:15.982Z :client_base_impl              :262     Client 4 EndpointFetcher_TmpClient emitting  receive_response
11:36:15.983Z :client_base_impl              :927   disconnecting client! (will set reconnectionIsCanceled to true
11:36:15.983Z :client_base_impl              :939   ClientBaseImpl#disconnect opc.tcp://192.168.2.40:4840
11:36:15.985Z :client_base_impl              :960   Disconnecting !
11:36:15.986Z :client_base_impl              :256     Client 4 EndpointFetcher_TmpClient : _internalState from     connected to disconnecting
11:36:15.987Z :client_base_impl              :183   uninstallPeriodicClockAdjustment  0
11:36:15.988Z :client_base_impl              :984   Closing channel
11:36:15.988Z :client_secure_channel_layer   :443   cancelPendingTransactions  PlantView EndpointFetcher_TmpClient  =
11:36:15.989Z :client_secure_channel_layer   :479   Sending CloseSecureChannelRequest to server
11:36:15.990Z :client_secure_channel_layer   :962   Adjusted timeout =  15000
11:36:15.992Z :client_base_impl              :262     Client 4 EndpointFetcher_TmpClient emitting  send_request
11:36:15.994Z :client_base_impl              :262     Client 4 EndpointFetcher_TmpClient emitting  send_chunk
11:36:16.007Z :tcp_transport                 :404    SOCKET END : ClientTCP_transport3 is disconnecting   false
11:36:16.007Z :tcp_transport                 :409    Transport Connection ended ClientTCP_transport3
11:36:16.008Z :tcp_transport                 :411    bytesRead    =  41916
11:36:16.009Z :tcp_transport                 :412    bytesWritten =  440
11:36:16.010Z :tcp_transport                 :370    SOCKET CLOSE ClientTCP_transport3:  had_error = false
11:36:16.010Z :client_tcp_transport          :114    ClientTCP_transport disposed
11:36:16.011Z :client_secure_channel_layer   :617    =>ClientSecureChannelLayer#_on_transport_closed  err= ClientTCP_transport3: socket has been disconnected by third party
11:36:16.012Z :client_base_impl              :1219   ClientBaseImpl emitting close undefined
11:36:16.013Z :client_base_impl              :262     Client 4 EndpointFetcher_TmpClient emitting  close
11:36:16.014Z :client_tcp_transport          :114    ClientTCP_transport disposed
11:36:16.015Z :client_secure_channel_layer   :602   _cancel_pending_transactions   [ '4' ] no transport
11:36:16.015Z :client_secure_channel_layer   :609   Cancelling pending transaction   CLO CloseSecureChannelRequest
11:36:16.016Z :client_secure_channel_layer   :969   ------------------------------------- Client receiving response  CloseSecureChannelRequest 4 null err= null securityTokenId= 1
11:36:16.018Z :client_secure_channel_layer   :362   abortConnection  false
11:36:16.019Z :client_base_impl              :1131   DESTROYING SECURE CHANNEL (isTransactionInProgress ? false )
11:36:16.019Z :client_base_impl              :1121  Client 4 EndpointFetcher_TmpClient byteWritten          =  440
11:36:16.020Z :client_base_impl              :1122  Client 4 EndpointFetcher_TmpClient byteRead             =  41916
11:36:16.021Z :client_base_impl              :1123  Client 4 EndpointFetcher_TmpClient transactions         =  4
11:36:16.022Z :client_base_impl              :1124  Client 4 EndpointFetcher_TmpClient timedOutRequestCount =  0
11:36:16.022Z :client_secure_channel_layer   :358   abortConnection already aborting!
11:36:16.023Z :client_base_impl              :256     Client 4 EndpointFetcher_TmpClient : _internalState from     disconnecting to disconnected
11:36:16.024Z :client_secure_channel_layer   :358   abortConnection already aborting!
11:36:16.025Z :client_base_impl              :143   xxxxxxxxxxxxxxxxxxxxx => selected EndPoint =  { /*EndpointDescription*/
 ...                                                 endpointUrl                   /*  String                                    */: opc.tcp://192.168.2.40:4840
 ...                                                 server                        /*  ApplicationDescription                    */: {
 ...                                                   applicationUri              /*  String                                    */: urn:SIMATIC.S7-1500.OPC-UA.Application:CPU1513-1FW3.0
 ...                                                   productUri                  /*  String                                    */: https://www.siemens.com/s7-1500
 ...                                                   applicationName             /*  LocalizedText                             */: locale=null text=SIMATIC.S7-1500.OPC-UA.Application:CPU1513-1FW3.0
 ...                                                   applicationType             /*  ApplicationType                           */: 0 /*(Server)*/
 ...                                                   gatewayServerUri            /*  String                                    */: null
 ...                                                   discoveryProfileUri         /*  String                                    */: null
 ...                                                   discoveryUrls               /*  String                                []  */: [ /* length =1*/
 ...                                                     opc.tcp://192.168.2.40:4840
 ...                                                   ]
 ...                                                 }
 ...                                                 serverCertificate             /*  ByteString                                */
 ...                                                Buffer:
 ...                                                3082048f30820377a00302010202087b...c41fcfd283dcf105f897e9ccb7ee657b
 ...                                                 securityMode                  /*  MessageSecurityMode                       */: 3 /*(SignAndEncrypt)*/
 ...                                                 securityPolicyUri             /*  String                                    */: http://opcfoundation.org/UA/SecurityPolicy#Aes256_Sha256_RsaPss
 ...                                                 userIdentityTokens            /*  UserTokenPolicy                       []  */: [
 ...                                                   { /* 0 - UserTokenPolicy*/
 ...                                                     policyId                  /*  String                                    */: UserName_Basic128Rsa15_Token
 ...                                                     tokenType                 /*  UserTokenType                             */: 1 /*(UserName)*/
 ...                                                     issuedTokenType           /*  String                                    */: null
 ...                                                     issuerEndpointUrl         /*  String                                    */: null
 ...                                                     securityPolicyUri         /*  String                                    */: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15
 ...                                                   },
 ...                                                 .... TRUNCATED ..... (NODEOPCUA_DEBUG_MAXLINE_PER_MESSAGE=25
11:36:16.064Z :certificate_manager           :76    checkCertificate => StatusCode =  BadCertificateUntrusted (0x801a0000)
11:36:16.067Z :certificate_manager           :80    automaticallyAcceptUnknownCertificate = true
11:36:16.067Z :certificate_manager           :81    certificate with thumbprint 376e3c896d61e0289cbb3d1e36e62899200f1447 is now trusted
11:36:16.071Z :client_base_impl              :656   connecting with endpoint :  opc.tcp://192.168.2.40:4840
11:36:16.072Z :client_base_impl              :178   installPeriodicClockAdjustment  0
11:36:16.073Z :client_base_impl              :678   __connectStep2
11:36:16.074Z :client_base_impl              :445   _internal_create_secure_channel creating new ClientSecureChannelLayer _internalState = connecting
11:36:16.075Z :client_base_impl              :468   _internal_create_secure_channel before secureChannel.create
11:36:16.089Z :tcp_transport                 :121   Setting socket ClientTCP_transport4 timeout =  60000
11:36:16.091Z :client_secure_channel_layer   :322   ClientSecureChannelLayer#create creating ClientTCP_transport with  transport.timeout =  60000
11:36:16.098Z :client_secure_channel_layer   :861   backoff will failed after  1
11:36:16.099Z :client_tcp_transport          :124   ClientTCP_transport#connect(endpointUrl = opc.tcp://192.168.2.40:4840)
11:36:16.100Z :tcp_transport                 :232     TCP_transport#install => setting ClientTCP_transport4 _socket.setTimeout to  60000
11:36:16.100Z :tcp_transport                 :236     TCP_transport#_install_socket  ClientTCP_transport4
11:36:16.102Z :client_tcp_transport          :35    connected to server! 192.168.2.40:4840 timeout:60000
11:36:16.102Z :client_tcp_transport          :159   entering _on_socket_connect
11:36:16.107Z :client_tcp_transport          :288   entering _perform_HEL_ACK_transaction
11:36:16.114Z :client_tcp_transport          :243   entering _send_HELLO_request
11:36:16.116Z :client_tcp_transport          :291   before  _on_ACK_response
11:36:16.117Z :client_tcp_transport          :265   entering _on_ACK_response
11:36:16.118Z :client_secure_channel_layer   :799   Connection => err null
11:36:16.122Z :client_secure_channel_layer   :777   Client now sending OpenSecureChannel
11:36:16.124Z :client_secure_channel_layer   :962   Adjusted timeout =  15000
11:36:16.248Z :tcp_transport                 :404    SOCKET END : ClientTCP_transport4 is disconnecting   false
11:36:16.249Z :tcp_transport                 :409    Transport Connection ended ClientTCP_transport4
11:36:16.252Z :tcp_transport                 :411    bytesRead    =  44
11:36:16.259Z :tcp_transport                 :412    bytesWritten =  1852
11:36:16.260Z :tcp_transport                 :370    SOCKET CLOSE ClientTCP_transport4:  had_error = false
11:36:16.261Z :client_tcp_transport          :114    ClientTCP_transport disposed
11:36:16.262Z :client_secure_channel_layer   :617    =>ClientSecureChannelLayer#_on_transport_closed  err= ClientTCP_transport4: socket has been disconnected by third party
11:36:16.262Z :client_tcp_transport          :114    ClientTCP_transport disposed
11:36:16.264Z :client_secure_channel_layer   :602   _cancel_pending_transactions   [ '1' ] no transport
11:36:16.265Z :client_secure_channel_layer   :609   Cancelling pending transaction   OPN OpenSecureChannelRequest
11:36:16.266Z :client_secure_channel_layer   :969   ------------------------------------- Client receiving response  OpenSecureChannelRequest 1 null err= ClientTCP_transport4: socket has been disconnected by third party securityTokenId= x
11:36:16.267Z :client_base_impl              :470   _internal_create_secure_channel after secureChannel.create
11:36:16.268Z :client_base_impl              :502   Inner create secure channel has failed ClientTCP_transport4: socket has been disconnected by third party
11:36:16.269Z :client_secure_channel_layer   :362   abortConnection  false
11:36:16.269Z :client_base_impl              :1131   DESTROYING SECURE CHANNEL (isTransactionInProgress ? false )
11:36:16.270Z :client_base_impl              :1121  Client 3 ClientSession byteWritten          =  1852
11:36:16.271Z :client_base_impl              :1122  Client 3 ClientSession byteRead             =  44
11:36:16.272Z :client_base_impl              :1123  Client 3 ClientSession transactions         =  1
11:36:16.273Z :client_base_impl              :1124  Client 3 ClientSession timedOutRequestCount =  0
11:36:16.280Z :client_secure_channel_layer   :358   abortConnection already aborting!
11:36:16.286Z :client_base_impl              :183   uninstallPeriodicClockAdjustment  0
11:36:16.288Z :client_base_impl              :689   SecureChannel creation has failed with error : ClientTCP_transport4: socket has been disconnected by third party
11:36:16.291Z :client_base_impl              :596   The connection may have been rejected by server,
 ...                                                Err = (ClientTCP_transport4: socket has been disconnected by third party)
11:36:16.300Z :client_base_impl              :262     Client 3 ClientSession emitting  connection_failed
11:36:16.301Z :client_base_impl              :256     Client 3 ClientSession : _internalState from     connecting to disconnected
11:36:16.303Z :client_secure_channel_layer   :358   abortConnection already aborting!**

**Comment by AndreasHeine** [comment]
does the server support that Policy?

**Comment by AndreasHeine** [comment]
another thing in the log is ->  BadCertificateUntrusted !!!

**Comment by erossignon** [comment]
simple answer : [Aes256_Sha256_RsaPss](http://opcfoundation.org/UA/SecurityPolicy#Aes256_Sha256_RsaPss) is not yet implemented nor supported in node-opcua.  you can fall back on a different security policy in in the meantime.

**Comment by raptorsj** [comment]
Does this support  -  **Aes128-Sha256-RsaOaep** security policy

**Comment by erossignon** [comment]
SecurityPolicy.Aes128_Sha256_RsaOaep should be supported.

**Comment by raptorsj** [comment]
It is throwing an error ..  **invalid message header detected** for  security policy -SecurityPolicy.Aes128_Sha256_RsaOaep for security mode - sign and sign&encrypt

**Comment by erossignon** [comment]
I just checked SecurityPolicy.Aes128_Sha256_RsaOaep connecttion between a node-opcua client and Prosys DemoServer and it works fine. 
Please contact sterfive support (contact@sterfive.com) for deeper private investigation on your setup.

**Comment by raptorsj** [comment]
Thankyou @erossignon.. SecurityPolicy.Aes128_Sha256_RsaPss is working
