### ISSUE TITLE
Update variable description dynamically 

### ISSUE THREAD

**Issue by ptorrent** [node-opcua/node-opcua#1284]
Hello there !

Just a simple question, is there a way to update dynamically the description of a variable ?
```
var variable = namespace.addVariable({
		description 	: description || '',
})

```

THanks for your support !

**Comment by erossignon** [comment]
In javascript:
```
variable.setDescription(coerceLocalizedText("Hello World"));
```
However I realized that the setDescription method was not yet exposed in the public typescript interface. Let me fix this.

**Comment by erossignon** [comment]
typescript definition file has been fixed in [2.106.0](https://github.com/node-opcua/node-opcua/releases/tag/v2.106.0)

**Comment by ptorrent** [comment]
Thanks a lot ! Other question about displayName and description properties:

Do I've to use coerceLocalizedText("Hello World") for both property, actually I'm not ? 

I'm using Matrikon as OPC client and I'm not able to read them. On some others clients it's work

**Comment by erossignon** [comment]
Both should work

`setDescription` takes a `LocalizedTextLike` argument 

LocalizedTextLike could be `string | { text: string, locale: string } | LocalizedText`

**Comment by erossignon** [comment]
[node-opcua@2.109.0](https://github.com/node-opcua/node-opcua/releases/tag/v2.109.0) now exposes BaseNode#setDiplayName and BaseNode#setDescription methods.
