### ISSUE TITLE
Despite requestExactEndpointUrl property set to false Error print and AuditUrlMismatchEventType event is generated

### ISSUE THREAD

**Issue by Graos** [node-opcua/node-opcua#1294]
node-opcua server version: 2.108.0
NodeJS version: v18.16.0

Despite **requestExactEndpointUrl** property set to false in the server object, following error prints are logged  

**12:52:25.744Z :opcua_server :450   Cannot find suitable endpoints in available endpoints. endpointUri = opc.tcp://192.168.147:26543**

and **AuditUrlMismatchEventType** event is generated and the incoming connection is successfully accepted.

The issue lies in the line 450 opcua_server.js where the error is logged and event is generated before the property flag **requestExactEndpointUrl** is checked.

if (endpoints.length === 0) {
        // we have a UrlMismatch here
        const ua_server = server.engine.addressSpace.rootFolder.objects.server;
        **errorLog("Cannot find suitable endpoints in available endpoints. endpointUri =", request.endpointUrl);
        ua_server.raiseEvent("AuditUrlMismatchEventType", {
            endpointUrl: { dataType: node_opcua_variant_1.DataType.String, value: request.endpointUrl }**
        });
        if (OPCUAServer.requestExactEndpointUrl) {
            return { errCode: node_opcua_status_code_1.StatusCodes.BadServiceUnsupported };
        }
        else {
            endpoints = server._get_endpoints(null);
        }
    }

**Comment by erossignon** [comment]
This is how the requestExactEndpointUrl feautre has been intentionaly implemented:


If OPCUAServer.requestExactEndpointUrl is set to true, the connection will be rejected if an exact endpoint match is not found. 

On the other hand, when it is set to false, the connection will be accepted, potentially using an endpoint that doesn't precisely match the requested one. 

In both scenarios, the AuditUrlMismatchEventType will be triggered to indicate that a connection attempt has been made with a non-exact endpoint."

**Comment by Graos** [comment]
I agree with the event but the error logging is not justified. Either it should be a warning or no log at all. Thanks for your insight.

**Comment by erossignon** [comment]
Please provide a PR to turn the ErrorLog to a warningLog. 
I understand that is is quite frequent not to use the exact endpoint while connecting and we don't need to be alarming.

**Comment by Graos** [comment]
I don't see AuditUrlMismatchEventType  in UaExpert Event view even though the URL is different. I tried enabling the isAuditing to true to see if i get any other audit events but i don't get anything up to the UaExpert client. Is there anything i need to enable to get this events at the client side ?
