### ISSUE TITLE
Node-red and Opc Ua with certificate connection problem

### ISSUE THREAD

**Issue by matteovi** [node-opcua/node-opcua#1297]
I'm tryng to connect node red with plc that use opc ua connection with certificates.
I've followed another guide to paste certificates and private key on the correct folders but it's doesn't work.

That's a screen of Node-Red configuration and console debug.

![immagine (1)](https://github.com/node-opcua/node-opcua/assets/109208376/03e0c8e8-7b2b-4f83-875e-9ab0bc54051d)

And the error:

![immagine (2)](https://github.com/node-opcua/node-opcua/assets/109208376/130a6cd9-ca2b-4075-8373-61e5c20837c8)

**Comment by erossignon** [comment]
You client certificate (in node-red) must be trusted by the server. 
This requires that you add your client certificate to the trusted list of your server by following the instructions provided by your server vendor.

**Comment by matteovi** [comment]
I have done. Certificate was trusted and activated on the machine

**Comment by erossignon** [comment]
can you send the certificate for inspection ?

**Comment by matteovi** [comment]
`-----BEGIN CERTIFICATE-----
MIIE0jCCA7qgAwIBAgICEAAwDQYJKoZIhvcNAQELBQAwczELMAkGA1UEBhMCRlIx
DDAKBgNVBAgTA0lERjEOMAwGA1UEBxMFUGFyaXMxLzAtBgNVBAoTJkxvY2FsIE5P
REUtT1BDVUEgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRUwEwYDVQQDEwxOb2RlT1BD
VUEtQ0EwIhgPMjAyMzA5MDYxNTM4MTdaGA8yMDM4MDkwMjE1MzgxN1owZzELMAkG
A1UEBhMCRlIxDDAKBgNVBAgMA0lERjEOMAwGA1UEBwwFUGFyaXMxEjAQBgNVBAoM
CU5vZGVPUENVQTENMAsGA1UECwwEVW5pdDEXMBUGA1UEAwwOTm9kZU9QQ1VBLVRF
U1QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCh7BFSJyKGVI6YA18V
170B7X2Cd+bQ493BmbChvuhzxO86vw79K8Mv7bx8BnxegEyEKT3DTNEb8Vo4ubkU
UStl+OGxnTB9qbAJC/g6SVMuJWld0L4YV8zIzz9Xf2YTGL0epwrKuurrCpPP7EMS
ggww9KDMYdfn3OCOsO4j5WxhYjBGimuYtC5aOf3C4L/U7rO9lY76mL9ioZf/RzNV
seAu9Tyk8Bzvqf7XQOqLXEERCKDdMLHDdpJlaBgDfhP3v8hzZcmh7+1UaAELKtnn
1MSlyvPF6TiKdJDRsH2KdlPlDTnQEu5lGOwVfZ7CFFu4mRUM9fuVusa9S0kcv90p
riXHAgMBAAGjggF2MIIBcjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBRO5pKPnMkk
QoGe3hVpOSAmgVnz4zCBpQYDVR0jBIGdMIGagBRuLqbl7lqn/sR0AoVkP/5PSQH9
1KF3pHUwczELMAkGA1UEBhMCRlIxDDAKBgNVBAgTA0lERjEOMAwGA1UEBxMFUGFy
aXMxLzAtBgNVBAoTJkxvY2FsIE5PREUtT1BDVUEgQ2VydGlmaWNhdGUgQXV0aG9y
aXR5MRUwEwYDVQQDEwxOb2RlT1BDVUEtQ0GCCQCzuBKZY+WCyzA7BgNVHREENDAy
hhx1cm46SUNOQjAxNDpOb2RlT1BDVUEtQ2xpZW50ggxtYWNoaW5lMS5jb22HBMCo
OGgwLAYJYIZIAYb4QgENBB8WHU9wZW5TU0wgR2VuZXJhdGVkIENlcnRpZmljYXRl
MA4GA1UdDwEB/wQEAwIC/DAgBgNVHSUBAf8EFjAUBggrBgEFBQcDAQYIKwYBBQUH
AwIwDQYJKoZIhvcNAQELBQADggEBAIr11FwzO3JjSTQiKkxemqVnFAeshERCyOSh
0KmvXmLT6Zqf8dD2khMrDo4+XLEcIIgx4KGWNIoN8W8GqMDnQNcAnyhtItEfIPUs
+rrTsbR6wypgrWh0zLLzgrR5OgQDAQXKIjJrS3Arig3jhUgzg0U7pgdOiYYvct5M
RwO+YxJTJ7nFawpcsVjDh5yKRGy0DMZ0BC9g78Ojfm8mYhENvVn5/iB2Pua29RhI
NZdDUo1UOxORRDlMkWEe38VP9FMrXDkwqBLixLpI6eZjLw4t48VLGuTqSDJvlnhR
a8mvrzq533i2WXJvV6bm9etW94koEPnmTl9Fub3Acv8Hz+QlrPQ=
-----END CERTIFICATE-----
`

[NodeOPCUA-TEST[f607840e44b2d9231c50a02424fb5eb8ecd0f688].zip](https://github.com/node-opcua/node-opcua/files/12547020/NodeOPCUA-TEST.f607840e44b2d9231c50a02424fb5eb8ecd0f688.zip)
