### ISSUE TITLE
Question: Is it possible to connect to an opc.udp:// address?

### ISSUE THREAD

**Issue by calss0t** [node-opcua/node-opcua#1309]
- (X) my question is related to node-opcua acting as an OPCUA CLIENT
- ( ) my question is related to node-opcua acting as an OPCUA SERVER

My code is working for a connection using opc.tcp address, but when I try to use a connection with opc.udp, I get an error.

**My code:**
```
function loadOpcUALib() {
    if (!opcua) {
        try { opcua = require('node-opcua'); } catch (error) {  console.log(error); }
        if (!opcua && manager) { try { opcua = manager.require('node-opcua'); } catch (error) {  console.log(error); } }
    }
    return (opcua) ? true : false;
}
let client = opcua.OPCUAClient.create(options);
```
This works: 
```
const endpoint = "opc.tcp://localhost:4840";

client.connect(endpoint, function (err) {
    if (err) {
        _clearVarsValue();
        logger.error(`'${data.name}' connect failure! ${err}`);
    } else {
        logger.info(`'${data.name}' connection`, true);
    }
    callback(err);
});
```
This does not work:
```
const endpoint = "opc.udp://localhost:4840";

client.connect(endpoint, function (err) {
    if (err) {
        _clearVarsValue();
        logger.error(`'${data.name}' connect failure! ${err}`);
    } else {
        logger.info(`'${data.name}' connection`, true);
    }
    callback(err);
});
```

Error:
```Error: The connection may have been rejected by server,
Err = ([NODE-OPCUA-E05] this transport protocol is not supported :opc.udp:)
```

With this error I can see that this protocol is not supported, but is there a way to work around this?

**Comment by erossignon** [comment]
Address like `opc.udp://224.0.5.1:4840’ are used in OPCUA PubSub ( see part 14) 

You need to use `opc.tcp://<hostname>:<port>` for using OPCUAClient classic connect.

We support OPCUA PubSub as a Sterfive commercial package. This package contains a set of libraries on top of NodeOPCUA to enable OPCUA PubSub and implements the Part 14 specificiation.
