### ISSUE TITLE
How to acknowledge alarm using Cogent DataHub 

### ISSUE THREAD

**Issue by InstantlyMoist** [node-opcua/node-opcua#1317]
Hi, 

For my intenrship I'm using Cogent Data Hub to translate AE to UA and connect to it using this library.

I've been trying to find documentation regarding AE and aknowledging alarms. But I'm out of ideas, this is the current structure.

![image](https://github.com/node-opcua/node-opcua/assets/32609460/42db1500-ab8a-4cc0-99f8-2dc9297c2255)

One thing I tried is adding a subscription to the 'Ack' and 'Status', unfortunately I don't see anything changing in the 'Ack' once aknowledging. The status however does change. One problem is that it is not writeable.

So I'm out of ideas on what to try, is there something obvious I'm missing here?

**Comment by AndreasHeine** [comment]
if the server exposes the Alarms and Conditions to the Addressspace like:
![image](https://github.com/node-opcua/node-opcua/assets/56362817/78a0352b-b263-4255-bcf8-d651ef7a9308)
then you have the method here

**Comment by InstantlyMoist** [comment]
> if the server exposes the Alarms and Conditions to the Addressspace like: ![image](https://user-images.githubusercontent.com/56362817/275763250-78a0352b-b263-4255-bcf8-d651ef7a9308.png) then you have the method here

Awesome, I checked it out and I see this:

![image](https://github.com/node-opcua/node-opcua/assets/32609460/c14a18c7-99a2-4fb5-a4b9-c780caa04843)

Doesn't seem like I'm getting any function calls in here

**Comment by AndreasHeine** [comment]
whats the typedefinition of that alarm?

**Comment by InstantlyMoist** [comment]
I hope this is what you mean :D

![image](https://github.com/node-opcua/node-opcua/assets/32609460/e2699387-0a8c-421f-ba42-69d26e076800)

**Comment by AndreasHeine** [comment]
![image](https://github.com/node-opcua/node-opcua/assets/56362817/9e8657f4-5639-4442-a7ee-6961308d8c28)

AlarmConditionType is a SubType of AcknowledgeableConditionType and should have that method because its mandatory...

**Comment by AndreasHeine** [comment]
maybe you can look into this:
https://github.com/node-opcua/node-opcua/blob/master/packages/node-opcua-samples/bin/simple_client_ts.ts

**Comment by AndreasHeine** [comment]
> Ah awesome! I see it now within the conditiontype.
> 
> ![image](https://user-images.githubusercontent.com/32609460/275767165-6ab3d0b0-14a7-48b8-9709-a510aec43979.png)
> 
> I will try to figure out how to call the function according to the documentation. I'll let you know!

the method of the type is not ment to be called as far as i know!

**Comment by InstantlyMoist** [comment]
What OPC-UA browser do you use? Maybe it's something wrong with the one I use. I'm also not really able to figure out where exactly the methods get called from the link you've provided.

**Comment by AndreasHeine** [comment]
> What OPC-UA browser do you use? Maybe it's something wrong with the one I use. I'm also not really able to figure out where exactly the methods get called from the link you've provided.

UA Expert its the Reference-Implementation of an UA Client

**Comment by AndreasHeine** [comment]
Did some research for you ;)

https://reference.opcfoundation.org/Core/Part9/v105/docs/5.7

5.7.3 Acknowledge Method

The [Acknowledge](https://reference.opcfoundation.org/search/306?t=Acknowledge) [Method](https://reference.opcfoundation.org/search/306?t=Method) is used to acknowledge an [Event Notification](https://reference.opcfoundation.org/search/306?t=Event%20Notification) for a [Condition](https://reference.opcfoundation.org/search/306?t=Condition) instance state where [AckedState](https://reference.opcfoundation.org/search/306?t=AckedState) is False. Normally, the [NodeId](https://reference.opcfoundation.org/search/306?t=NodeId) of the object instance is passed as the [ObjectId](https://reference.opcfoundation.org/search/306?t=ObjectId) to the [Call](https://reference.opcfoundation.org/search/306?t=Call) [Service](https://reference.opcfoundation.org/search/306?t=Service). However, some [Servers](https://reference.opcfoundation.org/search/306?t=Servers) do not expose [Condition](https://reference.opcfoundation.org/search/306?t=Condition) instances in the [AddressSpace. ](https://reference.opcfoundation.org/search/306?t=AddressSpace.)Therefore, [Servers](https://reference.opcfoundation.org/search/306?t=Servers) shall allow [Clients](https://reference.opcfoundation.org/search/306?t=Clients) to call the [Acknowledge](https://reference.opcfoundation.org/search/306?t=Acknowledge) [Method](https://reference.opcfoundation.org/search/306?t=Method) by specifying [ConditionId](https://reference.opcfoundation.org/search/306?t=ConditionId) as the [ObjectId.](https://reference.opcfoundation.org/search/306?t=ObjectId.) The [Method](https://reference.opcfoundation.org/search/306?t=Method) cannot be called with an [ObjectId](https://reference.opcfoundation.org/search/306?t=ObjectId) of the [AcknowledgeableConditionType](https://reference.opcfoundation.org/search/306?t=AcknowledgeableConditionType) [Node](https://reference.opcfoundation.org/search/306?t=Node).

**Comment by InstantlyMoist** [comment]
Thanks, I think I got a working piece of code (somewhat)

Unfortunately you're right that I can't call the 'acknowledge' function from the base data-type. Using OPC Expert gives me the same result:
![image](https://github.com/node-opcua/node-opcua/assets/32609460/560193d6-841c-4649-bcf6-0eef57247010)

No acknowledge method can be found. Honestly not sure what would be causing this...

**Comment by AndreasHeine** [comment]
unfortunately if all that did not work you need to contact Cogent DataHub... if the don't expose the method there are not compliant to OPC UA Spec. 

which would be a shame and yet another bad implementation of OPC UA...

**Comment by InstantlyMoist** [comment]
Bummer! is there another application you might know of that translates OPC AE to UA? Our systems currently do not support UA but in theory they will support it in the future. Hence why I want to focus on actually implementing something future-proof-ish :D

**Comment by InstantlyMoist** [comment]
seems to have the same issue for me. cogent datahub has a lot of different options for which opc ae server to connect to.

![image](https://github.com/node-opcua/node-opcua/assets/32609460/75ae27bd-930e-49b9-8680-174287ffac87)

This is with opc-ua wrapper enabled, and all possible servers selected. something seems of to me

**Comment by InstantlyMoist** [comment]
for example; right is cogent datahub.

![image](https://github.com/node-opcua/node-opcua/assets/32609460/eba4ae5a-4059-46a4-847b-5caf9a5d3fe1)

**Comment by InstantlyMoist** [comment]
Ah, starting to understand it. The Cogent Data Hub way was completely wrong so I now installed Matrikon OPC UA Tunneler. When using Prosys UA Browser I can monitor the events and I actually see them showing up now. 

Next thing is to figure out how to actually get them in my piece of code, and be able to aknowledge them :D

**Comment by InstantlyMoist** [comment]
Nevermind me again, I still can't find the events in my explorer. Only in the event view. Which renders it basically useles as I need the nodeId's...

**Comment by AndreasHeine** [comment]
so finally:

```js
const methodToCall = {
    objectId: <ConditionId_from_the_Event>,
    methodId: "i=9111",
    inputArguments: [
        new Variant({...}), // EventId (ByteString)
        new Variant({...}), // Comment (LocalizedText)
    ]
}
session.call(methodToCall,function(err,callResult) {
   if (!err) {
        console.log(" statusCode = ",callResult.statusCode);
        console.log(" inputArgumentResults[0] = ",callResult.inputArgumentResults[0].toString());
        console.log(" inputArgumentResults[1] = ",callResult.inputArgumentResults[1].toString());
        console.log(" outputArgument[0]       = ",callResult.outputArgument[0].toString()); // array of variant
   }
});
```

this should ack an alarm if it is not exposed to the addressspace

**Comment by InstantlyMoist** [comment]
I dont get how I'm supposed to get the alarms when they're not exposed to the namespace. I've tried adding a subscription which worked. But on subscribing it does not send me the already existing events. It only shows me new ones.

**Comment by AndreasHeine** [comment]
the alarm in the addressspace is just the current state of it. you need to create a event subscription for that alarmtype!

**Comment by InstantlyMoist** [comment]
@AndreasHeine I've actually had something similair to the listener. I still only get new/changed alarms. With a normal subscription you also get the 'already existing' alarms. For reference;

`    const aeConnection = await aeClient.connect(aeEndpointUrl); // TODO: Test if this is needed
    const aeSession = await aeClient.createSession2();

    const subscription = await aeSession.createSubscription2({
        maxNotificationsPerPublish: 10,
        priority: 10,
        publishingEnabled: true,
        requestedLifetimeCount: 1000,
        requestedMaxKeepAliveCount: 47,
        requestedPublishingInterval: 1000,
    });

    const fields = [
        "EventId",
        "EventType",
        "SourceNode",
        "SourceName",
        "Time",
        "ReceiveTime",
        "Message",
        "Severity",

        // ConditionType
        "ConditionClassId",
        "ConditionClassName",
        "ConditionName",
        "BranchId",
        "Retain",
        "EnabledState",
        "Quality",
        "LastSeverity",
        "Comment",
        "ClientUserId",

        // AcknowledgeConditionType
        "AckedState",
        "ConfirmedState",

        // AlarmConditionType
        "ActiveState",
        "InputNode",
        "SuppressedState",

        "HighLimit",
        "LowLimit",
        "HighHighLimit",
        "LowLowLimit",

        "Value"
    ];

    const eventFilter = constructEventFilter(fields, ofType("ConditionType"));

    const result = await subscription.monitor({
        attributeId: AttributeIds.EventNotifier,
        nodeId: ObjectIds.Server
    }, {
        samplingInterval: 1000,
        queueSize: 100000,
        discardOldest: false,

        filter: eventFilter,
    }, TimestampsToReturn.Both)

    result.on('changed', (value) => {
        console.log("new value " + value);
    });
`

**Comment by AndreasHeine** [comment]
sorry forgot to mention that... 

https://reference.opcfoundation.org/Core/Part9/v104/docs/5.5.7

> [ConditionRefresh](https://reference.opcfoundation.org/search/37?t=ConditionRefresh) allows a [Client](https://reference.opcfoundation.org/search/37?t=Client) to request a [Refresh](https://reference.opcfoundation.org/search/37?t=Refresh) of all [Condition ](https://reference.opcfoundation.org/search/37?t=Condition)instances that currently are in an interesting state (they have the [Retain](https://reference.opcfoundation.org/search/37?t=Retain) flag set). This includes previous states of a [Condition](https://reference.opcfoundation.org/search/37?t=Condition) instance for which the [Server](https://reference.opcfoundation.org/search/37?t=Server) maintains [Branches](https://reference.opcfoundation.org/search/37?t=Branches).

**Comment by InstantlyMoist** [comment]
Awesome, finally getting somewhere :D

I'm now able to Acknowledge the alarms via the code which is an amazing step so far. Meaning I'm finally able to link the alarms to my app that I'm making. In case you're wondering, this is the code that I came up with:

`
 const subscription = await aeSession.createSubscription2({
        maxNotificationsPerPublish: 10,
        priority: 10,
        publishingEnabled: true,
        requestedLifetimeCount: 1000,
        requestedMaxKeepAliveCount: 47,
        requestedPublishingInterval: 1000,
    });

    const fields = [
        "EventId",
        "SourceNode",
        "SourceName",
        "ConditionId",
        "Message",
        "Severity",
        "AckedState",
        "ConfirmedState",
        "ActiveState",
    ];

    const eventFilter = constructEventFilter(fields, ofType("ConditionType"));

    const result = await subscription.monitor({
        attributeId: AttributeIds.EventNotifier,
        nodeId: ObjectIds.Server
    }, {
        samplingInterval: 1000,
        queueSize: 100000,
        discardOldest: false,

        filter: eventFilter,
    }, TimestampsToReturn.Both)

    callConditionRefresh(subscription) // Give us the existing alarms!!!

    result.on('changed', async (values) => {
        const sourceNode = values[1].value; 
        if (sourceNode == undefined) return; // Probably not relevant for us.

        const eventId = values[0].value;
        const sourceName = values[2].value;
        const conditionId = values[3].value;
        const message = values[4].value.text;
        const serverity = values[5].value;
        const ackedState = values[6].value.text;
        const confirmedState = values[7].value;
        const activeState = values[8].value.text; // Goes to Inactive when acknowledged and removed


        console.log(conditionId.value); 
        console.log(sourceName + " " + message + " " + serverity + " " + ackedState + " " + confirmedState + " " + activeState);

        const methodToCall = {
            objectId: conditionId,
            methodId: MethodIds.AcknowledgeableConditionType_Acknowledge, // TODO: Replace to MethodIds
            inputArguments: [
                new Variant({ dataType: DataType.ByteString, value: eventId }),
                new Variant({ dataType: DataType.LocalizedText, value: "test comment!" })
            ]
        }

        aeSession.call(methodToCall, (err, result) => {
            if (err) return; // Currently not important
            console.log("Method call result: " + JSON.stringify(result, null, 2));
        });
    });

`

**Comment by mikakaraila** [comment]
Or this way:
            const status = await session.acknowledgeCondition(conditionId, eventId, comment);

**Comment by erossignon** [comment]
For the record a enhancement has been adede to the session.acknowledgeCondition method in [node-opcua@2.119.0](https://github.com/node-opcua/node-opcua/releases/tag/v2.119.0) that address the problem and fixes the behavior found with Cogent DataHub.
