### ISSUE TITLE
Manipulate Status Codes

### ISSUE THREAD

**Issue by immenz** [node-opcua/node-opcua#132]
Hello, 

where can i manipulate the status codes of the simulation nodes in the Server? I try to get random codes between good and bad.

**Comment by erossignon** [comment]
StatusCodes are currently expressed as enum 
see node-opcua\lib\datamodel\opcua_status_code.js, node-opcua\lib\raw_status_codes.js
This is convenient but doesn't allow any statuscode to be easily written.

What sort of missing StatusCode do you need ? Can you elaborate.

**Comment by erossignon** [comment]
StatusCode can be enriched with Status bits now ( see makeStatusCode )
https://github.com/node-opcua/node-opcua/blob/master/lib/datamodel/opcua_status_code.js#L12
https://github.com/node-opcua/node-opcua/blob/master/lib/datamodel/opcua_status_code.js#L307

and example of use:
https://github.com/node-opcua/node-opcua/blob/f59c35b774b944aca370f9ab02eb47b27327daff/test/datamodel/test_status_code.js#L105
