### ISSUE TITLE
MultiStateValueDiscrete_ValueAsText gives "Invalid" when Variable value is 0 

### ISSUE THREAD

**Issue by muddasir-barnes** [node-opcua/node-opcua#1323]
1. instantiated an object which has a child node of type MultiStateValueDiscreteType. 
2. Initialized the EnumValues property in the server
![image](https://github.com/node-opcua/node-opcua/assets/129770829/30216ee0-a33b-4e90-961d-4e2535a82341)
3. Initialized the getter and setter functions for the MultiStateValueDiscrete Variable using bindVariable Call. 
4. When 0 is written, the expected value of ValueAsText property should be "First", however, it shows "Invalid".( see screenshot below)
![image](https://github.com/node-opcua/node-opcua/assets/129770829/2b566475-a238-4119-9d65-48863ddf9078)
5. When other values are written (1,2,3), the ValueAsText works as expected (see screenshots below)
![image](https://github.com/node-opcua/node-opcua/assets/129770829/9c6e78f5-a410-45ac-bc61-e3aadc60b95b) 
![image](https://github.com/node-opcua/node-opcua/assets/129770829/7c24f403-3a11-4cde-942d-c8113f10e88b)
![image](https://github.com/node-opcua/node-opcua/assets/129770829/a5d4f2df-9c91-4836-9979-f01b267c14f2)

It seems like it works partially, only that 0 index value is not detected and value as text is set to Invalid 

#### Version
node-opcua": "^2.115.0"

**Comment by erossignon** [comment]
Please provide a gist to ensure that the issue can be reproduced.

**Comment by erossignon** [comment]
fixed in node-opcua@2.119.0
