### ISSUE TITLE
About OPC XML-DA web service

### ISSUE THREAD

**Issue by EasonWang01** [node-opcua/node-opcua#133]
hi,I don't know could I ask some opc question here.
I using a simotion control D410   manual: http://dfpd.siemens.ru/assets/files/infocenter/Documetations/Automation_systems/SIMOTION/Simotion%20IT/SIMOTION_IT_Programming_and_Web_Services.pdf

Default it is using a OPCXML.js library which is write with soap ,I not really know the structural.I was wondering how to access this opc server via nodejs. thanks

**Comment by demeyr** [comment]
The D410 probably only supports OPC DA, not OPC UA.
Maybe you can connect with for example a Kepware server and exposing the tags to OPC UA.
