### ISSUE TITLE
Timestamps not updating in latest versions

### ISSUE THREAD

**Issue by mb-software** [node-opcua/node-opcua#1342]
This was posted by another user in an old closed issue but seems to be a new problem of the latest versions. I get the same issue in version 2.120.0 with the sample server as well as with my own application:

> I am using the latest version (2.118.0) of node-opcua with [this](https://github.com/node-opcua/node-opcua-sampleserver) sample server.
> The sourceTimestamp and/or serverTimestamp are not updating for me.
> But the same is working for the node-opcua version 2.75.0.
> I attached the image below.
> 
> Image for V 2.118.0 :
> ![node-opcua-2 118 0](https://github.com/node-opcua/node-opcua/assets/153627817/62892c39-8442-440f-a9ae-6bdf9e704afd)
> 
> 
> Image for V 2.75.0 :
> ![node-opcua-2 75 0](https://github.com/node-opcua/node-opcua/assets/153627817/8745aa0b-6886-426b-ab81-6afec98cdb39)
> 
> Would you please check and update?
> 
> Thanks for the awesome lib !!

_Originally posted by @Akeel95 in https://github.com/node-opcua/node-opcua/issues/651#issuecomment-1852142246_

**Comment by erossignon** [comment]
fixed in (node-opcua@2.121.0](https://github.com/node-opcua/node-opcua/releases/tag/v2.121.0)

**Comment by Akeel95** [comment]
Hi @erossignon 

With respect to the timestamps there are 2 problems I faced which are explained below:

1. When constant data is coming on server continuously, the source and server timestamp is not updating in data access view. But the same is updating in Attributes Section on Right side.

<img width="960" alt="opcua-const-data-ts-changing-from-source" src="https://github.com/user-attachments/assets/628f9d94-31df-4ed4-81a1-35416ba0081e">

2. When continuous data is updating, it is not updating the server timestamp correctly. (ie. library is showing the sourceTimestamp in serverTimestamp)

<img width="960" alt="opcua-const-data-ts-changing-from-source" src="https://github.com/user-attachments/assets/4fa9e89b-473d-45f6-8bcd-191f41e9c39f">

In any of the case it should always change the serverTimestamp, but its not happening.

To check the scenarios I used the node-opcua library provided server [examples](https://github.com/node-opcua/node-opcua/blob/master/documentation/sample_server.js).

I used the method to update the sourceTimestamp:
      node.**setValueFromSource**(variant, StatusCodes.Good, new Date(timestamp));

Similar issue is reported here:
https://github.com/mikakaraila/node-red-contrib-opcua/issues/611

Please let us know about the fix or work around.

Thanks!!

**Comment by erossignon** [comment]
Hi Akeel95](https://github.com/Akeel95),

This ticket is closed and resolved and unlikely to be answered by anyone anymore.
 

Consider opening an new isssue to may be get a answer from the community. 

Also whilst node-opcua is open-source, we only do support through paid services.  (https://support.sterfive.com).
