### ISSUE TITLE
Add the ability to limit the number of monitoredItem for small embedded server

### ISSUE THREAD

**Issue by erossignon** [node-opcua/node-opcua#135]
We need to add the ability to restrict the number of monitored items a client can create to protect ~~nano~~ **micro** profile server from being overloaded.

**Comment by erleeman** [comment]
Hi @erossignon 

What would be the right place to implement this?
I am new with node / node-opcua but would like to support.

**Comment by konradheidrich** [comment]
Maybe I am wrong, but monitored items needs subscription and subscription is not part of Nano profile - it is implemented in Micro? AFAIK this is the main difference between Nano and Micro and related to many services which needs to be implemented to the server.

**Comment by erleeman** [comment]
I am currently working on this but the currentMonitoredItemsCount per Session is always 0. Is this a already known bug?

**Comment by erossignon** [comment]
@erleeman  currentMonitoredItemsCount is currenly not wired and always returns 0. This is work in progress.
