### ISSUE TITLE
AWS Lambda cannot create PKI folder for opcua-client 

### ISSUE THREAD

**Issue by gilcohen67** [node-opcua/node-opcua#1359]
**Current behavior**

```
START RequestId: bb39968f-a572-4d7d-8365-b9dffa16aca8 Version: $LATEST
2024-04-02T19:02:42.922Z	bb39968f-a572-4d7d-8365-b9dffa16aca8	INFO	Creating client...
2024-04-02T19:02:42.941Z	bb39968f-a572-4d7d-8365-b9dffa16aca8	INFO	19:02:42.941Z :handler                 :572    cannot create folder  /home/sbx_user1051/.config/node-opcua-default-nodejs/PKI false
2024-04-02T19:02:42.942Z	bb39968f-a572-4d7d-8365-b9dffa16aca8	ERROR	Error:  Error: ENOENT: no such file or directory, mkdir '/home/sbx_user1051/.config/node-opcua-default-nodejs/PKI'
```

**Describe the bug**
On creating client, the certificates folder cannot be created. Running on AWS Lambda.

**Step by step instruction to reproduce**

Running on AWS Lambda. 
Runtime: nodejs16.x
Architectures: x86_64
node-opcua: 2.120.0

```
    const client = OPCUAClient.create({
      endpointMustExist: false
    })
```

**Expected behavior**
Is there a way to bypass this behavior? I don't have any certificates, and is working on an ec2 instance. On Lambda I run into this folder creation issue. 

**Gist**

 
gist: https://gist.github.com/gilcohen67/ae6572c1725d8d3d4447f8b209476bf9

**Context**

- (*) my request is related to node-opcua acting as an OPCUA CLIENT
- ( ) my request is related to node-opcua acting as an OPCUA SERVER

- ( ) I have installed node-opcua from source ( using git clone)
- (*) I have installed node-opcua as a package ( using npm install )
- ( ) I am using an application that uses node-opcua

    - ( ) node-red
    - ( ) other : please specify

- **node-opcua version:** : 2.120.0

  
  

- **Node:**

  `node --version` = 16.X

**Comment by erossignon** [comment]
The latest edition of [NodeOPCUA by Example book](https://leanpub.com/node-opcuabyexample-edition2024) shows how you can create your custom PKI in a designated folder rather than the default one, that may accidentaly point to in a R/O folder.
