### ISSUE TITLE
nodeopcua wrong error prints when crawler read is attempted on a unknown NodeId from the server.

### ISSUE THREAD

**Issue by Graos** [node-opcua/node-opcua#1364]
nodeopcua version: 2.124.0

Wrong error print in the console when crawler read of NodeID, which is not available in the server is attempted.
Server returns BadNodeIdUnknown statusCode ( see the wireshark snapshot) but nodeopcua prints the following in the console

**Note:** nodeopcua ignores the Statuscode of the response from server and repeatedly tries Read and browse request for the NodeId in question.

Wrong Print Information from nodeopcua:

15:35:05.636Z :node_crawler_base             :260    node  ns=2;i=5007  has a invalid browseName null
15:35:05.637Z :node_crawler_base             :286    node  ns=2;i=5007  has a invalid displayName null
15:35:05.646Z :node_crawler_base             :260    node  ns=2;i=5007  has a invalid browseName null
15:35:05.647Z :node_crawler_base             :286    node  ns=2;i=5007  has a invalid displayName null

Wireshark snapshot of the ReadRequest/ReadResponse

Read Request from nodeopcua CLient
![image](https://github.com/node-opcua/node-opcua/assets/69800669/790ecf39-0264-4356-9550-c69eab708075)

Read Response from server

![image](https://github.com/node-opcua/node-opcua/assets/69800669/da404559-ca29-4bff-a81c-91e7d37d461b)

**Comment by erossignon** [comment]
As of version 2.82.0, the "node-opcua-client-crawler" module has been officially deprecated. It remains available "as is" for applications that currently utilize it, but it is no longer maintained. For details on the deprecation, please refer to the [release notes](https://github.com/node-opcua/node-opcua/releases/tag/v2.82.0).

A new and improved crawler version is now available exclusively for members of the NodeOPCUA Subscription program.

For access to the upgraded crawler and other exclusive features, please ensure your NodeOPCUA Subscription membership is active and contact sterfive.com to acquire a licence.
