### ISSUE TITLE
Type Declarations in separate package

### ISSUE THREAD

**Issue by goldim** [node-opcua/node-opcua#1371]
It would be great if a separate Type Declarations package was existed in **npm** repository. Usually packages comes with `@types/<name of package>` package.

**Comment by erossignon** [comment]
The trend of including type declarations directly within npm packages has made separate @types/<name of package> packages increasingly redundant. 
Most modern libraries now incorporate .d.ts files directly, simplifying dependency management and ensuring that type definitions are always in sync with the library code. 

While @types/ packages were crucial for providing TypeScript support for JavaScript-only libraries, they are less necessary as more libraries include built-in TypeScript support. 

This integration improves maintainability and developer experience by reducing the need for additional package installations and keeping everything needed within a single package.

Node-opcua benefits from having incorporate d.ts files incorporated, I am not sure separating them out is a good idea.
