### ISSUE TITLE
Client reconnection to server loaded with different AddressSpace configuration is not handled correctly.

### ISSUE THREAD

**Issue by Graos** [node-opcua/node-opcua#1372]
node-opcua client:2.125.0
nodejs version: v 18.20.1

Use case of client reconnection to OPC UA server loaded with different AddressSpace than the first time is not handled correctly.

It is very easy to reproduce the issue.

1. Establish a connection to server from node-opcua client.
2. Create subscription with signals. communication is established successfully with value change reported by node-opcua stack.
3. Disconnect the server.
4. Start the server with new AddressSpace configuration.
5. Client reestablish connection and creates subscription and adds monitored items without application intervention. Note here node-opcua stack neither reports the new subscription ID nor the bad status of the added monitored item which is not available in the server.
6. Server reports BadNodeIdUnknown for all the monitored item signals. This is not reported to the application and the node-opcua cyclically sends publish request for the keep alive subscription response.

Wireshark capture snapshot attached during reconnection

![image](https://github.com/node-opcua/node-opcua/assets/69800669/578f79b2-a863-4d52-9e93-eb4b62059c36)
![image](https://github.com/node-opcua/node-opcua/assets/69800669/578f79b2-a863-4d52-9e93-eb4b62059c36)
![image](https://github.com/node-opcua/node-opcua/assets/69800669/578f79b2-a863-4d52-9e93-eb4b62059c36)

**Comment by erossignon** [comment]
with the community version of node-opcua: You'll need to restart the client if the server has changed in shape between two restarts.
