### ISSUE TITLE
Inefficient and overly verbose connection closing

### ISSUE THREAD

**Issue by szakharchenko** [node-opcua/node-opcua#1377]
**Current behavior**

The client needlessly takes 5 seconds to disconnect from a compliant server, and issues an unnecessary warning message.

**Describe the bug**

As you're [aware](https://github.com/node-opcua/node-opcua/blob/9bc9059ed1eee2b50aeac99b7f878eeb93425116/packages/node-opcua-secure-channel/source/client/client_secure_channel_layer.ts#L830), servers are not expected to respond to a CloseSecureChannelRequest. In particular, [open62541 doesn't](https://github.com/open62541/open62541/blob/f6577611a9381e7301c5c2b7e47df46072af5ef2/src/server/ua_services_securechannel.c#L132).

The 1-second timeout specified [here](https://github.com/node-opcua/node-opcua/blob/9bc9059ed1eee2b50aeac99b7f878eeb93425116/packages/node-opcua-secure-channel/source/client/client_secure_channel_layer.ts#L840) is [overridden inside the _performMessageTransaction call](https://github.com/node-opcua/node-opcua/blob/9bc9059ed1eee2b50aeac99b7f878eeb93425116/packages/node-opcua-secure-channel/source/client/client_secure_channel_layer.ts#L1504) to be [5 seconds](https://github.com/node-opcua/node-opcua/blob/9bc9059ed1eee2b50aeac99b7f878eeb93425116/packages/node-opcua-secure-channel/source/client/client_secure_channel_layer.ts#L320), which is likely unintendedly and unnecessarily long.

Additionally, a [warning message](https://github.com/node-opcua/node-opcua/blob/9bc9059ed1eee2b50aeac99b7f878eeb93425116/packages/node-opcua-secure-channel/source/client/client_secure_channel_layer.ts#L852) is produced on the timeout, which makes no sense as not receiving a response is actually [the specified behaviour](https://reference.opcfoundation.org/Core/Part6/v104/docs/7.1.4).

**Step by step instruction to reproduce**

1. set up an open62541-based server (a sample would do; no particular data need to be served);
2. create and run a basic client that connects to it and immediately disconnects:
```js
...
            const client = OPCUAClient.create()
            await client.withSessionAsync(endpointUrl, async (session) => {})
...
```
3. run the client and observe that it takes 5 seconds to disconnect and logs a warning message.

**Expected behavior**

On disconnection, the client should wait for 1 second, as intended by the code, and handle absence of disconnection request response silently.

**Context**

- (x) my request is related to node-opcua acting as an OPCUA CLIENT
- ( ) my request is related to node-opcua acting as an OPCUA SERVER

- ( ) I have installed node-opcua from source ( using git clone)
- (x) I have installed node-opcua as a package ( using npm install )
- ( ) I am using an application that uses node-opcua

    - ( ) node-red
    - ( ) other : please specify

- Device: ______
- OS version: ______

    - ( ) Windows : version : ______
    - (x) Linux : version : (various: Debian Bookworm, Ubuntu Noble & similar)
    - ( ) MacOs : version : ______
    - ( ) Raspbian: version : ______
    - ( ) Other : specify : ______

- Description of the other OPCUA system I am trying to connect to:

    - Name: open62541 test
    - Version: just about any version; its behaviour in this respect can be traced
    - Manufacturer/Software vendor: ______
    - link to the manufacturer or product site: [open62541](https://github.com/open62541/open62541)

- **node-opcua version:** :

2.126.0

- **Node:**

  `node --version` = v18.17.1, v18.19.1

**Comment by erossignon** [comment]
```typescript
import { OPCUAClient } from "node-opcua-client";
const t = () => (new Date()).toISOString();
(async () => {
	const client = OPCUAClient.create({ endpointMustExist: false });
	console.log(t(), "connecting");
	await client.withSessionAsync("opc.tcp://localhost:4840", async (session) => {
		console.log(t(), "connected");
	});
	console.log(t(), "disconnected");
})();
```
