### ISSUE TITLE
Documentation is not working

### ISSUE THREAD

**Issue by Rednas83** [node-opcua/node-opcua#1380]
**Describe the bug**
After folllowing [creating_a_client_typescript](https://github.com/node-opcua/node-opcua/blob/v2.1.3/documentation/creating_a_client_typescript.md) I am getting an error
![image](https://github.com/user-attachments/assets/717019f0-d5d5-4590-977e-425c8d68cb12)

Tried
* Importing from `node-opcua-client` instead
![image](https://github.com/user-attachments/assets/c6c4d41b-eb64-4347-875a-79d999e4972e)
* Installing `node-opcua`
![image](https://github.com/user-attachments/assets/453f9596-a64d-4c36-8e7a-504a4f56224e)

In both attempts `ReadValueIdLike` is missing which seems to be required for subscriptions.

Also I am getting a deprecrated warning when using `readVariableValue`
![image](https://github.com/user-attachments/assets/ecaaf3ba-7092-4daf-af79-56a8539e5176)

After removing 'ReadValueIdLike' I get the result as expected
![image](https://github.com/user-attachments/assets/c2e62e3c-67f8-491a-84e4-3bc57eb05822)

How can you browse the objects inside a folder structure?

Something like
![image](https://github.com/user-attachments/assets/eb69ed0e-4d5d-46ba-b2d2-8e0c01f03be2)

Can you provide a working example for subscriptions? ...ReadValueIdLike seems to be missing
![image](https://github.com/user-attachments/assets/e1ca8842-5f92-4615-8544-828976c4cb2c)

Can you update the manual with the correct setup procedure?

**Expected behavior**
Working documentation

**Context**

- (x) my request is related to node-opcua acting as an OPCUA CLIENT
- ( ) my request is related to node-opcua acting as an OPCUA SERVER

- ( ) I have installed node-opcua from source ( using git clone)
- (x) I have installed node-opcua as a package ( using npm install )
- (x) I am using an application that uses node-opcua

    - ( ) node-red
    - ( ) other : please specify

- Device: ______
- OS version: ______

    - (x) Windows : version : ______
    - ( ) Linux : version : ______
    - ( ) MacOs : version : ______
    - ( ) Raspbian: version : ______
    - ( ) Other : specify : ______

- Description of the other OPCUA system I am trying to connect to:
EcoStruxure OPC UA Server Expert v2.1
![image](https://github.com/user-attachments/assets/98fdce3c-db6d-408a-baa8-f4f8b8c8e4ad)

- **node-opcua version:** :
```
  "dependencies": {
    "node-opcua-client": "^2.129.0"
  }
```
- **Node:**
![image](https://github.com/user-attachments/assets/ed6d215c-5cc3-4ab6-afcd-b1ccc7e0c5fc)

**Comment by Rednas83** [comment]
Any updates on this?

Also I was missing in the documentation how to read the discovered variables.

Something like
`const items = await session.ReadVariables() // returning [id, name, users, etc]`

How can this be achieved?

**Comment by erossignon** [comment]
You  can find tutorial and more in-depth examples in my book at https://leanpub.com/node-opcuabyexample-edition2024

**Comment by Rednas83** [comment]
Why did you close? The documentation is still outdated

Figured it out myself how to get the endpoints
`const endpoints = await OPCUAClient.getEndpoints()`

**Comment by Rednas83** [comment]
Just tried it but it only returns the server and not its content.
![image](https://github.com/user-attachments/assets/19e6e16d-2c89-4660-9c84-3a9154d439fc)
How to return the discoverable variables of the server?

Something like
![image](https://github.com/user-attachments/assets/4b794c2a-78eb-45f8-b72b-dcedac87c197)

Is it supported? I am not able to find it in the docs or in the examples at https://github.com/node-opcua/node-opcua/tree/v2.1.3/documentation
