### ISSUE TITLE
How to browse the discoverable tags from an endpoint

### ISSUE THREAD

**Issue by Rednas83** [node-opcua/node-opcua#1384]
**Current behavior**
`const browseResult = await session.browse("RootFolder") // Returns [Objects, Types, views]`
`const endpoints = await client.getEndpoints() // Returns opc ua server`

**Expected behavior**
Something like
`const tags= await session.getVariables() // Returns variables/objects`

How can this be achieved? I am not able to find this in the manual and in the examples

**Info**
```
------------------------------
- Operating System: Windows_NT
- Node Version:     v20.12.2
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.6.0
- Builder:          -
- User Config:      telemetry, modules, experimental, icon, build, routeRules, components, content, formkit, imports, css, devtools, compatibilityDate
- Runtime Modules:  @vueuse/nuxt@10.11.0, @nuxt/devtools@1.3.9, normalizedModule(), @nuxt/content@2.13.2, @formkit/nuxt@1.6.5, @nuxt/image@1.7.0, @nuxt/ui@2.18.3
- Build Modules:    -
------------------------------
```

**Comment by AndreasHeine** [comment]
Example how to Browse:

https://github.com/AndreasHeine/opcua-machinery-client/blob/728cc23c0ecf1ee5de17e45a2bed9d50762e8acc/src/ua-device.ts#L826

Browsing is following References! 

```ts
    private async findMachinesOnServer() {
        console.log(`OPC UA Client: findMachinesOnServer...`)
        const machineryIndex = this.getNamespaceIndex("http://opcfoundation.org/UA/Machinery/")
        if (machineryIndex === undefined) return
        const machinesFolderNodeId = `ns=${machineryIndex};i=1001` // id is defined in spec. and can be hardcoded!
        const browseResult = await this.session!.browse({
            nodeId: machinesFolderNodeId,
            browseDirection: BrowseDirection.Forward,
            referenceTypeId: ReferenceTypeIds.Organizes
        } as BrowseDescriptionLike)
        if (isStatusCodeGoodish(browseResult.statusCode)) {
            browseResult.references!.forEach((result) => {
                this.foundMachines.add(makeNodeIdStringFromExpandedNodeId(result.nodeId))
            })
            console.log(`OPC UA Client: found '${this.foundMachines.size}' machine instances!`)
        }
    }
```

so in the example above i have a nodeid where i want to start (may be "Root" or "Objects" or another common node which every OPC UA Server has). browseResult ("BrowseDescriptionLike") contains the found references ("Nodes" / Expanded-NodeId's) for the specified browseDirection ("Forward") and referenceTypeId ("Organizes") in this case it returns all Nodes which got "Organized" by the "machinesFolderNodeId"

References:
https://reference.opcfoundation.org/Core/Part4/v104/docs/5.8.2
https://reference.opcfoundation.org/Core/Part3/v104/docs/4.3.1#_Ref114466674

**Comment by Rednas83** [comment]
Thanks for sharing this project. It looks very intersting.

I would like to browse all variables inside "Objects/.ePAC:Project"
![image](https://github.com/user-attachments/assets/4e54609d-7804-4af0-894d-0c27ab5d8cd0)

Based on your project I Tried
```
    console.log(`OPC UA Client: findMachinesOnServer...`)
    const machinesFolderNodeId = `ns=2;s=Objects` // id is defined in spec. and can be hardcoded!
    const browseResult = await session!.browse({
      nodeId: machinesFolderNodeId,
      browseDirection: BrowseDirection.Forward,
      referenceTypeId: ReferenceTypeIds.Organizes,
    } as BrowseDescriptionLike)
    console.log(browseResult)
```
But it returns
![image](https://github.com/user-attachments/assets/696fbf59-f3f1-43ed-8f1c-8d517bdc02cd)

Any idea how to do this? The namespace is `2` and the folder I am trying to read is `Object/ePAC:Project`

**Comment by AndreasHeine** [comment]
`ns=2;s=Objects` is not a valid NodeId of your Server!

**Comment by AndreasHeine** [comment]
![grafik](https://github.com/user-attachments/assets/868c9a99-6332-4689-ad00-20e69ead87a7)

**Comment by Rednas83** [comment]
Can you help me setting up the `NodeId`?
Hereby the node attributes of the folder that I am trying to 'browse'
![image](https://github.com/user-attachments/assets/6d917f66-bcc6-4e57-854e-cac4b3ccdcbd)

Tried
```
ns=2;i=0 // Returns 'The node id refers to a node that does not exist in the server address space.'
2:ePAC:Project // Returns 'String cannot be coerced to a nodeId : 2:ePAC:Project'
2:Objects // Returns 'String cannot be coerced to a nodeId : 2:Objects'
ns=2;i=85 // Returns ''The node id refers to a node that does not exist in the server address space.''
```

Hereby the node attributes of the folder I am trying to 'browse'
![image](https://github.com/user-attachments/assets/8e279b80-5f13-41ff-bd8f-0a2e3c67614d)
![image](https://github.com/user-attachments/assets/648f2dab-1486-48be-a78f-5002c3ef247b)

**Comment by AndreasHeine** [comment]
just as an explanation:

"ns=2;i=0" translated to OPC UA means NamespaceIndex: 2 IdentifierType: Numeric ("i") and Identifier: 0
"2:ePAC:Project" is actually a BrowseName and not an NodeId...
"2:Objects" same... but Objects is always in NamespaceIndex: 0
"ns=2;i=85" translated to OPC UA means NamespaceIndex: 2 IdentifierType: Numeric ("i") and Identifier: 85 (85 is the Identifier of Objects but not in Namespace 2!)

**Comment by Rednas83** [comment]
I missed the ":" in the end.

I now get a good result.
![image](https://github.com/user-attachments/assets/6b78f77f-c60d-4ec5-9758-201f3eba8573)

Now I probably need to map the `reference `to `reference.browseName.toString()?`

**Comment by AndreasHeine** [comment]
now you know the NodeId's of all childnodes with that ReferenceTypeId!

its like you opend a folder in your filesystem... now you can Browse deeper or read some Attributes of the found Nodes... whatever your application should do ^^

**Comment by Rednas83** [comment]
I managed to get the names by mapping the `reference` to `reference.nodeId.value`

It returns something like
![image](https://github.com/user-attachments/assets/e402905a-675b-44ed-af62-59bd7d9308ed)

Any idea what the prefix of '0:' means?

**Comment by AndreasHeine** [comment]
thats beyond volentary/free support! you need to understand some of the core concepts of the OPC UA AddressSpace first... your questions are very basic... and i guess you need a crashcourse in OPC UA 😅

**Comment by Rednas83** [comment]
Thank you for support on browsing the variables inside Objects. I indeed would consider this as basic functionality. Perhaps it can also be added it in the documentation/example?

**Comment by AndreasHeine** [comment]
there is no need of extra documentation... it works like the OPC UA spec. describes it!

here you can start:
https://reference.opcfoundation.org/Core/Part1/v105/docs/6.3
https://reference.opcfoundation.org/Core/Part1/v105/docs/5.4.2
https://reference.opcfoundation.org/Core/Part1/v105/docs/7
https://reference.opcfoundation.org/Core/Part3/v105/docs/4.4
https://reference.opcfoundation.org/Core/Part4/v104/docs/5.8.2

**Comment by Rednas83** [comment]
A specification is usefull for writing a library. But not very practical
for creating an application that needs to use this library.

Please consider adding an example. I think it will be appreciated.

Op wo 7 aug 2024 10:04 schreef Andreas Heine ***@***.***>:

**Comment by AndreasHeine** [comment]
already availble... https://github.com/node-opcua/node-opcua/blob/master/documentation/creating_a_client_typescript.md#browsing-the-root-folder

but even with plenty examples... you need to know the basics to start building your OPC UA Application... i know where your at, i was there too 😉 skipping the basics creates a lot frustration while try and error!

**Comment by Rednas83** [comment]
There is an example for browsing the root folder
![image](https://github.com/user-attachments/assets/60ea84a9-5688-4f15-aaf0-db27c569725d)
But for others folders you would need to find out the NodeId first.

Something like:
`const TAG_PREFIX = "ns=2;s=0:" // BME NUA 0100 - Requires namespace (ns=2) and objects folder (s=0)`

Why is not possible to browse other folders by string just like "RootFolder"?

I don't mind if it's added or not but I think it could be helpfull for others in the community.

**Comment by AndreasHeine** [comment]
> Why is not possible to browse other folders by string just like "RootFolder"?

not part of the OPC UA Spec.!

there is a BrowsPath-Translation-Service (which you have to know exists):
https://github.com/node-opcua/node-opcua/blob/master/documentation/creating_a_client_typescript.md#finding-the-nodeid-of-a-node-by-browse-name

but for that you need to know what:
Namespaces, NodeIds and Browsnames / BrowsePaths are (and BrowsePaths have a bitter flavour... because they require you to apply the correct NamespaceIndex to the BrowseNames!)

there is no shortcut (longterm)...

Sample-Server with Sample-Client (build for www.umati.org):
https://github.com/AndreasHeine/opcua-machinery-client
https://github.com/AndreasHeine/SampleServer-node-opcua

**Comment by Rednas83** [comment]
That's not looking very performant🤔

I prefer to hardcode the `nodeid`.

Thanks for your support
