### ISSUE TITLE
Performance on AM3358 / BBB / Raspberry Pi

### ISSUE THREAD

**Issue by tesfel** [node-opcua/node-opcua#14]
I'm running a simple OPC UA server on my BeagleBoneBlack and get the data via a OPC UA client (on another computer) from the server. Both, client und server are written with the node-opcua tool. I read every second some variables with the client and the CPU load of the BBB (the server) is about 100%!
Obviously needs the software much more hardware performance to run the node-opcua module on a Raspberry Pi or BBB.
Any experience with BBB and this module or any idea to reduce the cpu load?

**Comment by brycheiniog** [comment]
I am interested in this as well. I have quite a simple OPC-UA server running on the BBB and it frequently hits >30% CPU. We have not investigated yet, but I have run the benchmarks on both a BBB and an Intel Edison. Which of the bench marks are most critical to performance of the OPC-UA stack?:

BBB Results:

   hostname     : beaglebone
    node version : v0.10.25
      V8 version : 3.14.5.8
 platform & arch : linux arm

 config : { target_defaults:
   { cflags: [],
     default_configuration: 'Release',
     defines: [],
     include_dirs: [],
     libraries:
      [ '-lz',
        '-lcares',
        '-lv8',
        '-lssl',
        '-lcrypto' ] },
  variables:
   { arm_fpu: 'vfpv3',
     arm_neon: 0,
     armv7: 1,
     clang: 0,
     gcc_version: 46,
     host_arch: 'arm',
     node_install_npm: false,
     node_prefix: '/usr',
     node_shared_cares: true,
     node_shared_http_parser: false,
     node_shared_libuv: false,
     node_shared_openssl: true,
     node_shared_v8: true,
     node_shared_zlib: true,
     node_tag: '',
     node_unsafe_optimizations: 0,
     node_use_dtrace: false,
     node_use_etw: false,
     node_use_openssl: true,
     node_use_perfctr: false,
     node_use_systemtap: false,
     python: '/usr/bin/python',
     target_arch: 'arm',
     v8_enable_gdbjit: 0,
     v8_no_strict_aliasing: 1,
     v8_use_arm_eabi_hardfloat: true,
     v8_use_snapshot: false } }

Richards            : 1310
DeltaBlue           : 1044
Crypto              : 1551
RayTrace            : 741
EarleyBoyer         : 1697
RegExp              : 200
Splay               : 459
SplayLatency        : 1254
NavierStokes        : 767
PdfJS               : 737
Mandreel            : 546
MandreelLatency     : 730
Gameboy             : 1016
CodeLoad            : 1204
Box2D               : 331
zlib                : 1418
Typescript          : 1053
----
Score (version 9): 830
 duration  325.90286258095875  seconds

I also ran it on the Intel Edison:

    hostname     : ubilinux
    node version : v0.10.36
      V8 version : 3.14.5.9
 platform & arch : linux ia32

 config : { target_defaults:
   { cflags: [],
     default_configuration: 'Release',
     defines: [],
     include_dirs: [],
     libraries: [] },
  variables:
   { clang: 0,
     gcc_version: 47,
     host_arch: 'ia32',
     node_install_npm: true,
     node_prefix: '/usr',
     node_shared_cares: false,
     node_shared_http_parser: false,
     node_shared_libuv: false,
     node_shared_openssl: false,
     node_shared_v8: false,
     node_shared_zlib: false,
     node_tag: '',
     node_unsafe_optimizations: 0,
     node_use_dtrace: false,
     node_use_etw: false,
     node_use_openssl: true,
     node_use_perfctr: false,
     node_use_systemtap: false,
     openssl_no_asm: 0,
     python: '/usr/bin/python',
     target_arch: 'ia32',
     v8_enable_gdbjit: 0,
     v8_no_strict_aliasing: 1,
     v8_use_snapshot: false,
     want_separate_host_toolset: 0 } }

Richards            : 1130
DeltaBlue           : 1490
Crypto              : 1484
RayTrace            : 1031
EarleyBoyer         : 2739
RegExp              : 272
Splay               : 577
SplayLatency        : 1474
NavierStokes        : 1850
PdfJS               : 870
Mandreel            : 130
MandreelLatency     : 554
Gameboy             : 1240
CodeLoad            : 1269
Box2D               : 517
zlib                : 1255
Typescript          : 1588
----
Score (version 9): 933
 duration  332  seconds

**Comment by erossignon** [comment]
the overall score version is a good indication of the performance of your box:
| Name | Score |
| beaglebone |  830 |
| Intel Edison |  933 |
| RaspberryPi old| tbd |

**Comment by brycheiniog** [comment]
Here are the results from a RaspberryPi 2 (Not overclocked):

[root@alarmpi benchmark-octane]# node run.js
    hostname     : alarmpi
    node version : v0.12.2
      V8 version : 3.28.73
 platform & arch : linux arm

 config : { target_defaults:
   { cflags: [],
     default_configuration: 'Release',
     defines: [],
     include_dirs: [],
     libraries: [ '-lz', '-lssl', '-lcrypto' ] },
  variables:
   { arm_float_abi: 'hard',
     arm_fpu: 'vfpv3',
     arm_neon: 0,
     arm_thumb: 0,
     arm_version: '7',
     clang: 0,
     gcc_version: 49,
     host_arch: 'arm',
     icu_small: false,
     node_install_npm: true,
     node_prefix: '/usr',
     node_shared_cares: false,
     node_shared_http_parser: false,
     node_shared_libuv: false,
     node_shared_openssl: true,
     node_shared_v8: false,
     node_shared_zlib: true,
     node_tag: '',
     node_use_dtrace: false,
     node_use_etw: false,
     node_use_mdb: false,
     node_use_openssl: true,
     node_use_perfctr: false,
     openssl_no_asm: 0,
     python2: '/usr/bin/python2',
     target_arch: 'arm',
     uv_library: 'static_library',
     uv_parent_path: '/deps/uv/',
     uv_use_dtrace: false,
     v8_enable_gdbjit: 0,
     v8_enable_i18n_support: 0,
     v8_no_strict_aliasing: 1,
     v8_optimized_debug: 0,
     v8_random_seed: 0,
     v8_use_snapshot: false,
     want_separate_host_toolset: 0 } }

Richards            : 1864
DeltaBlue           : 2596
Crypto              : 1854
RayTrace            : 2804
EarleyBoyer         : 2784
RegExp              : 308
Splay               : 600
SplayLatency        : 3684
NavierStokes        : 1901
PdfJS               : 1154
Mandreel            : 1151
MandreelLatency     : 790
Gameboy             : 2922
CodeLoad            : 1439
Box2D               : 1309
zlib                : 2789
Typescript          : 2423
----
Score (version 9): 1617
 duration  170.29  seconds
