### ISSUE TITLE
Easy guide to install and test node-opcua

### ISSUE THREAD

**Issue by dudanisu** [node-opcua/node-opcua#148]
Is there a easy guide that shows step by step how to install and test node-opcua. Has someone written this guide that I can use, I am new to programming and very new with node.js programming.
Thanks

**Comment by coussej** [comment]
Hi @dudanisu, I had the same problem a few months ago. However, best thing you can do is just try, fail, try, fail... until you have something working. This way, you not only get something working, but you learn an awful lot :-) a good start would be to follow the [tutorials](http://node-opcua.github.io/). Also have a look in the code for the OPCUA-Commander that Etienne has written, it's a small but complete application from which you can learn a lot.
