### ISSUE TITLE
Connection with userName/password and encryption

### ISSUE THREAD

**Issue by Nestoteles** [node-opcua/node-opcua#158]
Hey,

i was wondering, if it is possible to establish a connection, which uses userName/password as well as encryption?
I tried this with the simple_client and simple_server. When the client tries to create the session a BadIdentityTokenInvalidError occurs.
```
var userIdentity = {
            userName: argv.userName,
            password: argv.password
        };
client.createSession(userIdentity, function (err, session) {
            if (!err) {
                the_session = session;
                console.log(" session created".yellow);
                console.log(" sessionId : ", session.sessionId.toString());
            }
            callback(err);
        });
```
With securityMode = NONE, it's working fine.

**Comment by kingsreturn** [comment]
great,that solves my user authentification problem,thanks a lot
