### ISSUE TITLE
BadIdentityTokenInvalid when testing username / password support

### ISSUE THREAD

**Issue by kaithinkiq** [node-opcua/node-opcua#159]
Hi, thank you for all your work. Currently, I'm trying to test out username and password support by creating my own opc client and server, and I'm seeing the following error when calling 'createSession' on the client.

_Error:  ServiceResult is BadIdentityTokenInvalid (0x80200000)_

The opc server is set up with users like so:

```
var opcua_server_options = {
...
userManager: {
        isValidUser: function (userName, password) {
            if (userName === "user1" && password === "password1") {
                return true;
            }
            if (userName === "user2" && password === "password2") {
                return true;
            }
            return false;
        }
    }
};
```

On the client side, I'm creating a session like this:
```
function(callback) {
	opcuaClient.createSession({ userName: "user2", password: "password2" }, function(err, session) {
		if (!err) {
			console.log("session created!");
		}
		callback(err);
	});			
}
```

My code is highly based off of the simple_client and simple_server. Do you have any hints on what to try? Thanks.

**Comment by erossignon** [comment]
there is a fix not  yet release, see #158
