### ISSUE TITLE
OPC-client ERROR DETECTED IN event handler [ReferenceError: value is not defined]

### ISSUE THREAD

**Issue by bnouhanna** [node-opcua/node-opcua#167]
I am trying to connect my server on pi with the client on an other pi but I receive this error:
![image](https://cloud.githubusercontent.com/assets/15689673/13394708/7a511622-deea-11e5-8376-add88bcee567.png)
Server side 
![image](https://cloud.githubusercontent.com/assets/15689673/13394725/91b129ce-deea-11e5-98c2-08247e654b70.png)

I used the simple client code form github

Thanks for ur help

**Comment by erossignon** [comment]
Can you summit the clientNew.js code ( the error is raised here : line 57 )
