### ISSUE TITLE
Getting a reference description

### ISSUE THREAD

**Issue by gilesbradshaw** [node-opcua/node-opcua#172]
I can browse forward or backward from a node to get the reference descriptions of its parent and children.  Is there any way I can get the reference description of the node itself?

**Comment by erossignon** [comment]
a reference description is like a link/edge between two nodes. There is no such thing as reference description of a node itself. 
This being said, each link has a ReferenceType ( like Organizes, HasComponents etc ...). 
ReferenceTypes are nodes and you can read their attributes (browseName,isAbstract,InverseName etc...) using the session#read method.

**Comment by gilesbradshaw** [comment]
Many thanks
