### ISSUE TITLE
how to get the uri for a server index

### ISSUE THREAD

**Issue by gilesbradshaw** [node-opcua/node-opcua#175]
where a reference's node id has a server index how can I find the server corresponding to that index?

**Comment by erossignon** [comment]
[ReferenceDescription](https://github.com/node-opcua/node-opcua/blob/master/schemas/ReferenceDescription_schema.js)

**Comment by erossignon** [comment]
@gilesbradshaw  did this answer the question ?

**Comment by gilesbradshaw** [comment]
yes thanks that's brilliant
