### ISSUE TITLE
Deprecated deps

### ISSUE THREAD

**Issue by coussej** [node-opcua/node-opcua#179]
Hi, first of all, thanks for your work on this project. Looks awesome.

Nothing serious, but when I do an NPM install, I get the following warnings:

```
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
```

Looks like some deps are out of date?

**Comment by erossignon** [comment]
There is nothing we can do about it except raising the issue to the maintainer of the module that are using them : unzip, mocha, yargs, fstream , glob, path-type etc ...
Hopefully, they will be fixed over time. 

```npm ls``` shows module dependencies:

```
...
├─┬ unzip@0.1.11
│ ├─┬ binary@0.3.0
│ ├─┬ fstream@0.1.31
│ │ └── graceful-fs@3.0.8
...
├─┬ mocha@2.4.5
│ ├── commander@2.3.0
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── diff@1.4.0
│ ├── escape-string-regexp@1.0.2
│ ├─┬ glob@3.2.3
│ │ ├── graceful-fs@2.0.3
│ │ └─┬ minimatch@0.2.14
...
├─┬ yargs@4.3.1
│ ├─┬ pkg-conf@1.1.1
│ │ ├─┬ read-pkg@1.1.0
│ │ │ └─┬ path-type@1.1.0
│ │ │   └── graceful-fs@4.1.3

```
( full log gist:5cd4704d52591b53f12f)
