### ISSUE TITLE
graphQL

### ISSUE THREAD

**Issue by gilesbradshaw** [node-opcua/node-opcua#182]
Hi I thought you might like to see [this](https://ua-ql.herokuapp.com/graphql?query=%7BuaNode%28nodeId%3A%22ns%3D2%3Bi%3D10756%22%29%20%7B%0A%20%20...%20showNode%0A%20%20references%28first%3A10%29%20%7B%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20referenceTypeId%20%7B%0A%20%20%20%20%20%20%20%20%20%20uaNode%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20...%20showNode%20%20%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20typeDefinition%20%7B%0A%20%20%20%20%20%20%20%20%20%20uaNode%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20...%20showNode%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20browseName%20%7B%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20uaNode%20%7B%0A%20%20%20%20%20%20%20%20%20%20...%20showNode%0A%20%20%20%20%20%20%20%20%20%20dataType%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20...%20expandedNodeIdResult%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20dataValue%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20stringValue%0A%20%20%20%20%20%20%20%20%20%20%20%20typedValue%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20...%20on%20MethodParameterTypedArrayValue%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20value%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%7D%0A%0Afragment%20loctext%20on%20LocalizedTextResult%20%7B%0A%20%20value%20%7B%0A%20%20%20%20value%20%7B%0A%20%20%20%20%20%20text%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0Afragment%20showNode%20on%20UANode%20%7B%0A%20%20displayName%20%7B%0A%20%20%20%20...%20loctext%0A%20%20%7D%20%20%0A%7D%0A%0Afragment%20expandedNodeId%20on%20ExpandedNodeId%20%7B%0A%20%20%20%20uaNode%20%7B%0A%20%20%20%20%20%20...%20showNode%20%20%20%20%0A%20%20%20%20%7D%0A%7D%0A%0Afragment%20expandedNodeIdResult%20on%20ExpandedNodeIdResult%20%7B%0A%20%20value%20%7B%0A%20%20%20%20value%20%7B%0A%20%20%20%20%20%20...%20expandedNodeId%0A%20%20%20%20%7D%0A%20%20%7D%20%20%0A%7D) it's using your software to serve opcua data model as graphQL.  Not at all complete yet..  & for some reason IE doesn't like it.

repository is here https://github.com/gilesbradshaw/uaQL

**Comment by BLamy** [comment]
I'm actually also very interested in using GraphQL as a facade for OPC.

**Comment by gilesbradshaw** [comment]
I think it's a great fit + even more so when graphQL gets subscriptions

**Comment by gilesbradshaw** [comment]
@BLamy I got a little further forward with GraphQL and node-opcua - this is now using subscriptions for the live data..  https://gilesbradshaw.github.io/apollo-client/#/

**Comment by BLamy** [comment]
@gilesbradshaw Have you tried to mirror OPCUA's SOAP API to graphQL?

https://github.com/OPCFoundation/UA-.NET/blob/master/Stack/Core/Schema/Opc.Ua.Services.wsdl

![image](https://cloud.githubusercontent.com/assets/324928/25198084/563633e6-2514-11e7-931a-f8b6a66bfec3.png)

**Comment by gilesbradshaw** [comment]
Hi - no sorry but I'm sure it would be possible..
