### ISSUE TITLE
Ignoring reversed keyword  nodeClass

### ISSUE THREAD

**Issue by biancode** [node-opcua/node-opcua#190]
with the actual github master I got a red warning in log directly after "Started flows" info

Ignoring reversed keyword                                               nodeClass

**Comment by erossignon** [comment]
thank you for noticing , this need to be sorted out, but this will probably create some breaking changes.

**Comment by locka99** [comment]
I worked around this by setting server config's nodeset_filename to opcua.mini_nodeset_filename. Note that "reversed" should be "reserved"
