### ISSUE TITLE
Recursive browse all server items

### ISSUE THREAD

**Issue by trongtin** [node-opcua/node-opcua#20]
Hi erossignon,

How could I recursive browse all items of a OPC UA server?

I tried __browse__ function with many type of _browseDescription_. However, it returns only one level up/down from the browsed node.

I also try __crawler__ (as you used in /bin/simple_client.js) but I got following error message with KepWareEX Server or your sample server (https://github.com/node-opcua/node-opcua/blob/master/documentation/sample_server.js). It is ok with your server in /bin/simple_server.js!

_Error message:_
`[31mMessageBuilder : ERROR DETECTED IN event handler
[TypeError: Cannot call method 'substring' of undefined]
TypeError: Cannot call method 'substring' of undefined
    at lowerize (D:\WorkSpace\Node.js\testopcua\node_modules\node-opcua\lib\client\node_crawler.js:351:20)
    at D:\WorkSpace\Node.js\testopcua\node_modules\node-opcua\lib\client\node_crawler.js:393:27
    at Array.map (native)
    at _reconstruct_manageable_object (D:\WorkSpace\Node.js\testopcua\node_modules\node-opcua\lib\client\node_crawler.js:387:27)
    at done (D:\WorkSpace\Node.js\testopcua\node_modules\node-opcua\lib\client\node_crawler.js:423:17)
    at Object.self.q.drain (D:\WorkSpace\Node.js\testopcua\node_modules\node-opcua\lib\client\node_crawler.js:296:13)
    at next (D:\WorkSpace\Node.js\testopcua\node_modules\node-opcua\node_modules\async\lib\async.js:804:31)
[...]

**Comment by Jochen1980** [comment]
Hi Etienne, can you give add a short example related to your node crawler usage. I am not able to figure out, what should be given for parameters 'user_data' and 'callback function' in NodeCrawler.crawl(). Thanks in advance.

**Comment by ascatox** [comment]
Hi Etienne, there's the possibility to crawl the server **model** in a continuous way, or in alternative a way **to notify to the clients** that something changed in the model.
Thanks in advance.

**Comment by samminen** [comment]
Hello,
   I am trying to use crawl functionality in my OPC client, but I am getting this error.Any help ?
   It would be helpful to share a sample client implementation for crawling functionality; 


D:\Users\sudheer.ammineni\Documents\DDHub\opcua\opcua_client\sample_client.js:104
                treeify.asLines(obj, true, true, function (line) {
                ^

ReferenceError: treeify is not defined

function (callback)
	{
        var crawler = new crawlerRoot.NodeCrawler(the_session);

        crawler.on("browsed",function(element){
            console.log("->",element.browseName.name,element.nodeId.toString());
        });

        var nodeId = "ObjectsFolder";
        console.log("now crawling object folder ...please wait...");
        crawler.read(nodeId, function (err, obj) {
            if (!err) {
                treeify.asLines(obj, true, true, function (line) {
                    console.log(line);
                });
            }
            callback(err);
        });
	}
