### ISSUE TITLE
Write Service Limits

### ISSUE THREAD

**Issue by kaithinkiq** [node-opcua/node-opcua#206]
Hi Etienne, I have a question about the operational limits of the write service.

I'm creating multiple variant nodes and writing them to an OPCUA server. Is there a limit to the size of the value array for a node? Additionally, is there a limit to how many nodes I can write when invoking the write function of a session?

```
var node = new opcua.Variant({
        dataType : opcua.DataType.String,
        arrayType : opcua.VariantArrayType.Array,
        value : ["value1", "value2", "value3"]  // <-- is there a limit to how big this array can get? 
      });

// Imagine that nodesToWrite is an array [node1, node2, node3, .. , nodeN]
// I'm then writing these nodes by doing..

the_session.write(nodesToWrite, function(err, statusCodes, diagnosticInfos) { ... } )

// Is there a limit to the size of nodesToWrite for a single write?

```

**Comment by erossignon** [comment]
Probably, it will be implementation specific,
Please make sure to split your very large write operation into manageable chunks, this will give you smoother operation and may prevent Request to timeout depending on how the server is dealing with this large request on its side. An array of 1000  elements should be easily manageable.
