### ISSUE TITLE
Certificates won't generate in v0.0.54 in Win10 and  node v6.2.1.

### ISSUE THREAD

**Issue by awcullen** [node-opcua/node-opcua#212]
I needed to make these changes:

### Change 1
Change "install_prerequisite.js" to allow path with spaces
50: var cmd = path.join(cwd, "openssl.exe");
60:     execute(quote(cmd) + " version", function (err, exitCode, output) {

### Change 2
Change "crypto_create_CA.js" to work with win10 command line (no colors with stdout)
305:                 process.stdout.write("        err " + line + "\n");
309:             process.stdout.write("        out " + line + "\n");
`
node v6.2.1
visual studio 2015
node.js tools 1.2 alpha2

merci

**Comment by erossignon** [comment]
Change1 is been currently handled in https://github.com/node-opcua/node-opcua-pki , this module will soon be integrated in node-opcua.

Change2; 
- we investigate first why "colors" module doesn't work  as expected. hypothesis: May be line is a Buffer and not a string... This could be a breaking change introduced in node v6.2.1.
