### ISSUE TITLE
nodecrawler optmizations

### ISSUE THREAD

**Issue by mepdr** [node-opcua/node-opcua#226]
in order to improve the performance of nodecrawler is possible to
- tune nodecrawler to ignore browse paths containing leading underscores ?
- skip disabled devices, the ones that have _System.enabled equal to 0 ?

**Comment by erossignon** [comment]
As far as It doesn't affects others and provide a way not to ignore browse path with leading underscore and System.enabled, why not. May be a custom filter parameter could be added.

You can make a proposal if you wish using a pull request. Please remember to add a full featured unit test to demonstrate the new behavior.
