### ISSUE TITLE
Support Promisify functions

### ISSUE THREAD

**Issue by BLamy** [node-opcua/node-opcua#229]
It would be nice to see the api be a little bit more promise friendly. Even promisifying functions using Bluebird doesn't seem to work. Likely related to use of deferrer: https://github.com/node-opcua/node-opcua/blob/master/lib/client/client_base.js#L566

With async and await coming to javascript promises are even more advantageous than before. 
The Desired API would be

``` javascript
async function connect(client, endpoint, user, subscriptionConfig){
  try {
      await client.connect(endpoint);
      const session = await client.createSession(user);
      const subscription = new opcua.ClientSubscription(session, subscriptionConfig);
      subscription
        .on('started', _ => console.log('started'))
        .on('keepalive', _ => console.log('keepalive'))
        .on('terminated', _ => console.log('termianted'));
  catch (e) {
      console.log('failed to connect');
  }
}
---------------- OR -----------------
async function connect(client, endpoint, user, subscriptionConfig){
  try {
      const subscription = await client.connect(endpoint)
        .then(client => client.createSession(user))
        .then(session => new opcua.ClientSubscription(session, subscriptionConfig))
      subscription
        .on('started', _ => console.log('started'))
        .on('keepalive', _ => console.log('keepalive'))
        .on('terminated', _ => console.log('termianted'));
  catch (e) {
      console.log('failed to connect');
  }
}
```

My only workaround was to create a function which looks like this

``` javascript
const asyncCall = (target, fn, ...args) => (
  new Promise((resolve, reject) => {
    fn.call(target, ...args, (e, ...results) => {
      if (e) reject(e);
      else resolve(...results);
    });
  })
);
```

which gives me something a little like this:

``` javascript
async function connect(client, endpoint, user, subscriptionConfig){
  try {
      await asyncCall(client, client.connect, endpoint);
      const session = await asyncCall(client, client.createSession, user);
      const subscription = new opcua.ClientSubscription(session, subscriptionConfig);
      subscription
        .on('started', _ => console.log('started'))
        .on('keepalive', _ => console.log('keepalive'))
        .on('terminated', _ => console.log('termianted'));
  catch (e) {
      console.log('failed to connect');
  }
}
```
# edit

There are also a few instances where `asyncCall` wont even work. For instance, `client.closeSession` returns an error if it successfully closes the socket. 

![image](https://cloud.githubusercontent.com/assets/324928/16697910/d56a2b3a-4519-11e6-8285-e63197f421b2.png)

This forces a disconnect function which looks a little like this

``` javascript
const disconnect = (url, client, session) => {
  return async dispatch => {
    try {
      await asyncCall(client, client.closeSession, session);
    } catch (e) {
      if (e.message.startsWith('_socket has been disconnected')) {
        dispatch(({ type: DISCONNECT, url, client, session }));
      } else {
        dispatch(logError(e));
      }
    }
  }
};
```

**Comment by erossignon** [comment]
You're right, making the API more Promise friendly would be nice.
However, it seems strange that close session always returns a error, this would have benn spotted by one of the unit test I guess. May be there is a issue elsewhere.

**Comment by BLamy** [comment]
I've also begun using RXJS to wrap all monitor calls which seems to be a good fit. If ever considering promises it may also be worth looking at [observables](https://github.com/tc39/proposal-observable). 


A simplistic implementation would look a little something like this
```js
import {
  BehaviorSubject,
  Observable
} from 'rxjs/Rx';

function subscribe(subscription, config) {
  const observable = new BehaviorSubject();
  subscription.monitor(config).on('changed', observable.next.bind(observable));
  return observable;
}

...

const subscription = new opcua.ClientSubscription(session, someConfig);
const node1$ = subscribe(subscription, configForNode1);
const node2$ = subscribe(subscription, configForNode2);
const node1Value$ = node1$.map(node1 => node1.value.value)
const node2Value$ = node2$.map(node2 => node2.value.value)
const total$ = Observable.combineLatest(node1Value$, node2Value$, (node1Value, node2Value) => (
  node1Value + node2Value
);

...

total$.subscribe(
  total => {
    console.log(total);
  }
);
```

**Comment by erossignon** [comment]
see @coussej technic to promisify the node-opcua API using bluebird, as described in #291

**Comment by crussell52** [comment]
Relatively new to the Node world -- exploring this library in comparison with UA implementations in other languages and the native async/await pattern would greatly simplify implementations and make them much more readable/maintainable.

I have been successful with early attempts at promisifying with `bluebird`, but that has the unfortunate side effect of preventing IDE code completion.

Has there been any progress towards officially supporting promises?

**Comment by erossignon** [comment]
node-opcua@0.2.0 onward now  supports promises and async/await pattern 
http://node-opcua.github.io/tutorial/2018/01/22/node-opcua-embraces-async-await.html
