### ISSUE TITLE
Testing node-opcua

### ISSUE THREAD

**Issue by Alexi16** [node-opcua/node-opcua#232]
Hello!

I've seen that there are many scripts for testing the node-opcua applications. Great and valuable work! My question is: how can I use these tests to test my application? I've seen that you state to use TravisCI, but I can't find a yml file. Could you please provide a kind of tutorial of how to start and to do testing?

**Comment by BLamy** [comment]
Are you trying to run his test or are you trying to run integration test against mocked OPC server? 

Here's an end to end test where he constructs a server using helper methods in /test/helpers then queries it using an opc client. 
https://github.com/node-opcua/node-opcua/blob/master/test/end_to_end/test_e2e_client_node_crawler_crawl_write_crawl.js#L46-L53
