### ISSUE TITLE
0.0.57 - Error Certificate file must exist - install was OK

### ISSUE THREAD

**Issue by biancode** [node-opcua/node-opcua#241]
AssertionError: fs.existsSync(this.certificateFile), "Certificate file must exist :" + this.certificateFile

![screenshot 2016-08-14 at 09 57 58 am](https://cloud.githubusercontent.com/assets/4369867/17647938/a528b744-6205-11e6-8880-791878e08878.png)

**Comment by biancode** [comment]
Executing  node bin/generate_opcua_classes.js --clear 
done ... (0)
Executing  node bin/crypto_create_CA.js demo
done ... (0)

**Comment by erossignon** [comment]
Are you on Mac ? may be https://github.com/node-opcua/node-opcua/issues/235 could help

**Comment by biancode** [comment]
OK, that was also the openssl problem and brew force link doesn't work

steps done on Mac OS X:
 
- clone from git://git.openssl.org/openssl.git
- cd into path of that git clone of openssl
- ./Configure darwin64-x86_64-cc shared enable-ec_nistp_64_gcc_128 no-ssl2 no-ssl3 no-comp -openssldir=/usr/local/ssl/macos-x86_64
- make depend
- sudo make install
- uninstall node-opcua package
- install node-opcua package

works ...


see https://wiki.openssl.org/index.php/Compilation_and_Installation

**Comment by biancode** [comment]
![screenshot 2016-08-14 at 06 27 20 pm](https://cloud.githubusercontent.com/assets/4369867/17650391/c3b3e2dc-624c-11e6-904f-490d88311db2.png)

**Comment by erossignon** [comment]
:+1:
