### ISSUE TITLE
Dependency on collections modul breaks down Array's find method

### ISSUE THREAD

**Issue by mariocytr** [node-opcua/node-opcua#248]
Working with the node-opcua I encountered a problem with the Array.find method. It is broken. The collections modul which node-opcua depends on makes a polyfill with the wrong implemented find. It gives back an index instead of an array element.

**Comment by erossignon** [comment]
Strange ! Can you investigate and find the offending code ?

**Comment by erossignon** [comment]
A grep in the code shows  that the "collection" npm module is reimplementing the Array#find method
```
node_modules/collections/sorted-array.js:SortedArray.prototype.find = function (value, equals, index) {
node_modules/collections/sorted-array.js:SortedArray.prototype.findLast = function (value, equals, index) {
```

**Comment by BLamy** [comment]
I can confirm this issue. 

![image](https://cloud.githubusercontent.com/assets/324928/19686290/758ead42-9a8e-11e6-9908-8763939277a5.png)
![image](https://cloud.githubusercontent.com/assets/324928/19686300/7f5e4634-9a8e-11e6-9250-46effdc385e0.png)
![image](https://cloud.githubusercontent.com/assets/324928/19686315/8b2fd22a-9a8e-11e6-9e1c-b3b01b860bf1.png)
![image](https://cloud.githubusercontent.com/assets/324928/19686325/94631014-9a8e-11e6-9946-158b7dfb6b80.png)
![image](https://cloud.githubusercontent.com/assets/324928/19686355/b9fc3a1c-9a8e-11e6-99f4-e6aafaabaa05.png)

**Comment by erossignon** [comment]
thank you @BLamy ,
This seems to be a known issue of the ```collections``` package as stated in "http://www.collectionsjs.com/method/find-value" 

> In version 1, this method is called find, which conflicts with the definition of find provided by ECMAScript 6. In version 2, this method is called findValue to eliminate the conflict.

Let's remove the dependency to ```collections``` all together.

**Comment by BLamy** [comment]
Any chance you can push a new minor release. This bug keeps coming back to burn me over and over.

**Comment by erossignon** [comment]
Now on v0.0.59
