### ISSUE TITLE
Kepware KEPServerEX OPC UA hangs

### ISSUE THREAD

**Issue by ghost** [node-opcua/node-opcua#250]
After a successful connection, then a new session and a read(), then close the session and close connection, then next sequence of connect, session then read(), the read will fail, and it seems to be intermittent. There is one second between reads. Leaving the connection or session open with a read() of multiple nodes causes KepServerEX to lock up to where the KepServerEX exe process on the Windows machine has to be terminated, so that a new Node-OPCUA connection will be accepted. 

Kepware technical support has been contacted and they are not sure how to resolve this issue. 

Each read is a different tag or node and there are almost 2000 tags that are being polled from a web browser. The app uses Node JS express HTTP server with socket.io websockets. OPC UA Subscription seems complex since not all 2000 nodes are added at the same time, but rather on demand, as the browser requests them. 

There don't seem to be examples available for this scenario in terms of reading multiple dynamic tags (nodes); dynamic meaning adding or removing them from being read on the fly as a polling request or as a subscription. Most examples are a singe read of a single tag, as an example:
[https://github.com/node-opcua/node-opcua-htmlpanel](https://github.com/node-opcua/node-opcua-htmlpanel)

Can a subscription be changed (nodes added or deleted) on the fly, and would this be a better solution rather than polling a single node or tag?

These tests under Kepware KEPServerEX V5,

This is an awesome library. Thank you for the support.

**Comment by erossignon** [comment]
>> Can a subscription be changed (nodes added or deleted) on the fly, and would this be a better solution rather than polling a single node or tag?
yes, full subscription support is now in node-opcua, you can add and delete monitored.

**Comment by BartWitdouckVDW** [comment]
Hello @ghost

I'm having similar problems with KEPServerEX V5, did you find a solution for this problem?
Thanks
