### ISSUE TITLE
Dynamic Variables

### ISSUE THREAD

**Issue by gremlinc5** [node-opcua/node-opcua#258]
Hi, I have changed your server example code but I get exceptions writing, my code is this:

`var variables = {};
		
		for (var i = 0; i < tags.GetTags.length; i++)
		{
			variables[tags.GetTags[i].Tag] = 0;
			
			addressSpace.addVariable({
				componentOf: device,
				browseName: tags.GetTags[i].Tag,
				dataType: "Double",
				value: {
					get: function () {
						if (this.parent.browseName != undefined)
						{
							//console.log(Object.getOwnPropertyNames(this));
							return new opcua.Variant({dataType: opcua.DataType.Double, value: variables[this.browseName] });
						}
					},
					set: function (variant) {
						if (this.parent.browseName != undefined)
						{
							//console.log(Object.getOwnPropertyNames(this));
							variables[this.browseName] = parseFloat(variant.value);
							return opcua.StatusCodes.Good;
						}
					}
				}
			});
			
			console.log(tags.GetTags[i].Tag);
		}`

I try to use an array of variables to sync my server with opc server, I want to call a global variable in an array (dynamic) from inside the getter and setter but I got property browseName undefined.

**Comment by gremlinc5** [comment]
I found this solution:

`var variables = {};
		
		for (var i = 0; i < tags.GetTags.length; i++)
		{
			variables[tags.GetTags[i].Tag] = {"value" : 0.0, "is_set" : false};
			
			addressSpace.addVariable({
				componentOf: device,
				browseName: tags.GetTags[i].Tag,
				dataType: "Double",
				value: {
					get: function () {
						return new opcua.Variant({dataType: opcua.DataType.Double, value: variables[this["browseName"]] });
					},
					set: function (variant) {
						variables[this["browseName"]].value = parseFloat(variant.value);
						variables[this["browseName"]].is_set = true;
						return opcua.StatusCodes.Good;
					}
				}
			});
			
			console.log(tags.GetTags[i].Tag);
		}`

**Comment by erossignon** [comment]
this is related to understanding how javascript "closures" work.
( see http://stackoverflow.com/questions/111102/how-do-javascript-closures-work )
