### ISSUE TITLE
TranlateBrowsePathToNodeId

### ISSUE THREAD

**Issue by askdrgui** [node-opcua/node-opcua#265]
Hello all,

I need to translate a browsepath (which is constant in my server) to a NodeId (which may be transient in my server). Is the TranslateBrowsepathToNodeId Method supported? Can you provide some simple sample code to get started?

Any help is appreciated!

Thanks,
Daniel

**Comment by erossignon** [comment]
You'll find an example here : https://github.com/node-opcua/node-opcua/blob/68b1b57dec23a45148468fbea89ab71a39f9042f/test/end_to_end/u_test_e2e_translateBrowsePath.js

**Comment by askdrgui** [comment]
Great! This is exactly what I was looking for.

Thanks a lot!
Daniel
