### ISSUE TITLE
Websocket problems

### ISSUE THREAD

**Issue by antmag** [node-opcua/node-opcua#266]
Hello,

Im trying to read opcua variables with socket.io and monitoreditem.on(change) 
I can read the values but I have got an issue! When I'm on the chrome websocket console I can show my datas in real time but each 25 seconds I have got two datas ( 2 and 3). If I don't receive any value between this new datas each 25 secondes i can not anymore read the values ...

**Comment by antmag** [comment]
![img_1374](https://cloud.githubusercontent.com/assets/22215477/19888681/8a973414-a030-11e6-9562-f8b94c153ba5.JPG)
![img_1375](https://cloud.githubusercontent.com/assets/22215477/19888682/8a981186-a030-11e6-8ab3-74d2678e112d.JPG)
![img_1376](https://cloud.githubusercontent.com/assets/22215477/19888684/8a9df07e-a030-11e6-8cd2-72d6a4d77a53.JPG)
![img_1377](https://cloud.githubusercontent.com/assets/22215477/19888683/8a9aac16-a030-11e6-86fa-ce9881ea7613.JPG)

**Comment by antmag** [comment]
I think I need to change the ClientSubscription settings but it doesnt work..
The third picture is the picture of the websocket console when the connection is turn off because no values changes between the first data 2 3 and the second

**Comment by antmag** [comment]
I fixed the problem

**Comment by erossignon** [comment]
@antmag You reopened the issue. Have you fixed the problem ?

**Comment by antmag** [comment]
I found an other way to so but I didnt solved this issue

**Comment by erossignon** [comment]
I would use a smaller maxKeepAliveCount ( such as 60) just to make sure that the client and the server exchange some data every maxKeepAliveCount*publishingInterval milliseconds , this will prevent the connection and session to timeout.
