### ISSUE TITLE
Sending server certificate

### ISSUE THREAD

**Issue by constantinbeleca** [node-opcua/node-opcua#267]
Upon connecting to a node-opcua server pretty much the same as the one presented in the 'simple_server' example, from the windwos client from Integration Objects I get the following error and can't connect: 

"Session creation failed. Exception: Server did not return the certificate used to create the secure channel."

From UaExpert, the client from Unified Automation I can connect to the server but I always get the following message:

"BadCertificateChainIncomplete" with the errors "unable to get local issuer certificate[BadCertificateChainIncomplete]", "unable to get certificate CRL[BadCertificateRevocationUnknown]" and "unable to verify the first certificate[BadCertificateChainIncomplete]". If I select "Accept the server certificate temporarily for this session" I can connect to my node-opcua server but I would pretty much like to not have to do this every time.

I've searched between older posts but couldn't find anything helpful.
Am I missing something?

**Comment by erossignon** [comment]
node-opcua now  use self-signed certificate by default (commit 3a2092235311235ac810d2ca204d094016b38aa2 )

**Comment by erossignon** [comment]
Issuer certificate must be trusted on client side ...
