### ISSUE TITLE
Polling 1000 different tags @ 1 sec interval

### ISSUE THREAD

**Issue by mininggold** [node-opcua/node-opcua#269]
What is the best way to poll 1000 tags from the same OPC UA server with a 1 sec interval, round robin?

**Comment by erossignon** [comment]
Subscriptions and MonitoredItems will allow your client to be notified whenever  a monitored variable is changing, There is no need to poll.

**Comment by mininggold** [comment]
Thank you.  
I think the following approach could help, in terms of adding and remove nodes (tags) dynamically, without having to close the subscription:
[](http://stackoverflow.com/questions/34373347/node-js-opc-ua-many-monitored-items)
