### ISSUE TITLE
Generate OPC AC Events

### ISSUE THREAD

**Issue by carlos2000iconics** [node-opcua/node-opcua#278]
Hello

Do you have an example at generating AC Events from the SDK?

regards

Carl

**Comment by erossignon** [comment]
Yes, we now have A&C. This is still work in progress.
Unit test are a good place to find example.
What sort of A&C are you trying to implement ?

**Comment by carlos2000iconics** [comment]
Hello

I am try to generate events based on conditions of DA points, which need to
be acked knowledge.

Can you point me in the direction of the Unit tests please.

regards

Carl

**Comment by erossignon** [comment]
You will find an example of implementing [an AcknowledgeableConditionType here](https://github.com/node-opcua/node-opcua/blob/master/test/address_space/alarms_and_conditions/utest_acknowledgeable_condition.js)
