### ISSUE TITLE
Writing data with node-opcua

### ISSUE THREAD

**Issue by Diti24** [node-opcua/node-opcua#28]
Hi,
I didn't found any example somewhere on how to use node-opcua to write data to an opc server.
I tried to use both writeSingleNode and write.
I did somethin like:
```
  function(callback) {
         var nodesToWrite = [
             { nodeId: "ns=4;s=S7-1500 station_1.PLC System.CAN_message_DB.CAN_CMD",
               attributeId: 1,
               indexRange: 0,
               value: 0
               }
         ];
       var value = 0;
       the_session.write(nodesToWrite, function(err,statusCode,diagnosticInfo) {
           if (!err) {
               console.log(" write ok" );
               console.log(diagnosticInfo);
               console.log(statusCode);
           }
           callback(err);
       });
    },
```
But I always get BadNotWritable or BadTypeMismatch, while trying different options.
There is a very useful sample code for reading data, is there something similar for writing data around there?
Thanks in advance for your help

**Comment by anson2004** [comment]
Hi, 

  I want to ask is it possible now to write a variable which ArrayDimensions is bigger than 1 (In my case, 256). I try 
var  dataToWrite = {
		   dataType: "Double",
		   value: [1.2,1.2,1.2]
		}
       var value = 0;
       the_session.writeSingleNode ("ns=3;s=MEM_09/2:CalSampleRate",dataToWrite, function(err,statusCode,diagnosticInfo) {
           if (!err) {
               console.log(" write ok" );
              //console.log(diagnosticInfo);
              // console.log(statusCode);
           } else {
            	console.log(" write err = " ,err);
            }
           callback(err);

But it does not work.

Thanks,

Yiqing

**Comment by erossignon** [comment]
Hi yping:
dataType shall be a DataType enum,
you probably need to specify the arrayType 

```
var  dataToWrite = {
   dataType: opcua.DataType.Double,
   arrayType: opcua.VariantArrayType.Array
   value: [1.2,1.2,1.2]
}
```
