### ISSUE TITLE
Timeout until client.connect() enters callback

### ISSUE THREAD

**Issue by tMarvin91** [node-opcua/node-opcua#280]
Hey Guys,

When i enter the  function:
```

client.connect(endpointUrl,function (err) {
            if(err) {
                console.log(" cannot connect to endpoint :" , endpointUrl );
            } else {
                console.log("connected !");
            }
            callback(err);
        });
```

without an active OPC_UA Server, it takes about ~30 seconds until the function enters the callback ( if(err) case). How can i change this delay and enter the callback faster? I couldn't find it in the documentation.

Thank you

**Comment by erossignon** [comment]
By default, a client will try to connect to the server many times before giving up.
You'll find a solution to change this behavior and also to monitor what's going on during the connect/reconnect process in  #271
