### ISSUE TITLE
NodeIdType.BYTESTRING Assert issue in nodeid.js 

### ISSUE THREAD

**Issue by Laro88** [node-opcua/node-opcua#283]
Hello.
I have used the OPCUA in node-red (through the node-red-contrib-opcua module) and things seems ok, except when using the OpcUa-Browser. For some reason my OPC server returns a NodeIdType.BYTESTRING which triggers the Assert in lib/datamodel/nodeid.js line 125.

Is BYTESTRING not allowed in normal OPC as a nodeid? It might be the old OPC server that I am working with that is the root cause of the issue. If it is then how should it be handled?

**Comment by mikakaraila** [comment]
I think my node-red-contrib-opcua is actually not handling it. If I remember correctly it handles i= and s= formats. Have to check that later...

**Comment by Laro88** [comment]
That would be great @mikakaraila if you have the time. I did not find anything suspicious in 103-opcuabrowser.js though, but perhaps you can squeeze a handler in.
