### ISSUE TITLE
ServerTimeStamp and SourceTimestamp both 0

### ISSUE THREAD

**Issue by Laro88** [node-opcua/node-opcua#285]
I have been trying to find out why the timestamps are 0 when using ```readVariableValue(...``` seems like they are still ( #30 & #120 ) set to .Neither in client_session

What should be done to read out the timestamps? I can create a pull req. with an optional parameter if it helps :-)

**Comment by erossignon** [comment]
you can use ```session.read(nodesToRead,callback)``` which gives you a greater control. 
https://github.com/node-opcua/node-opcua/blob/master/lib/client/client_session.js#L522

**Comment by Laro88** [comment]
Perfect :-)
Just for other to learn. ```sourceTimestamp``` and ```serverTimestamp``` can be obtained like this:
```
var _name = "ns=2;s=ECL310_01184.Time_Date.data.Value";

    the_session.read([{ nodeId: _name }], 3*24*60*60*1000, function (err, nodes, data, diags) {
        logger.debug('data:' + util.inspect(data));
    });
```

I suspected that something was wrong since the readVariableValue returns the default values of the timestamps and picoseconds. One can argue that they should not be included / but it might break a lot of code in userland.
