### ISSUE TITLE
Time interval instead of .on('changed')?

### ISSUE THREAD

**Issue by shullw** [node-opcua/node-opcua#286]
I am the best at js and new to node so please forgive me.  I am trying to use this wonderful piece you have created to do the html dashboard.  I would like the graphs to keep ticking even if there was no change, but as it is written, the graphs only change when there is a change in the data.  Some of my inputs stay static for a time.  I would like that to be reflected in the graph.  Is there any other method beside 'changed' to trigger the io.sockets.emit message?  Thank you for your time.

**Comment by BLamy** [comment]
Here is an example using RXJS.

``` js
// use Socket.io to create a socket connection.
const socket = io.connect('http://localhost:3700')

// Put all websocket data into observable
const socket$ = Observable.create(observer => {
  socket.on('message', event => observer.next(event));
});

Observable.interval(1000).withLatestFrom(socket$).subscribe(event => {
// Will call this function every second with the latest event pushed into the socket$ observable.
});
```
