### ISSUE TITLE
Problem with historizing

### ISSUE THREAD

**Issue by zenonpelle** [node-opcua/node-opcua#287]
I can't get "historizing" work. Is there any example how it works?

**Comment by BLamy** [comment]
![image](https://cloud.githubusercontent.com/assets/324928/21493701/dc6583d8-cbda-11e6-962a-71fd8f9b264a.png)

Looking at the readme it seems like historical access isn't implemented yet. However you can record data yourself by subscribing to the data and inputting it into your own database such as MySQL or Influx db.

**Comment by erossignon** [comment]
@zenonpelle  Can you provide more info ?
 Are you willing to implement an historizing server ? or implement a client accessing a historizing server ?

**Comment by zenonpelle** [comment]
I was interested to use the historizing functionality för trends and alarm. Hvae you any idea howe historizing should be implemented server side. I could be interested to implement a historizing server

**Comment by erossignon** [comment]
Simple InMemory variable Historization is available.
Here is a [example](https://github.com/node-opcua/node-opcua/blob/master/documentation/creating_a_server_with_a_historizing_variable.md)

Let me know if this help.

**Comment by zenonpelle** [comment]
thank you! It helps a lot!
