### ISSUE TITLE
Open connection by using username ,password and encryption

### ISSUE THREAD

**Issue by sprod** [node-opcua/node-opcua#29]
How can i connect to an opc server by using an username, password and encryption? I'm not able to write any value. I just got error messages. Using a testing tool i have to type a username and password to connect and it works fine. Is there anything i have to take care by writing values an setting up the connection?

**Comment by sprod** [comment]
What parameters do i have to submit for "policyID" and "encryptionAlgorythm" ??
 
If I pass the params below, i just got the message "ServiceResult is BadIdentityTokenInvalid"

{ policyId: '',
userName: 'username',
password: 'password',
encryptionAlgorithm: 'basic256' }

**Comment by erossignon** [comment]
Anonymous use + sign&encrypt should be here.
However, There is more work to be done on username/password.
