### ISSUE TITLE
Connect to a KEPServerEX 5.19

### ISSUE THREAD

**Issue by stony17** [node-opcua/node-opcua#296]
Hello, I have a KEPServerEX 5.19.
How do I connect to these servers? Have already tried the example. If I start this c: \ dummy \ node-opcua-sample-master> node simple-client --endpoint opc.tcp :: //127.0.0.1: 49320 then nothing happens.
I can also access the KEPWare Server's tags from a javascript program.

Thanks
stony

**Comment by erossignon** [comment]
Let's close the issue for now, other users have no issue to connect to KepServerEx
