### ISSUE TITLE
How to get timestamp when call readVariableValue 

### ISSUE THREAD

**Issue by majj** [node-opcua/node-opcua#30]
readVariableValue doesn't return serverTimestamp & sourceTimestamp.

    OPCUASession.prototype.readVariableValue = function (nodes, callback) {
    ...

    var request = new read_service.ReadRequest({
        nodesToRead: nodesToRead,
        timestampsToReturn: read_service.TimestampsToReturn.Neither
    });

**Comment by erossignon** [comment]
I propose to change the readVariableValue as described in #120

**Comment by finalburner** [comment]
I resolved the same issue by changing 

> read_service.TimestampsToReturn.Neither
to
> read_service.TimestampsToReturn.Both

in lib/client/client_session.js

**Comment by finalburner** [comment]
After changing the require-dependency mecanism, the timestamp configuration is now in : 

node-opcua-client/src/client_session.js

and change 

read_service.TimestampsToReturn.Neither
to
read_service.TimestampsToReturn.Both

Cheers
