### ISSUE TITLE
Return a variable value for later usage 

### ISSUE THREAD

**Issue by YB260568** [node-opcua/node-opcua#303]
Hello,

I try to get a variable value from an opc ua Server (this example: robot tcp x position) to show it on a web page.

So far I used the readVariableValue method and I am able to show the value in the console as shown in the example for that method. But I need to write that value in a variable to use it in another method.

Sorry, I am a beginner, but would be very thanful, if someone could help me on this topic.

Thank you and best regards.

**Comment by erossignon** [comment]
what'about declaring a variable in the outer scope of your callback and assigned the value returned by readVariable callback to it?
```
let myVariable =null;

function myReadAsyncStep(callback) {
   session.read(/*...*/,callback(err,result) {
       myVariable = result.something;
   });
}
```
