### ISSUE TITLE
Any plans to support typescript ?

### ISSUE THREAD

**Issue by gillerman** [node-opcua/node-opcua#304]
I believe this would be the easiest way to support typescript functionality (at least using microsoft IDEs).

Note sure if this is the best place to post this comment

**Comment by erossignon** [comment]
I have initiated the typescript definition file for node-opcua ( node-opuca.d.ts )
The following gist is a example of a typescript node-opcua client (with very limited functionality)
 https://gist.github.com/erossignon/282de0912e32a66f47a41da36a5a9acb
It should demonstrate that  we can get better intellisense support this way.

**Comment by jugglingcats** [comment]
@erossignon I just created pull request #357 to cover monitoring of items in Typescript client. Hope this is appreciated.

**Comment by jugglingcats** [comment]
Also #359 - 'on' method for OPCUAClientBase

**Comment by bompi88** [comment]
I get the following errors when using `noImplicitAny: true`:

```bash
node_modules/node-opcua/node-opcua.d.ts(168,68): error TS7006: Parameter 'callback' implicitly has an 'any' type.
node_modules/node-opcua/node-opcua.d.ts(252,5): error TS7008: Member 'Good' implicitly has an 'any' type.
node_modules/node-opcua/node-opcua.d.ts(253,5): error TS7008: Member 'BadWaitingForInitialData' implicitly has an 'any' type.
```

**Comment by erossignon** [comment]
Typescript is now supported, improvement and typescript coverage in a on going task.
let's close this issue.
