### ISSUE TITLE
How to subscribe to Alarm & Event?

### ISSUE THREAD

**Issue by yangpu** [node-opcua/node-opcua#31]
Could you share an example for subscribing events from A&E server? Thanks.

**Comment by perok** [comment]
Hi, Any updates or ETA on this? We are currently trying to implement a system with this library.

**Comment by arun4san** [comment]
Hi, We could see Event subscription feature in the table listed on the github page. Does it mean the Event,Alarms & conditions subscription feature is available now with node-opcua 0.0.55 ?

**Comment by erossignon** [comment]
Event,Alarms & conditions are available on 0.0.65 onwards

**Comment by awadekaustubh** [comment]
Is there any sample code or documentation available for Event,Alarms & conditions?
