### ISSUE TITLE
Server "HistoricalDataNode" disables "CurrentWrite" for Client

### ISSUE THREAD

**Issue by tomsoftware** [node-opcua/node-opcua#310]
After adding a HistoricalDataNode Property to a node it is no longer possible to write/change that value with a opc-ua client (e.g. in this case add a variable to the history and change the current).

Server:

    var vesselPressure = addressSpace.addVariable({
        componentOf: ??MYROOT??,
        browseName: "Pressure",
        dataType: "Double",
        value: new Variant({ dataType: opcua.DataType.Double, value: 19.5 })
        });

    addressSpace.installHistoricalDataNode(vesselPressure); /* with out this line it works */

Client

    var nodesToWrite = [
    {
      nodeId: ??MYROOT.Pressure??,
      attributeId: opcua.AttributeIds.Value,
      value: /*new DataValue(*/{
          value: {/* Variant */dataType: opcua.DataType.Double, value: 999 }
      }
    }];

    self.session.write(nodesToWrite, function (err, statusCodes) {
      if (err) {
        console.log(err.message);
        return;
      }
      if (statusCodes[0].value != 0) {
        console.log(statusCodes[0].description);
        return;
      }
    });

Or I'm doing something wrong.

By the way, thank you so much for this project and all your work!

![grafik](https://cloud.githubusercontent.com/assets/3290888/23068922/d147d662-f525-11e6-859d-ada01b77cf47.png)

**Comment by erossignon** [comment]
You can manually restore AccessLevel and UserAccessLevel 

````
vesselPressure.accessLevel = opcua.makeAccessLevel("CurrentRead | CurrentWrite | HistoryRead").
````
