### ISSUE TITLE
Invalid server nonce

### ISSUE THREAD

**Issue by longtranphu2006** [node-opcua/node-opcua#311]
Hi, I am doing my school project work and I make the opc ua server from NxtStudio (NxtStudio.com) (A software to program PLC in standard IEC-61499.) 
Then I test the connection between the opc server and my nodejs opc ua client.
However I got the message Invalid Server Nonce. and it does not create the session for me anymore?. 
If I uncomment that validation then the connection works well. 
My server Nonce's Length is 1 so It is not valid for the validation. (require Length = 32).
I am not sure if there is any configuration that skip that validation?.

Thank you in advance. 
Kindest regards,
Long Tran.

**Comment by erossignon** [comment]
Your server seems to misbehaving and  not being conform to the specification.. I would suggest to update the server instead , rather than adding security hole in the client.
