### ISSUE TITLE
Mandatory Placeholder causes server.initialize to fail - XML Parser Error with Attribute Name ">"

### ISSUE THREAD

**Issue by tomsoftware** [node-opcua/node-opcua#312]
The call of server.initialize(post_initialize); does not raise an error neither calls the callback "post_initialize" if the nodeset_filename: [ path.join(modelFolder, "errortest.xml") ] contains an MandatoryPlaceholder Type? May it is caused by the node name BrowseName="1:&lt;values>"

    "use strict";

    var opcua = require("node-opcua");
    var path = require("path");

    var rootFolder = path.join(__dirname, "../");
    var modelFolder = path.join(rootFolder, "modeling/");

    // Let's create an instance of OPCUAServer
    var server = new opcua.OPCUAServer({
        port: 26543, // the port of the listening socket of the server
        resourcePath: "UA/MyLittleServer", // this path will be added to the endpoint resource name
        nodeset_filename: [
            opcua.standard_nodeset_file,
            path.join(modelFolder, "errortest.xml")
        ]
    });

    function post_initialize() {
        console.log("test"); /// <- never called
    }

    server.initialize(post_initialize);

![grafik](https://cloud.githubusercontent.com/assets/3290888/23126636/06225854-f778-11e6-9035-9d2fee83980b.png)

    <UANodeSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:uax="http://opcfoundation.org/UA/2008/02/Types.xsd" xmlns="http://opcfoundation.org/UA/2011/03/UANodeSet.xsd" xmlns:s1="http://yourorganisation.org/errortest/Types.xsd" xmlns:ua="http://unifiedautomation.com/Configuration/NodeSet.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <NamespaceUris>
        <Uri>http://yourorganisation.org/errortest/</Uri>
    </NamespaceUris>
    <Aliases>
        <Alias Alias="Double">i=11</Alias>
        <Alias Alias="String">i=12</Alias>
        <Alias Alias="HasModellingRule">i=37</Alias>
        <Alias Alias="HasTypeDefinition">i=40</Alias>
        <Alias Alias="HasSubtype">i=45</Alias>
        <Alias Alias="HasComponent">i=47</Alias>
    </Aliases>
    <Extensions>
        <Extension>
            <ua:ModelInfo Tool="UaModeler" Hash="ZyG5amlvZSx3GVwK0Wt9lg==" Version="1.5.0"/>
        </Extension>
    </Extensions>
    <UAObjectType NodeId="ns=1;i=1002" BrowseName="1:child">
        <DisplayName>child</DisplayName>
        <References>
            <Reference ReferenceType="HasSubtype" IsForward="false">i=58</Reference>
            <Reference ReferenceType="HasComponent">ns=1;i=6001</Reference>
            <Reference ReferenceType="HasComponent">ns=1;i=6002</Reference>
        </References>
    </UAObjectType>
    <UAVariable DataType="String" ParentNodeId="ns=1;i=1002" NodeId="ns=1;i=6001" BrowseName="1:name" UserAccessLevel="3" AccessLevel="3">
        <DisplayName>name</DisplayName>
        <References>
            <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
            <Reference ReferenceType="HasModellingRule">i=78</Reference>
            <Reference ReferenceType="HasComponent" IsForward="false">ns=1;i=1002</Reference>
        </References>
    </UAVariable>
    <UAVariable DataType="Double" ParentNodeId="ns=1;i=1002" NodeId="ns=1;i=6002" BrowseName="1:value" UserAccessLevel="3" AccessLevel="3">
        <DisplayName>value</DisplayName>
        <References>
            <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
            <Reference ReferenceType="HasModellingRule">i=78</Reference>
            <Reference ReferenceType="HasComponent" IsForward="false">ns=1;i=1002</Reference>
        </References>
    </UAVariable>
    <UAObjectType NodeId="ns=1;i=1003" BrowseName="1:container">
        <DisplayName>container</DisplayName>
        <References>
            <Reference ReferenceType="HasComponent">ns=1;i=5001</Reference>
            <Reference ReferenceType="HasSubtype" IsForward="false">i=58</Reference>
        </References>
    </UAObjectType>
    <UAObject SymbolicName="values" ParentNodeId="ns=1;i=1003" NodeId="ns=1;i=5001" BrowseName="1:&lt;values>">
        <DisplayName>&lt;values></DisplayName>
        <References>
            <Reference ReferenceType="HasTypeDefinition">ns=1;i=1002</Reference>
            <Reference ReferenceType="HasModellingRule">i=11510</Reference>
            <Reference ReferenceType="HasComponent" IsForward="false">ns=1;i=1003</Reference>
            <Reference ReferenceType="HasComponent">ns=1;i=6003</Reference>
            <Reference ReferenceType="HasComponent">ns=1;i=6004</Reference>
        </References>
    </UAObject>
    <UAVariable DataType="String" ParentNodeId="ns=1;i=5001" NodeId="ns=1;i=6003" BrowseName="1:name" UserAccessLevel="3" AccessLevel="3">
        <DisplayName>name</DisplayName>
        <References>
            <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
            <Reference ReferenceType="HasModellingRule">i=78</Reference>
            <Reference ReferenceType="HasComponent" IsForward="false">ns=1;i=5001</Reference>
        </References>
    </UAVariable>
    <UAVariable DataType="Double" ParentNodeId="ns=1;i=5001" NodeId="ns=1;i=6004" BrowseName="1:value" UserAccessLevel="3" AccessLevel="3">
        <DisplayName>value</DisplayName>
        <References>
            <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
            <Reference ReferenceType="HasModellingRule">i=78</Reference>
            <Reference ReferenceType="HasComponent" IsForward="false">ns=1;i=5001</Reference>
        </References>
    </UAVariable>
  </UANodeSet>

**Comment by erossignon** [comment]
there is a typo in the XML file that cause the xmlparser to get stuck
```<UAObject... BrowseName="1:&lt;values>">```
shall be
```<UAObject ... BrowseName="1:&lt;values&gt;"> ```
Took me a while to find !

**Comment by tomsoftware** [comment]
Thank you for looking at this bug but I'm not sure if this is really a typo... I think it is valid xml (but of cause bad style :-( )... I test this with Firefox, Edge and Chrome. They all can pars this. I create this with the UaModeler so other people may have the same issue - UaModeler is creating this "style" on every "<>" appearance in a node/browse name :-( ?!

- bad style position 1:

      BrowseName="1:&lt;values>"

- bad style position 2:

      <DisplayName>&lt;values></DisplayName>

now I fix this for my by search & replace the 

    >">
with

    &gt;">

sorry for ruin your weekend...

[original xml error_xml.zip](https://github.com/node-opcua/node-opcua/files/853676/error_xml.zip)
