### ISSUE TITLE
Events on address space change

### ISSUE THREAD

**Issue by ascatox** [node-opcua/node-opcua#324]
Hi All,
I'm encountering a big problem with the SDK.
I've an address space changing over the time, new **Objects** could be added to the address space.
There's an api **to notify** these change events to the clients, in order to subscribe/monitor these new Objects?
Thanks in advance.

**Comment by erossignon** [comment]
Yes, the OPCUA specification recommend that changes in the address space on the server side are notified to the clients using a dedicated Event that can be monitored on the "Server" (rootFolder.Objects.Server) node in the addressSpace. (The server on which you are trying to connect shall have this feature in place, not all servers implement this)

**Comment by ascatox** [comment]
Is it possible implement this feature server side with node-opcua SDK?

**Comment by erossignon** [comment]
Absolutely, this is implemented as per specification. 
You can refer to the corresponding [unit test](https://github.com/node-opcua/node-opcua/blob/68b1b57dec23a45148468fbea89ab71a39f9042f/test/address_space/test_address_space_model_change_event.js#L11) to understand how it works.
