### ISSUE TITLE
Can I use the typescript for this library

### ISSUE THREAD

**Issue by longtranphu2006** [node-opcua/node-opcua#325]
Hi,
I am not sure if the typescript definition is ready yet?. Because I would like to use typescript for my project.
I tried to search in @types/nodeopc-ua but no success. If it already supports the typescript, can you tell me how can I do that.

Thank you very much.
Kindest regards,
Long Tran

**Comment by erossignon** [comment]
the type script definition file is pretty much work in progress a001516272f1b1f23254db8dd46a5ba4c43b398d

**Comment by erossignon** [comment]
duplicate #304
