### ISSUE TITLE
Authorization of a specific action of specific resource by specific user.

### ISSUE THREAD

**Issue by enobufs** [node-opcua/node-opcua#326]
Here's a question.

From the OPC UA spec v1.03 - Part 3:
> 4.2.3 Authorization
The access to read, write, or execute resources should be authorized for only those entities that have a need for that access within the requirements of the system. Authorization can be as coarse-grained as allowing or disallowing a Client to access a Server or it could be much finer grained such as allowing specific actions on specific information items by specific users.

Say, a server has two variables; one is allowed to be accessed by User_A and User_B, but the other variable only allowed to be accessed by User_A.

Would this be possible with the current implementation of node-opcua? If so, could you please refer me to API doc or code (hopefully a sample code, if any) where I can find hints to do this?

**Comment by erossignon** [comment]
duplicates #171
