### ISSUE TITLE
EventType_Schema like DataType_Schema

### ISSUE THREAD

**Issue by biancode** [node-opcua/node-opcua#330]
Hi,

it would be great to have an EventType_enum (EventType_Schema) like the DataType_enum (DataType_Schema).

**Comment by erossignon** [comment]
The trouble is that DataType is a  well defined  enumeration with keys and values defined in the specification, but EventType is a nodeId that can refer to a EventType node defined in the standard UA namespace or in any custom namespace ... therefore it is difficult to prebuild.

Please provide an description of what you're trying to achieve ... do you care about this inside a client application or a server application ?

**Comment by biancode** [comment]
Dear Etienne,
it is for the client just to have the basic EventTypes for selection to start with events in OPC UA. For me, it would be great to have an enum of code_gen/NodeIds.csv -> '*EventTyp,' to provide a simple select field. Or is there a way to search for all possible events of a namespace, eventarea or for a root Node-Id and the child nodes to provide it in a select. (key: OPCEventAreaBrowser?)

**Comment by erossignon** [comment]
What about this  ? 
https://gist.github.com/erossignon/df6ffd19ca0ff228395fc95a688310ac

**Comment by erossignon** [comment]
@biancode  how this helped ?

**Comment by biancode** [comment]
I'll work on this weekend - have to find some time ;)

**Comment by biancode** [comment]
Perfect! Works very well! Thank you very much! 

That is my source now:

```
de.biancoroyal.opcua.iiot.core.listener.getAllEventTypes = function (session, callback) {
  let entries = []
  let makeNodeId = this.core.nodeOPCUA.makeNodeId
  let ObjectTypeIds = this.core.nodeOPCUA.ObjectTypeIds

  let browseEventTypes = {
    nodeId: makeNodeId(ObjectTypeIds.BaseEventType),
    referenceTypeId: this.core.nodeOPCUA.resolveNodeId('HasSubtype'),
    browseDirection: this.core.nodeOPCUA.browse_service.BrowseDirection.Forward,
    includeSubtypes: true,
    nodeClassMask: this.core.nodeOPCUA.browse_service.NodeClassMask.ObjectType,
    resultMask: 63 // all from ResultMask_Schema - a const with name ALL would be great
  }

  let nodesToBrowse = [browseEventTypes]

  session.browse(nodesToBrowse, function (err, results, diagnostics) {
    if (err) { callback(err) }
    results[0].references.forEach(function (reference) {
      entries.push({displayName: reference.displayName.text, nodeId: reference.nodeId, reference: reference})
    })

    callback(null, entries, diagnostics)
  })
}
```

**Comment by biancode** [comment]
opcuaIIoT:listener Listener Start OPC UA Session +0ms
  opcuaIIoT:listener AuditEventType : ns=0;i=2052 +213ms
  opcuaIIoT:listener SystemEventType : ns=0;i=2130 +1ms
  opcuaIIoT:listener BaseModelChangeEventType : ns=0;i=2132 +0ms
  opcuaIIoT:listener TransitionEventType : ns=0;i=2311 +0ms
  opcuaIIoT:listener ConditionType : ns=0;i=2782 +0ms
  opcuaIIoT:listener EventQueueOverflowEventType : ns=0;i=3035 +0ms
  opcuaIIoT:listener ProgressEventType : ns=0;i=11436 +0ms
  opcuaIIoT:listener GenerateValuesEventType : ns=2;i=9371 +1ms
