### ISSUE TITLE
Removing a monitored item

### ISSUE THREAD

**Issue by gcperrin** [node-opcua/node-opcua#334]
It looks like the implementation is generally unfinished around removing a monitored item. A patch including a public wrapper (and coorsponding test) around the following function, from _lib/client/client_subscription.js_ would be complete for a passing pull request? Or is there a function hiding elsewhere that provides the functionality.

@erossignon If you confirm I'll take a crack at it.

Best,
G

```javascript
ClientSubscription.prototype._delete_monitored_item = function (monitoredItem, callback) {
    var self = this;
    assert(self.isActive());

    var clientHandle = monitoredItem.monitoringParameters.clientHandle;

    assert(self.monitoredItems[clientHandle], "expecting existing monitoredItem");

    self.session.deleteMonitoredItems({
        subscriptionId: self.subscriptionId,
        monitoredItemIds: [monitoredItem.monitoredItemId]
    }, function (err) {

        // remove monitored items
        self._remove(monitoredItem);
        assert(!self.monitoredItems[clientHandle], "monitored item should have been removed");
        callback(err);
    });
};
```

**Comment by erossignon** [comment]
``` javascript
monitoredItem.terminate(function done() {
});
```
shall terminate and remove a single monitored item

**Comment by gcperrin** [comment]
Thank you for the insight, much obliged. Thought it would be there due to monitors existence should have dug deeper! Can close.

**Comment by erossignon** [comment]
you're welcome!
