### ISSUE TITLE
How to call an OPC-UA method from client

### ISSUE THREAD

**Issue by finalburner** [node-opcua/node-opcua#335]
Is there any example or explanation of how to call an OPC-UA server method from client ? @erossignon

**Comment by erossignon** [comment]
[example1](https://github.com/node-opcua/node-opcua/blob/692ae94f24351909b152ac789e20b03fe2c4eb6a/test/end_to_end/u_test_e2e_issue_223_demonstrate_client_call_service.js)
[example2](https://github.com/node-opcua/node-opcua/blob/fd5e48bac996625aaa7c177d1f8ed0c40ee92fbc/test/end_to_end/u_test_e2e_call_service.js)

**Comment by finalburner** [comment]
Thank you for your help ! @erossignon
