### ISSUE TITLE
Asynchronous value returns on server side

### ISSUE THREAD

**Issue by paragonRobotics** [node-opcua/node-opcua#34]
Your code looks great... thanks for all your hard work in developing this module.
We're looking to potentially use it in an upcoming project of ours, however I have a question/request.  From your example documentation, it looks like the only way to return a requested value on the server side is through a synchronous getter such as:

server.nodeVariable1 = server.engine.addVariableInFolder("MyDevice",{
	browseName: "MyVariable1",
	dataType: "Double",
	value: {
		get: function () {
			return new opcua.Variant({dataType: opcua.DataType.Double, value: variable1 });
		}
	}
});

However, for our needs (due to wireless latencies and other issues), we will need to asynchronously read this value on the server, and return it via a callback of some sort.  Is this functionality planned in the near future, or could you give me some guidance on where to look if you would like us to potentially modify and send a pull request?

Cheers--

**Comment by erossignon** [comment]
I have created #51 for the asynchronous write functionality enhancement, so this issue could be closed
