### ISSUE TITLE
Error: malformed X.509 certificate

### ISSUE THREAD

**Issue by i3fox** [node-opcua/node-opcua#345]
**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

**Current behavior**

The following invocation of `client.createSession()`

```
client.createSession({ username, password }, function (err, session) {})
```

results in a `malformed X.509 certificate PEM (code:005)` error when trying to connect to a server using a recently-created self-signed certificate. Other OPC-UA clients are able to connect without encountering the same issue, such as [UA-Expert](https://www.unified-automation.com/products/development-tools/uaexpert.html).

**Expected behavior**

The `client.createSession()` should result in a new connection/session being created.

**Minimal reproduction of the problem with instructions**

Unfortunately, this is happening on a private environment and we can’t share too many details about it.

**How we fixed it**

We noticed that this module depends on [https://github.com/erossignon/node-jsrsasign](https://github.com/erossignon/node-jsrsasign) v0.0.7, which includes an outdated version of the [https://github.com/kjur/jsrsasign](https://github.com/kjur/jsrsasign) library. We have manually updated [https://github.com/erossignon/node-jsrsasign/blob/master/main.js](https://github.com/erossignon/node-jsrsasign/blob/master/main.js) with the latest version of `jsrsasign` by replacing the old version with the entire content of [https://github.com/kjur/jsrsasign/blob/master/npm/lib/jsrsasign.js](https://github.com/kjur/jsrsasign/blob/master/npm/lib/jsrsasign.js). This has fixed the issue.

Version 0.0.64 of `node-opcua` uses the same version of `node-jsrsasign` - and therefore of `jsrsasign` - as v0.0.61.
  
**What is the motivation / use case for changing the behavior?**

An up-to-date version of `jsrsasign` would probably take care of this and other issues related to previously unsupported certificates.

**Please tell us about your environment:**

* [ ] I have installed node-opcua from source ( using git clone)
* [X] I have installed node-opcua as a package ( using npm install )
* [ ] I am using an application that uses node-opcua 
  * [ ] node-red
  * [ ] other : please specify 
        
* Device: VMWare VM
* OS version:
  * [ ] Windows
  * [X] Linux: Ubuntu 16.04.02 LTS
  * [ ] MacOs
  * [ ] Raspbian
  * [ ] Other

* **node-opcua version:** `bf6cb2c` (0.0.61 on NPM)

* **Node:** `node --version` = 4.8.2

**Comment by erossignon** [comment]
Thank you for providing the solution.
node-opcua-crypto now relies on ```jsrsasign``` instead of ```node-jsrsasign``` now. ```node-jsrsasign``` was a temporary patch while waiting for ```jsrsasign```  to be ready for npm.
