### ISSUE TITLE
Use of user-defined dataTypes (simple types)

### ISSUE THREAD

**Issue by c-falk** [node-opcua/node-opcua#349]
Hi everyone, 
how can user-defined dataTypes can be registered for proper handling inside the node-opcua?

I have following problem:

I use a .XML-node-set file in my node-opcua Server, created by Siemens' TiaPortal and build up my addressSpace with it. This file includes own dataType definitions e.g. "STRING" which is a subtype of the BaseDataType "String". If I bind get and set functions to a node with that dataType and try to set the value with the UaExpert Client, I get an Exeption while processing request because "4:STRING must be registered". 

Now my question is: Is there any way to work around this exception and set the value of a node with such a dataType? 
(I am using node-opcua: 0.0.64)

I attached a .zip-folder with my app.js and the .xml-file and a screenshot of the console with the exception as well.

Thanks for your help!

[exception_demo.zip](https://github.com/node-opcua/node-opcua/files/995393/exception_demo.zip)

![exception](https://cloud.githubusercontent.com/assets/28630387/25988345/e7079b2c-36f7-11e7-9bd3-27fe0daf7714.PNG)

**Comment by teropes** [comment]
This comment might be relevant:
https://github.com/node-opcua/node-opcua/issues/320#issuecomment-382690353
