### ISSUE TITLE
Dependency error 

### ISSUE THREAD

**Issue by finalburner** [node-opcua/node-opcua#352]
Hi everybody, 

I want to package my nodejs App (which's running without errors)  into ".exe" using the npm module "PKG".

I have theses unexplained error messages about not finding the .js component files, even if it's checking the right path.

Please, If you have any suggestion ou idea about the origin of the error, let me know.

![image](https://cloud.githubusercontent.com/assets/6690565/26307822/d676121e-3ef6-11e7-9d48-06abb57efbb2.png)

@erossignon

**Comment by erossignon** [comment]
This will be an issue until we switch out of the ```require("requirish")``` scheme that we use to handle relative paths.  see https://gist.github.com/branneman/8048520

**Comment by finalburner** [comment]
hi @erossignon,
I've looked a while to fix the require problem and package the application event following your instructions.
The PKG module works by including all module encountred in the require calls.

Why doesn't it work as the same for node-opcua

**Comment by finalburner** [comment]
Is there a way to bundle all node-opcua module in one js file in order to avoid relative path problems when packing ? @erossignon 

Thanks

**Comment by erossignon** [comment]
#392confirms that packing node-opcua code into a single script file is now working thanks to the new code layout. closing
