### ISSUE TITLE
Installation Failed in Windows 10

### ISSUE THREAD

**Issue by subu1979** [node-opcua/node-opcua#354]
Not able to install node-opcus in Windows 10

Node JS Version - 6.10.3
npm version - 3.10.10

steps followed
1) npm install node-opcua   -> Success
2) git clone https://github.com/node-opcua/node-opcua.git  --> Success
3) cd node-opcua
4) npm install - Failed 

![node_opcua](https://cloud.githubusercontent.com/assets/3286581/26670138/22451e4a-46ce-11e7-962d-b4861a4f0430.png)

**Comment by erossignon** [comment]
```npm install``` has failed apparently,  you need to investigate this first. Unfortunatly the interesting bit is already passed in your screenshot

**Comment by subu1979** [comment]
Hi,
Thanks for the quick reply. I re-installed and working fine.

Thanks for your support.
