### ISSUE TITLE
Additional information for browse reference result

### ISSUE THREAD

**Issue by Faerylnahr** [node-opcua/node-opcua#360]
I'm not pretty sure if it's a feature request. It's more a question in general and for better understanding.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use
    [gitter](https://gitter.im/node-opcua/node-opcua) or [stackoverflow](https://stackoverflow.com/questions/tagged/node-opcua)
```

**Current behavior**
I browse a node within my OPCua server and get several entries containing an reference item with the fields as mentioned in `node-opcua / schemas / ReferenceDescription_schema.js`

**Expected behavior**
I was wondering why I don't have additional Information about e.g. DataType or Value node. 

**Minimal reproduction of the problem with instructions**

  1. use node-red-contrib-opcua
  2. add a opcua browser item and browse a certain node which has subnodes
  3. debug output of opcua browser item
  
**What is the motivation / use case for changing the behavior?**
Read a set of subnodes instead of perform single read actions for each of the subnode items

**Please tell us about your environment:**

  * [ ] I have installed node-opcua from source ( using git clone)
  * [ ] I have installed node-opcua as a package ( using npm install )
  * [x] I am using an application that uses node-opcua 
        [ ] node-red
        [ ] other : node-red-contrib-opcua
        
  * Device: Laptop
  * OS version: x64
    [x] Windows : version : win7
    [ ] Linux   : version : _________
    [ ] MacOs   : version : _________
    [ ] Raspbian: version : _________
    [ ] Other   : specify :
   
* **node-opcua version:** `0.0.61`

* **Node:** `node --version` = `v6.10.3`

**Comment by erossignon** [comment]
You need to perform a separate read request to retrieve the DataType of a given Variable with ```attributeId: AttributeIds.DataType```
