### ISSUE TITLE
How to browse nodeId and attributeID for the sample client

### ISSUE THREAD

**Issue by longtranphu2006** [node-opcua/node-opcua#37]
Hello. I am new to the opcUA.
I am doing a small change in the sample client which just try to read the "MyVariable1" from the sample server. 
I changed "ns=4,s="free_mem" to "ns=1,s="1001".
The change come from reading data from UAExpert application. I guessed that i should change this.

The result is just "keep alive" or there is no variable found. 

Could you please tell me how can i read the NodeID and Attribute ?.
Thank you very much for considering my problem.

**Comment by Jochen1980** [comment]
Hi Erossignon, 

thanks for your work and your project! I am interested to browse the nodeId as well. How to get this done?

Thanks in advance.
Jochen

**Comment by Jochen1980** [comment]
Hi Etienne, 

I got the task done. To let all people know, here is a code snippet how to use a browse description. Make sure the identifier us uppercase only.

...
var browseDescription = { // TODO use uppercase-function
				nodeId : new opcua.NodeId(datamodelNodeId.NodeIdType.GUID,"360273AA-F2B9-4A7F-A5E3-37B7074E2529",3)
		}
		the_session.browse(browseDescription, function(err, browse_result, diagnostics){
				if(!err) {
