### ISSUE TITLE
empty EndpointUrl in RequestHeader (getEndpointsRequest)

### ISSUE THREAD

**Issue by zombinary** [node-opcua/node-opcua#376]
I want to connect to an server as anonymous. But the server returns an error message.
The Problem is the empty endpoint Url in the GetEndpointsRequest.

Is it possible to added the EndpointUrl to the RequestHeader?

![error_empty_endpointurl](https://user-images.githubusercontent.com/11854198/30796710-945e694a-a1d3-11e7-9a27-6a0e7db937c8.PNG)

**Comment by erossignon** [comment]
Not enough information provided, sorry ....

**Comment by AlexeyMineev** [comment]
It seems that error is in line 661 of **client_base.js**:

**options.endpointUrl = options.endpointUrl || self.endpoint_url;**

I've replaced **self.endpoint_url** by **self.endpointUrl** and it works fine now

**Comment by GhoshJit** [comment]
Read data from server is ok. but unable to write value .
Can you send me the OPC UA Client write value code in .net
