### ISSUE TITLE
CallMethod getMonitoredItems assertion error

### ISSUE THREAD

**Issue by zombinary** [node-opcua/node-opcua#379]
I have an Problem with my client to get the Monitored Items from an server.
In the Call Method the server Response return an 'UInt32Array' with an ArraySize -1.
This hit an assertion in Line1033 in 'client_session.js'

I change the assert to Fix them. Can you apply the change?

```
                assert(result.outputArguments.length === 2);
                var data = {
                    serverHandles: result.outputArguments[0].value, //
                    clientHandles: result.outputArguments[1].value
                };
                //assert(data.serverHandles instanceof Uint32Array);
                //assert(data.clientHandles instanceof Uint32Array);
                assert(result.outputArguments[0].dataType.key === 'UInt32');
                assert(result.outputArguments[1].dataType.key === 'UInt32');
```

![wrongarray_length](https://user-images.githubusercontent.com/11854198/31069110-45c08560-a75b-11e7-9d8c-8211e53cccc7.png)

**Comment by erossignon** [comment]
It would have been nice to fill the template:
  - what version of node-opcua ?
  - what type of server are you connecting to ?

**Comment by erossignon** [comment]
The fix makes sense, when ArraySize is 0xFFFFFFF , null is returns instead of an Uint32Array,
However I would recreate 2 Uint32Array instead to make it simpler

**Comment by zombinary** [comment]
I work with the node-opcua@0.0.65 and the problem occurs with an opc ua server.

**Comment by erossignon** [comment]
I would have guessed that you were trying to connect to an opcua sever ;-) the question was more about which type of server : product name version etc...
