### ISSUE TITLE
EventFilter Error after updating from 0.0.65 version

### ISSUE THREAD

**Issue by awadekaustubh** [node-opcua/node-opcua#384]
Hi,
I have successfully instantiated the alarm. But whenever the alarm is raised I am getting following error.

```
func readValueAsync has failed
 stack TypeError: Cannot read property 'length' of null
    at extractEventField (F:\opcua\node_modules\node-opcua-service-filter\src\tools_event_filter.js:200:32)
    at Array.map (native)
```

How to resolve the issue?
Also, how to get the change event on occurrence of any event? any sample code if provided will be helpful.

**I'm submitting a ...**  (check one with "x")

 - ( x) bug report => search github for a similar issue or PR before submitting
 - ( ) feature request
 - ( ) support request => Please do not submit support request here, instead see use 
       [gitter](https://gitter.im/node-opcua/node-opcua) or [stackoverflow](https://stackoverflow.com/questions/tagged/node-opcua)

**Current behavior**

``` 
var addressSpace = opcserver.engine.addressSpace;
        addressSpace.installAlarmsAndConditionsService();
        var tankLevel = opcserver.engine.addressSpace.findNode("ns=2;s=d1_hr1");
       
        var exclusiveLimitAlarmType = addressSpace.findEventType("ExclusiveLimitAlarmType");
        assert(exclusiveLimitAlarmType != null);
        var tankLevelCondition = addressSpace.instantiateExclusiveLimitAlarm(exclusiveLimitAlarmType,{
           // componentOf:     tank,
            conditionSource: tankLevel,
            browseName:      "TankLevelCondition",
            optionals: [
                "ConfirmedState", "Confirm" // confirm state and confirm Method
            ],
            inputNode:       tankLevel,   // the variable that will be monitored for change
            highHighLimit:   200,
            highLimit:       170,
            lowLimit:        70,
            lowLowLimit:     55
        });

        opcserver.tankLevelCondition = tankLevelCondition;
```

When above piece of code is executed  and alarm conditions are reached, it throws the mentioned error.

**Expected behavior**

I want a function which gets called when any event is called and I want the event details, so that I can call sms/email functionality to alert the users.

**Minimal reproduction of the problem with instructions**

  1. create and start the opc server.
  2. instantiate the alarm using pasted code
  3. Exception is thrown when limits of the values are crossed .
  ...
  
**What is the motivation / use case for changing the behavior?**

I am trying to create alarm functionality which will monitor the modbus device values and trigger the required function like sms/email.

**Please tell us about your environment:**

I have used jsmodbus to create a modbus device and read the values from the holding registers. This functionality is working fine for data monitoring. To test it, I am using Rsim simulator for values simulation.

  * ( ) I have installed node-opcua from source ( using git clone)
  * ( x) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: _____
  * OS version: _____
    
    - (x ) Windows : version : 7
    - ( ) Linux   : version : _________
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   

* **node-opcua version:** ``

0.1.0
* **Node:** 
   `node --version` = 8.0.0

Hope I have supplied enough information, please let me know if further more inputs are required.
Thanks in advance.

**Comment by erossignon** [comment]
Please fill the template and provide more information so the issue could be reproduced.

**Comment by awadekaustubh** [comment]
Sorry I am new to github. Can you tell me where is the template?

**Comment by erossignon** [comment]
I have pasted the template into your original post

**Comment by erossignon** [comment]
@awadekaustubh  thank you for filling the template. For the record, could you also describe the client application (name, vendor, version etcc)  you're are using to connect to your node-opcua server ?
On my side I have managed to reproduce your behavior with the Prosys OPCUAClient but not with the UAExpert Client.

**Comment by awadekaustubh** [comment]
@erossignon I am using Prosys OPCUAClient to test this. When can I expect this Bug fix?
