### ISSUE TITLE
node-opcua get Description of a Variable

### ISSUE THREAD

**Issue by opcua-user** [node-opcua/node-opcua#388]
**I'm submitting a ...**  (check one with "x")

 - ( ) bug report 
 - ( ) feature request
 - (x) support request 

**Current behavior**

I have tried to get the Description of a Variable using node-opcua 0.1.0-11.
![opcua-tree](https://user-images.githubusercontent.com/33144803/32091657-62a4f3e8-baf5-11e7-85c0-97ac42e676a5.PNG)

After browsing a Variable I get this Object:
![browsing_variable](https://user-images.githubusercontent.com/33144803/32091664-6c567704-baf5-11e7-8a93-fe6ab53f36d7.PNG)

After executing read I get this Object: 

![read_variable](https://user-images.githubusercontent.com/33144803/32091669-7105d222-baf5-11e7-8432-83158cfd532a.PNG)

How can I get the Description of a Variable or is it generally possible?

**Please tell us about your environment:**

  * ( ) I have installed node-opcua from source ( using git clone)
  * (x) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: VM
  * OS version: Ubuntu 16.04.3 LTS
    
    - ( ) Windows : version : _________
    - (x) Linux   : version :   Ubuntu 16.04.3 LTS
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name: UaExpert
     - Version: 1.5.0
     - Manufacturer/Software vendor:_________
     - link : https://
     
    
* **node-opcua version:** ``
node-opcua 0.1.0-11

* **Node:** 
   `node --version` = v8.7.0

**Comment by jakobgruber** [comment]
i had a similar issue with getting accessLevel of a node. reading a node with "attributeId: Value" only, will just return current value. you have to add all desired attributeIds

let nodesToRead = 
  { nodeId: nodeId, attributeId: opcua.AttributeIds.Value },
  { nodeId: nodeId, attributeId: opcua.AttributeIds.AccessLevel },
  { nodeId: nodeId, attributeId: opcua.AttributeIds.Description }
]

createdSession.read(nodesToRead, 0, function (err, nodesToRead, dataValues) { console.log(dataValues); }
