### ISSUE TITLE
URSA issue

### ISSUE THREAD

**Issue by finalburner** [node-opcua/node-opcua#391]
Hi everyone, 

I wanted to package a node.js application using nexe, and i encountred the error with the module 'URSA' which counld't be found from node-opcua-crypto\lib\crypto-utils.js

I've tried to install npm package URSA but i've go the following error on building process 

![image](https://user-images.githubusercontent.com/6690565/32320139-21443f36-bfbd-11e7-9301-d41188b0d14a.png)

After a lot of searches, I think that URSA has a compatibility problem with OpenSSL lastest version.

See https://github.com/electron-userland/electron-builder/issues/1652

So, as a resolution I've managed to switch to URSA-PUREJS by doing the following changes on line 255 of the file crypto-utils.js

  **ursa = require("ursa");   ==>   ursa = require("ursa-purejs");**

It seems to resolve the issue encountred when packaging with nexe or electron.

@erossignon

**Comment by erossignon** [comment]
ursa is not needed with recent version of npm. ursa was necessary with node 0.10 and node 0.12 due to some limitation in crypto with those version. I believe that you can simply tell webpack or nexe to ignore ursa module alltogether and it will work.
