### ISSUE TITLE
addMethod changes namespace of custom datatype

### ISSUE THREAD

**Issue by antiheld333** [node-opcua/node-opcua#411]
**I'm submitting a ...**  (check one with "x")

 - (x) bug report => search github for a similar issue or PR before submitting
 - ( ) feature request
 - ( ) support request => Please do not submit support request here, instead see use 
       [gitter](https://gitter.im/node-opcua/node-opcua) or [stackoverflow](https://stackoverflow.com/questions/tagged/node-opcua)

**Current behavior**

During defining a **method** with the default addMethod function and **a custom definded Input Arguments type** the `nodeId namespace` is changed to `0`. Browse and identify the `dataType` of the corresponding Argument in a Client isnt possible due to the wrong namespace and thereby wrong reference.

**Server Code**
```javascript
var temperatureSensorType = addressSpace.addObjectType({browseName: "TemperatureSensorType"});
addressSpace.addVariable({
            componentOf:     temperatureSensorType,
            browseName:     "Temperature",
            description:    "The temperature value measured by the sensor",
            dataType:       "Double",
            modellingRule:  "Mandatory",
            value: { dataType: opcua.DataType.Double, value: 19.5}
});


var method = server.engine.addressSpace.addMethod(device, {

            browseName: "myBark",

            inputArguments: [
                {
                    name: "nbBarks",
                    description: { text: "specifies the number of time I should bark" },
                    dataType: temperatureSensorType.nodeId,
                    valueRank: -1
                }, {
                    name: "volume",
                    description: { text: "specifies the sound volume [0 = quiet ,100 = loud]" },
                    dataType: opcua.DataType.UInt32
                }
            ],

            outputArguments: [{
                name: "Barks",
                description: { text: "the generated barks" },
                dataType: opcua.DataType.String,
                valueRank: 1
            }]
        });
```

**Expected behavior**

If the Bug is removed => the type of the custom defined Type is browseable cause its linked. 

# Solution ?
The Bug could be found under 
`packages\node-opcua-service-call\schemas\Argument_schema.js` - Line 51

The Code of the construct_hook - Function should be changed to:
```javascript
construct_hook: function(options) {

        var dataType = options.dataType;
        if (dataType) {
            if (typeof dataType === "string") {
                dataType = makeNodeId(dataType.value, 0);
                //dataType = coerceNodeId(DataType[dataType].value);
            } else {
                // ----------HERE------------
                // Add the Namespace here, otherwise it is reseted to 0
                dataType = coerceNodeId(dataType.value, dataType.namespace);
            }
           options.dataType = dataType;
        }
        return options;
    },
```

**Minimal reproduction of the problem with instructions**

  See example above. 
  ...
  
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

  * ( ) I have installed node-opcua from source ( using git clone)
  * (x) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: PC
  * OS version: Windows
    
    - (x) Windows : version : 7
    - ( ) Linux   : version : _________
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name: opcua-node custom server (see example above)
     - Version: same
     - Manufacturer/Software vendor: Etienne Rossignon
     - link : https://github.com/node-opcua/node-opcua
     
    
* **node-opcua version:** ``

* **Node:** 
   `node --version` = 9.2.0

**Comment by erossignon** [comment]
in fact, in your example temperatureSensorType is an ObjectType but not a DataType, and this should not be allowed.
As far as I understand , you  want to pass a reference to a Object Node to the method. 
I would declare the argument as being an NodeId and request the caller to pass the nodeId of the the TemperatureSensor you want to act upon.
