### ISSUE TITLE
postinstall fail on High Sierra (LibreSSL)

### ISSUE THREAD

**Issue by codanator** [node-opcua/node-opcua#416]
Hey,

i have troubles installing node-opcua on High Sierra.
The postinstall fails on generating the cetificates because libressl on mac does not support -rand.

Have you an workaround or any suggestions on solving this issue?

thx

**Comment by erossignon** [comment]
a workaround is described in https://github.com/node-opcua/node-opcua-pki/issues/4

**Comment by erossignon** [comment]
Problem shall be fixed in node-opcua-pki@0.0.29

**Comment by erossignon** [comment]
@codanator  can you confirm that node-opcua@0.2.0 now fixes the issue.

**Comment by codanator** [comment]
yes, postinstall now completes without error.

thx
