### ISSUE TITLE
can NodeOPCUA be used inside an Angular application ?

### ISSUE THREAD

**Issue by DieterOber** [node-opcua/node-opcua#423]
Hi,

i want to test node-opcua in an angular app and i got a Compiler error when i try to instantiate a new OPCClient like i.e. "let opcuaClient = new OPCUAClient(...);

There's a Problem with child_process. 

```
****ERROR in ./~/shelljs/src/exec.js
Module not found: Error: Can't resolve 'child_process' in 'D:\OS\Development\opcua\node_modules\shelljs\src'
 @ ./~/shelljs/src/exec.js 6:12-36
 @ ./~/shelljs/shell.js
 @ ./~/fqdn/index.js
 @ ./~/node-opcua-hostname/src/hostname.js
 @ ./~/node-opcua/index.js
 @ ./src/app/opcua-connect/opcua-connect.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts****
```

Any ideas ?

Regards
Dieter

**Comment by erossignon** [comment]
node-opcua is not designed to work inside the javascript script engine of a browser application but on the server side inside nodejs, sorry. 
This is a current limitation
