### ISSUE TITLE
Authenticating with a X509 Certificate (windows)

### ISSUE THREAD

**Issue by stevewillard** [node-opcua/node-opcua#427]
- (x) feature request
  * (x) I have installed node-opcua as a package ( using npm install )
      
* **node-opcua version:** 
0.2.1

* **Node:** 
   `node --version` = 6.12.3

I'm looking to authenticate an OPC connection using a x509 certificate on Windows. I was just wondering what the status of this feature is - I noticed some older closed issues talking about it, but it is not marked as a supported authentication feature.

<img width="538" alt="screen shot 2018-02-06 at 11 31 29 am" src="https://user-images.githubusercontent.com/11420/35871089-5f201612-0b31-11e8-8466-c2be4d5b919b.png">

**Comment by davidemess** [comment]
Follow

**Comment by erossignon** [comment]
duplicates #506
