### ISSUE TITLE
Can I connect WinCC OPC UA client on computer to node-opcua server on raspberry?

### ISSUE THREAD

**Issue by mymemoryq** [node-opcua/node-opcua#453]
Hello, I try to connect Wincc OPC UA client on computer to node-opcua server on raspberry but client can't connet (can't find url). Can you help me about this? Thank you!

**Comment by vo12nam** [comment]
yes,i have the same problem.I try to move certificate of wincc v14 to node opc sever ,but in the wincc can't browse the tcp of sever .

**Comment by erossignon** [comment]
Not enough information provided ..  issue form is not filled, closing
