### ISSUE TITLE
Bug for VariantArrayType in index.js?

### ISSUE THREAD

**Issue by limjunliang** [node-opcua/node-opcua#46]
Hi, 
The path in index.js file for VariantArrayType shows: 
module.exports.VariantArrayType = require("lib/datamodel/datavalue").VariantArrayType;

But, I could not find any VariantArrayType declaration in datavalue. 

Should it be lib/datamodel/variant instead?

**Comment by erossignon** [comment]
You're right . My mistake

Envoyé de mon iPhone
Excusez mes pouces
