### ISSUE TITLE
Session is being transferred from channel x  to channel  y - on opcua server

### ISSUE THREAD

**Issue by adhavann** [node-opcua/node-opcua#479]
**I'm submitting a ...**  (check one with "x")

 - ( x ) bug report => search github for a similar issue or PR before submitting
 - ( ) feature request
 - ( ) support request => Please do not submit support request here, instead see use 
      - use [gitter](https://gitter.im/node-opcua/node-opcua) or [stackoverflow](https://stackoverflow.com/questions/tagged/node-opcua) for community support, or 
      - [contact Sterfive for commercial support](https://www.sterfive.com)

**Current behavior**
When the opcua server starts and server session is created, it shows 'Session is being transferred from channel 2  to channel  4 ' (numbers change),  then  ' ERROR: channel.secureChannelId !== session.secureChannelId 5 4 '  and finally ' Server: closing SESSION  active ignition_CN554MOLD122  because of timeout =  120000  has expired without a keep alive '. All three error message occurs repetitively  with different channelIds .

**Expected behavior**
I expect none of the above message should pop up, I have also tried increasing timeout and with different opcua client (with software and node-opcua client) with keepalive option set to true.

**Minimal reproduction of the problem with instructions**
I expect it can be reproduced when you have more than 15 or 20 variables set in server with pub/sub mode.

  
**What is the motivation / use case for changing the behavior?**
To have a opcua server running without closing active session which in my case causes opcua client to reconnect multiple times 

**Please tell us about your environment:**
I am using yarn package manager v1.5.1 and node with 7.10.0

  * ( ) I have installed node-opcua from source ( using git clone)
  * ( x ) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: __raspberry pi___
  * OS version: _____
    
    - ( ) Windows : version : _________
    - ( x ) Linux   : version : ____4.9.14_____
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name:_____ node-opcua client____
     - Version:_____0.2.3____
     - Manufacturer/Software vendor:_________
     - link : https://
     
    
* **node-opcua version:** ``
 using node-opcua version - 0.2.3 for both server and client

* **Node:** 
   `node --version` = v7.10.0

**Comment by erossignon** [comment]
It looks like you have other OPCUA system in the loop ( I saw ignition_blah )
Can you provide more precise step to reproduce the issue with only n:ode-opcua server and node-opcua client involved as described.
Also please clarify what you mean by "I expect it can be reproduced when you have more than 15 or 20 variables set in server with pub/sub mode." because at this time node-opcua doesn't implement pub/sub. ( are you refering to subscription/monitored Item ?)

**Comment by adhavann** [comment]
I am sorry for the confusion,  let me explain the problem again (please forget about the node-opcua client part) , I am connecting the node-opcua server with InductiveAutomation quick client, when it gets connected, i could see the error messages as described previously on server log- 
' Session is being transferred from channel 2 to channel 4 ' (numbers change), then ' ERROR: channel.secureChannelId !== session.secureChannelId 5 4 ' and finally ' Server: closing SESSION active ignition_CN554MOLD122 because of timeout = 120000 has expired without a keep alive '. All three error message occurs repetitively with different channelIds .

To Reproduce the Error:
*   start the node-opcua server with alteast 15 server variables
*   Connect to the server using Inductive Automation (Ignition)
*   Attempt to read the server variables using quick client 
It might take some time for the error message to show up. It took me more than 30 minutes . Hope this helps 
![opcua issue](https://user-images.githubusercontent.com/2610615/39544089-02a6ff22-4e1b-11e8-89c3-e417d14080f9.JPG)

**Comment by adhavann** [comment]
Sorry, To answer your last question, yeah i mean subscription/monitored item.

**Comment by adhavann** [comment]
I am still experiencing the error " session is being transferred from channel <x> to channel <y>" , and also quite large number of disconnect and reconnect (with error message saying 'BadSecureChannelClosed') which i believe there is a co-relation between them. Could you please help me with this ?.

**Comment by Stormpass** [comment]
> If you are using the OPCUAClient module, setting the keepSessionAlive parameter within the client constructor will fix this issue. If using a third party client, you will have to review the documentation on how to configure the keep-alive property.
> 
> [https://node-opcua.github.io/api_doc/0.2.0/classes/OPCUAClient.html](url)

thanks you, it solved my problem
the newest doc is here
[OPCUAClientBaseOptions.html#keepSessionAlive](https://node-opcua.github.io/api_doc/2.68.0/interfaces/node_opcua_client.OPCUAClientBaseOptions.html#keepSessionAlive)
