### ISSUE TITLE
find nodeId by variable browseName

### ISSUE THREAD

**Issue by matc1** [node-opcua/node-opcua#482]
**I'm submitting a ...**  (check one with "x")

 - ( ) bug report => search github for a similar issue or PR before submitting
 - (X) feature request
 - () support request => Please do not submit support request here, instead see use 
      - use [gitter](https://gitter.im/node-opcua/node-opcua) or [stackoverflow](https://stackoverflow.com/questions/tagged/node-opcua) for community support, or 
      - [contact Sterfive for commercial support](https://www.sterfive.com)

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

  1. ________________
  2. ________________
  3. ________________
  ...
  
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

  * () I have installed node-opcua from source ( using git clone)
  * (x ) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: Server
  * OS version: Linux Ubuntu
    
    - ( ) Windows : version : _________
    - (x ) Linux   : version : Ubuntu Server 16.04
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name:_________
     - Version:_________
     - Manufacturer/Software vendor:_________
     - link : https://
     
    
* **node-opcua version:** ``

* **Node:** 
   `node --version` =

HI, i've a simple question, is it possible to determine a nodeId  by variable browseName?
For examples my variable browsename is 4:Temperature1 and it's unique name.
The nodeid is not costant and depend on PLC version, something like this
nodeId: "ns=4;s=|var|PLC3 **VXXXX** (3259) .Application.PersistentVars.Temperature1",
the part **VXXXX** is not costant depend on machine version.

How i can find nodeID of Temperature1 whithout know "PLC3 **VXXXX** (3259)" 

Thanks a lot

**Comment by erossignon** [comment]
duplicates #218
