### ISSUE TITLE
Not able to connect when using the client within a node-red function node

### ISSUE THREAD

**Issue by w4tsn** [node-opcua/node-opcua#485]
**I'm submitting a ...**  (check one with "x")

 - ( X ) bug report => search github for a similar issue or PR before submitting

**Current behavior**
The node-opcua-client invoked from a node-red function node does not connect to a node-opcua server running on the local machine, while the same code does work running within it's own node context (without node-red). It throws a connection error `Error: Good (0x00000)`

**Expected behavior**
The client code should establish a connection within the node-red function node the same way it does in a seperate node application context.

**Minimal reproduction of the problem with instructions**

1. Make sure a node-opcua server and node-red with node-opcua installed are running locally
2. Add node-opcua to the node-red context within the node-red `settings.js` file with `opcua: require('node-opcua')` in order to be able to use it within a function node
3. Use the code from the client tutorial within a function node in node-red. For node-red small adjustments have to be taken into account. Minimal this one (node-red version):

```
const opcua = global.get('opcua');

let client = new opcua.OPCUAClient({endpoint_must_exist: false});
let endpointUrl = "opc.tcp://localhost:4334/UA/Server/";

async.series([
        function(callback) {
            client.connect(endpointUrl, function(err) {
                if(err) {
                    node.error("cannot connect to endpoint: " + endpointUrl );
                } else {
                    node.log("connected!");
                }
                callback(err);
            });
        },
    ],
    function(err) {
        if (err) {
            node.error("[ERROR] " + err, err);
        } else {
            node.log("[INFO] done!");
        }
        client.disconnect(function(){});
    }
);
```

**What is the motivation / use case for changing the behavior?**
To be able to write a custom function node representing a simple client with specific logic which is able to create messages in the node-red flow.

**Please tell us about your environment:**

  * ( ) I have installed node-opcua from source ( using git clone)
  * (X) I have installed node-opcua as a package ( using npm install )
  * (X) I am using an application that uses node-opcua 
  
       - (X) node-red
       - ( ) other : please specify 
        
  * Device: OrangePiZero
  * OS version: ARMBian 5.38
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name: node-opcua
     - Version: 0.3.0
    
* **node-opcua version:**
Tested with 0.2.2 and 0.3.0

* **Node:** 
   `node --version` = 8.9.4

**Comment by erossignon** [comment]
@w4tsn , I suspect that we have 2 conflicting version of node-opcua installed, this causes the javascript code with StatusCodes Enum for instance to be declared and loaded twice within the context of your application, As a consequence it fails to check that someStatusCode === StatusCodes.Good because one comes from one version of node-opcua and the other one from the other.
 
could you perform some investigation:
```shell
$sudo apt-get install tree
$cd myappplication
$ tree
```

Check if node-opcua only appears once in tree .

**Comment by w4tsn** [comment]
Thank you very much! Now it is working. I removed some duplicate packages, which revealed another but and now I have a proper setup and it works.

In fact there was an old version of node-red-contrib-opcua installed for testing purposes, referencing node-opcua 0.0.61. Another 0.2.2 was declared within the package.json of the node-red project, while node-red-contrib-iiot-opcua 2.5.2 comes with 0.2.3.

The tree looks like this. So there is a second instance of node-opcua running originating from the xml2json package... this is odd, isn't it?

```
│   ├── node-opcua
│   │   ├── node-opcua.d.ts
│   │       └── test_node-opcua.js
│   ├── node-opcua-address-space
│   ├── node-opcua-address-space-for-conformance-testing
│   ├── node-opcua-assert
│   ├── node-opcua-basic-types
│   ├── node-opcua-binary-stream
│   ├── node-opcua-buffer-utils
│   ├── node-opcua-chunkmanager
│   ├── node-opcua-client
│   ├── node-opcua-client-crawler
│   ├── node-opcua-client-proxy
│   ├── node-opcua-common
│   ├── node-opcua-constants
│   ├── node-opcua-crypto
│   ├── node-opcua-data-access
│   ├── node-opcua-data-model
│   ├── node-opcua-data-value
│   ├── node-opcua-date-time
│   ├── node-opcua-debug
│   ├── node-opcua-enum
│   ├── node-opcua-extension-object
│   ├── node-opcua-factory
│   ├── node-opcua-guid
│   ├── node-opcua-hostname
│   ├── node-opcua-isa95
│   ├── node-opcua-nodeid
│   ├── node-opcua-nodesets
│   ├── node-opcua-numeric-range
│   ├── node-opcua-object-registry
│   ├── node-opcua-packet-analyzer
│   ├── node-opcua-packet-assembler
│   ├── node-opcua-pki
│   ├── node-opcua-secure-channel
│   ├── node-opcua-server
│   ├── node-opcua-server-discovery
│   ├── node-opcua-service-browse
│   ├── node-opcua-service-call
│   ├── node-opcua-service-endpoints
│   ├── node-opcua-service-filter
│   ├── node-opcua-service-history
│   ├── node-opcua-service-node-management
│   ├── node-opcua-service-query
│   ├── node-opcua-service-read
│   ├── node-opcua-service-register-node
│   ├── node-opcua-service-register-server
│   ├── node-opcua-service-secure-channel
│   ├── node-opcua-service-session
│   ├── node-opcua-service-subscription
│   ├── node-opcua-service-translate-browse-path
│   ├── node-opcua-service-write
│   ├── node-opcua-status-code
│   ├── node-opcua-transport
│   ├── node-opcua-utils
│   ├── node-opcua-variant
│   ├── node-opcua-vendor-diagnostic
│   ├── node-opcua-xml2json
│   │   │   ├── node-opcua
│   │   │   │   ├── node-opcua.d.ts
│   │   │   │       └── test_node-opcua.js
│   │   │   ├── node-opcua-address-space
│   │   │   ├── node-opcua-address-space-for-conformance-testing
│   │   │   ├── node-opcua-basic-types
│   │   │   ├── node-opcua-binary-stream
│   │   │   ├── node-opcua-chunkmanager
│   │   │   ├── node-opcua-client
│   │   │   ├── node-opcua-client-crawler
│   │   │   ├── node-opcua-client-proxy
│   │   │   ├── node-opcua-common
│   │   │   ├── node-opcua-data-access
│   │   │   ├── node-opcua-data-model
│   │   │   ├── node-opcua-data-value
│   │   │   ├── node-opcua-date-time
│   │   │   ├── node-opcua-enum
│   │   │   ├── node-opcua-extension-object
│   │   │   ├── node-opcua-factory
│   │   │   ├── node-opcua-nodeid
│   │   │   ├── node-opcua-numeric-range
│   │   │   ├── node-opcua-object-registry
│   │   │   ├── node-opcua-packet-analyzer
│   │   │   ├── node-opcua-secure-channel
│   │   │   ├── node-opcua-server
│   │   │   ├── node-opcua-server-discovery
│   │   │   ├── node-opcua-service-browse
│   │   │   ├── node-opcua-service-call
│   │   │   ├── node-opcua-service-endpoints
│   │   │   ├── node-opcua-service-filter
│   │   │   ├── node-opcua-service-history
│   │   │   ├── node-opcua-service-node-management
│   │   │   ├── node-opcua-service-query
│   │   │   ├── node-opcua-service-read
│   │   │   ├── node-opcua-service-register-node
│   │   │   ├── node-opcua-service-register-server
│   │   │   ├── node-opcua-service-secure-channel
│   │   │   ├── node-opcua-service-session
│   │   │   ├── node-opcua-service-subscription
│   │   │   ├── node-opcua-service-translate-browse-path
│   │   │   ├── node-opcua-service-write
│   │   │   ├── node-opcua-status-code
│   │   │   ├── node-opcua-transport
│   │   │   ├── node-opcua-utils
│   │   │   ├── node-opcua-variant
│   │   │   ├── node-opcua-vendor-diagnostic
│   │   │   ├── node-opcua
│   │   │   ├── node-opcua-crypto
│   │   │   ├── node-opcua-pki
```

After getting my setup right, the tree looks normal.

The last command

```
$ find . -name package.json  | xargs grep \"node-opcua\"
```

revealed the three duplicate entries for node-opcua, like you said.
