### ISSUE TITLE
Regex in node-opcua-transport/tools flawed

### ISSUE THREAD

**Issue by saenglert** [node-opcua/node-opcua#488]
**I'm submitting a ...**  (check one with "x")

 - (x ) bug report => search github for a similar issue or PR before submitting

**Current behavior**
The URL parameter for OPCUAClient.connect(url) requires a trailing `:` but no port number 

**Expected behavior**
The url should either require a port number or no port segment at all (and use default port).
However as I'm not really familiar with OPCUA I am unsure whether it defines a default port at all or actually requires the port number. If clarification is given I'm happy to provide a fix in form of a pull request.

**Minimal reproduction of the problem with instructions**
```
import * as opcua from 'node-opcua';

const url: string = 'opc.tcp://192.168.178.142';
const client: opcua.OPCUAClient = new opcua.OPCUAClient({});

 const init = async () => {
  try {
    await client.connect(url);
  } catch (error) {
    console.log(error);
  } finally {
    try {
      await client.disconnect();
    } catch (error) {
      console.log(error);
    }
  }
};

init();
```
```
Error: Invalid endpoint url
  at parseEndpointUrl (/Users/sascha/git/opcua_test/node_modules/node-opcua-transport/src/tools.js:70:11)
```
**What is the motivation / use case for changing the behavior?**
Ease of use

**Please tell us about your environment:**
Not relevant in this case
    
* **node-opcua version:** ``
commit 5f3602169ba85856e92893ffcdfb62c2854d975a

* **Node:** 
   `node --version` = v9.4.0

**Comment by erossignon** [comment]
There is no default port in OPCUA ( except may be for the LocalDiscovery Server on port 4840) and a port need to be specified. So yes, you can provide a pull request that enforce a port to be present after the ":" character ( with unit tests )
