### ISSUE TITLE
Can node-opcua server communicates over a GSM connection as a transport layer on a RPI ?

### ISSUE THREAD

**Issue by tototrix** [node-opcua/node-opcua#491]
Hello,

I apologize for using the issues tab but i don't find the right place for asking a question.

Is it possible to use node-opcua with a GPRS modem on a Raspberry ? If so, have you advices or links to start with ?

Thank you in advance.

**Comment by erossignon** [comment]
If there any way to communicate with your GPRS modem in nodejs , then yes ...
this package may help https://www.npmjs.com/package/simcom

**Comment by tototrix** [comment]
Thank you for your answer. 

In the "simple server example" when you define the server as below, the socket seems to be automaticaly configured and managed by either the library or by the BSP. It's obviously perfect for ethernet or Wifi:

![image](https://user-images.githubusercontent.com/6389984/41334467-043afb9a-6ee6-11e8-82c5-79e46c4b2440.png)

==> Therfore i don't see how to link the node-opcua library to an other medium of communication (like à GPRS)

**Comment by erossignon** [comment]
OK, I understand now that you want to use GPRS modem as a Transport Layer for the OPCUA communication. At this time the OPCUA specifications only provide TCP/IP transport. So if  your GPRS module can be seen as a Ethernet card, this should be possible. 
However, nothing exists in the OPCUA spec to describe a communication over raw AT command of a GRPS module.
The Transport layer is pretty well abstracted and one could decide to extend node-opcua to implement a dedicated transport if necessary . (big task though)
