### ISSUE TITLE
OPCUA server.engine.addressSpace.getPrivateNamespace() method not found

### ISSUE THREAD

**Issue by innoaloe** [node-opcua/node-opcua#493]
**I'm submitting a ...** 

 - (x) bug report
 - ( ) feature request
 - ( ) support request

**Current behavior**

Following the "Simple Server" tutorial (https://github.com/node-opcua/node-opcua/blob/master/documentation/creating_a_server.md), I'm stuck at the the point to get namespace definition from the OPCUAServer engine.
It says the getPrivateNamespace() method which is required there is not a method.
I'm coding it using Visual Studio Code, and indeed the Intellisense cannot find the said method when I'm writing server.engine.addressSpace.getPrivateNamespace() outside of function definitions.

**Expected behavior**

As the tutorial suggest, this method should have existed somewhere in the API. Maybe the tutorial version has deprecated? Or am I missing something else here...

**Minimal reproduction of the problem with instructions**

  1. Just following the entire "Simple Server" tutorial. Copy-pasting the whole code to it's respective sections produces same result.
  2. ________________
  3. ________________
  ...
  
**What is the motivation / use case for changing the behavior?**

To get the server working.

**Please tell us about your environment:**

  * ( ) I have installed node-opcua from source ( using git clone)
  * (x) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: Personal Computer
  * OS version: 64-bit
    
    - (x) Windows : version : Windows 10
    - ( ) Linux   : version : _________
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name:_________
     - Version:_________
     - Manufacturer/Software vendor:_________
     - link : https://
     
    
* **node-opcua version:** ``

0.4.1

* **Node:** 
   `node --version` = 8.11.3

**Comment by erossignon** [comment]
In fact, the tutorial is too much ahead of the current node-opcua version (0.4.1).

getPrivateNamespace() has just been introduced recently,  you'll need to clone node-opcua and use the most recent version on master. 

We need to do something to make sure that our link points to the correct documentation.

**Comment by erossignon** [comment]
I have updated http://node-opcua.github.io/ so that examples relates to current published version and not master.

**Comment by innoaloe** [comment]
@erossignon Thank you for the response. Will try on the tutorial for the released version. And thank you to develop this great API.
