### ISSUE TITLE
send a file to server and back to client

### ISSUE THREAD

**Issue by RasPiTool** [node-opcua/node-opcua#496]
Hello,
Thanks for node-opcua!
I have a fmu-file or zip-file which contians the compiled simulation file.
Now I would like to send this fmu-file or zip-file from PC (Client) to Raspberry PI (Server).
The Server should unzip the file and execute the simulation.
Unzipping and simulation on Raspberry Pi works fine.
But how can i send the file to the Server and after simulation back to the client?

I am new at OPC UA. Is there an example of file transfer on node-opcua?

**Comment by mikakaraila** [comment]
Look addressSpace test code:
https://github.com/node-opcua/node-opcua/blob/07d87a1ab5cbfcb031ddada85aa75912d9c83ba8/packages/node-opcua-address-space-for-conformance-testing/src/address_space_for_conformance_testing.js
