### ISSUE TITLE
OPC UA does not emit same data after configurable time interval

### ISSUE THREAD

**Issue by vishalb747** [node-opcua/node-opcua#502]
Hi, 
   I am using OPC UA. I have tried lots of combination of get the OPC UA server data after configurable time interval. But I did not get any data. It showing as below image 
![screen shot 2018-07-11 at 10 11 05 pm](https://user-images.githubusercontent.com/28604618/42587128-6c5a8772-8557-11e8-937d-d822f303f4e6.png)

I am trying to get exact subscription combination
{
    "requestedPublishingInterval": 1000,   
    "requestedMaxKeepAliveCount": 5,
    "requestedLifetimeCount": 10, 
    "maxNotificationsPerPublish": 10,  
    "publishingEnabled": true, 
    "priority": 10
}

**Comment by erossignon** [comment]
please provide a  example source code for investigation
