### ISSUE TITLE
Cannot read:C:\Users\siemens\AppData\Roaming\npm\node_modules\node-opcua-client\certificates\client_selfsigned_cert_1024.pem file

### ISSUE THREAD

**Issue by Dhiaaeddinanabtawi** [node-opcua/node-opcua#503]
Hi,

I am new to Node-RED and right now I have installed it and everything works fine. After creating my first flow, every time I start node red, I get an error saying:

```
Cannot read:C:\Users\siemens\AppData\Roaming\npm\node_modules\node-opcua-client\certificates\client_selfsigned_cert_1024.pem file
cannot locate certificate file C:\Users\siemens\AppData\Roaming\npm\node_modules\node-opcua-client\certificates\client_selfsigned_cert_1024.pem
```
Well, I figured out that in my `node-modules` folder I don't have any folder called `node-opcua-client` at all. Is there any explanation of why this error happened and how to solve it?
I am using Node-red on a windows 7 virtual machine with the following:
NPM: 5.6.0
Node: v8.11.3
Node-RED: v0.18.7
I know there is a similar issue, but nothing helped me so far.

**Comment by mikakaraila** [comment]
You have installed this with -g global, not under .node-red but check if you have it in local not roaming profile. Hope this helps...

**Comment by Dhiaaeddinanabtawi** [comment]
Maybe it is a dum question, but when I search for it, I find them under the mentioned folder, but when I open that folder, I see nothing?
How to solve this problem?
