### ISSUE TITLE
Client requested SamplingInterval may not be used by the server

### ISSUE THREAD

**Issue by rrdlpl** [node-opcua/node-opcua#510]
**I'm submitting a ...**  (check one with "x")

 - (x ) bug report => search github for a similar issue or PR before submitting

**Current behavior**
I am monitoring a node on a real plc with samplingInterval of every ten seconds, but the value gets polled every five seconds.
**Expected behavior**
The node should be monitored every ten seconds as I set on my samplingInterval

This is a snippet of my Code where I'm monitoring the nodes:
```

const dataPoint = nodesToMonitor[nodeName] as MVPDataPoint;
            // tslint:disable-next-line:max-line-length
            const node = new NodeId(this.nodeIdTypes[dataPoint.nodeIdType.value], dataPoint.nodeId.value, dataPoint.namespace.value);
            console.log(`Building node for ${nodeName}. Polling rate = ${dataPoint!.pollingRate!.value}`);
            const requestedParameters = {
                samplingInterval: 10000,
                discardOldest: true,
                queueSize: 100
            };
            const monitor = await this.subscription!.monitor({
                nodeId: node,
                attributeId: AttributeIds.Value,
            },
                requestedParameters,
                undefined
            );
            monitor.on('changed', (dataValue: DataValue) => {
                callback(nodeName, dataValue.value.value);
            });



```

**Please tell us about your environment:**

Client: OPC UA Client.
Equipment: B&R PLC X20CP0484 https://www.br-automation.com/en/products/control-systems/x20-system/compact-s-cpus/x20cp0484/

  
  * (x ) I have installed node-opcua as a package ( using npm install )
    
    - (x) Linux   : version : Debian stretch 

* Description of the other OPCUA system I am trying to connect to:
   
     - Name: X20CP0484
     - Version: F4.4
     - Manufacturer/Software vendor:B&R
     - link : https://www.br-automation.com/en/products/control-systems/x20-system/compact-s-cpus/x20cp0484/
     
    
* **node-opcua version:** ``
    "node-opcua": "^0.4.1",

* **Node:** 
   `node --version` = 8.11.3

**Comment by rrdlpl** [comment]
This is an example of the node that I'm trying to poll

<a href="https://ibb.co/h6MPGK"><img src="https://preview.ibb.co/gxvjGK/Screenshot_from_2018_08_08_11_33_23.png" alt="Screenshot_from_2018_08_08_11_33_23" border="0"></a>

**Comment by erossignon** [comment]
The server may modify the sampling interval that you are requesting. 
In fact, the client suggests a sampling interval and the server can adjust it according to its own rules and limitations.Server can decide to increase or decrease the sampling interval value.

The actual value used for the monitored item is known by the client, as the server  returns the revised sampling interval in the CreateMonitoredItem Result.

You can figure it out in your client code by 

``` javascript
 const node = new NodeId(...);
 const requestedParameters = {
      samplingInterval: 10000,
      discardOldest: true,
      queueSize: 100
 };
     
const monitorItem = await this.subscription!.monitor({
     nodeId: node,
     attributeId: AttributeIds.Value,
 },requestedParameters, undefined);


// display the server's revised parameters ( may not be the one we have requested !)
console.log(" revised sampling interval ",        monitorItem .monitoringParameters.samplingInterval);
console.log(" revised queue size ",        monitorItem .monitoringParameters.queueSize );

monitorItem.on('changed', (dataValue: DataValue) => {
          console.log(" Value = ", dataValue.toString());
});

 ```

**Comment by rrdlpl** [comment]
@erossignon  The debug lines that you added doesn't work in the example, because monitoringParameters property is not in the typedefinition of ClientMonitoredItem.

**Comment by erossignon** [comment]
you find a lack in the TypeScript definition file for MonitoredItem

Please note that a brand new TypeScript  version of node-opcua is being actively developed at this time and is available for test in the "next" branch.

Here is a easy workaround for the time being:
you can cast the monitorItem  to any so you can access hidden member and prevent Typescript checking
```javascript
console.log(" revised sampling interval ",        (monitorItem as any).monitoringParameters.samplingInterval);
console.log(" revised queue size ",        (monitorItem as any) .monitoringParameters.queueSize );
```
