### ISSUE TITLE
Multiple clients connected to one device

### ISSUE THREAD

**Issue by fillco** [node-opcua/node-opcua#517]
**I'm submitting a ...**  (check one with "x")
 - (x) generic OPCUA question (see also stackoverflow )

I have the following question about management of multiple client connections to same device.

I am currently making a research and I am not sure about one case:
 We have multiple clients connected to same device with OPCUA server on it and two or more of clients want to read/write or configure the device at same time. My question is what will be the behavior of the server? How the server will manage clients requests?

**Comment by erossignon** [comment]
Usually OPCUA Servers are capable of dealing with multiple client connections.
 Advanced servers (such as aggregators etc ...)  can deal with several hundred of concurrent connections if needed. Read/Write are done on a first arrived first served basis. This being said each servers may implements concurrent access to the same underlying device variable differently.
On the other end of the spectrum, Nano Servers (running on device with low ressource) may restrict access to one or two clients max.
Embedded servers (running on embedded board ) may restrict access to 5 simultaneous clients.
