### ISSUE TITLE
simple_client.js does not connect Prosys Server, Basic256/SIGN

### ISSUE THREAD

**Issue by zombinary** [node-opcua/node-opcua#520]
Im using the node-opcua@0.4.1 to connect an opcua server with security settings Basic256/SIGN in a Node-RED instance. The Certificate is Trusted on the Serverside and the method OPCUAClient.connect() return with an **Error: Transaction has timed out ( timeout = 60000 ms)**.

I have the same problem with **node-opcua-samples/bin/simple_client.js**, show this log:

```
NT0002A233E5F1:/opt/node-opcua_0.4.1/node_modules/node-opcua-samples/bin$ node simple_client.js -e opc.tcp://192.168.253.113:53530 -P=Basic256 -s=SIGN -n="ns=6=5;s=Counter1"
securityMode        =  SIGN
securityPolicy      =  Basic256
timeout             =  20000
 monitoring node id =  ns=6=5;s=Counter1
 connecting to  opc.tcp://192.168.253.113:53530
    strategy { maxRetry: 10, initialDelay: 2000, maxDelay: 10000 }
...
 .... ( 1037)
Options =  SIGN Basic256
 reconnecting to  opc.tcp://192.168.253.113:53530
 message was
undefined
 message was 2: { /*GetEndpointsRequest*/
 requestHeader                 /* RequestHeader                    */: {
   authenticationToken         /* NodeId                           */: ns=0;i=0
   timeStamp                   /* UtcTime                          */: 2018-09-11T14:56:05.142Z
   requestHandle               /* IntegerId                        */: 2               0x2
   returnDiagnostics           /* UInt32                           */: 0               0x0
   auditEntryId                /* UAString                         */: null
   timeoutHint                 /* UInt32                           */: 0               0x0
   additionalHeader            /* ExtensionObject                  */: null
 }
 endpointUrl                   /* String                           */:
 localeIds                     /* LocaleId                      [] */: [ /* empty*/ ]
 profileUris                   /* String                        [] */: [ /* empty*/ ]
};
 Timeout .... waiting for response for  GetEndpointsRequest { /*RequestHeader*/
 authenticationToken           /* NodeId                           */: ns=0;i=0
 timeStamp                     /* UtcTime                          */: 2018-09-11T14:56:05.142Z
 requestHandle                 /* IntegerId                        */: 2               0x2
 returnDiagnostics             /* UInt32                           */: 0               0x0
 auditEntryId                  /* UAString                         */: null
 timeoutHint                   /* UInt32                           */: 0               0x0
 additionalHeader              /* ExtensionObject                  */: null
};
 disconnected
 client : process terminated with an error
 error Error: Transaction has timed out ( timeout = 60000 ms)
    at Timeout._onTimeout (/opt/node-opcua_0.4.1/node_modules/node-opcua-samples/node_modules/node-opcua-secure-channel/src/client/client_secure_channel_layer.js:1021:27)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
 stack trace Error: Transaction has timed out ( timeout = 60000 ms)
    at Timeout._onTimeout (/opt/node-opcua_0.4.1/node_modules/node-opcua-samples/node_modules/node-opcua-secure-channel/src/client/client_secure_channel_layer.js:1021:27)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
Exiting
```

I compared the connection setup with Wireshark (UAExpert-->Prosys Simulation Server).
The UaExpert send an CreateSessionRequest after the OpenSecureChannel message and node-opcua send an getEndpointRequest(). I think there is a Problem in the Statemachine to connect the server correctly.

![uaexpert](https://user-images.githubusercontent.com/11854198/45369888-3d944480-b5e7-11e8-88eb-171242f14eea.png)

 - see also:
   can't connect uaAnsiC with security SIGN Basic256 #425

  * OS version: Linux
    
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name: Prosys Simulation Server
     - Version: V2.3.2
     - link : https://
     
    
* **node-opcua version:** 
node-opcua@0.4.1

* **Node:** 
 8.11.3

**Comment by zombinary** [comment]
Same Problem in 
**Cannot connect to sample_server with Prosys OPC UA Client** #512

and fixed in v0.4.4.
I will test if this bug is fixed for me too.

**Comment by zombinary** [comment]
I have tested node-opcua@0.4.4 and node-opcua@0.4.5 with a external and local machine (WIN7x64 and WIN10x64) and could connect the simple_client.js with Prosys (Basic256/SIGN).

**Under the linux machine (yocto-linux) the problem still exists.**

**Comment by konradheidrich** [comment]
the head line is confusing. Should be "**simple_client.js does not connect Prosys Server, Basic256/SIGN**"

**Comment by erossignon** [comment]
@zombinary :  can you double check the version of node-opcua running on the yocto-linux ?  may be are you still using an old version of node-opcua that has this issue. Best think would be to reinstall from scratch and may be also delete any package-lock.json that may force  you using an old version..

**Comment by zombinary** [comment]
My problem was an incorrectly set timezone and I assumed that the [Mailformed Message] was the trigger. After setup the correct timezone on the yocto device, the simple_client could subscribed to the variable.

With DEBUG=ALL I am responding to the error message:
```
client_secure_channel_layer :396 client: Security Token 1 is about to expired, let's raise lifetime_75 event
```

Is it possible to pass this error message to the callback of client.connect() without waiting for the 'Transaction has timed out'?

**Comment by erossignon** [comment]
@zombinary unfortunatly the security token renewal happens at some point between 75% and 100% of the security token lifetime.
I would suggest that after creating the session , your client reads the currentTime of the server and verify that the drift is acceptable ( doesn't exceed a few second, may be one minute ) max .
By the way, OPCUA specifications indicates that the clock of both server and client must be in sync and it is a good practice to check time drift.

**Comment by zombinary** [comment]
OK thanks, this is a good idea to check and manage the current server time.
