### ISSUE TITLE
opc-server write method problem

### ISSUE THREAD

**Issue by ericccccccc** [node-opcua/node-opcua#537]
**I'm submitting a ...**  (check one with "x")

 - ( ) bug report => search github for a similar issue or PR before submitting
 - ( ) feature request
 - (**X**) support request => Please do not submit support request here, instead see use 
      - use [gitter](https://gitter.im/node-opcua/node-opcua) or [stackoverflow](https://stackoverflow.com/questions/tagged/node-opcua) for community support, or 
      - [contact Sterfive for commercial support](https://www.sterfive.com)

**Current behavior**

i loaded my information model by generated xml, but i want to update the variable value every 5 seconds. i've found that the ServerEngine has "write" method ~
![image](https://user-images.githubusercontent.com/35401606/46713563-eaff8400-cc89-11e8-8c01-c2fd51acb6d3.png)

So i use this method like this ~
![image](https://user-images.githubusercontent.com/35401606/46713678-76791500-cc8a-11e8-9971-b4641b2d6565.png)

**Expected behavior**

then when i run the server,i got the error~
![image](https://user-images.githubusercontent.com/35401606/46713726-b3dda280-cc8a-11e8-80f3-ff4f600bc323.png)

is something i missed or use the in the wrong way ?

**Comment by erossignon** [comment]
value must be a DataValue like object: try this;
 ```javascript
const nodeToWrite = {
     nodeId: "ns=2;i=2001",
     attributeId: opcua.AttributeIds.Value,
     value : {
            sourceTimestamp: new Date(),
            statusCode: opcua.StatusCodes.Good,
            value: {
                 dataType: opcua.DataType.Int32 // check this type in your context
                  value: 42
             }
     } 
}
```
PS: note that write takes either a single node to write or an array of node to write: make sure you name nodeToWrite ( without s) in your case.

**Comment by erossignon** [comment]
I have requalified the issue as a question / Support request rather than bug

**Comment by ericccccccc** [comment]
i have tried what you say~ still get this problems
![image](https://user-images.githubusercontent.com/35401606/46748925-5297ec80-cce7-11e8-95d1-272f637e76ce.png)

i think is that i didn't add this params with  " serverEngine Write method "?
![image](https://user-images.githubusercontent.com/35401606/46749163-c0dcaf00-cce7-11e8-9d5a-ccbff9d4e467.png)

but what is context ?
how to define it ?

**Comment by erossignon** [comment]
Sorry, I didn't catch you're trying to set the value of a UAVariable Node from within a server.
In this case, you need to 
a/ get the variable node from its node id
b/ use setValueFromSource to change its value

``` javascript
const node = server.engine.addressSpace.findNode("ns=1,i=2001");
node.setValueFromSource({ dataType: opcua.DataType.Float, value: 4.2});
```

**Comment by ericccccccc** [comment]
thx ! ! it works!!
