### ISSUE TITLE
how check the client is connected

### ISSUE THREAD

**Issue by mariodiciccio** [node-opcua/node-opcua#539]
- ( ) bug report => search github for a similar issue or PR before submitting
 - ( ) feature request
 - (x) support request => Please do not submit support request here, instead see use...

it is possible add opcuaClient.isConnected()?

thanks

  * ( ) I have installed node-opcua from source ( using git clone)
  * ( x ) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: _____
  * OS version: _____
    
    - ( ) Windows : version : _________
    - ( ) Linux   : version : _________
    - ( x) MacOs   : version : 10.13.6
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :

**Comment by erossignon** [comment]
```
const client = new opcua.OPCUAClient();
await client.connect(endpointurl);

if (client.isConnected) {
   console.log("client is connected"); 
} else {
   console.log("client may be trying to  reconnected"); 
}
```
alternatively , you can listen to some event that are raised when connection is changing

````
 client.on("connection_reestablished",function() {
            });
        client.on("backoff", function (retryCount, delay) {
         });
        client.on("start_reconnection", function () {
         });
```
in next version there will be also:
```
        client.on("connection_lost", function() {
         });
```

**Comment by mariodiciccio** [comment]
thank you very much, i will wait next version

**Comment by mariodiciccio** [comment]
Why the command client.isConnected return "undefined"?

**Comment by panManfredini** [comment]
Hi,
it looks like "isConnected" is not a member of OPCUAClient. This would be actually an interesting feature to add.
My solution up to now is:
```javascript

client.isConnected = false;
client.on('close',()=>{ client.isConneted = false;});
client.on('connection_lost',()=>{client.isConneted = false;});
client.on("connection_reestablished", () => {client.isConneted = true;});

try{
   await client.connect(endpointUrl) ;
   client.isConnected= true;
}
catch(e){
// do something
}
```

**Comment by erossignon** [comment]
In fact, `isConnected` flag applies to `session` object

**Comment by nur455** [comment]
Property 'isConnected' does not exist on type 'OPCUAClient'

**Comment by erossignon** [comment]
use  !client.isReconnecting instead
