### ISSUE TITLE
passing a String NodeId  on the command line

### ISSUE THREAD

**Issue by Jochen1980** [node-opcua/node-opcua#54]
Hi Etienne,

I wanted to test your command line interface mentioned in line 10 of simple_client.js. I was not able to set an accepted NodeId name, i.e. if I call 
```
    node bin/simple_client.js --endpoint opc.tcp://ehome09:48010 --node "ns=3,s={360273AA-F2B9-4A7F-A5E3-37B7074E2529}.MechanicalDomain"
```

I will get an error: 
```
throw new Error("String cannot be coerced to a nodeId : " + value)
                  ^
Error: String cannot be coerced to a nodeId : ns=3,s={360273AA-F2B9-4A7F-A5E3-37B7074E2529}.MechanicalDomain
    at TypeSchema.coerceNodeId ...
```
Can you verify that your example in your code is still working or are you able to add one more example call?

This is the corresponding file in node-opcua-project:
https://github.com/node-opcua/node-opcua/blob/master/bin/simple_client.js

**Comment by erossignon** [comment]
you'll need a ```;``` instead of a ```,``` to separate the ```ns=``` part and the ```s=``
