### ISSUE TITLE
unable to create certificate using  openssl  when we do npm install node-opcua --save  behind a proxy

### ISSUE THREAD

**Issue by samminen** [node-opcua/node-opcua#556]
I cloned node-opcua git repository and did npm install inside node-opcua\ path. I got below error when it try to do openssl stuff;

I did setup corporate proxy, but still i am getting below issue. I tried on WIN10 OS.

ERROR:

C:\opcuanode\sample_server>npm install --save node-opcua --proxy=http://np2prxy801
npm WARN deprecated delayed@1.0.1: no longer maintained

> node-opcua-client@0.5.0 postinstall C:\opcuanode\sample_server\node_modules\node-opcua-client
> node test_helpers/create_certificates.js certificate -s -o certificates/client_selfsigned_cert_1024.pem

 Creating default g_config file  C:\opcuanode\sample_server\node_modules\node-opcua-client\certificates\config.js
checking presence of  C:\Users\H198358\AppData\Local\Programs\openssl\openssl.exe
Done
 cannot find file C:\Users\H198358\AppData\Local\Programs\openssl\openssl.exe
openssl seems to be missing and need to be installed
downloading https://github.com/node-opcua/node-opcua-pki/files/1886617/openssl-1.0.2o-x64_86-win64.zip
{ Error: connect ECONNREFUSED 192.30.253.113:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.30.253.113',
  port: 443 }

> node-opcua-server@0.5.0 postinstall C:\opcuanode\sample_server\node_modules\node-opcua-server
> node test_helpers/create_certificates.js certificate -s -o certificates/server_selfsigned_cert_2048.pem

 Creating default g_config file  C:\opcuanode\sample_server\node_modules\node-opcua-server\certificates\config.js
checking presence of  C:\Users\H198358\AppData\Local\Programs\openssl\openssl.exe
Done
 cannot find file C:\Users\H198358\AppData\Local\Programs\openssl\openssl.exe
openssl seems to be missing and need to be installed
downloading https://github.com/node-opcua/node-opcua-pki/files/1886617/openssl-1.0.2o-x64_86-win64.zip
{ Error: connect ECONNREFUSED 192.30.253.113:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.30.253.113',
  port: 443 }

**Comment by sanderd17** [comment]
This is the same issue as #555 , the proxy you use doesn't allow you to connect to github. Please check with your IT department to fix this.
