### ISSUE TITLE
How to read multiple NodeID values using opcua client using subscription.monitor() method

### ISSUE THREAD

**Issue by samminen** [node-opcua/node-opcua#557]
I want to read all the variables values my server publishing using opcua client using subscription.monitor() method; How to implement it ? ALso, I want to print NodeID along with values once I read in my opcua client program.

Server publish below 3 values: 
1. variable1 
2. variable2 
3. available_memory()
*************************************************

Server Publishing below variable values: 

let variable1 = 1;
        
        // emulate variable1 changing every 500 ms
        setInterval(function(){  variable1+=1; }, 500);
namespace.addVariable({
            componentOf: device,
            browseName: "MyVariable1",
            dataType: "Double",
            value: {
                get: function () {
                    return new opcua.Variant({dataType: opcua.DataType.Double, value: variable1 });
                }
            }
        });
        
        // add a variable named MyVariable2 to the newly created folder "MyDevice"
        let variable2 = 10.0;
        
        namespace.addVariable({
            
            componentOf: device,
            
            nodeId: "ns=1;b=1020FFAA", // some opaque NodeId in namespace 4
            
            browseName: "MyVariable2",
            
            dataType: "Double",    
            
            value: {
                get: function () {
                    return new opcua.Variant({dataType: opcua.DataType.Double, value: variable2 });
                },
                set: function (variant) {
                    variable2 = parseFloat(variant.value);
                    return opcua.StatusCodes.Good;
                }
            }
        });
        const os = require("os");
        /**
         * returns the percentage of free memory on the running machine
         * @return {double}
         */
        function available_memory() {
            // var value = process.memoryUsage().heapUsed / 1000000;
            const percentageMemUsed = os.freemem() / os.totalmem() * 100.0;
            return percentageMemUsed;
        }
        namespace.addVariable({
            
            componentOf: device,
            
            nodeId: "s=free_memory", // a string nodeID
            browseName: "FreeMemory",
            dataType: "Double",    
            value: {
                get: function () {
					return new opcua.Variant({dataType: opcua.DataType.Double, value: available_memory() });
					}
            }
        });
    }

**Comment by erossignon** [comment]
As stated in the template , please use stackoverflow for support issue or contact sterfive.com for commercial support.
