### ISSUE TITLE
Firing Discrete Alarm

### ISSUE THREAD

**Issue by Muddasir-Shakil** [node-opcua/node-opcua#559]
**Current behavior**
The Discrete Alarm is not firing even though the input node is changing. It instantiated normally. But when I am trying to fire it by changing the value of InputNode, it does not show any response. On the other hand I have created OffNormalAlarm which works fine (Compairing Normalstate with InputNode). 
Discrete Alarm does not have a unit test so I could not find any help.  
Question: is it possible to fire Discrete Alarm with new Conditioninfo (._calculateConditionInfo)?
**Expected behavior**
I am trying to use Discrete Alarm to check if my device is functional or not. Therefore I am monitoring tankstate which is a boolean variable. by Changing the InputNode value (from true to false), server should detect value change and fire the event. 

   

**Minimal reproduction of the problem with instructions**
1. This is how I have set it up 
Tank state ( true/ false)

```javascript
var tankstate = namespace.addVariable({
    browseName: "Tankstate",
    propertyOf: tank,
    dataType: "Boolean",
    eventSourceOf: tank,
    value:new opcua.Variant({
      dataType: opcua.DataType.Boolean,
      value: true
    })
  });`
```
2. And the Discrete Alarm Instantiation

```javascript
var discreteAlarm = addressSpace.findEventType("DiscreteAlarmType");
var alarm3 = addressSpace.instantiateDiscreteAlarm(discreteAlarm,{
  organizedBy: tank,
  conditionSource: tankstate,
  browseName: "DiscreteAlarmInstance",
  inputNode: tankstate,   // the variable that will be monitored for change
  optionals: [
      "ConfirmedState", "Confirm" // confirm state and confirm Method
  ]
});
```
3. This is how I am overwriting ConditionInfo
```javascript
alarm3._calculateConditionInfo = function (stateData, isActive, value, oldCondition){
  return {
      message: "tank stopped working",
      severity: "1000",
      quality: opcua.StatusCodes.Good,
      retain: true
    }
};
```

**Please tell us about your environment:**

Linux Debian
OPC UA Server
  * (x)  my request is related to node-opcua acting as a OPCUA SERVER 
  * (x) I have installed node-opcua as a package ( using npm install ) 
* **node-opcua version:**  :
`node-opcua< --version` = 0.5.0
* **Node:** 
   `node --version` = v8.12.0

I am attaching the source file as well 
[index.zip](https://github.com/node-opcua/node-opcua/files/2607928/index.zip)

**Comment by erossignon** [comment]
I don't think you should reimplement the internal method _calculateConditionInfo. Methods starting with _ are meant to be private and for internal use only.

You're right the DiscreteAlarm doesn't automatically raise when the associated Variable is changing.
I suggest that you implement it this way on your end ...

```javascript
    tankstate.on("value_changed", function (newDataValue, oldDataValue) {
        if (some condition) {
            alarm3 .raiseNewCondition(...);
        }
    });
```

**Comment by Muddasir-Shakil** [comment]
Thank you.
