### ISSUE TITLE
Client support for continuation points

### ISSUE THREAD

**Issue by buhlj** [node-opcua/node-opcua#563]
**I'm submitting a ...**  (check one with "x")

 - ( ) bug report => search github for a similar issue or PR before submitting
 - (x) feature request
 - ( ) support request => Please do not submit support request here, instead see use 
      - use [gitter](https://gitter.im/node-opcua/node-opcua) or [stackoverflow](https://stackoverflow.com/questions/tagged/node-opcua) for community support, or 
      - [contact Sterfive for commercial support](https://www.sterfive.com)

**Current behavior**

Do not support continuation points. An assert is triggered in NodeCrawler

**Expected behavior**

Support for client continuation points

**Minimal reproduction of the problem with instructions**

  1. Crawl a server that return an continuation point

  
**What is the motivation / use case for changing the behavior?**

Support for serves that return continuation points. Are there any plans for supporting this?

**Please tell us about your environment:**

  * (x) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * ( )  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * (x) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: _____
  * OS version: _____
    
    - ( ) Windows : version : _________
    - (x ) Linux   : version : Debian 9
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name: B&R opc ua server on buscontroller
     - Version: 1.16
     - Manufacturer/Software vendor: B&R
     - link : https://
     
    
* **node-opcua version:**  :

node-opcua 0.5.0

* **Node:** 
   `node --version` = Node v11.1.0

**Comment by erossignon** [comment]
fixed in version 2.0.0 released today
