### ISSUE TITLE
Is there any example code of  Alarm and Conditions  ?

### ISSUE THREAD

**Issue by ericccccccc** [node-opcua/node-opcua#564]
**I'm submitting a ...**  (check one with "x")

 - ( ) bug report => search github for a similar issue or PR before submitting
 - ( ) feature request
 - (x) support request => Please do not submit support request here, instead see use 
      - use [gitter](https://gitter.im/node-opcua/node-opcua) or [stackoverflow](https://stackoverflow.com/questions/tagged/node-opcua) for community support, or 
      - [contact Sterfive for commercial support](https://www.sterfive.com)

![image](https://user-images.githubusercontent.com/35401606/49074815-75b73500-f270-11e8-98d4-768eed53d344.png)

is that any A&C example to understand how it work??
i'm confused about what is Event or Condition in OPCUA , how it Alarm to client ??
And what's different with Pub/Sub? i think they are same ~

thx for anyone helps!!

**Comment by erossignon** [comment]
@ericccccccc please refer to OPCUA Specitficiation part 3 4 5 and 9  to read about Events, Condition and then Alarms in general.
Unit tests are also a good place to find example of use.

**Comment by ericccccccc** [comment]
i've found there are some Event example (simple_server.js 、simple_client.js) in 
node-opcua/packages/node-opcua-samples/bin/ ~
 when i try , i can't get any event notify , but only value of variable changing.
  
 
![image](https://user-images.githubusercontent.com/35401606/49211697-1f2a3200-f3fb-11e8-88ad-68731d1a6be2.png)

is that when i subscribe the event with the Object, when something change under the Object (like the value of variable is changing)  i can get the event notify on the monitor ??
i've watched the spec, but still confused about the event..
