### ISSUE TITLE
Cannot rebind permissions on nodes from nodeset

### ISSUE THREAD

**Issue by num-lock** [node-opcua/node-opcua#569]
**I'm submitting a ...**
 - (x) bug report (hopefully)

**Current behavior**

When loading a nodeset from XML it appears I cannot overwrite the permissions on those nodes created by the nodeset. This makes it impossible to implement a `set` function that actually gets called. Tested with several clients. (e.g. UAExpert, opcua commander) Trying to set the value always gives `BadUserAccessDenied`.

**Expected behavior**

It would be nice to overwrite the permissions and implement a usable `set` as expected.

**Minimal reproduction of the problem with instructions**

I have created a repo with a ready to use codebase including the nodesets.

https://github.com/num-lock/node-opcua-permission-issue

The issue is not here but this is the demonstration of the problem basically:

https://github.com/num-lock/node-opcua-permission-issue/blob/a223afd02ad4d428fe744cd342e3c9cabe191eae/index.js#L42-L45
  
**Please tell us about your environment:**

Latest version installed by yarn. Happens on all OSes.

  * (x)  my request is related to node-opcua acting as a OPCUA SERVER 

  * (x) I have installed node-opcua as a package (using yarn install)     
    
* **node-opcua version:**  : 0.5.0

* **Node:** 
   `node --version` = v10.14.1

I apologize in advance if I am using the API wrong and this should not be a bug at all.

**Comment by erossignon** [comment]
have you tried 
```
 node.userAccessLevel = opcua.makeAccessLevel("CurrentRead | CurrentWrite");
 node.accessLevel = opcua.makeAccessLevel("CurrentRead | CurrentWrite");
``` ?

**Comment by num-lock** [comment]
Thanks. It's working. I've updated my code. Should I do the same with `permissions`? What's the general convention? Use `bindVariable` only for `set`, `get`, `refreshFunc`, `timestamped_set` etc.? I was trying to get things done by the [documentation](http://node-opcua.github.io/api_doc/0.4.5/classes/UAVariable.html#methods) but it appears to be outdated?

**Comment by num-lock** [comment]
> Thanks. It's working.

Well, no. Well, writing values does now, but permissions are still not right. Now I can write values, but it appears everyone can.

https://github.com/num-lock/node-opcua-permission-issue/blob/0b9e824a4a7e71600addffab5774eef086fa37df/index.js#L53-L58

I tried to set `permissions` both directly on node and within the `bindVariable` function. Neither one gives the expected result. Without setting `CurrentWrite` on `userAccessLevel` no one can write. Same when I leave the access levels out completely and only define permissions.

**Comment by erossignon** [comment]
I forget to mention this:
```
node.setPermissions(somePermissions);
```

**Comment by num-lock** [comment]
Ok, now it's working as expeceted.

https://github.com/num-lock/node-opcua-permission-issue/blob/b4a3c667b0424b2b9a786633db92bd6c63ab0609/index.js#L72-L75

Is this documented somewhere? At least the current docs for 0.4.5 don't show it.
