### ISSUE TITLE
OPCUA Pubsub (Part 14)

### ISSUE THREAD

**Issue by jwende** [node-opcua/node-opcua#571]
Hi there,

thank you for the existing code. 
I wonder if you have any plans / ideas for implementing OPCUA pub/sub based on Part 14 of the specification?

Regards
Joerg

**Comment by erossignon** [comment]
Pub/Sub is implementation in node-opcua is currently being considered... I'll contact you about this.

**Comment by jwende** [comment]
Glad to provide any help - even if I‘m not a hard core coder 🤓
Cheers 
J.

**Comment by erossignon** [comment]
NodeOPCUA PubSub Module is available as a commercial module from Sterfive. 
An evaluation version has been published as a npm modules

https://www.npmjs.com/package/node-opcua-pubsub-server
https://www.npmjs.com/package/node-opcua-pubsub-client


```` 
npm install node-opcua-pubsub-server
````
See https://node-opcua.github.io/tutorial/2022/02/16/node-opcua-pubsub-episode1.html for more info

Full version, including source -code and npm modules are available for customers through [Sterfive](mailto:contact@sterfive.com) 's private repository

**Comment by JoelKrec** [comment]
Hi everyone,
it seems that there is some kind of problem of importing the EventEmitter inside both pubsub evaluation packages which prevents transpilling user written code from typescript to javascript with strict settings. Is TypeScript not supported or is that a mistake that will be fixed?

**Comment by gasiepgodoy** [comment]
Hello this link (https://node-opcua.github.io/tutorial/2022/02/16/node-opcua-pubsub-episode1.html) is broken. Any other source? Tks
