### ISSUE TITLE
No Connection to OPC UA server - Error: Unsupported security policy 

### ISSUE THREAD

**Issue by dev03954kd** [node-opcua/node-opcua#574]
**I'm submitting a ...**  (check one with "x")

 - ( x) bug report => search github for a similar issue or PR before submitting
 - ( ) feature request
 - ( ) support request => Please do not submit support request here, instead see use 
      - use [gitter](https://gitter.im/node-opcua/node-opcua) or [stackoverflow](https://stackoverflow.com/questions/tagged/node-opcua) for community support, or 
      - [contact Sterfive for commercial support](https://www.sterfive.com)

**Current behavior**
I have an OPC UA client based on your sample_client.js. I want to connect to an Softing DataFeed OPC UA server with user authentication by user/password. I´ve set the correct userIdentity settings to "createSession" but everytime the client fails to activate session - getting: `failure  Error:  Unsupported security Policy`

With an 3rd Party OPC UA Client I can connect with the same user/password settings to this server. 

**Expected behavior**
OPC UA client can connect to this server with user/password authentication settings

**Minimal reproduction of the problem with instructions**

  1.Setup OPCUA client with your sample_client.js
  2. Set endpointUrl to our OPC UA server
  3. Set 
`var userIdentity = {
            userName: "myuser",
            password: "mypassword"
        };`
 4. Pass this settings in createSession
`client.createSession(userIdentity, function(err,session) {
`
  
**What is the motivation / use case for changing the behavior?**
-

**Please tell us about your environment:**

  * ( x) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * ( )  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * (x ) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: PC (Dell)
  * OS version: Windows 10
    
    - ( x) Windows : version : Windows 10 Pro
    - ( ) Linux   : version : _________
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name: Softing DataFeed
     - Version: latest
     - Manufacturer/Software vendor: Softing DataFeed
     - link : https://data-intelligence.softing.com/de/produkte/opc-software-plattform/datafeed-opc-suite/
     
    
* **node-opcua version:**  :

* **Node:** 
   `node --version` =8.12.0

![screenshot_debug](https://user-images.githubusercontent.com/45762442/49784822-c1f97f00-fd1e-11e8-9197-c7a6845fb147.png)

**Comment by dev03954kd** [comment]
Simple question: How do I get this improvements into my enviroment? It´s still not available as package - right?

**Comment by erossignon** [comment]
It will be published in node-opcua@0.5.5 in a  moment, it is already available in node-opcua@2.0.0-alpha.8

**Comment by erossignon** [comment]
Important note:
Please be aware that this type of token policy imposed by the server (Softing DataFeed) you're trying to connect to is unsecure. username and password will be send unencrypted and in clear text over the tcp layer and will be easily hacked by anyone on the your network using a packet sniffer.

**Comment by dev03954kd** [comment]
Thanks for the quick reply.

**Comment by dev03954kd** [comment]
Etienne in node-opcua@2.0.0-alpha.8 `client.connect(endpointUrl,function (err) ` seems to be broken. I´m getting `TypeError: client.connect is not a function` on this. (No code change on my side)

**Comment by erossignon** [comment]
There are some breacking changes with node-opcua@2.0.0 due to the typescript adoption and a different isolation of the publich interface.

Client need to be created this way 
```
const client = opcua.OPCUAClient.create({});
``` 
instead of
```
const client = new opcua.OPCUAClient({});
```

**Comment by dev03954kd** [comment]
Thank you Etienne. Tried it with 0.5.5. Works fine. 
You can close this issue.

Btw. When will v.2.0.0 be released?

**Comment by lucarv** [comment]
Hello Etienne,

I am using 0.7.1 and trying to connect to a PLC protected by username and password.
When I create the session, I simply passed an object 
```
var userIdentity = {
	userName: pn.OpcNodes.ServerUsername,
	password: pn.OpcNodes.ServerPassword
};
```
It fails with:
```
 failure  Error: Cannot find ANONYMOUS user token policy in end point description
    at createAnonymousIdentityToken (/Users/lucarv/opc-ua/simple_opcua_publisher/node_modules/node-opcua-client/src/opcua_client.js:324:15)
```
Do I also need to pdefine the security options (mode and policy) when i create the client?
