### ISSUE TITLE
How to designate variables as read-only?

### ISSUE THREAD

**Issue by 2xaronl** [node-opcua/node-opcua#575]
I can't find any documentation showing how to specify that a variable added with namespace.addVariable() is read-only.  If I omit a "set" function in the variable definition then obviously nothing will happen if a client tries to perform a "set" but the variable still presents as read/write and not read-only to the client.  This causes some clients to adopt troublesome default settings when interacting with these points.

Is there an option to make a variable added with the addVariable (or similar) method read-only?

**Comment by erossignon** [comment]
try 
```
addVariable({
...
accessLevel: "CurrentRead"
...
});
```
https://github.com/node-opcua/node-opcua/blob/ad79724f1934568cb1d8f84327e862bd0bad3a2b/packages/node-opcua-end2end-test/test_helpers/hvac_system.js#L74
