### ISSUE TITLE
How is it possible to change a  status of a variable?

### ISSUE THREAD

**Issue by web-experiments** [node-opcua/node-opcua#579]
I try to change the Status of a Variable but nothing happens.

I use the Sample Server and change the following Lines:

 value: {
                get: function () {
                    return new opcua.Variant({dataType: opcua.DataType.Double, value: variable2 });
                },
                set: function (variant) {
                    variable2 = parseFloat(variant.value);
                    return opcua.StatusCodes.BadOutOfMemory;
                }
            }

The Status of the Variable is good and doesnt change after a write to BadOutOfMemory.

**Comment by erossignon** [comment]
I,f your trying to change the variable datavalue status from within a server try:
```
node.setValueFromSource({dataType:"Double", value: 0}, StatusCodes.BadOutOfMemory);
``` 
http://node-opcua.github.io/api_doc/0.5.4/classes/UAVariable.html#method_setValueFromSource
