### ISSUE TITLE
unable to browse all nodes using xml file in node-opcua server

### ISSUE THREAD

**Issue by samminen** [node-opcua/node-opcua#581]
in my node-opcua server, I am loading an XML file with nodes and references defined. When I run my node-opcua server and connect to it (using unitified OPC client), I can only see top level nodes. But when i browse my node in client, i see below error:
    
    
    10:26:24.696 | AddressSpaceModel  | Test1234                       | Browse on node 'ns=2;g=b37327c6-19ac-4655-bafe-b4064b48f01a' failed with error 'BadNodeIdUnknown'.
    10:26:24.696 | AddressSpaceModel  | Test1234                       | Browse on node 'ns=2;g=b37327c6-19ac-4655-bafe-b4064b48f01a' failed with error 'BadNodeIdUnknown'.
    10:41:55.117 | TypeCache          | Test1234                       | Reading type info of NodeId NS0|Numeric|84 succeeded
    10:41:55.117 | Attribute Plugin   | Test1234                       | Read attributes of node 'NS0|Numeric|84' succeeded [ret = Good].
    10:41:55.117 | TypeCache          | Test1234                       | Reading type info of NodeId NS0|Numeric|61 succeeded
    10:46:31.451 | AddressSpaceModel  | Test1234                       | Browse on node 'ns=2;g=b37327c6-19ac-4655-bafe-b4064b48f01a' failed with error 'BadNodeIdUnknown'.
    10:46:31.451 | AddressSpaceModel  | Test1234                       | Browse on node 'ns=2;g=b37327c6-19ac-4655-bafe-b4064b48f01a' failed with error 'BadNodeIdUnknown'.
    const server_options = {
        //certificateFile: server_certificate_file,
        //privateKeyFile: server_certificate_privatekey_file,
        port: port,
        nodeset_filename: [
    		path.join(rootFolder,"modeling/DDHubOPCUA.NodeSet2.xml"),
            standard_nodeset_file
            
        ]
        };
        const server = new OPCUAServer(server_options);
        const endpointUrl = server.endpoints[0].endpointDescriptions()  
        [0].endpointUrl;
    
        const hostname = require("os").hostname();
    
    
        console.log("  server PID          :".yellow, process.pid);
    
        server.on("post_initialize", function () {
        const addressSpace = server.engine.addressSpace;
        const rootFolder = addressSpace.findNode("RootFolder");
    
        });
    
         server.start(function (err) {
        if (err) {
            console.log(" Server failed to start ... exiting");
            process.exit(-3);
        }
        console.log("  server on port      :".yellow, 
         server.endpoints[0].port.toString().cyan);
        console.log("  endpointUrl         :".yellow, endpointUrl.cyan);
        console.log("\n  server now waiting for connections. CTRL+C to 
        stop".yellow);
        });
    
Unified client screenshot, where we can see the node brose issue:

![image](https://user-images.githubusercontent.com/44412902/50701356-2bfdff00-1013-11e9-9718-87e1bad0ba76.png)

XML file name I am using:  DDHubOPCUA.NodeSet2.xml

**Comment by erossignon** [comment]
It would be useful to have access to  DDHubOPCUA.NodeSet2.xml for investigation. 
If data is sensitive please send a mail to contact@sterfive.com

**Comment by samminen** [comment]
thank you Etienne for the update on this issue; It was very helpful and able to resolve my issue.

**Comment by erossignon** [comment]
Closing then
