### ISSUE TITLE
Cannot find nodeId

### ISSUE THREAD

**Issue by salomondeep** [node-opcua/node-opcua#582]
Hello,
I have a question regarding the OPC-UA server and client tutorials.
I am running both and the client successfully connects to the server, but cannot retrieve the value of a node existing in the namespace of the server. It return a null value with a description that says that it cannot find the desired nodeId.
![error opc](https://user-images.githubusercontent.com/28398984/50972190-d9728600-14dd-11e9-80f4-01bd6c0b49b0.png)

**Comment by erossignon** [comment]
The object with the corresponding nodeId doesn't exists on the server apparently.
(each server exposes a different set of object with different nodeId)
Can you disclose the source of your index.js file ?

**Comment by salomondeep** [comment]
The index.js file is the client opc-ua from the tutorial-> [https://github.com/node-opcua/node-opcua/blob/v0.4.5/documentation/sample_client.js](url)

I'm trying to read the other 2 variables besides the free_memory and I cannot. It just tells me that the node doesn't exist.

**Comment by salomondeep** [comment]
> The index.js file is the client opc-ua from the tutorial-> [https://github.com/node-opcua/node-opcua/blob/v0.4.5/documentation/sample_client.js](url)
> 
> I'm trying to read the other 2 variables besides the free_memory and I cannot. It just tells me that the node doesn't exist.

Solved it. It was an issue w/ the names of the variables. 
One other thing, the server closes because of a keepalive that does not receive. How do I solve this in order for the server not to close and run 'forever'.
![closed session](https://user-images.githubusercontent.com/28398984/51110302-1d240300-17f0-11e9-974a-9ab9777ab8ca.jpg)

**Comment by erossignon** [comment]
ok closing then
