### ISSUE TITLE
NamespaceIndex of nodeId in XML file are not translated in current NamespaceIndex of Server

### ISSUE THREAD

**Issue by msalafia** [node-opcua/node-opcua#603]
- (X) bug report 
 - ( ) feature request
 - ( ) support request

**Current behavior**
I am importing an InformationModel XML file built with UA Modeler an containing the following piece:
```xml
<UAVariable DataType="Identifier" ParentNodeId="ns=1;i=1006" NodeId="ns=1;i=6019" BrowseName="1:identification" AccessLevel="3">
        <DisplayName>identification</DisplayName>
        <References>
            <Reference ReferenceType="HasProperty" IsForward="false">ns=1;i=1006</Reference>
            <Reference ReferenceType="HasTypeDefinition">i=68</Reference>
        </References>
        <Value>
            <uax:ExtensionObject>
                <uax:TypeId>
                    <uax:Identifier>ns=1;i=5002</uax:Identifier>
                </uax:TypeId>
                <uax:Body>
                    <Identifier xmlns="http://dieei.unict.it/coreAAS/Types.xsd">
                        <id></id>
                        <idType>IRDI_0</idType>
                    </Identifier>
                </uax:Body>
            </uax:ExtensionObject>
        </Value>
</UAVariable>
```
The namespace of the Encoding Object NodeId inside the ExtensionObject VAlue is not normalized in the current server namespaceindex when imported. The piece `<uax:Identifier>ns=1;i=5002</uax:Identifier>` is imported looking for the wrong node id. Thus this value cannot be decoded when imported.

If i import my Information Model in the following way:
```
var xmlFiles = [
    opcua.standard_nodeset_file,
    opcua.coreaas.nodeset_file
];

var server = new opcua.OPCUAServer({
    nodeset_filename: xmlFiles,
});
```
This lead to the following error at the startup of the server:
![image](https://user-images.githubusercontent.com/11465611/53629622-4a950680-3c0e-11e9-9065-24158e7ff4e6.png)

This is an error because the right nodeid for the encoding object should be (in my example) `ns=1;i=5002`.

**Expected behavior**
I expect that during the parsing of an Xml information model the node id of ExtensionObject TypeId is normalized to the current Server namespaceindex for that information model, as for the other nodeIds.

**Comment by erossignon** [comment]
In fact the warning that you see during the loadnodeset indicates that the Extension object is not known by your server when the  xml file is loaded, therefore it cannot interpret and construct the extension object in   <uax:ExtensionObject>.

This currently a limitation and cannot be solved easily.
This would require that the http://dieei.unict.it/coreAAS/Types.xsd files get processed to extract the Extension object definition and create corresponding javascript classes and register them in the object constructor factory.

This topic is on  our roadmap but not engaged yet , looking for sponsors
