### ISSUE TITLE
Creating a OPC-UA server without encryption

### ISSUE THREAD

**Issue by zeekrey** [node-opcua/node-opcua#620]
**Hey there,**

first of all, thank you for your great open sourcen work!  👍  Just a short question: It seems like my windows group policies don't like self-signed certificates. Since this I would like to ask, if it is possible to create a server without encryption enabled. I searched the docs (http://node-opcua.github.io/api_doc/next/classes/node_opcua_server.opcuaserver.html) but couldn't find anything about it.

Cheers
**Christian**

**Comment by erossignon** [comment]
Hi @zeekrey ,
Could you be more specific ?
 How your windows group policies don't like self-signed certificate ?
Are you developing a client or a server ?
You can have unencrypted communication between a client and a server, however server need a certificate to proof its identity to the client and vice-versa.
there is a way to create certificate from a Certificate Authority if you prefer.
