### ISSUE TITLE
how to read a node form OPC UA server

### ISSUE THREAD

**Issue by kamishuki76** [node-opcua/node-opcua#623]
I have an problem with this OPC UA from PLCSIM_Advanced
![image](https://user-images.githubusercontent.com/50210154/57088899-77a88700-6d2d-11e9-910d-605c41e39fea.png)
I need to read the "Tag_1". So I use readVariableValue and Read. 
![image](https://user-images.githubusercontent.com/50210154/57088684-036de380-6d2d-11e9-9dc5-bb13476c41a2.png)
But this is my result. StatusCode: BadNodeIdUnknown.
![image](https://user-images.githubusercontent.com/50210154/57088769-2e583780-6d2d-11e9-8d1d-359979ba7d25.png)
Although I can read Variable from Object/Server (ns=1), I can't read Variable from Object/PLC_1(ns=3).
May I write wrong NodeId's syntax or I forgot write something??? Can you help me solve this problem. I'm a beginner. Thank you

**Comment by erossignon** [comment]
may be try ```"ns=3;s=\"Tag_1\""```  instead of ```ns=3;s=Tag_1``` , just guessing
