### ISSUE TITLE
Old Opc.Ua.NodeSet2.xml nodeset file in node-opcua version 0.7.*

### ISSUE THREAD

**Issue by msalafia** [node-opcua/node-opcua#624]
It seems that the standard nodeset provided from the stable version 0.7.2 still provide the old version of the Opc.Ua.NodeSet2.xml file without including, for example, new elements from new OPC UA Amendament. 

But i have noticed that the new nodeset is provided for the 2.0.0-alpha version. Is it possible update the 0.7.2 version since it is the stable version available on npm?

**Comment by erossignon** [comment]
Please note that version @2.0.0 is now out and superseed 0.7.2

**Comment by msalafia** [comment]
Isn't it an alpha version?

**Comment by erossignon** [comment]
not anymore !

**Comment by msalafia** [comment]
Very nice, i am closing this issue. Thank you @erossignon
