### ISSUE TITLE
Unexpected data type comes with event change notification callback

### ISSUE THREAD

**Issue by hdnn** [node-opcua/node-opcua#626]
**I'm submitting a ...**  (check one with "x")
 - (x) bug report => search github for a similar issue or PR before submitting

**Current behavior**
Event notification callback(from `ClientMonitoredItem `object) comes with argument that Array of variants, but in node-opcua.d.ts this argument declared as `DataValue` type/

**Minimal reproduction of the problem with instructions**
1) Use node-opcua in TypeScript
2) Subscribe to event notification:
```
const fields = ["EventType","SourceName", "EventId", "ReceiveTime","Severity","Message"];
...
this.monitoredItem  = this.opcuaSubscription.monitor(readValue, requestedParameters, TimestampsToReturn.Both);   
  this.monitoredItem.on("changed", function (eventData) { ... }
```
3) in `node-opcua.d.ts` onChanged event declared as `on(event: "changed", eventHandler: (dataValue: DataValue)  => void): this;`
4) So, in our callback we expect that `eventData` have `DataValue` type
5) `eventData `field is Array of Variants
  
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

  * (x) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * ( )  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * (x) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: PC
  * OS version: Win10 Pro
    
    - (x) Windows : version : 10.0.17763.503
    - ( ) Linux   : version : _________
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name: OPC UA ANSI C Demo Server
     - Version: 1.8.3
     - Manufacturer/Software vendor: Unified Automation
     - link : https://www.unified-automation.com/downloads/opc-ua-servers/file/download/details/opc-ua-ansi-c-demo-server-v183-windows.html
     
    
* **node-opcua version:**  : v0.7.2

* **Node:** 
   `node --version` = v10.15.0

![1](https://user-images.githubusercontent.com/8512124/58617021-bcd9bd80-82c7-11e9-9f7a-21b322204b7c.jpg)
![2](https://user-images.githubusercontent.com/8512124/58617022-bd725400-82c7-11e9-980b-28438741b1fd.jpg)

**Comment by erossignon** [comment]
now  `on "change" ` event is defined with  2 overloading types:
```typescript
interface ClientWebMonitoredItemBase {

    on(eventName: "changed", eventHanlder: (dataValue: DataValue) => void): void ;
    on(eventName: "changed", eventHanlder: (dataValue: Variant[]) => void): void ;
}

````
