### ISSUE TITLE
Best way to create 100s of tags

### ISSUE THREAD

**Issue by kallegit1950** [node-opcua/node-opcua#631]
Hello,

I am having an issue to create hundreds of nodes, lets say I have 20 devices and each has 20 tags, that would make in total 400 tags. I could now write  for each device

        var device1 = addressSpace.getOwnNamespace().addObject({
            organizedBy: addressSpace.rootFolder.objects,
            browseName: "Device1"
        });

and for each tag

        var pressure1= addressSpace.getOwnNamespace().addVariable({
            componentOf: device1,
			nodeId: "ns=1;s=Pressure",
            browseName: "Pressure",
            dataType: "Double",
            value: {
                get: function () {
                    return new opcua.Variant({dataType: opcua.DataType.Double, value: pressureValue[0] });
                }
            }
        });

I know that this would work, but maintaing these thousands lines of code **in one file**  is probably not what someone wants to do. I thought use for each device an own js file and using require statement. But the issue here is that I am not sure if I get in trouble if I have to return all the tags in an array and secondly pressureValue[0] is for example a global variable I need, but that lives of course only in one of the js files. 

What would be the best approach?

Thanks!

**Comment by erossignon** [comment]
```for loop``` s may help.
