### ISSUE TITLE
0.7.2 to 2.0 caused a few undocumented hiccups

### ISSUE THREAD

**Issue by ajcanterbury** [node-opcua/node-opcua#633]
**I'm submitting a ...**  (check one with "x")

 - (x) bug report => search github for a similar issue or PR before submitting
 - ( ) feature request
 - ( ) support request => Please do not submit support request here, instead see use 
      - use [gitter](https://gitter.im/node-opcua/node-opcua) or [stackoverflow](https://stackoverflow.com/questions/tagged/node-opcua) for community support, or 
      - [contact Sterfive for commercial support](https://www.sterfive.com)

**Current behavior**
Upgraded from 0.7.2 to 2.0 on a fairly large application, had some breaking issues that were not documented in the "2.0.0-breaking-changes" wiki.

**Expected behavior**
Changes to be documented (maybe I'm missing a doc link).

**Minimal reproduction of the problem with instructions**
I'll list the changes necessary for the upgrade discovered here:
  1. opcua-server no longer accepting `resourcePath` beginning without `/`, looks to be due to the assert on line 329 in `opcua-server/source/server_end_point.ts`.
  2. Security Modes are no longer all caps (e.q. "NONE" is now "None").
  3. Session credentials no longer are ignored if username and password are blank strings (must be nulled).
  4. Read object no longer has dataType and arrayType `key` property (they are now just an index).
  5. `nodeClass` on browse object is now just an index.
  6. `subscription.isActive` is no longer a function (now it's a prop).
  7. From the [breaking-changes wiki](https://github.com/node-opcua/node-opcua/wiki/2.0.0-breaking-changes) MonitoredItems, the "now variant 2 async/await" doesn't work for me without a callback function which is strange. 

**Please tell us about your environment:**
OS X and Linux

  * ( ) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * ( )  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * (x) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: _____
  * OS version: _____
    
    - ( ) Windows : version : _________
    - (x) Linux   : version : Ubuntu 16.04, Ubuntu 18.04
    - (x) MacOs   : version : 10.14.5
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name: Test node-opcua server and various simulators
     - Version:_________
     - Manufacturer/Software vendor:_________
     - link : https://
     
    
* **node-opcua version:**  :
2.0.0

* **Node:** 
   `node --version` = 10.15.3

**Comment by erossignon** [comment]
Thank you, wiki page updated .. do not hesitate to share your other findings by directly editing the page 
https://github.com/node-opcua/node-opcua/wiki/2.0.0-breaking-changes
