### ISSUE TITLE
bulksubscription feature for Node OPC UA V2.0

### ISSUE THREAD

**Issue by samminen** [node-opcua/node-opcua#639]
Hello,
    I am eagerly waiting for bulk node IDs subscription using Node OPC UA and want to receive values at one go for all the subscribed node Ids. But as per 2.0 documentation, I do not see this feature added. 

i.e I should be able to subscribe to multiple node ids in one subscription and want to receive values for all those node ids as single message from onMonitor() .

Do  we have this feature in V2.0 node opc SDK ?

**Comment by erossignon** [comment]
Would you consider sponsoring this feature ? please contact@sterfive.com or myself  to discuss this matter;
