### ISSUE TITLE
Sample simple_client / simple_server. Client crash when executed 2 or more times (while server is still running).

### ISSUE THREAD

**Issue by EtienneHelfer** [node-opcua/node-opcua#642]
**I'm submitting a ...**  (check one with "x")

 - ( x) bug report => search github for a similar issue or PR before submitting
 - ( ) feature request
 - ( ) support request => Please do not submit support request here, instead see use 
      - use [gitter](https://gitter.im/node-opcua/node-opcua) or [stackoverflow](https://stackoverflow.com/questions/tagged/node-opcua) for community support, or 
      - [contact Sterfive for commercial support](https://www.sterfive.com)

**Current behavior**

Was testing in the samples the simple_client and simple_server on the same machine.
It works the first time the client is run. If the client is executed again, then sometimes it crashes with an error during the SIMULATE CONNECTION BREAK. 

Below the simple_client crash:
![image](https://user-images.githubusercontent.com/35633370/61045793-db10fe00-a3db-11e9-97fd-e564e9b00eab.png)

**Expected behavior**

The simple_client execution should be consitent, even if the simple_server has already served a simple_client session before.
**Minimal reproduction of the problem with instructions**

  1. run simple_server
  2. run simple_client
  3. rerun simple_client until crash occurs (sometimes it works, sometimes it crashes)
  ...
  
**What is the motivation / use case for changing the behavior?**

It is basic samples for beginners, it should work reliably. 

**Please tell us about your environment:**

  * ( x) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * ( x)  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * (x ) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: _____
  * OS version: _____
    
    - ( ) Windows : version : _________
    - ( ) Linux   : version : _________
    - ( ) MacOs   : version : _________
    - (x ) Raspbian: version : _________
    - ( ) Other   : specify :
  
* **node-opcua version:**  :

installed today from npm install

* **Node:** 
   `node --version` =8.15.1

**Comment by erossignon** [comment]
one important piece of information is missing, please specify : node-opcua version: :
