### ISSUE TITLE
unable to get node node values from opcua server using node js

### ISSUE THREAD

**Issue by kumarkumaresh** [node-opcua/node-opcua#652]
i am connected to opcua server using node js code.
i get node ids perfectly using UA Expert tool but when i am trying to get node values from node js code it throws invalid node id error.
ua expert

![uaexpert](https://user-images.githubusercontent.com/26242398/62358993-8b81a600-b533-11e9-9f5e-cc8713ee5212.PNG)

code
===
![code](https://user-images.githubusercontent.com/26242398/62359066-b0761900-b533-11e9-8d48-34343c470c85.PNG)

error
====
![error](https://user-images.githubusercontent.com/26242398/62359079-ba981780-b533-11e9-9020-8f88832b31e8.PNG)

**Comment by erossignon** [comment]
it looks like the nodeId you want to access are string based... but they also contain quotes (")

I would replace 
`"ns=3;s=SomeText"` with  "ns=3;s=\"SomeText\""`

**Comment by erossignon** [comment]
duplicates #623

**Comment by kumarkumaresh** [comment]
@erossignon Thanks for your reply, yes it worked.
thanks a lot again.
