### ISSUE TITLE
crawler is not reading all the elements of the array if the array size is greater than 100'

### ISSUE THREAD

**Issue by Nandish-Reddy** [node-opcua/node-opcua#655]
**Current behavior**
when i use node crawler or opcua commander to browse array data types with size greater than 100 from opcua server.
An interesting observation,
while i browse a node arr[0..199] using crawler, it browses from 100th element, 101,102 ...199.
If i use opcua commander too, it browses only till 99. i.e. from 0,1,2 .. 99.
If i use UAExpert client it browses everything from 0.. 199.

**Expected behavior**
should successfully browse all the array elements

**Minimal reproduction of the problem with instructions**
create a array of size greater than 100 or greater than 1000 in opcua server,
try using node crawler to browse the nodes.
 
**Please tell us about your environment:**

  (*) my request is related to node-opcua acting as a  OPCUA CLIENT 

   I have installed node-opcua as a package ( using npm install )
   I am using an application that uses node-opcua 
  
     
    - ( ) Linux   : version : debian

   * Description of the other OPCUA system I am trying to connect to:
     
    
* **Node:** 
   `node --version` = 12.13.1

**Comment by erossignon** [comment]
Can you descrive hte other OPCUA system you are trying to connect to ?
May this server is not supporting large browse and read Request ... and is not exposing its limit the way it should.

I would suggest that you limit the nodeCrawler 


```
        const crawler = new NodeCrawler(session);
        crawler.maxNodesPerBrowse = 50;
        crawler.maxNodesPerRead = 50;
``

**Comment by Nandish-Reddy** [comment]
Hi Etienne,

Thanks for looking into this.

Tried the above configurations but it did not help us. 

Python opcua gui client and UAexpert both were able to browse all the elements of large array.

The data type field for array node is not properly set,which is undefined.

while i browse a node arr[0..199] using crawler, it browses from 100th element, 101,102 ...199.

One more observation, In the packets seen in wireshark , i am able to see all the array elements data. which has reached node opcua client from opcua server system.

I am using UA opcua server.

**Comment by erossignon** [comment]
Please provide source code that you are using to access  the server so issue can be reproduced

**Comment by jagadishpb89** [comment]
Hi Etienne, 

Thanks for quick reply on this. I was also looking for this.

I am also facing the same issue for even scalar data types. When I have scalar data type elements with names IntVar1, IntVar2, IntVar3,...........IntVar1000 in opcua server, it is printing all the elements starting from IntVar101 to IntVar1000. Missed elements from IntVar1 to IntVar100.

We are not getting 'browsed' events for remaining elements.

If I have only 98 elements from IntVar1 to IntVar97, then node-crawler browses everything, we getall the 'browsed' events. 

Please find below the crawler code.
node-opcua version: 2.0.0

              var opcua = require("node-opcua");
               var crawler = new opcua.NodeCrawler(the_session);
               var nodeId="ObjectsFolder"
               console.log("Browsing data in the server");
               crawler.read(nodeId, function (err, obj) {
                  if (err) {
                     console.log("Failed to Read Data");
                  }
                  else {
                     console.log("data read from PLC is Successful");
                  }
                  cb3(err);
               });
               crawler.on("browsed", function (element) {
               }


You can add some scalar data type elements in any opcua server, try to browse as per above code. You may reproduce the issue.

Thanks

**Comment by erossignon** [comment]
the code looks incomplete. could you provide an complete standalone example  ?

**Comment by jagadishpb89** [comment]
Here is complete code.

async.series([
   function (cb3) {

      client.connect(endpointUrl, function (err) {

         if (err) {
            console.log(" cannot connect to endpoint :", endpointUrl);
         } else {
            console.log("connected !");
         }
         cb3(err);

      });

   },
   function (cb3) {
      client.createSession(function (err, session) {
         if (err) {
            console.log("Failed to Create the Browse Session");
         }
         else {
            console.log("Browse Session Creates Session Successfully!");
            the_session = session;
         }
         cb3(err);
      });

   },
   function (cb3) {
      var crawler = new opcua.NodeCrawler(the_session);
      var nodeId = "ns=3;i=85"
      console.log("Browsing Data in the server");
      crawler.read(nodeId, function (err, obj) {
         if (err) {
            console.log("Failed to Read Data");
         }
         else {
            console.log("Data read from PLC is Successful");
         }
         cb3(err);
      });

      crawler.on("browsed", function (element) {
         console.log("element name:" + element.browseName.name);
      });
   }
],
   function (err) {
      if (err) {
         console.log("Failure in opcua browsing!", err);
         callback(err)
      } else {
         console.log("No Error :)");
         callback()
      }
      console.log("disconnected");
      client.disconnect(function () { });
   })

**Comment by erossignon** [comment]
@jagadishpb89 running your sample on the Unified Automation Ansi C Server provide the following result on my end . as you can see all node of the Mass Variable foder are properly extracted.

see this [gist](https://gist.github.com/erossignon/84e9ec090909da037401d4c29b51b85b)

what is the result on your end ? ( please provide a full gist)

**Comment by erossignon** [comment]
I have modified  NodeCrawler so that when  `crawler.maxNodesPerBrowse` or crawler.maxNodesPerRead` is set,  the value serves as a minimum that can restrict the value provided by the server
```javascript
const crawler = new NodeCrawler(session);
crawler.maxNodesPerBrowse = 50;
crawler.maxNodesPerRead = 50;
```
this is available in node-opcua@2.1.3

**Comment by jagadishpb89** [comment]
We have tried with above configurations. Unfortunately we still could not get all the nodes.

Looked into the node crawler code, applied some debug logs there. I did print the browse results in browse function and browseNext functions .

My opcua server had 600 elements , first 100 references of a node  were getting printed as part of browse() response itself. Next 500 references were being printed as part of browseNext()'s response. where each response were having 100 elements , i got 5 such browseNext's responses with continuationPoints results with 100 elements each.

Now , I am missing browse emit events for the elements (first 100) which browse() api has returned.

We are still debugging the code, Thanks a lot for the update.

**Comment by Nandish-Reddy** [comment]
> We have tried with above configurations. Unfortunately we still could not get all the nodes.
> 
> Looked into the node crawler code, applied some debug logs there. I did print the browse results in browse function and browseNext functions .
> 
> My opcua server had 600 elements , first 100 references of a node were getting printed as part of browse() response itself. Next 500 references were being printed as part of browseNext()'s response. where each response were having 100 elements , i got 5 such browseNext's responses with continuationPoints results with 100 elements each.
> 
> Now , I am missing browse emit events for the elements (first 100) which browse() api has returned.
> 
> We are still debugging the code, Thanks a lot for the update.

 Facing similar issue.In some opcua servers, i see first 1000 elements are skipped  if elements are more than 1000. If elements are less than 1000 it prints all the elements.

**Comment by erossignon** [comment]
@Nandish-Reddy ; there is nothing we can do with statement like "with some opcua servers" , as we need to be able to reproduce the problem for investigation.

please answer the question asked above, and that are left unanswered in your reply so far or not accurately enough:

  -Can you describe the other OPCUA system you are trying to connect to ?
    OPCUA server vendor, version number, etc ...

  - Please provide source code of the client program (js or ts + package.json etc ) that you are using to access the server so issue can be reproduced. Please provide minimal , yet complete functional code

Also I am adding 2 more questions for you:

   - have you try upgrading to node-opcua@2.1.3
  - what is the output of the [sample program I have provided in this gist](https://gist.github.com/erossignon/84e9ec090909da037401d4c29b51b85b)

**Comment by erossignon** [comment]
OK.. I can now reproduce it, it happens when the server limits the number of browseResult and provides a continuation point ...

**Comment by erossignon** [comment]
should be fixed now in version node-opcua@2.1.5 , @Nandish-Reddy , @jagadishpb89 please confirm.

**Comment by jagadishpb89** [comment]
Hi Etienne,

Thanks a lot for your great help. Sorry for late reply.
I was debugging the issue, thinking it is something to do with synchronous read and browse operations.

I tried with version node-opcua@2.1.5. It works. You can close the issue.

**Comment by binaryPUNCH** [comment]
´How do you guys create NodeCrawlerClientSession to begin with?
