### ISSUE TITLE
ERROR: channel.secureChannelId !== channel.secureChannelId

### ISSUE THREAD

**Issue by pelis** [node-opcua/node-opcua#656]
- (?) bug report => search github for a similar issue or PR before submitting
 - ( ) feature request
 - ( ) support request 

**Current behavior**
This seems to be similar to issue 110…
I have implemented an OPC-UA Server.
A foreign client (MES System) does access that server (no write, just read or subscribe)
From time to time I get the following errors on the console (opcua_server.js):
ERROR: channel.secureChannelId !== channel.secureChannelId
Before that error I get from server_engine.js:
Server: closing SESSION <...> because of timeout
server_engine.js keeps the subscription:
engine.closeSession(session.authenticationToken, /*deleteSubscription=*/false, /* reason =*/"Timeout");
- Is there any suggestions how the server should behave in such situations?
- What happens anyways? Is that a client only question how to react in that case?
- Is there a good “clean” way how to add an event handler for this timeout case?

**Expected behavior**
probably close session and subscription - not sure...

**Minimal reproduction of the problem with instructions**
cannot reporduce it

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
- windows 10
- nodejs 8.11.2
- node-opcua 0.7.2

  * ( ) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * (x )  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * ( x) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( x) node-red
       - ( ) other : please specify 
        
  * Device: _____
  * OS version: _____
    
    - (x ) Windows : version : ___10______
    - ( ) Linux   : version : _________
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name:_________
     - Version:_________
     - Manufacturer/Software vendor:_________
     - link : https://
     
    
* **node-opcua version:**  : 0.7.2

* **Node:** 
   `node --version` = 8.11.2

**Comment by erossignon** [comment]
A wireshark dump would be needed to investigate what's going on ... 
Please contact@sterfive.com for support.
