### ISSUE TITLE
Nasty stack trace on wrong nodeId format

### ISSUE THREAD

**Issue by sanderd17** [node-opcua/node-opcua#688]
**I'm submitting a ...**  (check one with "x")

 - (x) bug report => I searched github before submitting this
 - ( ) feature request
 - ( ) support request

**Current behavior**
When subscribing to a nodeId with a wrong format (f.e as just a string without the "ns=1;s=*" part), it shuts down Node with a stacktrace that's hard to read (doesn't trace back to the code using the library). It also seems impossible to catch this error as a library user, as it traces back directly to the root of the event loop.

**Expected behavior**
The error should be thrown earlier, when actually creating the monitoredItem. That way, the stack would trace back to the correct line, and it's possible to catch it as a library user. It would also make it clearer it's an issue with the configuration of the monitoredItem (of which the nodeId is one part).

**Minimal reproduction of the problem with instructions**
I started from the example server and client, and just let it subscribe to the nodeId "free_memory" instead of "ns=1;s=free_memory" from the example server. And it illustrates the crash.

In the example, the first subscription is a valid one, and works without issues. The second subscription (added after 5 seconds) shows the nasty behaviour.

This is my console output:
```
$ node --experimental-modules test_client.js 
(node:17565) ExperimentalWarning: The ESM module loader is experimental.
connected !
session created !
subscription started for 2 seconds - subscriptionId= 149197
 value has changed :  Variant(Scalar<Double>, value: 64.43247621055508)
 value has changed :  Variant(Scalar<Double>, value: 64.43092817044757)
 value has changed :  Variant(Scalar<Double>, value: 64.82599783470961)
 value has changed :  Variant(Scalar<Double>, value: 64.82722643796954)
 value has changed :  Variant(Scalar<Double>, value: 64.82882362220744)
 value has changed :  Variant(Scalar<Double>, value: 64.82727558209994)
 value has changed :  Variant(Scalar<Double>, value: 64.82413035775453)
 value has changed :  Variant(Scalar<Double>, value: 64.84889899947464)
 value has changed :  Variant(Scalar<Double>, value: 64.84735095936715)
 value has changed :  Variant(Scalar<Double>, value: 64.866517170222)
.../node_modules/node-opcua-assert/dist/index.js:19
        throw err;
        ^

Error
    at Object.assert (.../node_modules/node-opcua-assert/dist/index.js:10:21)
    at nodeID_encodingByte (.../node_modules/node-opcua-basic-types/dist/nodeid.js:23:25)
    at Object.encodeNodeId (.../node_modules/node-opcua-basic-types/dist/nodeid.js:104:24)
    at ReadValueId.encode (.../node_modules/node-opcua-types/dist/_generated_opcua_types.js:14220:34)
    at MonitoredItemCreateRequest.encode (.../node_modules/node-opcua-types/dist/_generated_opcua_types.js:17141:28)
    at .../node_modules/node-opcua-types/dist/_generated_opcua_types.js:17308:98
    at Object.encodeArray (.../node_modules/node-opcua-basic-types/dist/array.js:22:9)
    at CreateMonitoredItemsRequest.encode (.../node_modules/node-opcua-types/dist/_generated_opcua_types.js:17308:34)
    at CreateMonitoredItemsRequest.binaryStoreSize (.../node-opcua-factory/dist/factories_baseobject.js:298:14)
    at MessageChunker.chunkSecureMessage (.../node_modules/node-opcua-secure-channel/dist/source/message_chunker.js:46:33)
```

gist:
server: just the default example server: https://github.com/node-opcua/node-opcua/blob/v2.1.3/documentation/sample_server.js
client: The client example is plain node js, but with `--experimental-modules` enabled to activate the import syntax: https://gist.github.com/sanderd17/a38f1e22bc8b1a188355c9df0e807a25
  
**What is the motivation / use case for changing the behavior?**
Error should be catchable and readable by the library users, so should happen when the stack trace points to library calls.

**Please tell us about your environment:**
  * (x) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * ( )  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * (x) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
        
  * OS version: Arch Linux (up-to-date)
    
* **node-opcua version:**  : 2.1.9

* **Node:** 
   `node --version` = v12.11.1

**Comment by erossignon** [comment]
@sanderd17  please verify that node-opcua@2.2.0 now fixes this issue.
