### ISSUE TITLE
Snyk cannot import a project containing node-opcua semver dependency

### ISSUE THREAD

**Issue by PietroGreco** [node-opcua/node-opcua#692]
**I'm submitting a ...**

 - (x ) bug report => search github for a similar issue or PR before submitting
 - ( ) feature request
 - ( ) support request => Please do not submit support request here, instead see use 
      - use [gitter](https://gitter.im/node-opcua/node-opcua) or [stackoverflow](https://stackoverflow.com/questions/tagged/node-opcua) for community support, or 
      - [contact Sterfive for commercial support](https://www.sterfive.com) (contact (@) sterfive.com )

**Current behavior**
A project containing the node-opcua library installed using `npm install` cannot be imported by Snyk.

If the node-opcua library is included as **Git URL** dependency, Snyk can import the project.

**Expected behavior**
Snyk should be able to import a project containing the node-opcua "version-style" dependency 

**Minimal reproduction of the problem with instructions**

  1. Create a minimal npm project using `npm init`
  2. Add node-opcua dependency using `npm install node-opcua`
  3. Push the project to GitHub
  4. Try to import this project from Snyk Dashboard 

**Please tell us about your environment:**

  * ( ) I have installed node-opcua from source ( using git clone)
  * (x ) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
        
 - (x) Linux
   

     
    
* **node-opcua version:**  : 2.1.8 and 2.2.0

* **Node:** 
   `node --version` = v10.16.1

**Comment by erossignon** [comment]
Why not ask Snyk Dashboard ?
