### ISSUE TITLE
checkBit method returns false if multiple bits are set

### ISSUE THREAD

**Issue by demike** [node-opcua/node-opcua#694]
https://github.com/node-opcua/node-opcua/blob/e40ec665aa8d36e38ff6baaadd484ee0cffb971d/packages/node-opcua-status-code/source/opcua_status_code.ts#L166

if multiple bits are set this check method will always fail if you test only for one.

should this be:
`return (this.value  & mask) !== 0 ;`
?

**Comment by erossignon** [comment]
OK then we need a checkBits (with a s) method

**Comment by erossignon** [comment]
I recommend that you do 
    
    const condition = status.checkBit(MASK1) || status.checkBit(MASK2)

**Comment by demike** [comment]
You are right. Closing this issue!
