### ISSUE TITLE
Sample Client monitoredItem.on error

### ISSUE THREAD

**Issue by nicolacalgaro89** [node-opcua/node-opcua#701]
**I'm submitting a ...**  (check one with "x")

 - (x) bug report => search github for a similar issue or PR before submitting
 - ( ) feature request
 - ( ) support request => Please do not submit support request here, instead see use 
      - use [gitter](https://gitter.im/node-opcua/node-opcua) or [stackoverflow](https://stackoverflow.com/questions/tagged/node-opcua) for community support, or 
      - [contact Sterfive for commercial support](https://www.sterfive.com) (contact (@) sterfive.com )

**Current behavior**

I follow both "documentation/creating_a_server.md" and "documentation/creating_a_client_callback.md" tutorials using "documentation/sample_server.js" and "documentation/sample_client.js" scripts directly from this repository without any changes. After building up the server I launch also the client and I see that all steps works fine (create session, readings, ...), also subscription seems to works well but just after the creation of subscription it appens the error listed below: 
```
MBP-di-Nicola-001:OPCUA-sample-client nicola$ node sample_client.js
connected !
Browsing rootfolder: 
Objects ns=0;i=85
Types ns=0;i=86
Views ns=0;i=87
 free mem % =  DataValue:
   value:           Variant(Scalar<Double>, value: 28.420090675354004)
   statusCode:      Good (0x00000)
   serverTimestamp: null
   sourceTimestamp: null
 free mem % =  DataValue:
   value:           Variant(Scalar<Double>, value: 28.420090675354004)
   statusCode:      Good (0x00000)
   serverTimestamp: 2019-11-14T19:41:10.939Z $ 301.976.000
   sourceTimestamp: 2019-11-14T19:41:10.939Z $ 301.976.000
-------------------------------------
/Users/nicola/Desktop/Repos/OPCUA-sample-client/sample_client.js:117
       monitoredItem.on("changed", function(dataValue) {
                     ^

TypeError: monitoredItem.on is not a function
    at /Users/nicola/Desktop/Repos/OPCUA-sample-client/sample_client.js:117:22

```
**Expected behavior**
I expect that sample_client.js stays up and logs subscription items data changes.

**Minimal reproduction of the problem with instructions**

  1. follow "documentation/creating_a_server.md" using "documentation/sample_server.js" script.
  2. follow "documentation/creating_a_client_callback.md" using "documentation/sample_client.js" script.
  3. run sample_server.js and then sample_client.js.
  ...

gist:

  
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

  * (x) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * ( )  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * (x) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: _____
  * OS version: _____
    
    - ( ) Windows : version : _________
    - ( ) Linux   : version : _________
    - (x) MacOs   : version : 10.13.6 (17G65)
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name:_________
     - Version:_________
     - Manufacturer/Software vendor:_________
     - link : https://
     
    
* **node-opcua version:**  : 
"node-opcua-client": {
      "version": "2.2.0",
      "resolved": "https://registry.npmjs.org/node-opcua-client/-/node-opcua-client-2.2.0.tgz",
      "integrity": "sha512-snHC9qQBnKFhTivxnnC2Jx+7A/MtmN6hj5ecxY8veq7eCMDCoQ9G0PzeE3XZTRCcmLnPOd1LE5LZPphcwZq/eg=="

* **Node:** 
   `node --version` = v10.13.0

**Comment by erossignon** [comment]
Doc issue ... fixed now
