### ISSUE TITLE
Update OPC variable value runtime

### ISSUE THREAD

**Issue by AnsMumtaz-IMS** [node-opcua/node-opcua#708]
This my function which i am using to write new values for OPC DA server variable. Actually, variable is MeterCount which shows the length in meters and i am making a button to reset its value(means 0). I want to write the new value from WPF application(VS 2015) but its not working... can anyone please help me with this. Reading the values is not problem its working perfectly but writing is not working.

   private void MeterReset_Click(object sender, RoutedEventArgs e)
    {
        try
        {
            object[] opcvalues = { true , "0.00 m" };   
            HRESULT[] rs = readGroup.Write(readGroup.Items, opcvalues);
            readGroup.ValuesChanged += OnGroupValuesChanged;
            readGroup.UpdateRate = TimeSpan.FromMilliseconds(100);
        }
        catch (Exception ex)
        {
            MessageBox.Show(ex.Message);
        }
    }

**Comment by erossignon** [comment]
Oops, I am not sure this is the right forum, node-opcua is a typescript/javascript stack and your question seems to be related to a stack in CSharp.
