### ISSUE TITLE
Assignment to constant variable when running monitoring_home_temperature_with_a_raspberry.md

### ISSUE THREAD

**Issue by mellerbeck** [node-opcua/node-opcua#715]
**I'm submitting a ...**  (check one with "x")

- (X) bug report => search github for a similar issue or PR before submitting
 - ( ) feature request
 - ( ) support request => Please do not submit support request here, instead see use 
      - use [gitter](https://gitter.im/node-opcua/node-opcua) or [stackoverflow](https://stackoverflow.com/questions/tagged/node-opcua) for community support, or 
      - [contact Sterfive for commercial support](https://www.sterfive.com) (contact (@) sterfive.com )

**Current behavior**
Following this quick guide
https://github.com/node-opcua/node-opcua/blob/master/documentation/monitoring_home_temperature_with_a_raspberry.md

created homeserver

ran npm init  (I accepted the defaults, don't know if I should do differently?)

I ran npm install node-opcua --unsafe-perms (to resolve cannot find module 'node-opcua')

created index.js with code from tutorial

ran node  index.js

error TypeError: Assignment to constant variable.
    at /home/pi/homeserver/index.js:10:15
    at _fulfilled (/home/pi/homeserver/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/home/pi/homeserver/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/home/pi/homeserver/node_modules/q/q.js:816:13)
    at /home/pi/homeserver/node_modules/q/q.js:624:44
    at runSingle (/home/pi/homeserver/node_modules/q/q.js:137:13)
    at flush (/home/pi/homeserver/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Expected behavior**

Expose the temperature of the connected temperature sensor

I have tested cat w1_slave and am able to see the data.

**Minimal reproduction of the problem with instructions**

  1. ________________
  2. ________________
  3. ________________
  ...

gist:

  
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

  * ( ) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * (X)  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * (X) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: _____
  * OS version: _____
    
    - ( ) Windows : version : _________
    - ( ) Linux   : version : _________
    - ( ) MacOs   : version : _________
    - (X) Raspbian: version : _________
    - ( ) Other   : specify :
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name:_________
     - Version:_________
     - Manufacturer/Software vendor:_________
     - link : https://
     
    
* **node-opcua version:**  :

* **Node:** 
   `node --version` = v8.16.1

**Comment by zacherybrown** [comment]
> **I'm submitting a ...** (check one with "x")
> 
> * (X) bug report => search github for a similar issue or PR before submitting
> * ( ) feature request
> * ( ) support request => Please do not submit support request here, instead see use
>   
>   * use [gitter](https://gitter.im/node-opcua/node-opcua) or [stackoverflow](https://stackoverflow.com/questions/tagged/node-opcua) for community support, or
>   * [contact Sterfive for commercial support](https://www.sterfive.com) (contact (@) sterfive.com )
> 
> **Current behavior** Following this quick guide https://github.com/node-opcua/node-opcua/blob/master/documentation/monitoring_home_temperature_with_a_raspberry.md
> 
> created homeserver
> 
> ran npm init (I accepted the defaults, don't know if I should do differently?)
> 
> I ran npm install node-opcua --unsafe-perms (to resolve cannot find module 'node-opcua')
> 
> created index.js with code from tutorial
> 
> ran node index.js
> 
> error TypeError: Assignment to constant variable. at /home/pi/homeserver/index.js:10:15 at _fulfilled (/home/pi/homeserver/node_modules/q/q.js:854:54) at self.promiseDispatch.done (/home/pi/homeserver/node_modules/q/q.js:883:30) at Promise.promise.promiseDispatch (/home/pi/homeserver/node_modules/q/q.js:816:13) at /home/pi/homeserver/node_modules/q/q.js:624:44 at runSingle (/home/pi/homeserver/node_modules/q/q.js:137:13) at flush (/home/pi/homeserver/node_modules/q/q.js:125:13) at _combinedTickCallback (internal/process/next_tick.js:132:7) at process._tickCallback (internal/process/next_tick.js:181:9)
> 
> **Expected behavior**
> 
> Expose the temperature of the connected temperature sensor
> 
> I have tested cat w1_slave and am able to see the data.
> 
> **Minimal reproduction of the problem with instructions**
> 
> 1. 
> 2. 
> 3. 
> 
> ...
> 
> gist:
> 
> **What is the motivation / use case for changing the behavior?**
> 
> **Please tell us about your environment:**
> 
> * ( ) my request is related to node-opcua acting as a  OPCUA CLIENT
> * (X)  my request is related to node-opcua acting as a OPCUA SERVER
> * ( ) I have installed node-opcua from source ( using git clone)
> * (X) I have installed node-opcua as a package ( using npm install )
> * ( ) I am using an application that uses node-opcua
>   
>   * ( ) node-red
>   * ( ) other : please specify
> * Device: _____
> * OS version: _____
>   
>   * ( ) Windows : version : _________
>   * ( ) Linux   : version : _________
>   * ( ) MacOs   : version : _________
>   * (X) Raspbian: version : _________
>   * ( ) Other   : specify :
> * Description of the other OPCUA system I am trying to connect to:
>   
>   * Name:_________
>   * Version:_________
>   * Manufacturer/Software vendor:_________
>   * link : https://
> * **node-opcua version:**  :
> 
> * **Node:**
>   `node --version` = v8.16.1
#1173
Duplicate of
