### ISSUE TITLE
Assignment to constant variable, https://github.com/node-opcua/node-opcua/blob/master/documentation/monitoring_home_temperature_with_a_raspberry.md

### ISSUE THREAD

**Issue by mellerbeck** [node-opcua/node-opcua#716]
My apologies I tried this again and it is still throwing the error.

I can successfully start this sample server https://github.com/node-opcua/node-opcua/blob/v2.1.3/documentation/sample_server.js 

Most of this is new to me NPM, node.js etc.. so I might just be doing something stupid.

I'm submitting a ... (check one with "x")

(X) bug report => search github for a similar issue or PR before submitting
( ) feature request
( ) support request => Please do not submit support request here, instead see use
use gitter or stackoverflow for community support, or
contact Sterfive for commercial support (contact (@) sterfive.com )
Current behavior
Following this quick guide
https://github.com/node-opcua/node-opcua/blob/master/documentation/monitoring_home_temperature_with_a_raspberry.md

created directory homeserver

ran npm init (I accepted the defaults, don't know if I should do differently?)

I ran npm install node-opcua --unsafe-perms (to resolve cannot find module 'node-opcua')

created index.js with code from tutorial

ran node index.js

error TypeError: Assignment to constant variable.
at /home/pi/homeserver/index.js:10:15
at _fulfilled (/home/pi/homeserver/node_modules/q/q.js:854:54)
at self.promiseDispatch.done (/home/pi/homeserver/node_modules/q/q.js:883:30)
at Promise.promise.promiseDispatch (/home/pi/homeserver/node_modules/q/q.js:816:13)
at /home/pi/homeserver/node_modules/q/q.js:624:44
at runSingle (/home/pi/homeserver/node_modules/q/q.js:137:13)
at flush (/home/pi/homeserver/node_modules/q/q.js:125:13)
at _combinedTickCallback (internal/process/next_tick.js:132:7)
at process._tickCallback (internal/process/next_tick.js:181:9)

Expected behavior

Expose the temperature of the connected temperature sensor

I have tested cat w1_slave and am able to see the data.

Minimal reproduction of the problem with instructions

...

gist:

What is the motivation / use case for changing the behavior?

Please tell us about your environment:

( ) my request is related to node-opcua acting as a OPCUA CLIENT

(X) my request is related to node-opcua acting as a OPCUA SERVER

( ) I have installed node-opcua from source ( using git clone)

(X) I have installed node-opcua as a package ( using npm install )

( ) I am using an application that uses node-opcua

( ) node-red
( ) other : please specify
Device: _____

OS version: _____

( ) Windows : version : _________
( ) Linux : version : _________
( ) MacOs : version : _________
(X) Raspbian: version : _________
( ) Other : specify :
Description of the other OPCUA system I am trying to connect to:

Name:_________
Version:_________
Manufacturer/Software vendor:_________
link : https://
node-opcua version: :

Node:
node --version = v8.16.1

**Comment by aljoshakoecher** [comment]
Hi,

I don't know what you're doing in line 10 of your index.js but it looks like a rather simple mistake in your code. You declared a variable as 'const' (or used one that was declared in the example you mentioned) and later changed the value of that variable.
If you really want to reassign a variable, you should use 'let' instead of 'const'.
