### ISSUE TITLE
add/delete dynamically variable after starting server OPCUA with data request through HTML UI.

### ISSUE THREAD

**Issue by tttranducdung** [node-opcua/node-opcua#730]
Hello, I am writing OPCUA-Server using node-opcua, nodejs, and express. Variables on my OPCUA-server are added statically by file .json
`{

	"appName" : "OPCUA_Communication",
	"description" : "Sample configuration file for Data Simulation", 
	"serverConfig" : 
	{
		    "port" : 4840,
			"allowAnonymous" : false,
			"userList" : 
			[
				{
					"user" : "Siemens" ,
					"password" : "Siemens"
				},
				{
					"user" : "user" ,
					"password" : "user"
				}
			]
	},
	"SimulationData" : 
	[
		{
			"deviceName" : "Device_1",
			"variablesList": 
			[
				{
						"name": "Variable_1",				
						"dataType": "Double",
                                                "writable": false,
                                                "value": 1
				},
				{
						"name": "Variable_2",						
						"dataType": "Double",
                                                "writable": true,
                                                "value": 2
				},
				{
						"name": "Variable_3",						
						"dataType": "Double",
                                                "writable": true,
                                                "value": 3
				}
			]
		}
					
		
	]}`

CODE add that variables to my server:

`{
function opcuaAddDevice(nameDevice, DataSet, uaNodeList, addressSpace, namespace)
{
    
    let device = namespace.addObject({
        organizedBy : addressSpace.rootFolder.objects,
        browseName : nameDevice
    });

    // Add each tag (variable) to server
    for( let j = 0; j < DataSet.variablesList.length; j++){
        let variable = DataSet.variablesList[j];
        let setID = 's="' + nameDevice + '"."' + variable.name + '"';  
        DataSet.variablesList[j].id = setID;
        let myValue = variable.value;
        {                      
        namespace.addVariable({
            componentOf: device,
            browseName: variable.name,
            dataType: moduleTypesMap[variable.dataType],
            nodeId: setID,
            value: {
                get: function () {
                    let mydataType = moduleTypesCodeMap[moduleTypesMap[variable.dataType]];
                    return new opcua.Variant({dataType: mydataType, value: myValue });
                },
                set: function (variant) {
                    return opcua.StatusCodes.BadNotWritable;
                }
            }
        });
    }
    else {

        namespace.addVariable({
            componentOf: device,
            browseName: variable.name,
            dataType: moduleTypesMap[variable.dataType],
            nodeId: setID,
            value: {
                get: function () {
                    let mydataType = moduleTypesCodeMap[moduleTypesMap[variable.dataType]];
                    return new opcua.Variant({dataType: mydataType, value: myValue });
                    
                },
                set: function (variant) {
                    myValue = parseFloat(variant.value);
                    DataSet.variablesList[j].value = variant.value;
                    return opcua.StatusCodes.Good;
                } 
            }
        });

    }
    }
    uaNodeList.push(device);
}
}`

I also one application using HTML and expressJS to manage my Server ( as dashboard)
Afer starting server, I wanted add/delete dynamically variable to MY SERVER with data that is requested by manager of OPCUA-server through HTML UI.
CAN I DO THAT? AND HOW? I don't search anymore methods to do it.

**Comment by kevz93** [comment]
Can you add nodes after starting the server ?
