### ISSUE TITLE
delete/add nodes to OPC UA Server

### ISSUE THREAD

**Issue by tttranducdung** [node-opcua/node-opcua#735]
Hello
After you start an OPC UA server (based node-opcua), can I delete/add nodes in namespace dynamically?

**Comment by mikakaraila** [comment]
Yes of course. Add method that will ask needed parameters.

**Comment by tttranducdung** [comment]
> 
> 
> Yes of course. Add method that will ask needed parameters.

Can you help me by some ex? I am so confuse about "method". Because parameters that you said, I will receive from Web ( expressJS, nodeJS , HTML ) as OPC UA Server Manager Page, not receive from OPCUA Client.

**Comment by pelis** [comment]
I recommend to buy the book from Etienne, it contains a lot of good examples
