### ISSUE TITLE
DataTypeDefinition of DataTypes not correctly filled

### ISSUE THREAD

**Issue by eoursel** [node-opcua/node-opcua#743]
**Current behavior**
In the OPC UA client the BaseDataType field of DataTypeDefinition is not filled correctly. The identifier is 0. It can be verified with any opc ua client. 

**Describe the bug**
DataTypeDefinition should contain a valid BaseDataType. Some clients may use this information to rebuild complex types. This is what the OPC Foundation Stack in C# is doing. 

**To Reproduce**
1. .... Start any server
2. ...... With a client browse the DataTypes. Check any datatype derived from structure. 
3....... Observe in the attributes of the nodes that DataTypeDefinition/BaseDataType is not filled. 

**Expected behavior**
Check the specification about description of the DataTypeDeinition. 

![image](https://user-images.githubusercontent.com/6437134/76442868-d5801380-63c1-11ea-9823-30419ee36028.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/6437134/76441844-56d6a680-63c0-11ea-82a4-fe7356af80db.png)

**Gist**
gist:

 * ( ) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * ( *)  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * ( *) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: rpi4
  * OS version: ubuntu 19.10
    
    - ( ) Windows : version : _________
    - ( ) Linux   : version : _________
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( *) Other   : specify : ubuntu 19.10 arm64
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name:_________
     - Version:_________
     - Manufacturer/Software vendor:_________
     - link : https://
     

* **node-opcua version:**  : 2.5.0-alpha12

* **Node:** 
   `node --version` = 12

**Comment by erossignon** [comment]
fixed in [version 2.5.1](/releases/tag/v2.5.1) @eoursel can you confirm and close ?
