### ISSUE TITLE
Possibly wrongly defined valueOf method on StatusCode class

### ISSUE THREAD

**Issue by bompi88** [node-opcua/node-opcua#744]
**Current behavior**

Mongoose and a bunch of other libraries depend on `valueOf` to be a function that returns the primitive value of the given variable. When I call `myStatusCode.valueOf()`, it fails with `TypeError: status.valueOf is not a function`, because `ConstantStatusCode`'s `valueOf` is a getter.

**To Reproduce**
Script to show the behavior:
```typescript
import { ConstantStatusCode } from 'node-opcua';
const status = new ConstantStatusCode({ value: 123, description: 'No error', name: 'GoodOrBad' });

status.valueOf(); // TypeError: status.valueOf is not a function
```

**Expected behavior**
I expect the `valueOf` function to be a function and not a getter. I expect that `valueOf` returns the numeric or the string value of the status code object.

**Suggested fix**
Remove the `get` keyword for the `valueOf` method. Update`valueOf` to either return the numeric or the string representation of the object, based on what's expected.

* (*) my request is related to node-opcua acting as a  OPCUA CLIENT 
* (*) I have installed node-opcua as a package ( using npm install )        
* **Device:** Mac
* **OS version:** MacOs 10.14.6   
* **node-opcua version:** `2.3.0`
* **Node version:** `v12.14.0`

**Comment by erossignon** [comment]
fixed in [version 2.5.1](/releases/tag/v2.5.1). @bompi88 Can you confirm and close ?
