### ISSUE TITLE
OPC UA SERVER on VPS 

### ISSUE THREAD

**Issue by tttranducdung** [node-opcua/node-opcua#748]
I run a demo OPCUA-Server based on node-opcua, it's good with LOCAL.
But, when I deploy to my VPS on AWS amazon, then I use ProsysClient in my Laptop to connect, it's failed "CAN'T NOT DISCOVER APPLICATIONS FROM opc.tcp://.....". Seem it can't discover online.
What is the problem I encountered?

**Comment by mtrabelsi** [comment]
it seems the same issue with Google cloud too.. I guess something has to do with firewall, I'm looking into it, will post any finding here

**Comment by erossignon** [comment]
assuming you are running on a Linux VPS:  what is the output of:

    $ hostname --fqdn 
  
    $ hostname 

?
