### ISSUE TITLE
MonitoredItem in OPCUA Client

### ISSUE THREAD

**Issue by tttranducdung** [node-opcua/node-opcua#754]
Hello all, I have a OPCUA Client, and I need get value 40 nodes on my OPCUA Server. But, I  only can read value nodes invidually.
How to I can get all nodes in once time?
Tks for supports.

**Comment by erossignon** [comment]
you will find an example in https://leanpub.com/node-opcuabyexample in chapter 
8.7 client with large number of monitored items
