### ISSUE TITLE
browseDirection Invalid

### ISSUE THREAD

**Issue by demeyr** [node-opcua/node-opcua#76]
The browse part of the sample_client tutorial is not working anymore, maybe caused by the recent changes?
https://github.com/node-opcua/node-opcua/commit/8c94fad6fcf6759f4cfb858f99d18ef1295412dc#diff-e2bb0ba745e1ddd4a808958f0407878c   

```javascript
// step 3 : browse
    function(callback) {
       the_session.browse("RootFolder", function(err,browse_result){
           if(!err) {
               browse_result[0].references.forEach(function(reference) {
                   console.log( reference.browseName);
               });
           }
           callback(err);
       });
    },
```

If Forward direction is forced in BrowseDirection_enum.js then everything is fine.

**Comment by erossignon** [comment]
This looks now fixed.
