### ISSUE TITLE
If statement for OPCUAServerEndpointOptions seems wrong

### ISSUE THREAD

**Issue by aki-0919** [node-opcua/node-opcua#764]
I guess the last condition of [this ](https://github.com/node-opcua/node-opcua/blob/v2.5.7/packages/node-opcua-server/source/opcua_server.ts#L1120)line should be `typeof options2.port !== "number"`, not `options.port`.

If OPCUA server is created without port, it throws error of `expecting a valid port (number)`

Works: `server = new opcua.OPCUAServer({ port: 26543 });`
Error: `server = new opcua.OPCUAServer();`

- node-opcua version: :2.5.7

**Comment by aki-0919** [comment]
If OPCUA server is created without `port`, it throws error of `expecting a valid port (number)`

Works: `server = new opcua.OPCUAServer({ port: 26543 });`
Error: `server = new opcua.OPCUAServer();`

**Comment by erossignon** [comment]
Thank you ; fixed in d2cb13f972f36de5c75ab6bf2db36087cd595317
