### ISSUE TITLE
Get UserName Identity on OPC UA Server when OPCUA Client connect?

### ISSUE THREAD

**Issue by tttranducdung** [node-opcua/node-opcua#771]
When Clients create session with OPCUA Server, it will send userName & password Identity to activeSession on Server. How to I can know that "UserName" when client connect to Server on my Server (node-opcua)? Here is an example of Prosys OPC UA Simulation Server.
![user](https://user-images.githubusercontent.com/61015563/80818099-d3d20f80-8bfc-11ea-98c6-f6b2806f50c1.png)

**Comment by tttranducdung** [comment]
@erossignon can you help me to solve this problem?

**Comment by erossignon** [comment]
you could capture it during the `"session_activate"` event:

````
    server.on("session_activated", (session) => {
        console.log("username is =", session.userIdentityToken.userName);
    });
```
