### ISSUE TITLE
client with historization

### ISSUE THREAD

**Issue by Sam-kemit** [node-opcua/node-opcua#778]
I developed a server with HA and now I'm trying to create a client to display historical data but I don't know how to do it.

Does anyone have an example that could help me, please?

Best regards!

**Comment by erossignon** [comment]
Displaying information is beyond the scope of node-opcua which only deal with the OPCUA specific stuff.
example of reading historical data can be found in the book [NodeOPCUA by Example](https://leanpub.com/node-opcuabyexample)
