### ISSUE TITLE
Is there a Changelog?

### ISSUE THREAD

**Issue by Razzeee** [node-opcua/node-opcua#787]
I'm not sure if I'm missing something, but is there any place I can read about changes from version to version. Especially breaking changes. New features and bugfixes would also be helpful.

**Comment by mikakaraila** [comment]
It is already fixed to 0.2.58

**Comment by erossignon** [comment]
Yes here : https://github.com/node-opcua/node-opcua/releases

**Comment by Razzeee** [comment]
Sorry for the noise, not sure how I missed that.
