### ISSUE TITLE
Support for cluster mode

### ISSUE THREAD

**Issue by avalla** [node-opcua/node-opcua#788]
Is there any way to support cluster mode efficiently?

e.g. using server listen in exclusive mode

**Comment by erossignon** [comment]
you mean passing the `{ exclusive: true}` flag to `server.listen()` ?

**Comment by avalla** [comment]
sorry, it was badly explained, as use { exclusive: false }

I added an opc-ua server in a clustered application and it was not working like express (same port multiple instances)

maybe it was bad architecture design, now my opc-ua server runs on a different (not clustered) process

**Comment by erossignon** [comment]
@avalla , the architecture you choose makes sense, it is cleaner to have your node-opcua running inside its own process and separated from your express(like) app.
