### ISSUE TITLE
coerceVariantType on string "true"

### ISSUE THREAD

**Issue by fkhederoo** [node-opcua/node-opcua#794]
Hi,

I am pulling values from a CSV file and running coerceVariantType() on the value before writing to the server.

Works for all except, booleans.

`
   let valueToWrite = coerceVariantType(DataType.Boolean, "true")
`

This will return a string, not true. Any support for that in the future ?

**Comment by erossignon** [comment]
If you feel it is useful, please go for it ! 
Provide a PR and I will be happy to assist you for inclusion to master
The code and its unit tests resides in node-opcua-variant ...

**Comment by erossignon** [comment]
PR#929 is closed now
