### ISSUE TITLE
ClientSession interface is missing ```deleteMonitoredItems``` method

### ISSUE THREAD

**Issue by demike** [node-opcua/node-opcua#796]
https://github.com/node-opcua/node-opcua/blob/0d168bdc8351bbaf7ff9e60e21d459e8c4bdfeca/packages/node-opcua-client/source/client_session.ts#L412

**Comment by mikakaraila** [comment]
You can use monitedItem.terminate(); not obvious but working.

**Comment by demike** [comment]
> You can use monitedItem.terminate(); not obvious but working.

Yes but that's no batch request

**Comment by erossignon** [comment]
@demike, well spoted !   deleteMonitoredItems is not exposed in the typescript interface.

However,
- the method exists and can be called if needed. 
- as @mikakaraila  pointed out, deleteMonitoredItems is proably not needed in most cases as the subscription will be handled with the ClientSubscriputon object that will take care of dealing with the monitoredItem  for you .

**Comment by demike** [comment]
Yes of course. Just spotted it when writing some e2e tests not using the createSubscription2 approach.

**Comment by demike** [comment]
Should be fixed now

**Comment by erossignon** [comment]
Not released yet ... but not far !
