### ISSUE TITLE
Let Crawler assign raw object of DataValue & DataType instead of convert to string

### ISSUE THREAD

**Issue by bruegth** [node-opcua/node-opcua#803]
**Is your feature request related to a problem? Please describe.**
Reuse of crawled dataValue and datatype objects is not possible because they will converted to string.

**Describe the solution you'd like**
Assign DataValue & DataType as it is. 

**Describe alternatives you've considered**
Implement an option in crawler to make String conversion.

**Additional context**
https://github.com/node-opcua/node-opcua/blob/bca147370c37c5615678e23dca514bef0f63c15c/packages/node-opcua-client-crawler/source/node_crawler.ts#L879

**Comment by erossignon** [comment]
fixed in node-opcua@2.5.6 Thomas, can you confirm it's working as expected.
( note; dataTypes remain as string and can be easilu converted back to NodeId using resolveNodeId)

**Comment by bruegth** [comment]
> fixed in node-opcua@2.5.6 Thomas, can you confirm it's working as expected ?
> ( note; dataTypes remain as string and can be easilu converted back to NodeId using resolveNodeId)

ToJSON will convert enum's to string and not to related numbers.

So instead of using resolveNodeId, I do this:
OpcUa.DataType[node.dataValue.value.dataType as keyof typeof OpcUa.DataType]

Because this can be also applied to VariantArrayType,  because it's also string and can't be converted by resolveNodeId.

**Comment by erossignon** [comment]
I mentioned resolveNodeId to rebuild a nodeId from the dataType property of the UAVariable, that you were referring node-opcua/packages/node-opcua-client-crawler/source/node_crawler.ts Line 879 in bca1473
not he dataType property of the Variant object.

**Comment by bruegth** [comment]
That's correct I refer only DataType but I need both DataType and DataValue. DataValue.ToJSON() will convert underlying  DataValue.Value.dataType to e.g. "Double" so but for both cases "x as keyof typeof DataType" will convert it back to Datatype in every case.

So I can work with your change, and no longer need a custom version of crawler.

**Comment by erossignon** [comment]
Thank you Thomas. Using enumeration value as string was a design decision to make it more user friendly as number can be confusing. I am glad that we have a easy way to convert enum values string<->value with Typescript.
