### ISSUE TITLE
monitoring with TimestampsToReturn.Source does not return sourceTimestamp

### ISSUE THREAD

**Issue by mstfldmr** [node-opcua/node-opcua#804]
**Current behavior**
After creating a monitored item with TimestampsToReturn.Both, I get updates with both sourceTimestamp and serverTimestamp.

**Describe the bug**
When I create a monitored item with TimestampsToReturn.Source, I get updates with null sourceTimestamp and null serverTimestamp.

**To Reproduce**
```
      const monitoredItem = ClientMonitoredItem.create(theSubscription, {
          nodeId: nodeId,
          attributeId: AttributeIds.Value
        }, {
          samplingInterval: 500,
          discardOldest: false,
          queueSize: 10
        },
        TimestampsToReturn.Source
      );
```

**Expected behavior**
Getting an update with valid sourceTimestamp.

**Screenshots**

**Gist**
gist: https://gist.github.com/mstfldmr/7353695f5b388077d626f9d8601d7074

 * (X) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * ( )  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * (X) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: AWS EC2
  * OS version: Ubuntu 18.04
    
    - ( ) Windows : version : _________
    - (X) Linux   : version :  Ubuntu 18.04
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name: Kepware
     - Version: 6.9.572
     - Manufacturer/Software vendor:_________
     - link : https://
     

* **node-opcua version:**  :
2.6.4

* **Node:** 
   `node --version` = v12.18.0

**Comment by erossignon** [comment]
should be fixed in @2.5.6. please confirm
