### ISSUE TITLE
link client and FileHandle

### ISSUE THREAD

**Issue by Baum200** [node-opcua/node-opcua#805]
To realize a file download I use the **node-opcua-file-transfer** package.

**Current behavior**
A FileHandle can be used by different clients. The generated file handles are not randomized.

**Expected behavior**
The FileHandle can only be used by the client who requested the handle.

Thanks.

**Comment by erossignon** [comment]
should be fixed in @2.5.6. please confirm

**Comment by Baum200** [comment]
Thanks!
