### ISSUE TITLE
File download via the UaExpert

### ISSUE THREAD

**Issue by Baum200** [node-opcua/node-opcua#806]
**Current behavior**

To realize a file download I use the node-opcua-file-transfer package. I created a file node in the OPC UA server as described in the Readme file of the package. For testing I am using the UaExpert (Version 1.5.1 331).

**Describe the bug**
After a right cklick on the FileType-Object the UaExpert offers me a Download dialog (read to local file). When I try to execute the Download dialog it fails and the OPC UA Server returned the error: _Method ns=0;i=11580 Open\_ has not been bound_.

* **Node:** 
   `node --version` = v12.14.0

**Comment by erossignon** [comment]
should be fixed in @2.5.6. please confirm

**Comment by Baum200** [comment]
Thanks!
