### ISSUE TITLE
Is there a possibility to wrap multiple servers?

### ISSUE THREAD

**Issue by Blume987** [node-opcua/node-opcua#813]
Hi,
is there a possibility to wrap multiple servers with this library?

We have like ~15 opc servers running on one machine, each opc server running on a own application. Each opc ua application has its own port (4334; 4335; 4336; ...). Is there a possibility to wrap/proxy all the servers into a single server?
```
|------| |------| |------|
| UA 1 | | UA 2 | | UA 3 |
|------| |------| |------|
   î        î        î
|------------------------|
|      OPC UA Wrapper    |
|------------------------|
      î            î
|----------|  |----------|
| Client A |  | Client B | 
|----------|  |----------|
```

Because I want to get all the data of the opcua servers without establishing 15 connections for each client.

Thank you

**Comment by erossignon** [comment]
Yes, the wrapper is called an aggregator.
sterfive.com proposes a aggregator as a commercial product. It is based on node-opcua. 
The aggregator can connect to dozens of servers and can aggregate millions of variables and present a consolidated address space with a single connection point. 
Please contact me at contact@sterfive.com  for more info.
