### ISSUE TITLE
OPC UA server on Heroku

### ISSUE THREAD

**Issue by PManlio** [node-opcua/node-opcua#817]
Hi,
I'm working to a uni project in which we (me and my collegue) should deploy our node.js server OPC UA on Heroku or Azure.
So, the fact is: from Heroku's App CLI we get an enpoint URL like this `opc.tcp://a8e31ec7-a1b7-4376-8660-453c4091c235.prvt.dyno.rt.heroku.com:15089/UA/IndustrialInformaticsServer` but when we put this endpoint into UA Expert, we get timeout/bad request errors as response, like this server cannot be discovered.

We tried also the stuff about the firewall but nothing changes... can you help us? (Sorry for my bad english)

**Comment by erossignon** [comment]
I am not sure you'll be able to expose a OPCUA Server publicly on Heroku. ( see https://stackoverflow.com/questions/18600814/deploying-a-tcp-server-to-heroku) 
However, you'll be able to achieve this easily on Azure in a small VM.
