### ISSUE TITLE
server.applicationUri not returned in CreateSessionResponse

### ISSUE THREAD

**Issue by padraic-padraic** [node-opcua/node-opcua#826]
**Current behavior**

While investigating a communication problem between the node-opcua server and the NI OPC UA client, we noticed in the messages that the server endpoints in the CreateSessionResponse do not contain the server.applicationUri. The OPC-UA spec mentions that server.applicationUri should be amongst the information retained in the CreateSessionResponse (https://reference.opcfoundation.org/v104/Core/docs/Part4/5.6.2/#5.6.2.2)

**Describe the bug**
The server does not return all required information in

**To Reproduce**
1. Create an opcua server following e.g. an example
2. Enabled debugging by setting the environment variable NODEOPCUADEBUG=SERVERTRACE,TRACE,PERF
3 Inspect the server endpoints during a connection attempt

**Expected behavior**
The CreateSessionResponse includes the server applicationUri

**Screenshots**

**Gist**
gist: https://gist.github.com/padraic-padraic/0b90069fbcf551c66dac36ef33c39058

 * ( ) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * (x)  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * (x) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: AWS EC2 server
  * OS version: 
    
    - ( ) Windows : version : _________
    - (x) Linux   : version : Debian Buster, Ubuntu 18.04 LTS
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name:_________
     - Version:_________
     - Manufacturer/Software vendor:_________
     - link : https://
     

* **node-opcua version:**  : 2.7.0

* **Node:** 
   `node --version` = v14.2.0

**Comment by erossignon** [comment]
Thank you for spotting this, server.applicationUri is a new requirement of 1.04
