### ISSUE TITLE
Certificate generation fails with v2.8.1 on Raspberry

### ISSUE THREAD

**Issue by mikakaraila** [node-opcua/node-opcua#841]
Details can be found from here:
https://github.com/mikakaraila/node-red-contrib-opcua/issues/181

**Current behavior**
postinstall fails to generate certificates

**Describe the bug**

**To Reproduce**
1. Try to install node-red-contrib-opcua on Raspberry
2. See console log
3. Postinstall fails

**Expected behavior**

**Screenshots**

**Gist**
gist:

 * ( ) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * ( )  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * ( ) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: _____
  * OS version: _____
    
    - ( ) Windows : version : _________
    - ( ) Linux   : version : _________
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name:_________
     - Version:_________
     - Manufacturer/Software vendor:_________
     - link : https://
     

* **node-opcua version:**  :

* **Node:** 
   `node --version` =

**Comment by erossignon** [comment]
* Try to install node-red-contrib-opcua on Raspberry
* See console log
 * Postinstall succeed

Tried on a RaspberryPI 4,
