### ISSUE TITLE
Get server Publications as a whole instead of split monitoredItems changes

### ISSUE THREAD

**Issue by AzIz000** [node-opcua/node-opcua#851]
Is there any way to receive and process full server publication event (i.e. 1000 changes of different monitored items) instead of one event per each monitored item changed (as per monitoredItem.on("changed", (dataValue) => {...}) ) ?

**Comment by erossignon** [comment]
`subscription.on("raw_notification", (notificiations)=>{});` shall do the trick.

**Comment by AzIz000** [comment]
Thanks a lot @erossignon , that was exactly what I was looking for. BR!
