### ISSUE TITLE
Hooks like WriteRequest, ReadRequest, etc along with existing server.on("request")

### ISSUE THREAD

**Issue by tejad2805** [node-opcua/node-opcua#864]
**Is your feature request related to a problem? Please describe.**
My current issue is that I cannot get a hold of Write Request to handle the data depending on which client it is coming from

**Describe the solution you'd like**
Currently there is a server.on("request") handler. But there is no way to drill down to the request type. It would be nice to have different request types like
* ReadRequest
* WriteRequest
* CreateConnectionRequest
* CreateSessionRequest, etc

**Describe alternatives you've considered**
Currently this is the best opcua option available for node, haven't looked at anything else

**Comment by erossignon** [comment]
I am not sure we need to add this to the library as it can easily be acheived: 

a switch case can help here

````
server.on("request", (request) => { 
   switch(request.constructor.name) {
        case "ReadRequest":   server.emit("readRequest",  request); break;
       ....
  }
});
````

You get the idea ...
