### ISSUE TITLE
Certificate revocation lists in PKI should be CRL, not CLR

### ISSUE THREAD

**Issue by marcodisarno** [node-opcua/node-opcua#883]
**Current behavior**

Some of the test cases in the OPC Compliance Testing Tool fail because the node-opcua-server (or, I guess, node-opcua-pki's certificate manager) stores CRLs in `<PKI_DIR>/issuers/clr` and `<PKI_DIR>/trusted/clr`.

The CTT would expect them at `crl`, which is why during installation / preparation it makes problems.

**To Reproduce**
0. Prepare the PKI from CTT (the copyToServer folder)
1. Start up a simple server
2. Run CTT test cases "Security Certificate Validation -> Test Cases"
3. Find lots of Errors with certificate revocation

**Expected behavior**
The OPCUA server should store its revocation lists in `<PKI>/.../crl`

**Screenshots**

![image](https://user-images.githubusercontent.com/14130041/95466948-3209d800-097d-11eb-8509-bd7d4da69836.png)

![image](https://user-images.githubusercontent.com/14130041/95466797-0555c080-097d-11eb-805b-5e16a1e95c1b.png)

 * ( ) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * (X)  my request is related to node-opcua acting as a OPCUA SERVER 

  * (X) I have installed node-opcua from source ( using git clone)
  * (X) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: PC
  * OS version: Windows 10
    
    - (X) Windows : version : 10
    - ( ) Linux   : version : _________
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :

* **node-opcua version:**  : 2.18.0

* **Node:** 
   `node --version` = 12.16.1

**Comment by erossignon** [comment]
Thank you for spotting this ...  This is now fixed in node-opcua-pki@ 2.1.8
