### ISSUE TITLE
Problems with Conditions and Events

### ISSUE THREAD

**Issue by julien-schultz** [node-opcua/node-opcua#893]
![grafik](https://user-images.githubusercontent.com/64416528/97176417-331c7100-1795-11eb-9f70-9f8110b49f6c.png)

Hello,
I´m trying to throw some Events or better Alarms in node-opcua (server). 
I have some booleans representing the alarm-State and should show some errormessages to the user.
I choose the OffNormalAlarm Type for this problem, I think it matches well.
I also get events when the normalState or the actualState changes, but in UAExpert I don´t see the Message or the
Severity in the EventView,,, Can you maybe tell me what I can improove? Also in your Example with the Tanks and the ExclusiveLimitAlarms I only see the Server/Object collumn, the rest are blank. Up to the this.emit("event", eventData); in ua_condition_base.js file there is the EventData width the conditionInfo incl message text included.

Maybe you can tell me where I ´have to put the message or Severity on in this object...

Tank you very much!
Julien

**Comment by erossignon** [comment]
let me close this issue as it hasn't received any update.

 if the problem persists or you need additional assistance; please contact sterfive.
