### ISSUE TITLE
Executing UAMethod should check user authorization

### ISSUE THREAD

**Issue by MarcoSeb** [node-opcua/node-opcua#896]
# Desireable Feature
With UAVariable I can set permissions. The same behaviour would be usefull for UAMethods

# Example:
Having UAMethods to control a door.
Lock()
Unlock()
Openr()
Close()

All AuthenticatedUser should be able to open & close the door.
But only Supervisor should be allowed to lock & unlock the door.

# Preferred solution
add `setPermissions(permission: Permisson)` to `UAMethod`
add `Execute?: string[];` to `interface Permissions`

# Alternatives
Possible to implement it, without making changes on node-opcua.
```
function myAcessRestrictionChecker(userRole, allowedRoles){
    ...
}

namespace.addMethod(...).bindMethod((inputArguments, context, callback) => {
    if(myAcessRestrictionChecker(context.getCurrentUserRole(), ["SuperVisor"])){
        return callback(null, { statusCode: StatusCodes.BadUserAccessDenied });
    }
    ...
}
```
Disadvantages:
- It looks like a workaround as it is not consistent with UAVariabe interface.
- It makes developers reimplement the behaviour of `SessionContext.checkPermission(...)`

# Related stuff:
[Feature Request User Authorization #171](https://github.com/node-opcua/node-opcua/issues/171)
[4.8.2 Well Known Roles](https://reference.opcfoundation.org/v104/Core/docs/Part3/4.8.2/)

**Comment by erossignon** [comment]
Fixed by @marcelwinh  in PR #900
