### ISSUE TITLE
Support user with multiple roles

### ISSUE THREAD

**Issue by MarcoSeb** [node-opcua/node-opcua#898]
# Feature Request
The node-opcua server does not support a user having multiple roles. This is a very common use case.

# Problem
Using LDAP-user to grant Permissions to the device.
Every user is assigned multiple groups(opc: _Roles_). Every group grants permission to _Nodes_ in the _AddressSpace_

# OPC Specification
[The OPC UA approach assigns Permissions to Roles for each Node in the AddressSpace. Clients are then granted Roles when they create a Session based on the information provided by the Client](https://reference.opcfoundation.org/v104/Core/docs/Part5/F.1/)

[The OPC UA approach assigns Permissions to Roles. Clients are then granted Roles based on connection information](https://reference.opcfoundation.org/v104/Core/docs/Part2/4.12/)

# Solution
`export type GetUserRoleFunc = (username: string) => string;`
should allow to return multiple roles `... => string[];`
For backwards compatibility:
`export type GetUserRoleFunc = (username: string) => string | string[];`

**Comment by erossignon** [comment]
you can combine multiple roles by separating them with `;' for instance `AuthenticatedUser;SecurityAdmin`.

**Comment by MarcoSeb** [comment]
Thanks, I started to work on a PR and realize that is already possible.
This feature is not obvious from the interface.

For now, it should be explained in the doc.

**Comment by erossignon** [comment]
available in node-opcua@2.24.0
