### ISSUE TITLE
node-opcua server does not initialize the NodeId type variable with its value configured in nodeset file.

### ISSUE THREAD

**Issue by Graos** [node-opcua/node-opcua#899]
**Current behavior**
ExclusiveLimitAlarm object instance "Input node" variable component is configured with the NodeId of the eventsource (FloatTypeData1) in the modeling tool and nodeset file is generated. After the generated nodeset file is loaded into node-opcua server the "Input node" variable component is not initialized with the NodeId value configured in the nodeset file. The value type is shown as null in UAExpert.

**Describe the bug**
ExclusiveLimitAlarm object instance "Input node" variable component is configured with the NodeId of the eventsource (FloatTypeData1). After the nodeset file is loaded into node-opcua server the "Input node" variable component is not initialized with the NodeId value configured in the nodeset file. The value type is shown as null in UAExpert. Because of this Alarm and event generation does not work.

**To Reproduce**
1. Load the attached nodeset file into the server
2. Read the Input node variable of the ExclusiveLimitAlarm object configured under IOChannelSet object.
3.The value is empty and the type is shown as null

![image](https://user-images.githubusercontent.com/69800669/97665599-db864a00-1aa1-11eb-920a-bd89748bae0f.png)

**Expected behavior**
I expect the alarm and event to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/69800669/97665666-0a9cbb80-1aa2-11eb-8d1a-61914fbb3791.png)

**Gist**
gist:

 
  * ( )  my request is related to node-opcua acting as a OPCUA SERVER 

 
  * ( ) I have installed node-opcua as a package ( using npm install )
 
 
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name:____UaExpert_____
     - Version:______1.5.1___
     - Manufacturer/Software vendor:___Unified Automation______
     - link : https://
     

* **node-opcua version:**  :

* **Node:** 
   `node --version` = 2.22.0

**Comment by Graos** [comment]
Nodeset file attached.
[CI874TypesTestAlarm.zip](https://github.com/node-opcua/node-opcua/files/5463199/CI874TypesTestAlarm.zip)

**Comment by Graos** [comment]
I am not sure if this is a support request. I thought it is an issue with the Node-opcua server.

**Comment by erossignon** [comment]
It may be an issue but nevertheless, this is an unimplemented feature in the product. 
It's a support request as you are requesting external people to write the required enhancement for you. 
Our business model is to improve node-opcua for all. However, we do need the support of our users.
There are several ways to contribute:
   - ask the community, 
   - jump in and write a PR  yourself and get the author helping you to integrate 
   - ask & encourage  the author by (you or your employer ABB) becoming [a sponsor](https://github.com/sponsors/node-opcua)
   - or request professional support and establish a sustainable relationship with the author and possibly influence the direction of the roadmap. 
   
This being said the parsing of "NodeID"  value has been added especially for you on node-opcua@2.21.0 ....  ball's on your side.

**Comment by Graos** [comment]
OK Thanks. I agree.
