### ISSUE TITLE
serverCapabilities.minSupportedSampleRate being ignored (question?)

### ISSUE THREAD

**Issue by k1r0s** [node-opcua/node-opcua#901]
https://github.com/node-opcua/node-opcua/blob/8eb6d67ecc89e34aa5bb99e9d6025aec2fa79743/packages/node-opcua-server/source/server_capabilities.ts#L175

**Current behavior**

Im trying to showcase OPC/ua speed against other protocols but im unable to get a subscription running below 10ms rate with opcua server implementation.

im using this file as a example https://github.com/node-opcua/node-opcua/blob/master/documentation/sample_server.js

I just reduce the setInterval ms rate to 10ms and my subscription values are:

```
527
532
537
542
547
```
So, even though is quite fast, im loosing a lot of precission

**Describe the bug**
I guess the client runs okay, i have to check other server implementations in other languages but the node server implementation is ignoring the `serverCapabilities.minSupportedSampleRate` which allows clients to suggest a samplingRate (my client is using 1)

**Expected behavior**
to not loose any value

* **node-opcua version:**  :
latest
* **Node:** 
   `node --version` = v10.13.0

**Comment by erossignon** [comment]
setting interval rate for subscription to less than 10ms is unrealistic. OPCUA server will adjust sampling Rate to something more manageable on their end. Client cannot enforce this, just make a suggestion to the server. The server at the end decide which sampling rate shall be used.

**Comment by k1r0s** [comment]
merci! that was helpful

**Comment by k1r0s** [comment]
Hello again. 

Just wondering how to make the server answer more quicker: 

./behavior.json
```json
[
  {
    "variable": "V1",
    "interval": 200,
    "increment": {
      "start": 0,
      "step": 1,
      "reset": 5000
    }
  },
  {
    "variable": "V2",
    "interval": 200,
    "increment": {
      "start": 0,
      "step": 5,
      "reset": 200
    }
  },
  {
    "variable": "V3",
    "interval": 200,
    "increment": {
      "start": 0,
      "step": 1,
      "reset": 1
    }
  },
  {
    "variable": "V4",
    "interval": 200,
    "increment": {
      "start": 0,
      "step": 5,
      "reset": 200
    }
  }
]
```

./index.js
```javascript
const { OPCUAServer, Variant, DataType, MonitoredItem } = require("node-opcua");
const { PORT = 4840 } = process.env;
const behavior = require("./behavior.json");

MonitoredItem.minimumSamplingInterval = 10;

const server = new OPCUAServer({
  port: PORT,
  resourcePath: "/",
  buildInfo: {
    productName: "OPCUA-sv-stub",
    buildNumber: "1",
    buildDate: new Date()
  },
  serverCapabilities: {
    minSupportedSampleRate: 1
  }
});

server.initialize().then(() => {

  const addressSpace = server.engine.addressSpace;
  const namespace = addressSpace.getOwnNamespace();

  const stubObject = namespace.addObject({
    organizedBy: addressSpace.rootFolder.objects,
    browseName: "OPCUA stub"
  });

  behavior.forEach(({ variable, interval, increment }) => {
    let value = increment.start;

    setInterval(() => {
      if(increment.reset && value === increment.reset) value = increment.start;
      else value = value + increment.step;
    }, interval);

    namespace.addVariable({
      componentOf: stubObject,
      nodeId: `s=${variable}`,
      browseName: `${variable}#BrowseName`,
      dataType: "Double",
      value: {
        get: () => new Variant({ dataType: DataType.Double, value })
      }
    });
  })


  server.start(() => console.log(`OPCUA stub server running on port ${PORT}`));
});
```
Im making a stub server just to run some e2e tests on my application. 

Then using this CLI https://github.com/node-opcua/opcua-commander

I monitor any variable and Im loosing a lot of precision. 

The expected for `ns=1;s=V4` should be: 

0,5,10,15,20

But Im getting steps over 0,20,45,70 and so (im loosing 3 values every 4 changes).

Connecting two clients to the server and triggering read (force fetch value) i can speed up the subscription sampling in the other client (literaly pressing up and down so fetching the value actually triggers the subscription sooner on the other client).

Please can you explain how to properly emulate real hardware. Thanks

**Comment by k1r0s** [comment]
![image](https://user-images.githubusercontent.com/6052309/113516898-28a0a780-957d-11eb-9fc5-b1b38fd6c28b.png)

**Comment by k1r0s** [comment]
Ok, so it seems that opcua-commander does not use the same configurations as this sample file

https://raw.githubusercontent.com/node-opcua/node-opcua/master/documentation/sample_client.js

sorry to bother you!
