### ISSUE TITLE
Cannot find module 'underscore' in production build

### ISSUE THREAD

**Issue by IagoSRL** [node-opcua/node-opcua#911]
**Current behavior**
 `node-opcua-client-dynamic-extension-object` does not install `async` as a dependency, but is imported/required at runtime.

**Describe the bug**
Crash at runtime when using the node-opcua client, with next stack trace (just until own code)
```
Error: Cannot find module 'underscore'
Require stack:
- /usr/src/app/node_modules/node-opcua-client-dynamic-extension-object/dist/client_dynamic_extension_object.js
- /usr/src/app/node_modules/node-opcua-client-dynamic-extension-object/dist/index.js
- /usr/src/app/node_modules/node-opcua-address-space/dist/source/helpers/call_helpers.js
- /usr/src/app/node_modules/node-opcua-address-space/dist/source/pseudo_session.js
- /usr/src/app/node_modules/node-opcua-address-space/dist/source/index.js
- /usr/src/app/node_modules/node-opcua-address-space/dist/src/address_space.js
- /usr/src/app/node_modules/node-opcua-address-space/dist/src/index_current.js
- /usr/src/app/node_modules/node-opcua-address-space/distHelpers/get_mini_address_space.js
- /usr/src/app/node_modules/node-opcua-address-space/distHelpers/index.js
- /usr/src/app/node_modules/node-opcua-address-space/testHelpers.js
- /usr/src/app/node_modules/node-opcua/dist/index.js
```

**To Reproduce**
Install only the production modules in the project, with `npm i --production` (In a clean project --no node_modules in place).

Or use the command `npm ci --only=production` (or with environment variable `NODE_ENV=production` set).

This is usual when preparing the project for deployment, like packaging it as a Docker image, or executed at a server preventing that "dev" modules get installed using more time and disk space.

**Expected behavior**
It should find the module, already installed as a production dependency, and able to use the node-opcua API.

**Gist**
gist:
```bash
npm i node-opcua
npm ci --only=production
node
```
```javascript
require('node-opcua')
```

 * (X) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * ( )  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * (X) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: PC
  * OS version: Debian GNU/Linux 9 (stretch), as part of docker image "node:12.18.4"
    
    - ( ) Windows : version : 10
    - (x) Linux   : version : "4.15.0-112-generic" at the production server, "4.19.128-microsoft-standard" (when trying Docker on Windows), as given by "uname -r".
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   
* **node-opcua version:**  :
v2.23.0

* **Node:** 
   `node --version` = 12.18.4

**Proposed solution**
As happened with issue #878, found that the dependency is listed as a "devDependencies" but not as "dependencies" (production dependency). Moving it should fix the problem.

**Addition bug**
Before realise about the dependencies list, I tried switching to just use `node-opcua-client` module. I had the same kind of bug, but the blamed module was `async` as required by `node-opcua-secure-channel`.

**Comment by erossignon** [comment]
fixed in version 2.26.0, thanks
