### ISSUE TITLE
what is the nodejs version more appropriate for node-opcua?

### ISSUE THREAD

**Issue by mariodiciccio** [node-opcua/node-opcua#924]
Hi,
as the title.

I am developing an application desktop and i would to knows what is the best nwjs version for my goal.

thanks

**Comment by erossignon** [comment]
We follow the [nodejs release calendar](https://nodejs.org/en/about/releases/) and favor the long term release (even number : 8 10 14 etc ..)

node 14 is currently the most appropriate version for node-opcua.

we are still supporting node version 8.0 but this very is now end of life and will be not supported anymore soon.

(node 15 hasn't been formally tested yet)

**Comment by mariodiciccio** [comment]
Thank you
