### ISSUE TITLE
Is there any support to browse the AddressSpace of server and generate nodeset file ?

### ISSUE THREAD

**Issue by Graos** [node-opcua/node-opcua#938]
**Current behavior**

**Describe the bug**

**To Reproduce**

1. ....
2. ......
   3.......

**Expected behavior**

**Screenshots**

**Gist**
gist:

- ( ) my request is related to node-opcua acting as an OPCUA CLIENT
- ( ) my request is related to node-opcua acting as an OPCUA SERVER

  - ( ) I have installed node-opcua from source ( using git clone)
  - ( ) I have installed node-opcua as a package ( using npm install )
  - ( ) I am using an application that uses node-opcua

    - ( ) node-red
    - ( ) other : please specify

  - Device: **\_**
  - OS version: **\_**

    - ( ) Windows : version : \***\*\_\*\***
    - ( ) Linux : version : \***\*\_\*\***
    - ( ) MacOs : version : \***\*\_\*\***
    - ( ) Raspbian: version : \***\*\_\*\***
    - ( ) Other : specify :

  - Description of the other OPCUA system I am trying to connect to:

    - Name:\***\*\_\*\***
    - Version:\***\*\_\*\***
    - Manufacturer/Software vendor:\***\*\_\*\***
    - link : https://

- **node-opcua version:** :
  
  

- **Node:**
  `node --version` =

**Comment by MarcoSeb** [comment]
generate xml nodeset file:: http://node-opcua.github.io/api_doc/2.20.0/classes/uanamespace.html#tonodeset2xml

**Comment by Graos** [comment]
I tried this in server it works fine. How do i do from client perspective ?

**Comment by simonbowen** [comment]
@Graos I am also looking for this answer, did you manage to generate a nodeset using client instead of a server?

**Comment by Graos** [comment]
No I did not manage to generate a nodeset file from Node OPC UA client. In fact I doubt if there is any direct interface to do that. To my understanding client needs to browse the server and generate a nodeset file from those responses based on the schema defined in part 6.

**Comment by simonbowen** [comment]
Ah OK. That's a real shame, I need to simulate a server and was hoping to export it to XML.

I am having to manually build it which is cumbersome, thank you for your response.

**Comment by mikakaraila** [comment]
Server has dumpXML() but not really tested / used. If you write your server with node-opcua then you could add method to call it.
And do some testing.
BTW UaExpert has Document for nodeset that can export XML, but I have not tested it neither.

**Comment by simonbowen** [comment]
@mikakaraila Thanks for that information. Unfortunately that isn't what I am trying to achieve. I want to connect to a 3rd Party server and dump the nodes to XML. This means I need to use the client, not define my own server.

**Comment by mikakaraila** [comment]
Have you tried with UaExpert:
![image](https://user-images.githubusercontent.com/5184524/111522698-3378d100-8763-11eb-9f14-d90945a6a701.png)

**Comment by simonbowen** [comment]
@mikakaraila I have tried with UAExpert, with the free license it only supports exporting upto 20 nodes.

**Comment by mikakaraila** [comment]
Sorry forgot that limitation
