### ISSUE TITLE
Node OPC UA server does not copies the client certificate in the APPDATA trusted folder when AcceptUnknownCertificates is true

### ISSUE THREAD

**Issue by Graos** [node-opcua/node-opcua#939]
**Current behavior**

When the server is run for the first time. It creates two folders in %APPDATA%
"$\AppData\Roaming\NodeOPCUA-Default-nodejs"
"$\AppData\Roaming\NodeOPCUA-nodejs"

\AppData\Roaming\NodeOPCUA-Default-nodejs\Config\certificates\own contains the generated server certificate and Private key
\AppData\Roaming\NodeOPCUA-Default-nodejs\Config\certificates\trusted\certs contains again the the generated server certificate with a different name (MyOPCUAServerApplicationName[35ff7b63c4254b7636b9688f2c91d86c75a1127a])

**Describe the bug**
 what is the use in generating $\AppData\Roaming\NodeOPCUA-nodejs folder ?
why the server certificate is copied with different name in \AppData\Roaming\NodeOPCUA-Default-nodejs\Config\certificates\trusted\certs

I dont find client certificate stored in trusted folder when the flag AutomaticallAcceptUnknowCertificate is true. In fact i don't see the client certificate stored anywhere. This changed from 2.28.3 

**To Reproduce**

1. Run the server and check the certificate folder and its content in %APPDATA%
2. ......
   3.......

**Expected behavior**
I expect to see the client certificate inside the trusted folder.
**Screenshots**

**Gist**
gist:

- ( ) my request is related to node-opcua acting as an OPCUA SERVER

  - ( ) I have installed node-opcua from source ( using git clone)
  - ( ) I have installed node-opcua as a package ( using npm install )
  - ( ) I am using an application that uses node-opcua

    - ( ) node-red
    - ( ) other : please specify

  - Device: **\_**
  - OS version: **\_**

    - ( ) Windows : version : \***\*\_\*\***
    - ( ) Linux : version : \***\*\_\*\***
    - ( ) MacOs : version : \***\*\_\*\***
    - ( ) Raspbian: version : \***\*\_\*\***
    - ( ) Other : specify :

  - Description of the other OPCUA system I am trying to connect to:

    - Name:\***\*\_\*\***
    - Version:\***\*\_\*\***
    - Manufacturer/Software vendor:\***\*\_\*\***
    - link : https://

- **node-opcua version:** : 2.30.0
  
  

- **Node:**
  `node --version` =

**Comment by erossignon** [comment]
> what is the use in generating $\AppData\Roaming\NodeOPCUA-nodejs folder ?

This change has been introduced in version 2.29.0 to get rid of an long-standing post-install step that was causing node-opcua to create default certificate inside the node_module folder during npm install.  On Raspbian, for instance, some installs of node-js causes the node_module folder to be write protected, and causes all sorts of weird issues, mainly for node-red users .
Now, client / server are using a proper PKI stored in %APPDATA% or ~/.config and default certificates are created during first use in those location.
see [release note 2.29](https://github.com/node-opcua/node-opcua/releases/tag/v2.29.0) for more info  

> why the server certificate is copied with different name in \AppData\Roaming\NodeOPCUA-Default-nodejs\Config\certificates\trusted\certs 

We have started some work (starting to appear in 2.30) to add a extra step at server/client creation to verify that the server/client certificate and its private key are valid. This diagnostic produces warning message that will help you to identifies potential gotchas in certificate management. The purpose is to reduce the technical support effort for diagnosing why sometimes connection fails. We found out that most of the time our users generates certificates with third parties tools, but those certificates are not compliant with the OPCUA specifications, this create many support calls. We found appropriate to find those classical mistake early.  
At this time, the diagnostics tools requires that the server checked its own certificate, hence the necessity to copy the server certificat inside it's own PKI trusted folder. This feature is still under development and behavior might be slightly revisited in the future.  This should not affects you.  Your feedback is welcome;

> Node OPC UA server does not copies the client certificate in the APPDATA trusted folder when AcceptUnknownCertificates is true

Correct , it stores in inside the trusted\cert folder.

The area of certificate management is getting a overhaul on our side and should not be considered stable, more changes to come on this in the next versions.

If you want to get a sense of what is going on in this area , please subscribe to the node-opcua membership at https://support.sterfive.com ,we reserve greater visibility of what is going on and why to our members and also helps them to perform incremental adjustment to their application as we move along.
