### ISSUE TITLE
UaExpert throws BadCertificateHostNameInvalid when connecting to server.  Issue is seen  both with default certificate and generated certificate

### ISSUE THREAD

**Issue by Graos** [node-opcua/node-opcua#941]
**Current behavior**

UaExpert throws BadCertificateHostNameInvalid when server used with default certificate

**Describe the bug**
NodeOPCUA server uses the default certificate created in %APPDATA%. when the client(UaExpert') connects to server with Basic256Sha256 (sign and Encrypt) UaExpert throws BadCertificateHostNameInvalid(Hostname or IP address in certificate does not match with the hostname or IP address the client connected to)

**To Reproduce**

1. .Run the NodeOPCUA server
2. .connect the client (UaExpert) to server with Basic256Sha256 security policy with sign and encrypt)
   3.......

**Screenshots**
![image](https://user-images.githubusercontent.com/69800669/105451031-cd5f5880-5ca1-11eb-8b23-f2c3aeac5c37.png)

![image](https://user-images.githubusercontent.com/69800669/105451106-e9fb9080-5ca1-11eb-84f4-aa13ecdd432f.png)

**Gist**
gist:

Exposed Endpoint from the server
opc.tcp://DE-L-7224240.EUROPE.ABB.COM:26543 http://opcfoundation.org/UA/SecurityPolicy#None              None
opc.tcp://DE-L-7224240.EUROPE.ABB.COM:26543 http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15     Sign
opc.tcp://DE-L-7224240.EUROPE.ABB.COM:26543 http://opcfoundation.org/UA/SecurityPolicy#Basic256          Sign
opc.tcp://DE-L-7224240.EUROPE.ABB.COM:26543 http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256    Sign
opc.tcp://DE-L-7224240.EUROPE.ABB.COM:26543 http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15     SignAndEncrypt
opc.tcp://DE-L-7224240.EUROPE.ABB.COM:26543 http://opcfoundation.org/UA/SecurityPolicy#Basic256          SignAndEncrypt
opc.tcp://DE-L-7224240.EUROPE.ABB.COM:26543 http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256    SignAndEncrypt

- ( ) my request is related to node-opcua acting as an OPCUA SERVER

  - ( ) I have installed node-opcua as a package ( using npm install )

    - ( ) node-red
    - ( ) other : please specify

  - Device: **\_**
  - OS version: **\_**

    - ( ) Windows : version : \***\*\_\*\***
    - ( ) Linux : version : \***\*\_\*\***
    - ( ) MacOs : version : \***\*\_\*\***
    - ( ) Raspbian: version : \***\*\_\*\***
    - ( ) Other : specify :

  - Description of the other OPCUA system I am trying to connect to:

    - Name:\***\*\_\*\***
    - Version:\***\*\_\*\***
    - Manufacturer/Software vendor:\***\*\_\*\***
    - link : https://

- **node-opcua version:** : 2.30.0
  
  

- **Node:**
  `node --version` =

**Comment by AndreasHeine** [comment]
have you renamed your computer after installing UaExpert (the certs are generated while installation) you can look inside the cert:
UaExpert -> Settings -> Manage Certificates -> <Trusted Own Certificate> -> open it -> lookup DNS-Name compare it against your computername!

**Comment by Graos** [comment]
Domain name from server certificate in UaExpert shows  DE-L-7224240 and the endpoint to connect to is DE-L-7224240.EUROPE.ABB.COM. The difference is what the UaExpert complains about.

**Comment by AndreasHeine** [comment]
add the FHQN to the UaExperts own cert under domainnames like i mentioned in "FYI"!

![Unbenannt2](https://user-images.githubusercontent.com/56362817/105460448-13112680-5c8c-11eb-9c6e-5470c7b2825b.PNG)

![Unbenannt1](https://user-images.githubusercontent.com/56362817/105460319-eb21c300-5c8b-11eb-95d8-f7411760e31c.PNG)

**Comment by AndreasHeine** [comment]
if you create your certs with open ssl you could use the ip instead of the domain name
