### ISSUE TITLE
Unable to Browse the Functional Blocks created in TIA Projects.

### ISSUE THREAD

**Issue by shribadiger** [node-opcua/node-opcua#947]
**Current behavior**

We have a Functional Blocks in the TIA Projects running in Siemens 1500 PLCs. Node OPCUA Client is able to browse the tags which are present inside the data block but its not able to browse the tags inside the functional block.

**Describe the bug**
We are using the node-opcua-client to browse the tags from the Siemens PLCs 1500. We are getting the configured tags in the plain data block. But if we create the functional blocks, not able to browse the tags and giving wrong address format. Screen shot of address format is attached. As of now, We are using the docker to run node-opcua clinet hence not able to collect the debug logs. Need support to collect logs in docker services(debug logs).
![image](https://user-images.githubusercontent.com/6604828/107462669-9edaec00-6b82-11eb-9338-38e7162db86b.png)

Browse Tags: V_"FB_1_Sequence"."ExternalSignal"  -- Wrong address to read tag from the PLCs via OPCUA Channel.

**To Reproduce**
1. Configure the functional blocks in TIA ( Siemens Total Integrated Automation Tool)
2. Start OPCUA Server in PLC 1500 Family
3. Start to browse the tags by node-opcua-client by passing the IP of 

**Expected behavior**
It should browse the Functional Blocks and display proper Tag Address. 
**Screenshots**

  - Device: Siemens S7 1500 PLCs
  - OS version: Debian 10

- **Node:**
  `node --version` =Node 12 version.

**Comment by AndreasHeine** [comment]
which node-opcua version? 
working alot with s7-1500 opcua servers i'll make a quick test! just one more question: can you browse the tags with UaExpert?

**Comment by AndreasHeine** [comment]
no issues...
CPU 11505SP F FW2.6
node-opcua 2.33.0
![Unbenannt(1)](https://user-images.githubusercontent.com/56362817/107475598-af846580-6b74-11eb-810f-d0edab50480a.png)

but check if the tags are avalible with UaExpert! if not it might be a wrong OPC UA Configuration in the s7 or sometimes you need to reload the Hardware-Configuratiration if you changed OPC UA Server relevant stuff in the plc program.
