### ISSUE TITLE
Return Statuscode or Variant in Variable Getter

### ISSUE THREAD

**Issue by SaibotFlow** [node-opcua/node-opcua#948]
I want return a specific StatusCode when a client is reading a variable.
I already checked your posts (https://github.com/node-opcua/node-opcua/issues/8#) and I saw that you fixed it in 2014. But I cant return a StatusCode instead of a Variant in the Getter of a variable in the version 2.33

So what can I do?

Thank you for your effort.

Best regards On3

_Originally posted by @On3byT in https://github.com/node-opcua/node-opcua/issues/8#issuecomment-776854666_

**Comment by erossignon** [comment]
use timestamped_get instead of get : timestamped_get offers a richer API.
Or better simply use `variable.setValueFromSource(variant, statusCode)` when ever the value changes on the server side. getter/setter should not be overused.
