### ISSUE TITLE
Enumeration type with negative values

### ISSUE THREAD

**Issue by zenonpelle** [node-opcua/node-opcua#949]
**Current behavior**

**Describe the bug**
 Trying to import an enumerated typ from XML with negative values. This is done for backward compbility reasons

**To Reproduce**

1.  Create an enumerated type in XML for example red = -1, blue = 1
2. .Import the XML
3.  The server dumps
   

**Expected behavior**
As far as I can read I can not find any limits on the enumeration type in OPC UA definitons or in IEC61131-3 definition.
**Screenshots**

**Gist**
gist:

- ( ) my request is related to node-opcua acting as an OPCUA CLIENT
- ( x) my request is related to node-opcua acting as an OPCUA SERVER

  - ( ) I have installed node-opcua from source ( using git clone)
  - ( x) I have installed node-opcua as a package ( using npm install )
  - ( ) I am using an application that uses node-opcua

    - ( ) node-red
    - ( ) other : please specify

  - Device: **\PC**
  - OS version: **\_**

    - ( x) Windows : version : \***\*\_\*\***
    - ( ) Linux : version : \***\*\_\*\***
    - ( ) MacOs : version : \***\*\_\*\***
    - ( ) Raspbian: version : \***\*\_\*\***
    - ( ) Other : specify :

  - Description of the other OPCUA system I am trying to connect to:

    - Name:\***\*\_\*\***
    - Version:\***\*\_\*\***
    - Manufacturer/Software vendor:\***\*\_\*\***
    - link : https://

- **node-opcua version:** : 2.31
  
  

- **Node:**
  `node --version` =

**Comment by erossignon** [comment]
duplicates #937
