### ISSUE TITLE
Client subscription increases memory usage on server side

### ISSUE THREAD

**Issue by acabrero-deeptrack** [node-opcua/node-opcua#955]
**I'm submitting a ...**  (check one with "x")

 - ( ) bug report => search github for a similar issue or PR before submitting
 - (X) feature request
 - ( ) support request 

**Current behavior**
Limit or monitor client queueSize,  sampling interval, publishingInterval and maxNotificationsPerPublish from server side.
Client subscription increases memory use too much (above 1GB of RAM) in server (node-opcua).

**Expected behavior**
Detect from server side client subscription parameters and limit them or monitor them.

**Minimal reproduction of the problem with instructions**

  1. ________________
  2. ________________
  3. ________________
  ...

gist:

  
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Server:
nodejs v 12.20.1-alpine in Docker 20.10.5
Ubuntu 18.04.4 lts
4 CPUs
8GB RAM

  * ( ) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * (X)  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * (X) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device:
  * OS version:

    
    - ( ) Windows : version : _________
    - (X) Linux   : version : Ubuntu 18.04.4 lts
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name:
     - Version:_________
     - Manufacturer/Software vendor:_________
     - link : https://
     
    
* **node-opcua version:**  :

2.33.0

* **Node:** 
   `node --version` = 12.20.1

* **Typscript:** 
   `tsc --version` =

**Comment by erossignon** [comment]
Node (in fact V8) is handling memory and may use all memory available, "memory unused is memory wasted". 
You should see that your node application will work well as well with less memory available, nodejs is quite adaptive.
