### ISSUE TITLE
Unsubscribe by Subscription ID

### ISSUE THREAD

**Issue by reto88** [node-opcua/node-opcua#963]
I am useing the opc ua node with socket.io. I have several connections with different subscription Id.
How can I` UASUBSCRIPTION.terminate()` by `SubscriptionId `when a connection is finished? At the moment it terminate all subscritpion.

**Comment by erossignon** [comment]
If you wish to terminate a subscription, without closing a session, use 

```` 
    await subscription.terminate();
```` 


However, subscriptions will be automatically terminated when you close the session except if you set deleteSubscriptions to false

```` 
    await session.close(/* deleteSubscriptions */ false);
```` 

by default, you should be using

```` 
    await session.close();
```` 
which is equivalent to 
```` 
    await session.close(/* deleteSubscriptions */ true);
````

**Comment by mikakaraila** [comment]
And for one variable similar way:
monitoredItem.terminate();
