### ISSUE TITLE
How enable and disable subscription?

### ISSUE THREAD

**Issue by mariodiciccio** [node-opcua/node-opcua#969]
Hi,
there is an example for this issue?

var subscription = new ClientSubscription(session, {
    requestedPublishingInterval: 100,
    requestedLifetimeCount: 10 ,
    requestedMaxKeepAliveCount: 100,
    maxNotificationsPerPublish: 1000,
    publishingEnabled: false,
    priority: 6
});

setTimeout(()=>{
  subscription.publishingEnabled = true
}, 3000);

Thanks

**Comment by erossignon** [comment]
await subscription.setPublishingMode(true);

**Comment by mariodiciccio** [comment]
Thank you very much, but the first call is a lot slow about 1 min, while the next calls is fast about less 1 sec, why?

**Comment by erossignon** [comment]
I would investigate what's going on in the server, The client just sends a simple command here.

**Comment by mariodiciccio** [comment]
How can I help you?

**Comment by erossignon** [comment]
You could help you/me by subscribing to support (https://support.sterfive.com) so we can investigate deeper on your specific setup, as suggested in the issue template.
