### ISSUE TITLE
Adding monitored items failed when using npx webpack

### ISSUE THREAD

**Issue by matthias-heller** [node-opcua/node-opcua#974]
**Current behavior**

I created a sample client identical to what is described in https://github.com/node-opcua/node-opcua-sample/blob/master/simple_client_ts.ts. The application runs quite fine. In order to have a minified version of my application I started to add the usage of webpack to my build scripts. When using webpack the application fails when trying to add items to the subscription in the following line of the sample client

```javascript
const monitoredItem = await subscription.monitor({
            nodeId,
            attributeId: AttributeIds.Value
        },
            {
                samplingInterval: 100,
                discardOldest: true,
                queueSize: 10
            }, TimestampsToReturn.Both);
```

**Describe the bug**
An exception is being called from the await subscription.monitor method
{ type: 'Exception occured', message: '', code: 'SERVER_EXCEPTION' }

**Step by step instruction to reproduce**

1. build the sample application with tsc
2. create a webpack config with the following content:
```javascript 
const path = require('path');

module.exports = {
  target: 'node',
  entry: './out-tsc/app.js',
  mode: 'production',
  module: {
    rules: [
      {
        test: /\.node$/,
        loader: 'node-loader',
      },
    ],
  },
  output: {
    filename: 'app.js',
    path: path.resolve(__dirname, 'bundle'),
  },
  externals: { 
    'bufferutil': 'bufferutil',
    'utf-8-validate': 'utf-8-validate'
  },
  resolve: { modules: ['node_modules'] }
};
```
3. build the package with webpack
4. run the test application again

**Expected behavior**

The application should run whether I use webpack or not

**Context**

- (x ) my request is related to node-opcua acting as an OPCUA CLIENT
- ( ) my request is related to node-opcua acting as an OPCUA SERVER

- ( ) I have installed node-opcua from source ( using git clone)
- ( ) I have installed node-opcua as a package ( using npm install )
- ( ) I am using an application that uses node-opcua

    - ( ) node-red
    - ( ) other : please specify

- Device: PC and S7-1500
- OS version: Windows 10

    - ( x) Windows : version : Windows 10 1909
    - ( ) Linux : version : ______
    - ( ) MacOs : version : ______
    - ( ) Raspbian: version : ______
    - ( ) Other : specify : ______

- Description of the other OPCUA system I am trying to connect to:

    - Name: Siemens S7-1500
    - Version: ______
    - Manufacturer/Software vendor: ______
    - link to the manufacturer or product site: https://

- **node-opcua version:** :
  
  

- **Node:**
  `node --version` = 14.16.0 TLS

**Comment by erossignon** [comment]
Make sure to provide all required files. for instance the './out-tsc/app.js' file is missing
