### ISSUE TITLE
Question: Find and reuse open sessions

### ISSUE THREAD

**Issue by hchris1** [node-opcua/node-opcua#977]
Hi,

I would like to create an OPC UA integration for a node based program (n8n) similiar to Node-RED using this library. 
The idea is basically to be able to drag a node into a workspace which can be setup to trigger the workflow when new OPC UA values come in.

Everything works well, but I am facing an issue when it comes to having many nodes simultaneously:
- n8n doesn't allow to have global variables for all nodes; they act independent
- Therefore I have to create a client and session for each trigger which is limited by the maximum number of allowed sessions.

I couldn't find any similar issues or things pointing in the right direction... Does someone have an idea how I could solve that issue? Maybe somehow find open sessions and reuse them from a different client?

Thanks for any suggestions

**Comment by erossignon** [comment]
If you close the session once you finish using it, you should not reach the session limit problem.
Make sure that session is opened just before you read/write to the node and then closed afterward.
