### ISSUE TITLE
Support for session-less connection

### ISSUE THREAD

**Issue by maximivanov** [node-opcua/node-opcua#983]
I wonder if this library supports making session-less requests to an OPC UA server? The description of the feature can be found here: https://youtu.be/fiuamY0DzLM?t=902

**Is your feature request related to a problem? Please describe.**

Making a lot of queries to the OPC UA server (not from node-opcua) from stateless backend Node.js servers using node-opcua.

**Describe the solution you'd like**

Using session-less connection to avoid an overhead of creating and destroying a session on the OPC server.

**Describe alternatives you've considered**

Creating a session with the OPC UA server, reading the value from the server and destroying the session on every invocation of the backend code.

**Additional context**

https://youtu.be/fiuamY0DzLM?t=902

Thanks!

**Comment by erossignon** [comment]
This feature is not yet implemented on our side, Sterfive is awaiting interest and funding from a major cloud company (for instance= to implement this.
