### ISSUE TITLE
Module '"node-opcua"' has no exported member 'ReadValueIdLike'.ts(2305)

### ISSUE THREAD

**Issue by TomaszPrazniewski89** [node-opcua/node-opcua#989]
I have followed the instruction of  Client copnfiguration and i am affraid i got stuck with the error described below:

Module '"node-opcua"' has no exported member 'ReadValueIdLike'.ts(2305)

**Comment by erossignon** [comment]
Try ReadValueIdOptions

**Comment by erossignon** [comment]
Duplicates  #980
