### ISSUE TITLE
Event "err" Not Working for ClientMonitoredItem

### ISSUE THREAD

**Issue by rodp82** [node-opcua/node-opcua#99]
Hi,

In the code below, the "changed" event on the monitoredItem works fine, however the "err" event is never triggered when an unknown node ID is supplied.

```javascript
monitoredItem.on('err ', function(statusCode ){
    console.log('an error has occured');
    console.log(statusCode );
});

monitoredItem.on('changed', function(dataValue){
    console.log(dataValue.value.value,);
});
```

The library itself logs a "monitoredItemResult statusCode =  BadNodeIdUnknown (0x80340000)" message. And in the code in lib/client/client_monitored_item.js (line142), the following code is called.
```
self.emit("err", monitoredItemResult.statusCode);
```

Is there something else that I'm missing?

**Comment by erossignon** [comment]
You have a trailing space in 'err ' ,it should be 'err'

**Comment by rodp82** [comment]
Well spotted. I'd been staring at that for a long time.
Thanks
